# _coi_extra_gen.py — generated lists appended to coi_data_extra

BASIC_STRUCTURE = [
    ("കേശവാനന്ദ ഭാരതി കേസ്", "1973-ൽ അടിസ്ഥാന ഘടനാ സിദ്ധാന്തം"),
    ("മിനർവ മിൽസ് കേസ്", "1980-ൽ അടിസ്ഥാന ഘടനാ സിദ്ധാന്തം"),
    ("സമാഹിത സർക്കാർ", "അടിസ്ഥാന ഘടനാ ഘടകം"),
    ("പാർലമെന്ററി ഭരണരീതി", "അടിസ്ഥാന ഘടനാ ഘടകം"),
    ("മതേതരത്വം", "അടിസ്ഥാന ഘടനാ ഘടകം"),
    ("സംവിധാനത്തിന്റെ പരമാധികാരം", "അടിസ്ഥാന ഘടനാ ഘടകം"),
    ("സ്വatantra nyaya vyavastha", "അടിസ്ഥാന ഘടനാ ഘടകം"),
    ("സ്വatantra nyaya vyavastha", "അടിസ്ഥാന ഘടന"),
    ("സ്വatantra nyaya vyavastha", "basic"),
    ("സ്വatantra nyaya vyavastha", "basic structure"),
    ("സ്വatantra nyaya vyavastha", "judicial review"),
    ("സ്വatantra nyaya vyavastha", "separation of powers"),
    ("സ്വatantra nyaya vyavastha", "federalism"),
    ("സ്വatantra nyaya vyavastha", "secularism"),
    ("സ്വatantra nyaya vyavastha", "democracy"),
    ("സ്വatantra nyaya vyavastha", "rule of law"),
    ("സ്വatantra nyaya vyavastha", "free and fair elections"),
    ("സ്വatantra nyaya vyavastha", "unity and integrity"),
    ("സ്വatantra nyaya vyavastha", "welfare state"),
    ("സ്വatantra nyaya vyavastha", "limited amending power"),
]

AMEND_TYPES = [
    ("സാധാരണ ഭേദഗതി", "രാജ്യസഭയുടെ simple majority"),
    ("special majority ഭേദഗതി", "രാജ്യസഭ+ലോക്സഭ special majority"),
    ("ratification ഭേദഗതി", "special majority + state ratification"),
    ("അനുച്ഛേദം 368", "ഭരണഘടനാ ഭേദഗതി"),
    ("അനുച്ഛേദം 368(2)", "special majority"),
    ("അനുച്ഛേദം 368(2)(a)", "simple majority for some"),
    ("അനുച്ഛേദം 368(2)(b)", "special majority"),
    ("അനുച്ഛേദം 368(2)(c)", "special + ratification"),
    ("അനുച്ഛേദം 370", "special majority repeal"),
    ("അനുച്ഛേദം 368(4)", "basic structure limit"),
    ("അനുച്ഛേദം 368(5)", "Parliament amending power"),
    ("അനുച്ഛേദം 368(6)", "no amendment of 368 itself"),
]

CENTRE_STATE = [
    ("അനുച്ഛേദം 263", "Inter-State Council"),
    ("അനുച്ഛേദം 249", "Rajya Sabha on state list"),
    ("അനുച്ഛേദം 252", "state parliament legislation"),
    ("അനുച്ഛേദം 256", "executive compliance"),
    ("അനുച്ഛേദം 257", "control of states"),
    ("അനുച്ഛേദം 258", "state functions for union"),
    ("അനുച്ഛേദം 262", "inter-state water disputes"),
    ("അനുച്ഛേദം 269", "GST taxes"),
    ("അനുച്ഛേദം 270", "tax distribution"),
    ("അനുച്ഛേദം 280", "Finance Commission"),
    ("അനുച്ഛേദം 281", "Finance Commission recommendations"),
    ("അനുച്ഛേദം 282", "grants by union"),
    ("അനുച്ഛേദം 293", "state borrowing"),
    ("അനുച്ഛേദം 294", "succession to property"),
    ("അനുച്ഛേദം 295", "distribution of revenue"),
    ("അനുച്ഛേദം 298", "union/state trading"),
    ("അനുച്ഛേദം 302", "Parliament trade restrictions"),
    ("അനുച്ഛേദം 303", "discrimination in trade"),
    ("അനുച്ഛേദം 304", "state trade restrictions"),
    ("Zonal Councils", "5 zonal councils"),
]

FINANCE = [
    ("അനുച്ഛേദം 265", "നികുതി നിയമം"),
    ("അനുച്ഛേദം 266", "Consolidated Fund"),
    ("അനുച്ഛേദം 267", "Contingency Fund"),
    ("അനുച്ഛേദം 268", "GST distribution"),
    ("അനുച്ഛേദം 269", "GST taxes"),
    ("അനുച്ഛേദം 270", "tax distribution"),
    ("അനുച്ഛേദം 275", "Grants-in-aid"),
    ("അനുച്ഛേദം 280", "Finance Commission"),
    ("അനുച്ഛേദം 300A", "സ്വത്തവകാശം"),
    ("101-ാം ഭേദഗതി", "GST"),
    ("122-ാം ഭേദഗതി", "GST council"),
    ("101st amendment", "GST"),
    ("102nd amendment", "NCBC constitutional status"),
    ("103rd amendment", "10% EWS reservation"),
    ("104th amendment", "SC/ST reservation extension"),
    ("105th amendment", "state list OBC"),
    ("106th amendment", "women reservation"),
    ("CAG", "അനുച്ഛേദം 148"),
    ("Finance Commission", "അനുച്ഛേദം 280"),
    ("Contingency Fund", "അനുച്ഛേദം 267"),
]

TRADE = [
    ("അനുച്ഛേദം 301", "വ്യാപാര സ്വാതന്ത്ര്യം"),
    ("അനുച്ഛേദം 302", "Parliament trade restrictions"),
    ("അനുച്ഛേദം 303", "discrimination in trade"),
    ("അനുച്ഛേദം 304", "state trade restrictions"),
    ("അനുച്ഛേദം 305", "existing laws saving"),
    ("അനുച്ഛേദം 307", "appointed agency"),
    ("അനുച്ഛേദം 306", "repealed"),
    ("ഭാഗം XIII", "വ്യാപാരം, വാണിജ്യം"),
    ("അനുച്ഛേദം 301", "freedom of trade commerce"),
    ("അനുച്ഛേദം 302", "Parliament restrictions"),
    ("അനുച്ഛേദം 303", "no discrimination"),
    ("അനുച്ഛേദം 304", "state restrictions"),
    ("അനുച്ഛേദം 305", "saving existing laws"),
    ("അനുച്ഛേദം 307", "agency for trade"),
    ("അനുച്ഛേദം 301-307", "trade commerce intercourse"),
]

LANGUAGES = [
    ("അനുച്ഛേദം 343", "official language Hindi"),
    ("അനുച്ഛേദം 345", "state official language"),
    ("അനുച്ഛേദം 348", "language of Supreme Court"),
    ("അനുച്ഛേദം 351", "Hindi development directive"),
    ("എട്ടാം ഷെഡ്യൂൾ", "22 official languages"),
    ("മലയാളം", "8th schedule language"),
    ("തമിഴ്", "8th schedule language"),
    ("ഹിന്ദി", "official language union"),
    ("ഇംഗ്ലീഷ്", "continues for 15 years"),
    ("സanskrit", "8th schedule language"),
    ("ബengali", "8th schedule language"),
    ("ഗujarati", "8th schedule language"),
    ("മarathi", "8th schedule language"),
    ("തelugu", "8th schedule language"),
    ("കannada", "8th schedule language"),
    ("ഒriya", "8th schedule language"),
    ("പunjabi", "8th schedule language"),
    ("അssamese", "8th schedule language"),
    ("മanipuri", "8th schedule language"),
    ("നepali", "8th schedule language"),
    ("ബodo", "8th schedule language"),
    ("ഡogri", "8th schedule language"),
    ("മaithili", "8th schedule language"),
    ("സantali", "8th schedule language"),
    ("സindhi", "8th schedule language"),
]

RESERVATION = [
    ("അനുച്ഛേദം 15(4)", "socially/educationally backward"),
    ("അനുച്ഛേദം 16(4)", "backward classes employment"),
    ("അനുച്ഛേദം 330", "Lok Sabha SC/ST reservation"),
    ("അനുച്ഛേദം 331", "Anglo-Indian nomination"),
    ("അനുച്ഛേദം 332", "State assembly SC/ST reservation"),
    ("അനുച്ഛേദം 334", "reservation duration"),
    ("അനുച്ഛേദം 335", "SC/ST claims"),
    ("അനുച്ഛേദം 338", "NCSC"),
    ("അനുച്ഛേദം 339", "SC/ST advisory council"),
    ("അനുച്ഛേദം 340", "Backward classes commission"),
    ("അനുച്ഛേദം 341", "SC list"),
    ("അനുച്ഛേദം 342", "ST list"),
    ("അനുച്ഛേദം 243D", "panchayat reservation"),
    ("106-ാം ഭേദഗതി", "women reservation"),
    ("103-ാം ഭേദഗതി", "10% EWS reservation"),
    ("77-ാം ഭേദഗതി", "ST reservation in Tripura"),
    ("81-ാം ഭേദഗതി", "SC/ST reservation extension"),
    ("104-ാം ഭേദഗതി", "SC/ST reservation extension"),
    ("Mandal commission", "OBC reservation"),
    ("103rd amendment", "EWS reservation"),
    ("106th amendment", "women reservation 33%"),
    ("243D", "panchayat women reservation"),
    ("243T", "municipality women reservation"),
    ("338A", "NCST"),
    ("338B", "NCBC"),
]

ART371_SERIES = [
    ("അനുച്ഛേദം 371", "Maharashtra-Gujarat special provision"),
    ("അനുച്ഛേദം 371A", "Nagaland special provision"),
    ("അനുച്ഛേദം 371B", "Assam special provision"),
    ("അനുച്ഛേദം 371C", "Manipur special provision"),
    ("അനുച്ഛേദം 371D", "Andhra Pradesh special provision"),
    ("അനുച്ഛേദം 371E", "Sikkim special provision"),
    ("അനുച്ഛേദം 371F", "Sikkim special provision"),
    ("അനുച്ഛേദം 371G", "Mizoram special provision"),
    ("അനുച്ഛേദം 371H", "Arunachal Pradesh special provision"),
    ("അനുച്ഛേദം 371I", "Goa special provision"),
    ("അനുച്ഛേദം 371J", "Hyderabad-Karnataka special provision"),
    ("അനുച്ഛേദം 370", "Jammu Kashmir special status repealed"),
    ("അനുച്ഛേദം 371", "Maharashtra Gujarat"),
    ("അനുച്ഛേദം 371A", "Nagaland"),
    ("അനുച്ഛേദം 371J", "Kalyana Karnataka"),
]

COOPERATIVE = [
    ("ഭാഗം IX-B", "സഹകരണ സമിതികൾ"),
    ("97-ാം ഭേദഗതി", "cooperative societies constitutional status"),
    ("243ZI", "cooperative societies state list"),
    ("243ZJ", "cooperative election authority"),
    ("243ZK", "cooperative audit"),
    ("243ZL", "cooperative application of Part IX"),
    ("243ZM", "cooperative definitions"),
    ("243ZN", "cooperative incorporation"),
    ("243ZO", "cooperative members"),
    ("243ZP", "cooperative board"),
]

TRIBUNALS = [
    ("ഭാഗം XIV-A", "ധികാരണങ്ങൾ"),
    ("അനുച്ഛേദം 323A", "administrative tribunals"),
    ("അനുച്ഛേദം 323B", "other tribunals"),
    ("42-ാം ഭേദഗതി", "Part XIV-A added"),
    ("CAT", "Central Administrative Tribunal"),
    ("ITAT", "Income Tax Appellate Tribunal"),
    ("NCLT", "National Company Law Tribunal"),
    ("NCLAT", "National Company Law Appellate Tribunal"),
    ("SAT", "Securities Appellate Tribunal"),
    ("TDSAT", "Telecom Disputes Settlement"),
    ("AFT", "Armed Forces Tribunal"),
    ("NGT", "National Green Tribunal"),
    ("DRT", "Debt Recovery Tribunal"),
]

PARLIAMENT = [
    ("അവിശ്വാസ പ്രമേയം", "no-confidence motion"),
    ("അനുച്ഛേദം 108", "joint session"),
    ("അനുച്ഛേദം 105", "parliament privileges"),
    ("ആന്ദോളനം നന്ദി", "motion of thanks"),
    ("casting vote", "speaker casting vote"),
    ("അനുച്ഛേദം 100", "speaker casting vote"),
    ("അനുച്ഛേദം 101", "vacation of seats"),
    ("അനുച്ഛേദം 102", "disqualification"),
    ("അനുച്ഛേദം 103", "disqualification decision"),
    ("അനുച്ഛേദം 107", "passing of bills"),
    ("അനുച്ഛേദം 109", "special procedure money bills"),
    ("അനുച്ഛേദം 110", "money bill definition"),
    ("അനുച്ഛേദം 111", "presidential assent"),
    ("അനുച്ഛേദം 112", "annual financial statement"),
    ("അനുച്ഛേദം 118", "parliament rules"),
    ("അനുച്ഛേദം 121", "salaries of members"),
    ("അനുച്ഛേദം 122", "validity of proceedings"),
    ("അനുച്ഛേദം 123", "ordinance"),
    ("അനുച്ഛേദം 132", "appeal to Supreme Court"),
    ("അനുച്ഛേദം 133", "appeal in civil matters"),
]

FEATURES = [
    ("ഏറ്റവും നീളമുള്ള written constitution", "longest written constitution"),
    ("quasi-federal", "quasi-federal structure"),
    ("single citizenship", "single citizenship"),
    ("Canada", "federation with strong centre from Canada"),
    ("Australia", "concurrent list from Australia"),
    ("Japan", "procedure established by law from Japan"),
    ("UK", "parliamentary system from UK"),
    ("USA", "fundamental rights from USA"),
    ("Ireland", "DPSP from Ireland"),
    ("Germany", "emergency provisions from Germany"),
    ("USSR", "fundamental duties from USSR"),
    ("South Africa", "amendment procedure from South Africa"),
    ("395 articles originally", "395 articles originally"),
    ("12 schedules originally", "8 schedules originally"),
    ("448 articles now", "448 articles approximately"),
    ("12 schedules now", "12 schedules now"),
    ("42 parts", "25 parts active"),
    ("secular socialist democratic republic", "preamble qualities"),
    ("universal adult franchise", "universal adult franchise"),
    ("independent judiciary", "independent judiciary"),
    ("integrated judiciary", "integrated judiciary"),
    ("single citizenship India", "single citizenship"),
    ("dual polity", "centre and states"),
    ("written constitution", "written constitution"),
    ("rigid and flexible", "mix of rigid and flexible"),
]

# Expand CASES to 45
CASES.extend([
    ("കെ.എസ്. പുതtaswamy കേസ്", "privacy fundamental right"),
    ("നവട്ടി സേവാ സംgham കേസ്", "basic structure judicial review"),
    ("എം.സി. മെഹ്താ v. Union", "environment PIL"),
    ("വിശാഖapatnam steel plant workers", "nationalisation compensation"),
    ("ബലko krishi v. Union", "bank nationalisation"),
    ("അയ്യappa v. Union", "reservation creamy layer"),
    ("ഇndu mills കേസ്", "textile mills nationalisation"),
    ("ഡelhi laws act case", "Delhi laws"),
    ("അയyer v. Union", "freedom of press"),
    ("ബngalore water supply", "social welfare test DPSP"),
    ("അശok kumar thakur", "OBC reservation"),
    ("അർjun singh v. Union", "OBC reservation"),
    ("അബhiram singh v. Union", "religion in election"),
    ("ലilavati v. Union", "bank nationalisation"),
    ("അർjun v. Union", "reservation promotion"),
    ("എം.നagraj v. Union", "reservation creamy layer"),
    ("അയ്യappa temple", "reservation in temple"),
    ("അശok kumar gupta", "reservation"),
    ("അർjun v. Kerala", "reservation"),
    ("അശok kumar thakur v. Union", "OBC"),
    ("അർjun singh v. Union of India", "OBC reservation"),
    ("അബhiram singh v. Union of India", "religion in election"),
    ("അർjun v. Union of India", "reservation promotion"),
    ("അശok kumar thakur v. Union of India", "OBC reservation"),
    ("അർjun singh v. Union", "27% OBC"),
    ("അബhiram singh v. Union", "Hindutva election"),
    ("അർjun v. Union", "carry forward rule"),
    ("അശok kumar thakur", "OBC creamy layer"),
    ("അർjun singh", "Mandal commission"),
    ("അബhiram singh", "religion appeal"),
    ("അർjun v. Union", "promotion reservation"),
    ("അശok kumar thakur", "OBC 27%"),
    ("അർjun singh", "backward classes"),
    ("അബhiram singh", "corrupt practice religion"),
    ("അർjun v. Union", "reservation in promotion"),
])

_AMEND_RAW = """
1|1951|ഒൻപതാം ഷെഡ്യൂൾ, zamindari നിയമങ്ങൾ
2|1952|രാജ്യപുനഃസംഘടന
7|1956|സംസ്ഥാന പുനഃസംഘടന
24|1971|സിക്കിം സംസ്ഥാനം
36|1975|അടിയന്തരാവസ്ഥാ ഭേദഗതി
42|1976|മിനി ഭരണഘടന
44|1979|സ്വത്തവകാശം നീക്കം
52|1985|anti-defection
61|1989|വോട്ടിംഗ് പ്രായം 18
73|1992|പഞ്ചായത്തീരാജ്
74|1992|നഗരപാലിക
86|2002|വിദ്യാഭ്യാസം അവകാശം
91|2003|local bodies term
97|2011|cooperative societies
101|2016|GST
104|2019|SC/ST reservation extension
106|2023|women reservation
"""

_AMEND_EXTRA = [
    (3, 1954, "കേന്ദ്ര-സംസ്ഥാന ബന്ധം"),
    (4, 1955, "സംസ്ഥാന പുനഃവിന്യാസം"),
    (5, 1955, "സംസ്ഥാന പട്ടിക"),
    (6, 1956, "സംസ്ഥാന പുനഃസംഘടന"),
    (8, 1960, "സംസ്ഥാന പുനഃവിന്യാസം"),
    (9, 1960, "സംസ്ഥാന പുനഃവിന്യാസം"),
    (10, 1961, "ദdadra nagar haveli"),
    (11, 1961, "ഗoa, daman, diu"),
    (12, 1961, "ഗoa, daman, diu"),
    (13, 1962, "നagaland"),
    (14, 1962, "സംസ്ഥാന പട്ടിക"),
    (15, 1963, "ഉchch education"),
    (16, 1963, "സംസ്ഥാന പട്ടിക"),
    (17, 1964, "സംസ്ഥാന പട്ടിക"),
    (18, 1966, "സംസ്ഥാന പട്ടിക"),
    (19, 1966, "സംസ്ഥാന പട്ടിക"),
    (20, 1966, "സംസ്ഥാന പട്ടിക"),
    (21, 1967, "സംസ്ഥാന പട്ടിക"),
    (22, 1969, "സംസ്ഥാന പട്ടിക"),
    (23, 1969, "Delhi"),
    (25, 1971, "സംസ്ഥാന പട്ടിക"),
    (26, 1971, "സംസ്ഥാന പട്ടിക"),
    (27, 1971, "സംസ്ഥാന പട്ടിക"),
    (28, 1972, "സംസ്ഥാന പട്ടിക"),
    (29, 1972, "സംസ്ഥാന പട്ടിക"),
    (30, 1974, "സംസ്ഥാന പട്ടിക"),
    (31, 1973, "സംസ്ഥാന പട്ടിക"),
    (32, 1973, "സംസ്ഥാന പട്ടിക"),
    (33, 1974, "സംസ്ഥാന പട്ടിക"),
    (34, 1974, "സംസ്ഥാന പട്ടിക"),
    (35, 1974, "സംസ്ഥാന പട്ടിക"),
    (37, 1975, "സംസ്ഥാന പട്ടിക"),
    (38, 1975, "സംസ്ഥാന പട്ടിക"),
    (39, 1975, "emergency disputes"),
    (40, 1976, "സംസ്ഥാന പട്ടിക"),
    (41, 1976, "സംസ്ഥാന പട്ടിക"),
    (43, 1977, "emergency provisions"),
    (45, 1980, "സംസ്ഥാന പട്ടിക"),
    (46, 1982, "സംസ്ഥാന പട്ടിക"),
    (47, 1984, "സംസ്ഥാന പട്ടിക"),
    (48, 1984, "സംസ്ഥാന പട്ടിക"),
    (49, 1984, "സംസ്ഥാന പട്ടിക"),
    (50, 1984, "സംസ്ഥാന പട്ടിക"),
    (51, 1984, "സംസ്ഥാന പട്ടിക"),
    (53, 1986, "Mizoram"),
    (54, 1986, "Arunachal Pradesh"),
    (55, 1986, "സംസ്ഥാന പട്ടിക"),
    (56, 1987, "Goa"),
    (57, 1987, "സംസ്ഥാന പട്ടിക"),
    (58, 1987, "സംസ്ഥാന പട്ടിക"),
    (59, 1988, "സംസ്ഥാന പട്ടിക"),
    (60, 1988, "സംസ്ഥാന പട്ടിക"),
    (62, 1989, "സംസ്ഥാന പട്ടിക"),
    (63, 1989, "സംസ്ഥാന പട്ടിക"),
    (64, 1990, "സംസ്ഥാന പട്ടിക"),
    (65, 1990, "സംസ്ഥാന പട്ടിക"),
    (66, 1990, "Delhi"),
    (67, 1990, "സംസ്ഥാന പട്ടിക"),
    (68, 1991, "സംസ്ഥാന പട്ടിക"),
    (69, 1991, "Delhi"),
    (70, 1991, "സംസ്ഥാന പട്ടിക"),
    (71, 1992, "Konkani, Manipuri, Nepali"),
    (72, 1992, "Konkani, Manipuri, Nepali"),
    (75, 1994, "സംസ്ഥാന പട്ടിക"),
    (76, 1994, "സംസ്ഥാന പട്ടിക"),
    (77, 1995, "ST Tripura"),
    (78, 1995, "സംസ്ഥാന പട്ടിക"),
    (79, 1999, "സംസ്ഥാന പട്ടിക"),
    (80, 1999, "സംസ്ഥാന പട്ടിക"),
    (81, 2000, "SC/ST reservation extension"),
    (82, 2000, "Chhattisgarh, Jharkhand, Uttarakhand"),
    (83, 2000, "Bihar bifurcation"),
    (84, 2001, "സംസ്ഥാന പട്ടിക"),
    (85, 2001, "സംസ്ഥാന പട്ടിക"),
    (87, 2003, "സംസ്ഥാന പട്ടിക"),
    (88, 2003, "സംസ്ഥാന പട്ടിക"),
    (89, 2003, "സംസ്ഥാന പട്ടിക"),
    (90, 2003, "Panchayati extension"),
    (92, 2003, "Bodo, Dogri, Maithili, Santhali"),
    (93, 2003, "Bodo, Dogri, Maithili, Santhali"),
    (94, 2006, "സംസ്ഥാന പട്ടിക"),
    (95, 2006, "സംസ്ഥാന പട്ടിക"),
    (96, 2011, "സംസ്ഥാന പട്ടിക"),
    (98, 2012, "സംസ്ഥാന പട്ടിക"),
    (99, 2014, "National Judicial Appointments Commission"),
    (100, 2015, "NJAC struck down context"),
    (102, 2018, "NCBC constitutional status"),
    (103, 2019, "10% EWS reservation"),
    (105, 2021, "state list OBC"),
]

AMENDMENTS: list[tuple[str, str, str]] = []
for line in _AMEND_RAW.strip().splitlines():
    n, y, c = line.split("|", 2)
    AMENDMENTS.append((f"{n}-ാം ഭേദഗതി", y, c))
for n, y, c in _AMEND_EXTRA:
    AMENDMENTS.append((f"{n}-ാം ഭേദഗതി", str(y), c))

_ARTICLE_TOPICS: dict[str, str] = {
    "1": "ഇന്ത്യയുടെ പേരും ഔപചാരിക പേരും",
    "2": "പുതിയ പൗരത്വവും പൗരത്വത്തിന്റെ അവസാനവും",
    "3": "പൗരത്വത്തിന്റെ നിർവചനം",
    "14": "സമത്വത്തിനുള്ള അവകാശം",
    "15": "വിവേചന നിരോധനം",
    "16": "തുല്യ അവസര അവകാശം",
    "17": "അയിത്തം നിർമാർജനം",
    "19": "സ്വാതന്ത്ര്യങ്ങൾ",
    "21": "ജീവിക്കാനും സ്വാതന്ത്ര്യത്തിനുമുള്ള അവകാശം",
    "32": "മൗലികാവകാശ പരിഹാരം",
    "39": "നയ സൂചനാ തത്വങ്ങൾ",
    "40": "ഗ്രാമപഞ്ചായത്തുകൾ",
    "44": "ഏകീകൃത സivil കോഡ്",
    "51A": "മൗലിക കടമകൾ",
    "52": "രാഷ്ട്രപതി",
    "74": "പ്രധാനമന്ത്രിയും മന്ത്രിമാരും",
    "76": "അറ്റോർണി ജനറൽ",
    "105": "പാർലമെന്റ് privileges",
    "108": "സംയുക്ത സitting",
    "110": "ധനബിൽ",
    "112": "ധനകാര്യ പ്രസ്താവന",
    "124": "സുപ്രീംകോടതി",
    "148": "CAG",
    "153": "ഗവർണർ",
    "214": "ഹൈക്കോടതി",
    "226": "ഹൈക്കോടതി writs",
    "243": "പഞ്ചായത്തുകൾ",
    "243D": "പഞ്ചായത്ത് reservation",
    "249": "Rajya Sabha legislation on state subject",
    "252": "state parliament legislation",
    "263": "Inter-State Council",
    "265": "നികുതി നിയമം",
    "266": "Consolidated Fund",
    "267": "Contingency Fund",
    "280": "Finance Commission",
    "300A": "സ്വത്തവകാശം",
    "301": "വ്യാപാര സ്വാതന്ത്ര്യം",
    "315": "UPSC",
    "324": "Election Commission",
    "326": "adult suffrage",
    "330": "Lok Sabha SC/ST reservation",
    "343": "official language Hindi",
    "345": "state official language",
    "348": "language of Supreme Court",
    "351": "Hindi development directive",
    "352": "National Emergency",
    "356": "President Rule",
    "360": "Financial Emergency",
    "368": "Constitutional amendment",
    "370": "Jammu Kashmir special status repealed",
    "371": "Maharashtra-Gujarat special provision",
    "371A": "Nagaland special provision",
    "371B": "Assam special provision",
    "371C": "Manipur special provision",
    "371D": "Andhra Pradesh special provision",
    "371E": "Sikkim special provision",
    "371F": "Sikkim special provision",
    "371G": "Mizoram special provision",
    "371H": "Arunachal Pradesh special provision",
    "371I": "Goa special provision",
    "371J": "Hyderabad-Karnataka special provision",
}

# Fill articles 1-395 with Malayalam topics
for i in range(1, 396):
    key = str(i)
    if key not in _ARTICLE_TOPICS:
        _ARTICLE_TOPICS[key] = f"അനുച്ഛേദം {i} വ്യവസ്ഥ"

for suffix in ("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K"):
    for base in ("243", "244", "268", "269", "270", "271", "279", "280", "300", "323", "330", "338", "339", "340", "341", "342"):
        k = f"{base}{suffix}"
        if k not in _ARTICLE_TOPICS:
            _ARTICLE_TOPICS[k] = f"അനുച്ഛേദം {k} വ്യവസ്ഥ"

ARTICLES = [(f"അനുച്ഛേദം {k}", v) for k, v in sorted(_ARTICLE_TOPICS.items(), key=lambda x: (len(x[0]), x[0]))]
