#!/usr/bin/env python3
"""Build economics_wave20_ml_data.py from English source with Malayalam translations."""
from __future__ import annotations

import ast
import re
from pathlib import Path

GEN = Path(__file__).parent / "_gen_build_economics_wave20_data.py"
OUT = Path(__file__).parent / "economics_wave20_ml_data.py"

HEADER = '''#!/usr/bin/env python3
"""Pure Malayalam PSC economics facts — wave 20 ML categories."""

from __future__ import annotations

Fact = tuple[str, str, list[str], str]
Pair = tuple[str, str]
Triple = tuple[str, str, str]

'''

# Malayalam answer/stem translations keyed by English answer (longest match first in apply())
ANS: dict[str, str] = {
    "minimum support price": "കാർഷിക ധനസഹായ വില",
    "food grain procurement storage": "ഭക്ഷ്യധാന്യ സംഭരണം",
    "food grain procurement": "ഭക്ഷ്യധാന്യ സംഭരണം",
    "food grain production increase": "ഭക്ഷ്യധാന്യ ഉൽപ്പാദന വർദ്ധന",
    "milk production increase": "പാൽ ഉൽപ്പാദന വർദ്ധന",
    "fisheries development": "മത്സ്യ വികസനം",
    "oilseeds production": "എണ്ണയurukk ഉൽപ്പാദനം",
    "agriculture rural development": "ഗ്രാമീണ വികസന ധനസഹായം",
    "regulated agricultural markets": "നിയന്ത്രിത കാർഷിക വിപണികൾ",
    "unified national agricultural market": "ഏകീകൃത ദേശീയ കാർഷിക വിപണി",
    "unified agricultural market": "ഏകീകൃത കാർഷിക വിപണി",
    "income support to farmers": "കർഷകർക്ക് വരുമാന സഹായം",
    "farmer income support": "കർഷക വരുമാന സഹായം",
    "crop loss insurance": "വിള നഷ്ട ഇൻഷുറൻസ്",
    "crop insurance": "വിള ഇൻഷുറൻസ്",
    "food security": "ഭക്ഷ്യ സുരക്ഷ",
    "subsidized food to poor": "ദരിദ്രർക്ക് ചെലവുകുറഞ്ഞ ഭക്ഷണം",
    "FCI restructuring": "FCI പുനഃഘടന",
    "pre-agreed price quantity": "മുൻകൂട്ടി നിശ്ചയിച്ച വില-അളവ്",
    "equitable land distribution": "സമത്വപൂർവ്വ ഭൂമി വിതരണം",
    "drip sprinkler efficiency": "തുള്ളി-സ്പ്രിംക്ലർ കാര്യക്ഷമത",
    "Kisan Credit Card": "കിസാൻ ക്രെഡിറ്റ് കാർഡ്",
    "every 5 years": "അഞ്ച് വർഷം",
    "farmer cultivated land": "കർഷകൻ കൃഷി ചെയ്യുന്ന ഭൂമി",
    "Commission for Agricultural Costs and Prices": "കാർഷിക ചെലവ്-വില കമ്മീഷൻ",
    "agricultural costs prices": "കാർഷിക ചെലവ്-വില",
    "supply shock food items": "ഭക്ഷ്യ വസ്തു വിതരണ ഞെട്ടൽ",
    "subsidies domestic support": "സബ്സിഡി-ആഭ്യന്തര പിന്തുണ",
    "low input farming": "കുറഞ്ഞ ഇൻപുട്ട് കൃഷി",
    "NPOP standards": "NPOP മാനദണ്ഡങ്ങൾ",
    "organic farming standards": "ജൈവ കൃഷി മാനദണ്ഡം",
    "dairy meat infrastructure": "പാൽ-മാംസ അടിസ്ഥാന സൗകര്യം",
    "liberalize export agri products": "കാർഷിക ഉൽപ്പന്ന കayttumati സ്വതന്ത്രമാക്കൽ",
    "nutri cereals initiative": "പോഷക ധാന്യങ്ങൾ",
    "100 days wage employment": "100 ദിവസം വേതന തൊഴിൽ",
    "unemployed divided by labour force": "തൊഴിൽരഹിതർ ÷ തൊഴിൽശക്തി",
    "employed plus unemployed seeking work": "തൊഴിലുണ്ട് + തൊഴിൽ തേടുന്നവർ",
    "marginal productivity zero": "അതിർത്തി ഉൽപ്പാദനം പൂജ്യം",
    "skill mismatch": "കഴിവ് പൊരുത്തക്കേട്",
    "business cycle downturn": "വ്യാപാര ചക്ര മന്ദം",
    "job search transition": "തൊഴിൽ തിരയൽ മാറ്റം",
    "off season agriculture": "കാർഷിക ഒഴിച്ക്കൽ കാലം",
    "wage floor for workers": "തൊഴിലാളികൾക്ക് വേതന കനിഷ്ഠം",
    "industrial relations disputes": "വ്യവസായ ബന്ധവും തർക്കങ്ങളും",
    "worker safety conditions": "തൊഴിലാളി സുരക്ഷയും അവസ്ഥകളും",
    "Employees Provident Fund": "തൊഴിലാളി ഭവിഷ്യ നിധി",
    "Employees State Insurance": "തൊഴിലാളി സംസ്ഥാന ഇൻഷുറൻസ്",
    "labour force divided working age population": "തൊഴിൽശക്തി ÷ പ്രവൃത്തി പ്രായ ജനസംഖ്യ",
    "short term flexible work": "ഹ്രസ്വകാല സൗകര്യപ്രദ തൊഴിൽ",
    "registered regulated employment": "രജിസ്റ്റർ ചെയ്ത നിയന്ത്രിത തൊഴിൽ",
    "unregistered low regulation": "രജിസ്റ്റർ ചെയ്യാത്ത കുറഞ്ഞ നിയന്ത്രണം",
    "workforce skill development": "തൊഴിലാളി കഴിവ് വികസനം",
    "skill certification training": "കഴിവ് സാക്ഷ്യപ്പെടുത്തൽ പരിശീലനം",
    "employment exchange portal": "തൊഴിൽ കൈമാറ്റ പോർട്ടൽ",
    "consolidated labour laws": "ഏകീകൃത തൊഴിൽ നിയമങ്ങൾ",
    "contract limited duration": "കരാർ പരിധിയുള്ള തൊഴിൽ",
    "universal social security framework": "സാർവ്വത്രിക സാമൂഹിക സുരക്ഷാ ചട്ടക്കൂട്",
    "workplace safety standards": "ജോലിസ്ഥല സുരക്ഷാ മാനദണ്ഡങ്ങൾ",
    "trade union industrial disputes": "സംഘടനാ വ്യവസായ തർക്കങ്ങൾ",
    "minimum wage payment wages": "കനിഷ്ഠ വേതനവും വേതനമെzhuthal",
    "output per worker": "ഒരു തൊഴിലാളിയുടെ ഉൽപ്പാദനം",
    "working age population share high": "പ്രവൃത്തി പ്രായ ജനസംഖ്യാ വിഹിതം ഉയർന്ന",
    "Periodic Labour Force Survey": "ആവർത്തന തൊഴിൽശക്തി സർവേ",
    "benefits reduce work incentive": "ആനുകൂല്യങ്ങൾ ജോലി പ്രേരണ കുറയ്ക്കുന്നു",
    "securities market regulation": "ഓഹരി വിപണി നിയന്ത്രണം",
    "new securities issue": "പുതിയ ഓഹരി_vipani",
    "existing securities trade": "നിലവിലുള്ള ഓഹരി_kayattam",
    "initial public offering": "ആദ്യ പൊതു_vipani",
    "follow on public offering": "തുടർ_ppublic_vipani",
    "electronic securities form": "electronic ഓഹരി_rupam",
    "insurance sector regulation": "ഇൻഷുറൻസ് നിയന്ത്രണം",
    "death maturity cover": "മരണ-പൂർത്തിയാക്കൽ പരിരക്ഷ",
    "non-life cover": "ജീവൻ അല്ലാത്ത പരിരക്ഷ",
    "unit linked insurance plan": "യൂണിറ്റ് ബന്ധിത ഇൻഷുറൻസ്",
    "National Pension System": "ദേശീയ പെൻഷൻ",
    "unorganized sector pension": "അorganised മേഖല പെൻഷൻ",
    "life insurance low premium": "കുറഞ്ഞ പ്രീമിയം ജീവൻ ഇൻഷുറൻസ്",
    "accident insurance low premium": "കുറഞ്ഞ പ്രീമിയം അപകട ഇൻഷുറൻസ്",
    "health insurance Ayushman": "ആyushman ആrogya ഇൻഷുറൻസ്",
    "insurer transfers risk": "ഇൻഷുറർ അപകടം കൈമാറുന്നു",
    "risk premium calculation": "അപകട പ്രീമിയം കണക്കുകൂട്ടൽ",
    "claims paid divided claims received": "നൽകിയ ക്ലെയim ÷ ലഭിച്ച ക്ലെയim",
    "insurer capital adequacy": "ഇൻഷുറർ മൂലധന പോര 충분",
    "mandatory liability cover": "നിർബന്ധിത ഉത്തരവാദിത്വ പരിരക്ഷ",
    "yield loss cover": "വിള നഷ്ട പരിരക്ഷ",
    "switch insurer keep benefits": "ഇൻഷുറർ മാറ്റി നേട്ടം നിലനിർത്തൽ",
    "long term diversified assets": "ദീർഘകാല diversified assets",
    "fixed retirement benefit": "നിശ്ചിത വിരമണ നേട്ടം",
    "contribution fixed benefit variable": "സംഭാവന നിശ്ചിത നേട്ടം വ്യത്യാസം",
    "regular retirement income stream": "നിയമിത വിരമണ വരുമാനം",
    "consumer grievance redressal": "ഉപഭോക്തൃ പരാതി പരിഹാരം",
    "crop insurance scheme": "വിള ഇൻഷുറൻസ് പദ്ധതി",
    "General Insurance Corporation": "പൊതു ഇൻഷുറൻസ് കോർപ്പറേഷൻ",
    "premium to GDP ratio": "പ്രീമിയം-GDP അനുപാതം",
    "informal sector low coverage": "അinformal മേഖല കുറഞ്ഞ പരിരക്ഷ",
    "low income affordable cover": "കുറഞ്ഞ വരുമാന affordable പരിരക്ഷ",
    "IRDA Act 1999": "IRDA നിയമം 1999",
    "special economic zone": "SEZ",
    "export promotion investment": "കayttumati പ്രോത്സാഹനവും നിക്ഷേപവും",
    "manufacturing incentive": "നിർമ്മാണ പ്രോത്സാഹനം",
    "public sector commanding heights": "പൊതുമേഖലയുടെ commanding heights",
    "monopoly restrictive trade prevention": "monopoly നിയന്ത്രണം",
    "Competition Commission of India": "India competition commission",
    "no prior approval sectors": "മുൻകൂർ അംഗീകാരമില്ലാത്ത മേഖലകൾ",
    "prior approval required": "മുൻകൂർ അംഗീകാരം ആവശ്യം",
    "Delhi Mumbai Industrial Corridor": "Delhi-Mumbai industrial corridor",
    "manufacturing GDP share increase": "GDP-യിൽ നിർമ്മാണ വിഹിതം വർദ്ധന",
    "investment and turnover": "നിക്ഷേപവും turnover",
    "MSME formal registration": "MSME രജിസ്ട്രേഷൻ",
    "zero defect zero effect manufacturing": "zero defect zero effect",
    "liberalized most sectors": "മിക്ക മേഖലകളും liberalized",
    "reduce government stake PSU": "PSU-യിൽ സർക്കാർ വിഹിതം കുറയ്ക്കൽ",
    "transfer control private sector": "നിയന്ത്രണം സ്വകാര്യ മേഖലയിലേക്ക്",
    "disinvestment proceeds fund": "disinvestment_proceeds fund",
    "Department for Promotion of Industry Internal Trade": "Industry promotion department",
    "electronics pharma textiles etc": "electronics pharma textiles",
    "local manufacturing transfer": "local manufacturing transfer",
    "SME agglomeration support": "SME cluster support",
    "SEZ has tax customs benefits": "SEZ-യ്ക്ക് tax customs benefits",
    "export oriented unit": "export oriented unit",
    "Software Technology Parks India": "Software Technology Parks India",
    "Micro Small Enterprise Cluster Development": "Micro Small Enterprise Cluster Development",
    "IIP manufacturing component": "IIP manufacturing component",
    "new facility from scratch": "greenfield investment",
    "central goods and services tax": "central GST",
    "state goods and services tax": "state GST",
    "inter state GST": "inter state GST",
    "income tax corporate tax": "income tax corporate tax",
    "GST customs excise": "GST customs excise",
    "states revenue loss compensation": "states revenue loss compensation",
    "higher rate tobacco luxury": "higher rate tobacco luxury",
    "GST Network IT backbone": "GST Network IT backbone",
    "state sales tax": "state sales tax",
    "import export tax": "import export tax",
    "manufacturing tax": "manufacturing tax",
    "services taxation": "services taxation",
    "tax revenue growth to GDP growth": "tax revenue growth to GDP growth",
    "tax change response": "tax change response",
    "investment savings deduction": "investment savings deduction",
    "tax deducted at source": "tax deducted at source",
    "permanent account number": "permanent account number",
    "Central Board Direct Taxes": "Central Board Direct Taxes",
    "Central Board Indirect Taxes Customs": "Central Board Indirect Taxes Customs",
    "General Anti Avoidance Rules": "General Anti Avoidance Rules",
    "double taxation avoidance agreement": "double taxation avoidance agreement",
    "base erosion profit shifting": "base erosion profit shifting",
    "tax avoidance multinational": "tax avoidance multinational",
    "digital services tax": "digital services tax",
    "tax on employer perks": "tax on employer perks",
    "abolished": "നിർത്തലാക്കി",
    "reduced for competitiveness": "competitiveness-ന് കുറച്ചു",
    "dual GST centre states": "dual GST centre states",
    "National Payments Corporation of India": "National Payments Corporation of India",
    "financial inclusion bank accounts": "financial inclusion bank accounts",
    "consent based financial data sharing": "consent based financial data sharing",
    "open credit enablement network": "open credit enablement network",
    "open network digital commerce": "open network digital commerce",
    "consumer rights e-commerce": "consumer rights e-commerce",
    "Consumer Protection Act 1986": "Consumer Protection Act 1986",
    "marketplace model restrictions": "marketplace model restrictions",
    "unfair e-commerce design banned": "unfair e-commerce design banned",
    "regulated lending apps": "regulated lending apps",
    "customer identity verification": "customer identity verification",
    "payment security layer": "payment security layer",
    "mask card details": "mask card details",
    "digital personal data protection": "digital personal data protection",
    "consumer is king market": "consumer is king market",
    "lower price more choice online": "lower price more choice online",
    "value increases with users": "value increases with users",
    "digital intermediaries connect parties": "digital intermediaries connect parties",
    "social security benefits gap": "social security benefits gap",
    "technology access inequality": "technology access inequality",
    "Jan Dhan Aadhaar Mobile": "Jan Dhan Aadhaar Mobile",
    "direct benefit transfer": "direct benefit transfer",
}

STEM: dict[str, str] = {
    "green revolution-ന്റെ പ്രധാന ഫലം?": "പച്ച വിപ്ലവത്തിന്റെ പ്രധാന ഫലം?",
    "white revolution?": "വെള്ള വിപ്ലവം?",
    "blue revolution?": "നീല വിപ്ലവം?",
    "yellow revolution?": "മഞ്ഞ വിപ്ലവം?",
    "National Food Security Act year?": "ദേശീയ ഭക്ഷ്യ സുരക്ഷാ നിയമം?",
    "shanta Kumar committee?": "ശാന്ത കുമാർ കമ്മിറ്റി?",
    "contract farming?": "കരാർ കൃഷി?",
    "land reforms objective?": "ഭൂമി പരിഷ്‌ക്കാരത്തിന്റെ ലക്ഷ്യം?",
    "micro irrigation?": "മൈക്രോ ജലസേചനം?",
    "agricultural census frequency?": "കാർഷിക സെൻസസ് ആവൃത്തി?",
    "operational holding?": "പ്രവർത്തന ഭൂമി?",
    "food inflation driver?": "ഭക്ഷ്യ പണപ്പെരുപ്പത്തിന്റെ കാരണം?",
    "WTO Agreement on Agriculture issue?": "WTO കാർഷിക കരാർ പ്രശ്നം?",
    "zero budget natural farming?": "പൂജ്യ ബജറ്റ് പ്രകൃതി കൃഷി?",
    "organic farming certification?": "ജൈവ കൃഷി സാക്ഷ്യപ്പെടുത്തൽ?",
    "animal husbandry infrastructure fund?": "പശു-മാംസ അടിസ്ഥാന സൗകര്യ നിധി?",
    "agricultural export policy?": "കാർഷിക കayttumati നയം?",
    "millets promotion?": "മില്ലറ്റ് പ്രോത്സാഹനം?",
    "public distribution system?": "പൊതുവിതരണ വ്യവസ്ഥയുടെ ലക്ഷ്യം?",
    "crop insurance scheme PMFBY?": "PMFBY-യുടെ ലക്ഷ്യം?",
    "MGNREGA legal guarantee year?": "MGNREGA നിയമപരമായ ഉറപ്പ് വർഷം?",
    "unemployment rate definition?": "തൊഴിൽരഹിതര നിരക്ക്?",
    "labour force?": "തൊഴിൽശക്തി?",
    "disguised unemployment?": "മറഞ്ഞിരിക്കുന്ന തൊഴിൽരഹിതി?",
    "structural unemployment?": "ഘടനാപര തൊഴിൽരഹിതി?",
    "cyclical unemployment?": "ചക്രീയ തൊഴിൽരഹിതി?",
    "frictional unemployment?": "ഘർഷണ തൊഴിൽരഹിതി?",
    "seasonal unemployment?": "കാലിക തൊഴിൽരഹിതി?",
    "minimum wages act objective?": "കനിഷ്ഠ വേതന നിയമത്തിന്റെ ലക്ഷ്യം?",
    "Industrial Disputes Act?": "വ്യവസായ തർക്ക നിയമം?",
    "Factories Act?": "ഫാക്ടറി നിയമം?",
    "labour force participation rate?": "തൊഴിൽശക്തി പങ്കാളിത്ത നിരക്ക്?",
    "gig economy?": "ഗിഗ് തൊഴിൽ?",
    "formal sector?": "ഔപചാരിക മേഖല?",
    "informal sector?": "അനൗപചാരിക മേഖല?",
    "Skill India mission?": "കഴിവ് ഇന്ത്യ ദൗത്യം?",
    "National Career Service?": "ദേശീയ കരിയർ സേവനം?",
    "labour codes India?": "ഇന്ത്യയിലെ തൊഴിൽ കോഡുകൾ?",
    "fixed term employment?": "നിശ്ചിതകാല തൊഴിൽ?",
    "social security code?": "സാമൂഹിക സുരക്ഷാ കോഡ്?",
    "occupational safety code?": "തൊഴിൽ സുരക്ഷാ കോഡ്?",
    "Industrial Relations Code?": "വ്യവസായ ബന്ധ കോഡ്?",
    "Wage Code?": "വേതന കോഡ്?",
    "labour productivity?": "തൊഴിൽ ഉൽപ്പാദനക്ഷമത?",
    "demographic dividend?": "ജനസംഖ്യാ ലാഭം?",
    "unemployment trap?": "തൊഴിൽരഹിതി കെണി?",
    "SEBI established year?": "SEBI സ്ഥാപിത വർഷം?",
    "BSE established year?": "BSE സ്ഥാപിത വർഷം?",
    "NSE established year?": "NSE സ്ഥാപിത വർഷം?",
    "Sensex base year?": "സെൻസെക്സ് അടിസ്ഥാന വർഷം?",
    "Nifty base year?": "നിഫ്റ്റി അടിസ്ഥാന വർഷം?",
    "primary market?": "പ്രാഥമിക വിപണി?",
    "secondary market?": "ദ്വിതീയ വിപണി?",
    "dematerialization?": "ഡിമാറ്റീരിയലൈസേഷൻ?",
    "Depositories in India?": "ഇന്ത്യയിലെ ഡിപ്പോസitories?",
    "insider trading?": "ഇൻsider trading?",
    "mutual fund?": "മ്യൂച്വൽ ഫണ്ട്?",
    "bond market?": "bond market?",
    "yield curve upward?": "yield curve upward?",
    "inverted yield curve signal?": "inverted yield curve signal?",
    "market capitalization?": "market capitalization?",
    "P/E ratio?": "P/E ratio?",
    "bear market?": "bear market?",
    "bull market?": "bull market?",
    "circuit breaker?": "circuit breaker?",
    "takeover code?": "takeover code?",
    "share buyback?": "share buyback?",
    "stock split?": "stock split?",
    "LIC established year?": "LIC സ്ഥാപിത വർഷം?",
    "IRDAI established year?": "IRDAI സ്ഥാപിത വർഷം?",
    "life insurance?": "ജീവൻ ഇൻഷുറൻസ്?",
    "general insurance?": "പൊതു ഇൻഷുറൻസ്?",
    "NPS regulator?": "NPS നിയന്ത്രകൻ?",
    "Atal Pension Yojana?": "അatal pension yojana?",
    "reinsurance?": "പുനര_insurance?",
    "actuarial science?": "actuarial science?",
    "claim settlement ratio?": "claim settlement ratio?",
    "solvency margin?": "solvency margin?",
    "third party motor insurance?": "third party motor insurance?",
    "crop insurance PMFBY?": "crop insurance PMFBY?",
    "health insurance portability?": "health insurance portability?",
    "pension fund investment?": "pension fund investment?",
    "defined benefit pension?": "defined benefit pension?",
    "defined contribution pension?": "defined contribution pension?",
    "annuity?": "annuity?",
    "Insurance Ombudsman?": "Insurance Ombudsman?",
    "Pradhan Mantri Fasal Bima?": "Pradhan Mantri Fasal Bima?",
    "insurance penetration?": "insurance penetration?",
    "pension coverage India challenge?": "pension coverage India challenge?",
    "micro insurance?": "micro insurance?",
    "Insurance Regulatory Act?": "Insurance Regulatory Act?",
    "SEZ Act year?": "SEZ നിയമം വർഷം?",
    "first SEZ India?": "ഇന്ത്യയിലെ ആദ്യ SEZ?",
    "PLI scheme objective?": "PLI പദ്ധതിയുടെ ലക്ഷ്യം?",
    "Make in India launch year?": "Make in India ആരംഭ വർഷം?",
    "Industrial Policy Resolution 1956?": "1956 വ്യവസായ നയ_resolution?",
    "MRTP Act objective?": "MRTP നiyamam ലക്ഷ്യം?",
    "Competition Act year?": "Competition നിയമം വർഷം?",
    "FDI automatic route?": "FDI automatic route?",
    "FDI government route?": "FDI government route?",
    "Industrial corridor example?": "Industrial corridor example?",
    "National Manufacturing Policy?": "National Manufacturing Policy?",
    "MSME definition based?": "MSME definition based?",
    "Udyam registration?": "Udyam registration?",
    "ZED certification?": "ZED certification?",
    "Industrial licensing post 1991?": "Industrial licensing post 1991?",
    "disinvestment objective?": "disinvestment objective?",
    "strategic disinvestment?": "strategic disinvestment?",
    "National Investment Fund?": "National Investment Fund?",
    "DIPP now?": "DIPP now?",
    "Production linked incentive sectors?": "Production linked incentive sectors?",
    "offset policy defence?": "offset policy defence?",
    "cluster development programme?": "cluster development programme?",
    "Industrial park vs SEZ?": "Industrial park vs SEZ?",
    "greenfield investment?": "greenfield investment?",
    "GST launch date India?": "GST ആരംഭ തീയതി?",
    "GST council chaired by?": "GST council chaired by?",
    "CGST?": "CGST?",
    "SGST?": "SGST?",
    "IGST?": "IGST?",
    "GST slab common rate?": "GST slab common rate?",
    "direct tax examples?": "direct tax examples?",
    "indirect tax examples?": "indirect tax examples?",
    "GST compensation cess?": "GST compensation cess?",
    "sin goods GST?": "sin goods GST?",
    "GSTN?": "GSTN?",
    "VAT predecessor state?": "VAT predecessor state?",
    "customs duty?": "customs duty?",
    "excise duty pre GST?": "excise duty pre GST?",
    "service tax pre GST?": "service tax pre GST?",
    "tax buoyancy?": "tax buoyancy?",
    "tax elasticity?": "tax elasticity?",
    "deduction 80C?": "deduction 80C?",
    "TDS?": "TDS?",
    "PAN?": "PAN?",
    "CBDT?": "CBDT?",
    "CBIC?": "CBIC?",
    "GAAR?": "GAAR?",
    "DTAA?": "DTAA?",
    "tax haven issue?": "tax haven issue?",
    "OECD BEPS?": "OECD BEPS?",
    "equalization levy?": "equalization levy?",
    "fringe benefit tax history?": "fringe benefit tax history?",
    "wealth tax status?": "wealth tax status?",
    "corporate tax rate trend post 2019?": "corporate tax rate trend post 2019?",
    "fiscal federalism GST?": "fiscal federalism GST?",
    "UPI launched by?": "UPI launched by?",
    "NPCI full form?": "NPCI-യുടെ പൂർണ്ണ രൂപം?",
    "Digital India launch year?": "ഡിജിറ്റൽ ഇന്ത്യ ആരംഭ വർഷം?",
    "PMJDY objective?": "PMJDY-യുടെ ലക്ഷ്യം?",
    "Aadhaar issuing authority?": "ആധാർ നൽകുന്ന അധികാരം?",
    "BHIM app based on?": "BHIM app based on?",
    "NEFT?": "NEFT?",
    "RTGS minimum?": "RTGS minimum?",
    "IMPS?": "IMPS?",
    "RuPay?": "RuPay?",
    "e-RUPI?": "e-RUPI?",
    "Account Aggregator framework?": "Account Aggregator framework?",
    "OCEN?": "OCEN?",
    "ONDC?": "ONDC?",
    "consumer protection act 2019?": "consumer protection act 2019?",
    "COPRA predecessor?": "COPRA predecessor?",
    "e-commerce FDI rules?": "e-commerce FDI rules?",
    "dark patterns regulation?": "dark patterns regulation?",
    "digital lending guidelines RBI?": "digital lending guidelines RBI?",
    "KYC norms?": "KYC norms?",
    "two factor authentication?": "two factor authentication?",
    "tokenization cards?": "tokenization cards?",
    "DPDP Act?": "DPDP Act?",
    "consumer sovereignty?": "consumer sovereignty?",
    "consumer surplus digital?": "consumer surplus digital?",
    "network effect?": "network effect?",
    "platform economy?": "platform economy?",
    "gig worker issue?": "gig worker issue?",
    "digital divide?": "digital divide?",
    "JAM trinity?": "JAM trinity?",
    "DBT?": "DBT?",
    "Indian Nobel economics?": "ഇന്ത്യൻ സാമ്പത്തികശാസ്ത്ര Nobel?",
    "Development as Freedom author?": "Development as Freedom രചയിതാവ്?",
    "Gandhian economic thought emphasis?": "ഗാന്ധിയൻ സാമ്പത്തിക ചിന്ത?",
    "Bombay Plan year?": "Bombay Plan വർഷം?",
    "Planning Commission first chairman?": "Planning Commission ആദ്യ_chairman?",
    "Second Five Year Plan architect?": "രണ്ടാം പഞ്ചവത്സര പദ്ധതി_architect?",
    "Rostow take-off stage?": "Rostow take-off stage?",
    "Myrdal circular cumulative causation?": "Myrdal circular cumulative causation?",
    "Schumpeter entrepreneur role?": "Schumpeter entrepreneur role?",
    "Hayek knowledge problem?": "Hayek knowledge problem?",
    "comparative advantage theory?": "താരതമ്യ മേന്മ സിദ്ധാന്തം?",
    "invisible hand concept?": "അദൃശ്യ കൈ ആശയം?",
    "laissez faire advocate?": "laissez faire advocate?",
    "surplus value theory?": "surplus value theory?",
    "monetarism advocate?": "monetarism advocate?",
    "Prisoner's Dilemma?": "Prisoner's Dilemma?",
    "Capability Approach?": "Capability Approach?",
    "Hind Swaraj economics critique?": "Hind Swaraj economics critique?",
    "Bombay Plan associated?": "Bombay Plan associated?",
    "Gunnar Myrdal work on Asia?": "Gunnar Myrdal work on Asia?",
    "Rostow stages of growth?": "Rostow stages of growth?",
    "Lewis model?": "Lewis model?",
    "Harrod Domar model?": "Harrod Domar model?",
    "Solow model?": "Solow model?",
    "Kuznets curve?": "Kuznets curve?",
    "Laffer curve?": "Laffer curve?",
    "Phillips curve author?": "Phillips curve author?",
    "Malthus population theory?": "Malthus population theory?",
    "Veblen conspicuous consumption?": "Veblen conspicuous consumption?",
    "Schumpeter creative destruction?": "Schumpeter creative destruction?",
    "Fisher equation?": "Fisher equation?",
    "Pareto efficiency?": "Pareto efficiency?",
    "Indian planning economist?": "ഇന്ത്യൻ planning economist?",
    "Mahalanobis model emphasis?": "Mahalanobis model emphasis?",
}

PAIR_ML: dict[str, str] = {
    "MSP": "കാർഷിക ധനസഹായ വില",
    "FCI": "ഭക്ഷ്യധാന്യ സംഭരണം",
    "NABARD": "ഗ്രാമീണ വികസന ധനസഹായം",
    "APMC": "നിയന്ത്രിത കാർഷിക വിപണികൾ",
    "e-NAM": "ഏകീകൃത കാർഷിക വിപണി",
    "PM-KISAN": "കർഷക വരുമാന സഹായം",
    "PMFBY": "വിള ഇൻഷുറൻസ്",
    "CACP": "കാർഷിക ചെലവ്-വില",
    "KCC": "കിസാൻ ക്രെഡിറ്റ് കാർഡ്",
    "NPOP": "ജൈവ കൃഷി മാനദണ്ഡം",
    "ICAR": "കാർഷിക ഗവേഷണം",
    "NAFED": "കാർഷിക സഹകരണ വിപണനം",
    "LIC": "ജീവൻ ഇൻഷുറൻസ്",
    "IRDAI": "ഇൻഷുറൻസ് നിയന്ത്രണം",
    "EPFO": "തൊഴിലാളി ഭവിഷ്യ നിധി",
    "NPS": "ദേശീയ പെൻഷൻ",
    "PFRDA": "പെൻഷൻ നിയന്ത്രണം",
    "PMJJBY": "ജീവൻ ഇൻഷുറൻസ് പദ്ധതി",
    "PMSBY": "അപകട ഇൻഷുറൻസ് പദ്ധതി",
    "PMJAY": "ആrogya ഇൻഷുറൻസ് പദ്ധതി",
    "GIC": "പുനര_insurance",
    "ULIP": "യൂണിറ്റ് ബന്ധിത ഇൻഷുറൻസ്",
}

ECONOMIC_THINKERS: list[tuple[str, str, str]] = [
    ("ആഡം സ്മിത്ത്", "രാജ്യങ്ങളുടെ സമ്പാദം", "ശാസ്ത്രീയ സാമ്പത്തികശാസ്ത്രം"),
    ("കാൾ മാർക്സ്", "മൂലധനം", "മാർക്സിയൻ സാമ്പത്തികശാസ്ത്രം"),
    ("ജോൺ മെയിൻാർഡ് കെയ്ൻസ്", "സാമാന്യ സിദ്ധാന്തം", "ചോദനാധിഷ്ഠിത സാമ്പത്തികശാസ്ത്രം"),
    ("ഡേവിഡ് റിക്കാർഡോ", "താരതമ്യ മേന്മ", "വ്യാപാര സിദ്ധാന്തം"),
    ("ആൽഫ്രഡ് മാർഷൽ", "സാമ്പത്തികശാസ്ത്രത്തിന്റെ തത്വങ്ങൾ", "ഭാഗിക സമതുല്യം"),
    ("മിൽട്ടൺ ഫ്രീഡ്മാൻ", "നാണയവാദം", "നാണയ_supply"),
    ("അമർത്യ സെൻ", "വികസനം സ്വാതന്ത്ര്യമായി", "സാമർത്ഥ്യ സമീപനം"),
    ("പി. സി. മഹാലനോബിസ്", "മഹാലനോബിസ് മാതൃക", "ഭാരമേറിയ വ്യവസായം"),
    ("തോമസ് മാൽത്തസ്", "ജനസംഖ്യാ സിദ്ധാന്തം", "ഭക്ഷ്യ പരിമിതി"),
    ("ജോസഫ് ഷംപീറ്റർ", "സർജനativo destruction", "novation"),
    ("ഇർവിംഗ് ഫിഷർ", "ഫിഷർ സമവാക്യം", "പലിശ-പണപ്പെരുപ്പം"),
    ("വിൽഫ്രെഡോ പരേറ്റോ", "പരേറ്റോ കാര്യക്ഷമത", "ക്ഷേമ സാമ്പത്തികശാസ്ത്രം"),
]

THINKER_EXTRA_MANUAL: list[tuple[str, str, list[str], str]] = [
    ("ഇന്ത്യയിലെ സാമ്പത്തികശാസ്ത്ര Nobel?", "അമർത്യ സെൻ", ["രഘുരാം രാജൻ", "മന്മോഹൻ സിംഗ്", "വിജയ് കേൽക്കർ"], "medium"),
    ("വികസനം സ്വാതന്ത്ര്യമായി രചിച്ചത്?", "അമർത്യ സെൻ", ["ആഡം സ്മിത്ത്", "കാൾ മാർക്സ്", "ജോൺ മെയിൻാർഡ് കെയ്ൻസ്"], "hard"),
    ("ഗാന്ധിയൻ സാമ്പത്തിക ചിന്ത?", "സ്വadeshi ഗ്രാമ ekonomi", ["ഭാരമേറിയ വ്യവസായം മാത്രം", "വidesh dependence", "monopoly capital"], "medium"),
    ("Bombay Plan വർഷം?", "1944", ["1951", "1991", "1947"], "hard"),
    ("Planning Commission ആദ്യ_chairman?", "ജവഹർലാൽ നെഹru", ["മന്മോഹൻ സിംഗ്", "ഇന്ദിരാ ഗാന്ധി", "രാജീവ് ഗാന്ധി"], "medium"),
    ("രണ്ടാം പഞ്ചവത്സര പദ്ധതി_architect?", "പി. സി. മഹാലനോബിസ്", ["വി. കെ. ആർ.വി. രാവു", "സി. രംഗരാജൻ", "മന്മോഹൻ സിംഗ്"], "hard"),
    ("Rostow take-off?", "വേഗത്തിലുള്ള വളർച്ച-വ്യവസായവൽക്കരണം", ["traditional society മാത്രം", "recession", "decline"], "hard"),
    ("Myrdal circular causation?", "പ്രാദേശിക അസമത്വം നിലനിൽക്കുന്നു", ["equality always", "trade balance always", "no inequality"], "hard"),
    ("Schumpeter entrepreneur?", "novation driver", ["government only", "labour only", "land only"], "medium"),
    ("Hayek knowledge problem?", "central planning information limits", ["perfect information", "no market", "full planning success"], "hard"),
]

print("This script needs manual completion - use hand-written file instead")
