#!/usr/bin/env python3
"""Pure Malayalam cinema term facts — no English leaks in answers/options."""

from __future__ import annotations

Fact = tuple[str, str, list[str], str]

CINEMATOGRAPHY: list[Fact] = [
    ("ഡോളി ഷോട്ട്", "ക്യാമറ ട്രാക്കിൽ നീങ്ങി എടുക്കുന്ന ദൃശ്യം", ["സ്ഥിര ഷോട്ട്", "ഹാൻഡ് ഹെൽഡ്", "ഏരിയൽ ഷോട്ട്"], "medium"),
    ("ട്രാക്കിംഗ് ഷോട്ട്", "വസ്തുവിനൊപ്പം ക്യാമറ നീങ്ങുന്ന ദൃശ്യം", ["സ്ഥിര ഷോട്ട്", "ടിൽട്ട്", "സൂം"], "medium"),
    ("പാൻ ഷോട്ട്", "ക്യാമറ തിരശ്ചീനമായി നീങ്ങൽ", ["ടിൽട്ട്", "സൂം", "ഡോളി"], "easy"),
    ("ടിൽട്ട് ഷോട്ട്", "ക്യാമറ ലംബമായി നീങ്ങൽ", ["പാൻ", "സൂം", "ഡോളി"], "easy"),
    ("സൂം ഷോട്ട്", "ലെൻസ് ദൂരം മാറ്റി എടുക്കുന്ന ദൃശ്യം", ["ഡോളി", "ട്രാക്കിംഗ്", "പാൻ"], "easy"),
    ("ക്ലോസ്-അപ്പ്", "വസ്തുവിന്റെ സമീപദൃശ്യം", ["വൈഡ് ഷോട്ട്", "ഏരിയൽ", "ഇൻസേർട്ട്"], "easy"),
    ("വൈഡ് ഷോട്ട്", "വിസ്തൃത പശ്ചാത്തലമുള്ള ദൃശ്യം", ["ക്ലോസ്-അപ്പ്", "മാക്രോ", "ടു-ഷോട്ട്"], "easy"),
    ("ഓവർ-ദ-ഷോൾഡർ", "സംഭാഷണത്തിനുള്ള ദൃശ്യരീതി", ["ക്ലോസ്-അപ്പ്", "വൈഡ്", "ഏരിയൽ"], "medium"),
    ("ഡീപ് ഫോക്കസ്", "മുന്നും പിന്നും വ്യക്തമായി കാണുന്ന ഷോട്ട്", ["ഷalow ഫോക്കസ്", "മാക്രോ", "ടെലിഫോട്ടോ"], "hard"),
    ("ഷalow ഫോക്കസ്", "പശ്ചാത്തലം മങ്ങിയ ഷോട്ട്", ["ഡീപ് ഫോക്കസ്", "വൈഡ്", "ഏരിയൽ"], "medium"),
    ("ഹൈ-കീ ലൈറ്റിംഗ്", "പ്രകാശമേറിയ illumination", ["ലോ-കേ ലൈറ്റിംഗ്", "സിലhouette", "ഫ്ലാറ്റ് ലൈറ്റിംഗ്"], "medium"),
    ("ലോ-കേ ലൈറ്റിംഗ്", "കടുത്ത നിഴലുകളുള്ള illumination", ["ഹൈ-കേ ലൈറ്റിംഗ്", "ഫ്ലാറ്റ് ലൈറ്റിംഗ്", "സ്വാഭാവിക പ്രകാശം മാത്രം"], "medium"),
    ("പ്രകാശ-ഇരுள സംവാദം", "പ്രകാശ-ഇരுள之间的对比", ["ഹൈ-കേ", "ഫ്ലാറ്റ്", "ഓവർഎക്സ്പോഷർ"], "hard"),
    ("ത്രിപോин트 ലൈറ്റിംഗ്", "മുഖ്യ, പൂരക, പിൻവെളിച്ചം", ["സ്വാഭാവിക മാത്രം", "ഒറ്റ ഉറവിടം", "സിലhouette മാത്രം"], "hard"),
    ("ഗോൾഡൻ ഹവർ", "സൂര്യോദയ/അസ്തമയത്തിലെ മൃദുവായ പ്രകാശം", ["മധ്യാഹ്ന കടുത്ത", "രാത്രി ഷൂട്ട്", "സ്റ്റുഡിയോ മാത്രം"], "medium"),
    ("ഹാൻഡ് ഹെൽഡ്", "കൈയിൽ പിടിച്ച ഷൂട്ടിംഗ്", ["സ്റ്റെഡിക്കാം", "ട്രൈപോഡ്", "ക്രെയിൻ"], "medium"),
    ("സ്റ്റെഡിക്കാം", "സുഗമമായ ചലന ദൃശ്യം", ["ഹാൻഡ് ഹെൽഡ്", "സ്ഥിര ട്രൈപോഡ്", "സൂoom മാത്രം"], "medium"),
    ("ക്രെയിൻ ഷോട്ട്", "ലംബ ചലന ക്യാമറ ഷോട്ട്", ["ഡോളി മാത്രം", "പാൻ മാത്രം", "സ്ഥിര"], "medium"),
    ("ഡച്ച് ആംഗിൾ", "ചായം horizon", ["നേര水平", "ഏരിയൽ മാത്രം", "മാക്രോ"], "hard"),
    ("24 fps", "സിനിമയുടെ സtandard frame rate", ["30 fps", "60 fps", "12 fps"], "medium"),
    ("ബokeh", "ഫോക്കസ് പുറത്തുള്ള മങ്ങൽ", ["ഡീപ് ഫോക്കസ്", "എല്ലായിടത്തും sharp", "noise"], "hard"),
    ("റാക്ക് ഫോക്കസ്", "focus point മാറ്റം", ["സൂoom", "പാൻ", "ടിൽട്ട്"], "hard"),
    ("ചിത്രമാപകൻ", "ദൃശ്യ记录 നിയന്ത്രിക്കുന്ന കലാസാങ്കേതികൻ", ["എഡിറ്റർ", "ശബ്ദ സംവിധായകൻ", "കലാസംവിധായകൻ"], "easy"),
    ("ഗaffer", "ലൈറ്റിംഗ് മേധാവി", ["എഡിറ്റർ", "സ്ക്രിപ്റ്റ് സൂപ്പർവൈസർ", "സംഗീത സംവിധായകൻ"], "hard"),
    ("വൈഡ് ആംഗിൾ", "വിശാല ദൃശ്യപഥം", ["ടെലിഫോട്ടോ", "മാക്രോ", "ഫിഷൈ"], "medium"),
    ("ടെലിഫോട്ടോ", "ദൂരവസ്തുക്കൾക്കുള്ള ലെൻസ്", ["വൈഡ് ആംഗിൾ", "മാക്രോ", "ഫിഷൈ"], "hard"),
    ("മാക്രോ ലെൻസ്", "സൂക്ഷ്മ വസ്തുക്കൾക്കുള്ള ലെൻസ്", ["വൈഡ് ആംഗിൾ", "ടെലിഫോട്ടോ", "ഫിഷൈ"], "medium"),
    ("നിറgrading", "post-production നിറ adjustment", ["ശബ്ദ മിക്സ്", "കാസ്റ്റിംഗ്", "സെൻസർ"], "medium"),
    ("exposure", "പ്രകാശം sensor/film-ൽ падать", ["frame rate", "aspect ratio", "subtitle"], "easy"),
    ("ഏരിയൽ ഷോട്ട്", "ഉയരത്തിൽ നിന്നുള്ള ദൃശ്യം", ["ക്ലോസ്-അപ്പ്", "മാക്രോ", "ടു-ഷോട്ട്"], "medium"),
    ("ലോംഗ് ടേക്ക്", "നീണ്ട ഒറ്റ ഷോട്ട്", ["ക്വിക്ക് കട്ട്", "മോണ്ടേജ്", "ഇൻസേർട്ട്"], "medium"),
    ("ഇൻസേർട്ട് ഷോട്ട്", "വിശദാംശങ്ങൾ കാണിക്കൽ", ["വൈഡ്", "ഏരിയൽ", "സ്ഥിര"], "easy"),
    ("ടു-ഷോട്ട്", "രണ്ട് കഥാപാത്രങ്ങൾ ഒരുമിച്ച്", ["ക്ലോസ്-അപ്പ്", "വൈഡ്", "മാക്രോ"], "medium"),
    ("എസ്റ്റാബlished ഷോട്ട്", "സ്ഥലം/പശ്ചാത്തലം കാണിക്കൽ", ["ക്ലോസ്-അപ്പ്", "ഇൻസേർട്ട്", "മാക്രോ"], "easy"),
]

MISE_EN_SCENE: list[Fact] = [
    ("ദൃശ്യസജ്ജീകരണം", "ഫ്രെയിമിലെ ദൃശ്യ ഘടകങ്ങളുടെ ക്രമീകരണം", ["എഡിറ്റിംഗ് മാത്രം", "ശബ്ദ മിക്സ് മാത്രം", "ബോക്സ് ഓഫീസ്"], "medium"),
    ("സെറ്റ് ഡിസൈൻ", "ചിത്രീകരണ സets", ["ശബ്ദ രൂപകൽപ്പന", "ഉപശീർഷക ഫോണ്ട്", "ടിക്കറ്റ് വില"], "easy"),
    ("props", "കഥാപാത്രങ്ങൾ ഉപയോഗിക്കുന്ന വസ്തുക്കൾ", ["ക്യാമറ ലെൻസ്", "frame rate", "ബോക്സ് ഓഫീസ്"], "easy"),
    ("വസ്ത്രാലങ്കാരം", "കഥാപാത്രങ്ങളുടെ വേഷഭൂഷണം", ["ശബ്ദ എഡിറ്റിംഗ്", "VFX", "സെൻസർ"], "easy"),
    ("ലൈറ്റിംഗ് ഡിസൈൻ", "ദൃശ്യ mood സൃഷ്ടിക്കൽ", ["സംഭാഷണ രചന", "കാസ്റ്റിംഗ്", "വിതരണം"], "easy"),
    ("ബ്ലോക്കിംഗ്", "നടന്മാരുടെ സ്ഥാന-choreography", ["നിറgrading", "ശബ്ദ മിക്സ്", "ഉപശീർഷകം"], "medium"),
    ("കംposition", "ഫ്രെയിമിലെ ഘടക arrangement", ["ശബ്ദ രൂപകൽപ്പന", "സംഗീതം മാത്രം", "마케팅"], "medium"),
    ("ഉത്പാദന രൂപകൽപ്പന", "visual world building", ["ഫോളി", "എഡിറ്റിംഗ് pace", "കാസ്റ്റിംഗ്"], "medium"),
    ("കലാസംവിധാനം", "visual style supervision", ["ശബ്ദ മിക്സിംഗ്", "സ്റ്റണ്ട് മാത്രം", "ടിക്കറ്റ്"], "medium"),
    ("നിറ палитра", "ചിത്രത്തിന്റെ പ്രധാന നിറങ്ങൾ", ["frame rate", "aspect ratio", "runtime"], "medium"),
    ("കഥാലോക സ്ഥലം", "story world interior", ["non-diegetic", "ബോക്സ് ഓഫീസ്", "മേള"], "hard"),
    ("പ്രായോഗിക effects", "സെറ്റിൽ physical effects", ["CGI മാത്രം", "ഉപശീർഷകം", "ട്രെയ്ler"], "medium"),
    ("മേക്കപ്പ് പ്രോsthetics", "കഥാപാത്ര രൂപാന്തരം", ["ലെൻസ്", "frame rate", "aspect ratio"], "medium"),
    ("ലൊക്കേഷൻ തിര选", "ചിത്രീകരണ സ്ഥലം തിരഞ്ഞെടുക്കൽ", ["ശബ്ദ റെക്കോർഡ്", "എഡിറ്റിംഗ്", "마케팅"], "medium"),
    ("സ്റ്റോറിബോർഡ്", "ചിത്രീകരണത്തിനുമുമ്പുള്ള visual plan", ["അന്തിമ script", "പോസ്റ്റർ", "ടിക്കറ്റ്"], "easy"),
    ("ഷോട്ട് ലിസ്റ്റ്", "scene-wise planned shots", ["ബോക്സ് ഓഫീസ്", "റിവ്യൂ", "runtime"], "medium"),
    ("വസ്ത്ര continuity", "വേഷം的一致性", ["ശബ്ദ continuity", "ടിക്കറ്റ്", "മേള"], "hard"),
    ("സെറ്റ് dressing", "വിശദമായ പശ്ചാത്തലം", ["ADR", "നിറgrading", "IMDB"], "hard"),
    ("പ്രായോഗിക lighting", "ഫ്രെയിമിൽ visible sources", ["CGI light", "no lighting", "subtitle"], "hard"),
    ("ചുവപ്പ് symbolism", "passion/danger often", ["comedy always", "documentary always", "no meaning"], "hard"),
    ("depth staging", "foreground/background layers", ["single flat", "audio only", "text only"], "hard"),
    ("negative space", "empty area composition", ["crowded frame", "no composition", "sound only"], "hard"),
    ("symmetrical framing", "Wes Anderson style", ["handheld only", "no framing", "documentary only"], "hard"),
    ("silhouette", "backlit outline", ["high-key flat", "no contrast", "animation only"], "medium"),
    ("production value", "visual richness", ["runtime", "subtitle count", "ticket price"], "medium"),
]

SOUND: list[Fact] = [
    ("കഥാലോക ശബ്ദം", "ദൃശ്യത്തിൽ ഉത്ഭവിക്കുന്ന ശബ്ദം", ["പശ്ചാത്തല സംഗീതം", "ഉപശീർഷകം", "പോസ്റ്റർ"], "medium"),
    ("പശ്ചാത്തല സംഗീതം", "ദൃശ്യത്തിൽ ഇല്ലാത്ത ശബ്ദം/സംഗീതം", ["കഥാലോക ശബ്ദം", "സംഭാഷണം", "പാദശബ്ദം"], "medium"),
    ("ചലച്ചിത്ര സ്കോർ", "പശ്ചാത്തല സംഗീതം", ["ഉത്പാദന രൂപകൽപ്പന", "വസ്ത്രം", "കാസ്റ്റിംഗ്"], "easy"),
    ("ഫോളി", "post-recorded ശബ്ദ effects", ["on-set dialogue", "വസ്ത്രം", "ലൈറ്റിംഗ്"], "medium"),
    ("ADR", "post-ൽ dub ചെയ്ത dialogue", ["live on-set", "വസ്ത്രം", "props"], "hard"),
    ("ശബ്ദ മിക്സിംഗ്", "അന്തിമ audio balance", ["നിറgrading", "കാസ്റ്റിംഗ്", "마케팅"], "medium"),
    ("ശബ്ദ എഡിറ്റിംഗ്", "audio assembly", ["video editing", "വസ്ത്രം", "പോസ്റ്റർ"], "medium"),
    ("പരിസര ശബ്ദം", "environment background", ["solo music", "silent film", "subtitle"], "medium"),
    ("voice-over", "non-diegetic narration", ["diegetic", "silent", "subtitle only"], "easy"),
    ("മൗനം техник", "tension through absence", ["always loud", "no meaning", "always music"], "hard"),
    ("5.1 surround", "six-channel mix", ["mono only", "no channels", "text only"], "medium"),
    ("mono sound", "early talkies era", ["Atmos always", "7.1 always", "silent 2020"], "medium"),
    ("stereo sound", "two-channel", ["mono forever", "no channels", "text only"], "easy"),
    ("ലിപ് sync", "dialogue matching mouth", ["no dialogue", "ADR bad", "subtitle only"], "easy"),
    ("playback singing", "actor lip-sync to singer", ["live singing", "no music", "no sound"], "medium"),
    ("background score composer", "original music writer", ["costume designer", "gaffer", "prop master"], "easy"),
    ("theme song", "recurring musical motif", ["diegetic", "silent", "foley"], "easy"),
    ("leitmotif", "character-linked music", ["random noise", "no music", "subtitle"], "hard"),
    ("sound bridge", "audio links scenes", ["cut silence", "no audio edit", "visual only"], "hard"),
    ("J-cut", "hear next scene early", ["L-cut opposite", "no edit", "colour only"], "hard"),
    ("L-cut", "see next while audio prev", ["J-cut never", "no edit", "VFX only"], "hard"),
    ("subjective sound", "character mental perspective", ["objective", "silent", "mono"], "hard"),
    ("sound perspective", "distance simulation", ["no perspective", "mono flat", "colour only"], "hard"),
    ("MOS shot", "without sound recording", ["always recorded", "ADR bad", "never used"], "hard"),
    ("room tone", "location audio bed", ["silent", "music", "dialogue"], "hard"),
    ("walla", "crowd murmur loop", ["solo dialogue", "silent", "music"], "hard"),
]

PRODUCTION_ROLES: list[Fact] = [
    ("സംവിധായകൻ", "സൃഷ്ടിപരമായ ദിശ നൽകുന്നവർ", ["നിർമ്മാതാവ്", "എഡിറ്റർ", "ശബ്ദ സംവിധായകൻ"], "easy"),
    ("നിർമ്മാതാവ്", "ധനസഹായവും logistics", ["സംവിധായകൻ", "എഡിറ്റർ", "അഭിനേതാവ്"], "easy"),
    ("തിരക്കഥാകാരൻ", "script രചയിതാവ്", ["സംവിധായകൻ", "എഡിറ്റർ", "ഗaffer"], "easy"),
    ("ചിത്രമാപകൻ", "ക്യാമറയും lighting", ["എഡിറ്റർ", "ശബ്ദ", "costume"], "easy"),
    ("എഡിറ്റർ", "post-production assembly", ["സംവിധായകൻ", "costume", "actor"], "easy"),
    ("ഉത്പാദന രൂപകർത്താവ്", "visual environment", ["ശബ്ദ", "마케팅", "box office"], "medium"),
    ("വസ്ത്ര രൂപകർത്താവ്", "wardrobe creation", ["ശബ്ദ", "VFX", "ticket"], "medium"),
    ("മേക്കപ്പ് കലാകാരൻ", "appearance transformation", ["script", "finance", "distribution"], "medium"),
    ("ശബ്ദ രൂപകർത്താവ്", "audio landscape", ["costume", "props", "poster"], "medium"),
    ("സംഗീത സംവിധായകൻ", "original score", ["gaffer", "casting", "usher"], "easy"),
    ("കാസ്റ്റിംഗ് director", "actor selection", ["camera op", "editor", "composer"], "medium"),
    ("line producer", "day-to-day budget", ["actor", "critic", "audience"], "hard"),
    ("assistant director", "schedule coordination", ["composer", "distributor", "critic"], "medium"),
    ("script supervisor", "continuity notes", ["마케팅", "ticket", "usher"], "hard"),
    ("stunt coordinator", "action safety", ["costume", "dialogue writer", "composer"], "medium"),
    ("VFX supervisor", "visual effects", ["costume", "casting", "ticket"], "medium"),
    ("colorist", "final colour grade", ["sound mix", "casting", "stunt"], "hard"),
    ("distribution executive", "theatrical release", ["camera", "costume", "act"], "hard"),
    ("exhibitor", "theatre operator", ["screenwriter", "composer", "director"], "hard"),
    ("publicist", "media promotion", ["gaffer", "editor", "foley"], "hard"),
    ("choreographer", "dance sequences", ["sound mix", "VFX", "ticket"], "medium"),
    ("dialogue writer", "spoken lines", ["camera", "gaffer", "poster"], "medium"),
    ("ഗാനരചയിതാവ്", "song words", ["camera", "stunt", "ticket"], "easy"),
    ("music director", "song composition", ["costume", "gaffer", "poster"], "easy"),
    ("executive producer", "major funding", ["actor", "extra", "usher"], "hard"),
    ("associate producer", "production support", ["audience", "critic", "ticket buyer"], "hard"),
    ("unit production manager", "logistics admin", ["composer", "actor", "poster"], "hard"),
    ("boom operator", "dialogue microphone", ["costume", "poster", "ticket"], "hard"),
    ("focus puller", "camera focus assistant", ["costume", "lyricist", "usher"], "hard"),
]

PIPELINE: list[Fact] = [
    ("പൂർവ്വ ഉത്പാദനം", "ചിത്രീകരണത്തിനുമുമ്പുള്ള planning", ["തിയേറ്റrical release", "box office", "award"], "easy"),
    ("ഉത്പാദനം", "principal photography", ["마케팅", "distribution", "review"], "easy"),
    ("ഉത്തര ഉത്പാദനം", "edit, sound, colour, VFX", ["casting", "scouting", "financing"], "easy"),
    ("development", "script financing initial", ["theatrical run", "ticket", "festival premiere"], "hard"),
    ("principal photography", "main shooting schedule", ["trailer", "award", "dubbing"], "medium"),
    ("rough cut", "first editor assembly", ["colour grade", "premiere", "ticket"], "hard"),
    ("fine cut", "refined edit before sound", ["development", "casting", "scouting"], "hard"),
    ("colour grading stage", "final look", ["casting", "script", "financing"], "medium"),
    ("sound mix final", "theatrical audio master", ["costume", "scouting", "casting"], "medium"),
    ("VFX render", "CGI integration", ["costume", "audition", "press tour"], "hard"),
    ("마케팅 campaign", "promotion before release", ["photography", "script", "casting"], "easy"),
    ("theatrical window", "cinema exclusive period", ["development", "rough cut", "casting"], "medium"),
    ("OTT release", "digital platform debut", ["silent era", "development", "script pitch"], "medium"),
    ("സെൻസർ certification", "CBFC approval India", ["Oscar voting", "box office", "IMDB"], "easy"),
    ("dubbing", "other language voice", ["silent film", "costume", "poster"], "medium"),
    ("subtitling", "text translation", ["costume", "gaffer", "ticket"], "easy"),
    ("film festival premiere", "first public screening", ["development", "casting", "scouting"], "medium"),
    ("world premiere", "first ever public show", ["TV first", "OTT first", "home video first"], "hard"),
    ("trade screening", "industry preview", ["public opening", "OTT", "TV"], "hard"),
    ("test screening", "audience feedback", ["final release", "censor last", "award first"], "hard"),
    ("wrap party", "shoot completion", ["premiere", "Oscar", "OTT launch"], "hard"),
    ("call sheet", "daily shoot schedule", ["ticket stub", "review", "poster"], "hard"),
    ("daily rushes", "day footage review", ["theatrical print", "award", "ticket"], "hard"),
]

# Malayalam genre labels for GENRES pair category
GENRES_ML: list[tuple[str, str]] = [
    ("Psycho", "മനശ്ശാസ്ത്ര ത്രില്ലർ"),
    ("The Exorcist", "ഭീഷണി ചിത്രം"),
    ("Jaws", "_creature ത്രില്ലർ"),
    ("Star Wars", "സ്പേസ് ഓപ്പറ"),
    ("Blade Runner", "sci-fi noir"),
    ("The Matrix", "sci-fi action"),
    ("Mad Max Fury Road", "post-apocalyptic action"),
    ("Sholay", "മസാല വെസ്റ്റേൺ"),
    ("Dilwale Dulhania Le Jayenge", "പ്രണയ നാടകം"),
    ("Lagaan", "കായിക നാടകം"),
    ("3 Idiots", "campus comedy-drama"),
    ("Drishyam", "ക്രൈം ത്രില്ലർ"),
    ("Manichitrathazhu", "മനശ്ശാസ്ത്ര ഭീഷണി"),
    ("Bhargavi Nilayam", "മലയാളം ഭീഷണി"),
    ("Traffic", "hyperlink ത്രില്ലർ"),
    ("Premam", "പ്രണയ coming-of-age"),
    ("Bangalore Days", "യുവ നാടകം"),
    ("Kumbalangi Nights", "നാടകം"),
    ("Spirited Away", "anime fantasy"),
    ("My Neighbor Totoro", "anime family"),
    ("Toy Story", "CGI animation"),
    ("Finding Nemo", "Pixar adventure"),
    ("The Lion King", "animated musical"),
    ("Singin' in the Rain", "സംഗീത നാടകം"),
    ("La La Land", "modern musical"),
    ("Rocky", "കായിക നാടകം"),
    ("Raging Bull", "biographical sports"),
    ("Goodfellas", "crime biopic"),
    ("The Godfather", "ക്രൈം epic"),
    ("Pulp Fiction", "neo-noir"),
    ("No Country for Old Men", "neo-western thriller"),
    ("Unforgiven", "revisionist western"),
    ("Django Unchained", "spaghetti western homage"),
    ("Crouching Tiger", "wuxia"),
    ("RRR", "action epic"),
    ("Baahubali", "historical fantasy"),
    ("KGF", "action crime"),
    ("Pushpa", "action drama"),
    ("Documentary — An Inconvenient Truth", "environment documentary"),
    ("March of the Penguins", "nature documentary"),
    ("Michael Moore documentaries", "political documentary"),
    ("Nanook of the North", "early documentary"),
    ("Man with a Movie Camera", "experimental documentary"),
]
