#!/usr/bin/env python3
"""Sanitize coi20_data into coi_wave20_clean_data.py (Malayalam-only)."""

from __future__ import annotations

import pprint
import re
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "coi_wave20_clean_data.py"

MIXED = re.compile(r"[\u0D00-\u0D7F][a-zA-Z]|[a-zA-Z][\u0D00-\u0D7F]")
_LATIN4 = re.compile(r"[a-zA-Z]{4,}")
ALLOWED = re.compile(r"\b(GST|UPSC|CAG|NJAC|NCSC|NCST|NCBC|EWS)\b")
PLACEHOLDER = re.compile(r"^അനുച്ഛേദം .+ വ്യവസ്ഥ$")

NAME_FIX = {
    "മിസoram": "മിസോറം", "നാഗaland": "നാഗാലാൻഡ്", "ഛത്തീസ്ഗarh": "ഛത്തീസ്ഗഡ്",
    "ജammu കശ്മീർ": "ജമ്മു-കശ്മീർ", "ലadakh": "ലഡാക്", "ചണ്ഡigarh": "ചണ്ഡീഗഡ്",
    "ദādra നഗർ ഹവേലി": "ദാദ്ര നഗർ ഹവേലി", "ലക്ഷദweep": "ലക്ഷദ്വീപ്",
    "കൺട്രോളർ ആൻഡ് ഓഡിറ്റർ ജനറൽ": "നിയന്ത്രണ-ഓഡിറ്റ് ജനറൽ",
    "അറ്റോർണി ജനറൽ": "മുഖ്യ നിയമോപദേശകൻ",
    "pension ലabh്യമാക്കൽ": "വിരമണാനന്തര ആനുകൂല്യം",
    "pension ലഭ്യമാക്കൽ": "വിരമണാനന്തര ആനുകൂല്യം",
    "സത്യപ്രതിജ്ഞയും രഹസ്യസംrakshan": "സത്യപ്രതിജ്ഞാ രൂപവും രഹസ്യം പാലിക്കൽ",
    "Inter-State Council": "അന്തരസംസ്ഥാന കൗൺസിൽ",
    "Consolidated Fund": "ഏകീകൃത നിധി",
    "Contingency Fund": "അനിശ്ചിത നിധി",
    "Finance Commission": "ധനകമ്മിഷൻ",
    "Election Commission": "തിരഞ്ഞെടുപ്പ് കമ്മീഷൻ",
    "President Rule": "രാഷ്ട്രപതി ഭരണം",
    "National Emergency": "ദേശീയ അടിയന്തരാവസ്ഥ",
    "Financial Emergency": "ധനകാര്യ അടിയന്തരാവസ്ഥ",
    "official language Hindi": "ഔദ്യോഗിക ഭാഷ ഹിന്ദി",
    "state official language": "സംസ്ഥാന ഔദ്യോഗിക ഭാഷ",
    "language of Supreme Court": "സുപ്രീംകോടതിയുടെ ഭാഷ",
    "Hindi development directive": "ഹിന്ദി വികസന നിർദ്ദേശം",
    "8th schedule language": "എട്ടാം ഷെഡ്യൂളിലെ ഭാഷ",
    "official language union": "കേന്ദ്ര ഔദ്യോഗിക ഭാഷ",
    "continues for 15 years": "15 വർഷം തുടരുന്നു",
    "Zonal Councils": "മേഖലാ കൗൺസിലുകൾ",
    "5 zonal councils": "അഞ്ച് മേഖലാ കൗൺസിലുകൾ",
    "no-confidence motion": "അവിശ്വാസ പ്രമേയം",
    "joint session": "സംയുക്ത അധിവേശം",
    "parliament privileges": "പാർലമെന്റ്特権",
    "motion of thanks": "നന്ദി പ്രമേയം",
    "casting vote": "നിർണായക വോട്ട്",
    "speaker casting vote": "സ്പീക്കറുടെ നിർണായക വോട്ട്",
    "money bill definition": "ധനബിൽ നിർവചനം",
    "annual financial statement": "വാർഷിക ധനകാര്യ പ്രസ്താവന",
    "administrative tribunals": "ഭരണ ധികാരണങ്ങൾ",
    "other tribunals": "മറ്റ് ധികാരണങ്ങൾ",
    "Part XIV-A added": "ഭാഗം XIV-A ചേർത്തു",
    "cooperative societies constitutional status": "സഹകരണ സമിതികൾക്ക് ഭരണഘടനാ നില",
    "Canada": "കാനഡ",
    "Australia": "ഓസ്ട്രേലിയ",
    "Japan": "ജപ്പാൻ",
    "UK": "ഇംഗ്ലണ്ട്",
    "USA": "അമേരിക്ക",
    "Ireland": "അയർലൻഡ്",
    "Germany": "ജർമ്മനി",
    "USSR": "സോവിയറ്റ് യൂണിയൻ",
    "South Africa": "ദക്ഷിണാഫ്രിക്ക",
    "secularism": "മതേതരത്വം",
    "federalism": "സംഘടിതാധിപത്യം",
    "democracy": "ജനാധിപത്യം",
    "rule of law": "നിയമത്തിന്റെ ആധിപത്യം",
    "judicial review": "നീതിപരിശോധന",
    "separation of powers": "അധികാര വേർതിരിവ്",
    "free and fair elections": "സ്വതന്ത്രവും നീതിയുള്ളതുമായ തിരഞ്ഞെടുപ്പുകൾ",
    "welfare state": "ക്ഷേമ രാഷ്ട്രം",
    "limited amending power": "പരിമിത ഭേദഗതി അധികാരം",
    "quasi-federal structure": "അർദ്ധ-സംഘടിത ഘടന",
    "single citizenship": "ഏക പൗരത്വം",
    "parliamentary system from UK": "ഇംഗ്ലണ്ടിൽ നിന്നുള്ള പാർലമെന്റ് സംവിധാനം",
    "fundamental rights from USA": "അമേരിക്കയിൽ നിന്നുള്ള മൗലികാവകാശങ്ങൾ",
    "DPSP from Ireland": "അയർലൻഡിൽ നിന്നുള്ള നിർദ്ദേശക തത്വങ്ങൾ",
    "emergency provisions from Germany": "ജർമ്മനിയിൽ നിന്നുള്ള അടിയന്തരാവസ്ഥാ വ്യവസ്ഥകൾ",
    "fundamental duties from USSR": "സോവിയറ്റ് യൂണിയനിൽ നിന്നുള്ള മൗലിക കടമകൾ",
    "amendment procedure from South Africa": "ദക്ഷിണാഫ്രിക്കയിൽ നിന്നുള്ള ഭേദഗതി നടപടിക്രമം",
    "federation with strong centre from Canada": "കാനഡയിൽ നിന്നുള്ള ശക്തമായ കേന്ദ്രമുള്ള federation",
    "concurrent list from Australia": "ഓസ്ട്രേലിയയിൽ നിന്നുള്ള സമാന്തര പട്ടിക",
    "procedure established by law from Japan": "ജപ്പാനിൽ നിന്നുള്ള നിയമപ്രകാരമുള്ള നടപടിക്രമം",
    "longest written constitution": "ഏറ്റവും നീളമുള്ള written constitution",
    "395 articles originally": "最初 395 അനുച്ഛേദങ്ങൾ",
    "12 schedules originally": "最初 12 ഷെഡ്യൂളുകൾ",
    "448 articles approximately": "ഏകദേശം 448 അനുച്ഛേദങ്ങൾ",
    "12 schedules now": "ഇപ്പോൾ 12 ഷെഡ്യൂളുകൾ",
    "25 parts active": "25 സജീവ ഭാഗങ്ങൾ",
    "preamble qualities": "ആമുഖത്തിലെ ഗുണങ്ങൾ",
    "universal adult franchise": "സാർവത്രിക adult franchise",
    "independent judiciary": "സ്വതന്ത്ര നിയമ നirvahana",
    "integrated judiciary": "ഏകീകൃത judiciary",
    "dual polity": "ദ്വി-രാഷ്ട്രീയ ഘടന",
    "written constitution": "ലിഖിത ഭരണഘടന",
    "mix of rigid and flexible": "കടുക്കവും гибкийയും",
    "simple majority": "സാധാരണ ഭൂരിപക്ഷം",
    "special majority": "പ്രത്യേക ഭൂരിപക്ഷം",
    "ratification": "സംസ്ഥാന_ratification",
    "state ratification": "സംസ്ഥാന_ratification",
    "GST": "ജി.എസ്.ടി.",
    "101st amendment": "101-ാം ഭേദഗതി",
    "103rd amendment": "103-ാം ഭേദഗതി",
    "106th amendment": "106-ാം ഭേദഗതി",
    "104th amendment": "104-ാം ഭേദഗതി",
    "102nd amendment": "102-ാം ഭേദഗതി",
    "EWS reservation": "EWS സംവരണം",
    "women reservation": "സ്ത്രീ സംവരണം",
    "women reservation 33%": "33% സ്ത്രീ സംവരണം",
    "10% EWS reservation": "10% EWS സംവരണം",
    "SC/ST reservation extension": "എസ്.സി./എസ്.ടി. സംവരണം നീട്ടം",
    "NCBC constitutional status": "NCBC-ക്ക് ഭരണഘടനാ നില",
    "state list OBC": "സംസ്ഥാന പട്ടികയിലെ OBC",
    "OBC reservation": "OBC സംവരണം",
    "Mandal commission": "മandal കമ്മീഷൻ",
    "anti-defection": "anti-defection",
    "mini constitution": "മini ഭരണഘടന",
    "zamindari abolition acts protected": "ജമീന്ദാരി നിരോധന നിയമങ്ങൾ",
    "judicial review": "നീതിപരിശോധന",
    "basic structure review after Coelho": "കോയൽഹോ കേസിന് ശേഷം അടിസ്ഥാന ഘടനാ പരിശോധന",
    "284+ acts listed": "284+ നിയമങ്ങൾ",
    "future laws cannot be validated": "ഭാവി നിയമങ്ങൾ സാധൂകരിക്ക 불가",
    "Kesavananda impact": "കേശവാനന്ദ സ്വാധീനം",
    "Waman Rao case": "വാമൻ റാവു കേസ്",
    "scheduled areas": "അനുബന്ധിത പ്രദേശങ്ങൾ",
    "scheduled tribes areas": "ഗിരിജന قبائل പ്രദേശങ്ങൾ",
    "TAC Tribes Advisory Council": "ഗിരിജന ഉപദേശക സമിതി",
    "autonomous district governor": "സ്വയംഭരണ ജില്ലാ ഭരണം",
    "autonomous districts": "സ്വയംഭരണ ജില്ലകൾ",
    "manipur autonomous district council": "മണിപ്പൂർ സ്വയംഭരണ ജില്ലാ കൗൺസിൽ",
    "santhal parganas": "സാന്താൽ പർഗനാസ്",
    "north cachar hills": "North Cachar Hills",
    "scheduled tribes areas": "ഗിരിജന قبائل പ്രദേശങ്ങൾ",
    "land reforms acts": "ഭൂ reform നിയമങ്ങൾ",
    "284+ acts listed": "284+ നിയമങ്ങൾ",
    "Parliament alone cannot": "പാർലമെന്റ് മാത്രം കഴിയില്ല",
    "election validity": "തിരഞ്ഞെടുപ്പ് സാധുത",
    "356-ന്റെ judicial review": "356-ന്റെ നീതിപരിശോധന",
    "habeas corpus": "ഹേബിയസ് കോർപ്പസ്",
    "privacy fundamental right": "സ്വകാര്യത മൗലികാവകാശം",
    "environment PIL": "പരിസ്ഥിതി PIL",
    "nationalisation compensation": "ദേശീയകരണ നഷ്ടപരിഹാരം",
    "bank nationalisation": "ബാങ്ക് ദേശീയകരണം",
    "reservation creamy layer": "സംവരണ ക്രീം ലെയർ",
    "religion in election": "തിരഞ്ഞെടുപ്പിൽ മതം",
    "OBC 27%": "27% OBC",
    "Hindutva election": "ഹിന്ദുത്വ തിരഞ്ഞെടുപ്പ്",
    "backward classes": "പിന്നോക്ക വർഗ്ഗങ്ങൾ",
    "corrupt practice religion": "ദുrachar religion",
    "reservation in promotion": "promotion-ൽ സംവരണം",
    "reservation promotion": "promotion-ൽ സംവരണം",
    "carry forward rule": "carry forward rule",
    "religion appeal": "മത appeal",
    "27% OBC": "27% OBC",
    "OBC creamy layer": "OBC ക്രീം ലെയർ",
    "OBC reservation 27%": "27% OBC സംവരണം",
    "backward classes employment": "പിന്നോക്ക വർഗ്ഗങ്ങളുടെ തൊഴിൽ",
    "socially/educationally backward": "സാമൂഹിക/വിദ്യാഭ്യാസ പിന്നോക്കം",
    "Lok Sabha SC/ST reservation": "ലോക്സഭ എസ്.സി./എസ്.ടി. സംവരണം",
    "Anglo-Indian nomination": "ആംഗ്ലോ-ഇന്ത്യൻ nomination",
    "State assembly SC/ST reservation": "നിയമസഭ എസ്.സി./എസ്.ടി. സംവരണം",
    "reservation duration": "സംവരണ കാലാവധി",
    "SC/ST claims": "എസ്.സി./എസ്.ടി. claims",
    "SC/ST advisory council": "എസ്.സി./എസ്.ടി. ഉപദേശക സമിതി",
    "Backward classes commission": "പിന്നോക്ക വർഗ്ഗ കമ്മീഷൻ",
    "SC list": "പട്ടികജാതി പട്ടിക",
    "ST list": "പട്ടികവർഗ്ഗ പട്ടിക",
    "panchayat reservation": "പഞ്ചായത്ത് സംവരണം",
    "panchayat women reservation": "പഞ്ചായത്ത് സ്ത്രീ സംവരണം",
    "municipality women reservation": "നഗരസഭാ സ്ത്രീ സംവരണം",
    "Maharashtra-Gujarat special provision": "മഹാരാഷ്ട്ര-ഗുജറാത്ത് പ്രത്യേക വ്യവസ്ഥ",
    "Nagaland special provision": "നാഗാലാൻഡ് പ്രത്യേക വ്യവസ്ഥ",
    "Assam special provision": "അസം പ്രത്യേക വ്യവസ്ഥ",
    "Manipur special provision": "മണിപ്പൂർ പ്രത്യേck വ്യവസ്ഥ",
    "Andhra Pradesh special provision": "ആന്ധ്രപ്രദേശ് പ്രത്യേക വ്യവസ്ഥ",
    "Sikkim special provision": "സിക്കിം പ്രത്യേക വ്യവസ്ഥ",
    "Mizoram special provision": "മിസോറം പ്രത്യേക വ്യവസ്ഥ",
    "Arunachal Pradesh special provision": "അരുണാചൽ പ്രദേശ് പ്രത്യേക വ്യവസ്ഥ",
    "Goa special provision": "ഗോവ പ്രത്യേക വ്യവസ്ഥ",
    "Hyderabad-Karnataka special provision": "ഹൈദരാബാദ്-കarnataka പ്രത്യേക വ്യവസ്ഥ",
    "Kalyana Karnataka special provision": "കalyana Karnataka പ്രത്യേക വ്യവസ്ഥ",
    "Jammu Kashmir special status repealed": "ജമ്മു-കാശ്മീർ പ്രത്യേക നില നീക്കം",
    "Maharashtra Gujarat": "മഹാരാഷ്ട്ര-ഗുജറാത്ത്",
    "Nagaland": "നാഗാലാൻഡ്",
    "Kalyana Karnataka": "കalyana Karnataka",
    "CAT": "കേന്ദ്ര ഭരണ ധികാരണ",
    "Central Administrative Tribunal": "കേന്ദ്ര ഭരണ ധികാരണ",
    "ITAT": "Income Tax Appellate Tribunal",
    "NCLT": "ദേശീയ കമ്പനി നിയമ ധികാരണ",
    "NCLAT": "ദേശീയ കമ്പനി നിയമ അpellate ധികാരണ",
    "SAT": "Securities Appellate Tribunal",
    "TDSAT": "Telecom Disputes Settlement",
    "AFT": "Armed Forces Tribunal",
    "NGT": "ദേശീയ പരിസ്ഥിതി ധികാരണ",
    "DRT": "Debt Recovery Tribunal",
    "Part IX-B": "ഭാഗം IX-B",
    "Part XIV-A": "ഭാഗം XIV-A",
    "243ZI": "243ZI",
    "243ZJ": "243ZJ",
    "243ZK": "243ZK",
    "243ZL": "243ZL",
    "243ZM": "243ZM",
    "243ZN": "243ZN",
    "243ZO": "243ZO",
    "243ZP": "243ZP",
    "42-ാം ഭേദഗതി": "42-ാം ഭേദഗതി",
    "97-ാം ഭേദഗതി": "97-ാം ഭേദഗതി",
    "101-ാം ഭേദഗതി": "101-ാം ഭേദഗതി",
    "106-ാം ഭേദഗതി": "106-ാം ഭേദഗതി",
    "103-ാം ഭേദഗതി": "103-ാം ഭേദഗതി",
    "104-ാം ഭേദഗതി": "104-ാം ഭേദഗതി",
    "102-ാം ഭേദഗതി": "102-ാം ഭേദഗതി",
    "105-ാം ഭേദഗതി": "105-ാം ഭേദഗതി",
    "77-ാം ഭേദഗതി": "77-ാം ഭേദഗതി",
    "81-ാം ഭേദഗതി": "81-ാം ഭേദഗതി",
    "73-ാം ഭേദഗതി": "73-ാം ഭേദഗതി",
    "74-ാം ഭേദഗതി": "74-ാം ഭേദഗതി",
    "86-ാം ഭേദഗതി": "86-ാം ഭേദഗതി",
    "91-ാം ഭേദഗതി": "91-ാം ഭേദഗതി",
    "61-ാം ഭേദഗതി": "61-ാം ഭേദഗതി",
    "52-ാം ഭേദഗതി": "52-ാം ഭേദഗതി",
    "44-ാം ഭേദഗതി": "44-ാം ഭേദഗതി",
    "42-ാം ഭേദഗതി": "42-ാം ഭേദഗതി",
    "36-ാം ഭേദഗതി": "36-ാം ഭേദഗതി",
    "24-ാം ഭേദഗതി": "24-ാം ഭേദഗതി",
    "7-ാം ഭേദഗതി": "7-ാം ഭേദഗതി",
    "2-ാം ഭേദഗതി": "2-ാം ഭേദഗതി",
    "1-ാം ഭേദഗതി": "1-ാം ഭേദഗതി",
    "സanskrit": "സംസ്കൃതം",
    "ബengali": "ബengali",
    "ഗujarati": "ഗujarati",
    "മarathi": "മarathi",
    "തelugu": "തelugu",
    "കannada": "കannada",
    "ഒriya": "ഒriya",
    "പunjabi": "പunjabi",
    "അssamese": "അssamese",
    "മanipuri": "മanipuri",
    "നepali": "നepali",
    "ബodo": "ബodo",
    "ഡogri": "ഡogri",
    "മaithili": "മaithili",
    "സantali": "സantali",
    "സindhi": "സindhi",
}

# This approach is getting too messy with partial English fixes.
# Write clean data from scratch using verified lists only.

print("Use coi_wave20_clean_data.py partial + builder instead")
