#!/usr/bin/env python3
"""Wave 30 communication / journalism facts — 30 Kerala PSC topic types."""

from __future__ import annotations

import random

from refill_common import Candidate
from wave30_emit import emit_category, emit_direct

COMM_MODELS: list[tuple[str, str]] = [
    ('SMCR മോഡൽ', 'ഡേവിഡ് ബെർലോ'),
    ('ഷാനൺ-വീവർ മോഡൽ', 'ക്ലോഡ് ഷാനൺ'),
    ('ലാസ്വെൽ മോഡൽ', 'ഹാരോൾഡ് ലാസ്വെൽ'),
    ('ഒസ്ഗുഡ്-ഷ്രം മോഡൽ', 'ചാൾസ് ഒസ്ഗുഡ്'),
    ('ഹെലിക്സ് മോഡൽ', 'ഫ്രാങ്ക് ഡാൻസ്'),
    ('ഗേറ്റ്കീപ്പിംഗ് മോഡൽ', 'കുർട്ട് ലെവിൻ'),
    ('അജണ്ട സെറ്റിംഗ്', 'മакс്വെൽ മക്കോംബ്സ്'),
    ('ടു-സ്റ്റെപ്പ് ഫ്ലോ', 'പോൾ ലാസർഫെൽഡ്'),
    ('മാജിക് ബുള്ളറ്റ്', '1920-കളിലെ പ്രചാരണ സിദ്ധാന്തം'),
    ('നോയിസ് (കോലാഹലം)', 'സന്ദേശ കൈമാറ്റത്തിന് തടസ്സം'),
    ('എൻകോഡർ', 'സന്ദേശം അയക്കുന്ന ഭാഗം'),
    ('ഡീകോഡർ', 'സന്ദേശം സ്വീകരിക്കുന്ന ഭാഗം'),
    ('ചാനൽ', 'സന്ദേശം കടന്നുപോകുന്ന മാധ്യമം'),
    ('ഫീഡ്ബാക്ക്', 'സ്വീകരിക്കുന്നവന്റെ പ്രതികരണം'),
    ('ബാരിയർ', 'ആശയവിനിമയ തടസ്സം'),
    ('സെമantics', 'അർത്ഥവാദം'),
    ('സിന്റാക്സ്', 'ഘടനാവാദം'),
    ('പ്രാഗ്മatics', 'സന്ദർഭോചിത അർത്ഥം'),
    ('മാസ് കമ്മ്യൂണിക്കേഷൻ', 'വിപുലമായ പ്രേക്ഷകർ'),
    ('ഇന്റർപേഴ്സണൽ', 'രണ്ട് വ്യക്തികൾ'),
]
COMM_THEORIES: list[tuple[str, str]] = [
    ('ടു-സ്റ്റെപ്പ് ഫ്ലോ', 'പോൾ ലാസർഫെൽഡ്'),
    ('കൾട്ടിവേഷൻ', 'ജോർജ്ജ് ഗെർബ്നർ'),
    ('അജenda സെറ്റിംഗ്', 'മക്കോംബ്സ്-ഷാ'),
    ('മാജിക് ബുള്ളറ്റ്', '1920-കളിലെ പ്രചാരണ'),
    ('യൂസ് ആൻഡ് ഗ്രatifിക്കേഷൻ', 'എലിഹു കാറ്റ്സ്'),
    ('സോഷ്യൽ കോഗ്നിറ്റീവ്', 'ആൽബർട്ട് ബന്ദura'),
    ('സ്പിരൽ ഓഫ് സൈലൻസ്', 'എലിസabeth Noelle-Neumann'),
    ('ഫ്രെയിമിംഗ്', 'എർവിംഗ് ഗോഫ്മാൻ'),
    ('അജenda ബിൽഡിംഗ്', 'പീറ്റർ ലാംഗ്'),
    ('നോർം ക്രിട്ടിക്കൽ', 'യുർഗൻ ഹേബർമാസ്'),
    ('പബ്ലിക് സ്ഫിയർ', 'യുർഗൻ ഹേബർമാസ്'),
    ('മീഡിയ ഡെpendency', 'ബല്ലറോക്ക്-കാറ്റ്സ്'),
    ('സോഷ്യൽ ലേർണിംഗ്', 'ആൽബർട്ട് ബന്ദura'),
    ('ഡിഫ്യൂഷൻ ഓഫ് ഇnnovations', 'എവrett Rogers'),
    ('കൾച്ചറൽ സ്റ്റഡീസ്', 'സ്റ്റുവർട്ട് ഹാൾ'),
    ('ഹെഗemony', 'അന്റോണിയോ ഗ്രാംഷി'),
    ('പ്രോpaganda', 'വിൽബർ ശ്രം'),
    ('സെമiotics', 'ഫെർdinand de Saussure'),
    ('ഗ്ലോബൽ vilLAGE', 'മാർഷൽ മക്ലൂഹൻ'),
    ('മീഡിയം is the Message', 'മാർഷൽ മക്ലൂഹൻ'),
]
THEORY_MEANING: list[tuple[str, str]] = [
    ('മാജിക് ബുള്ളറ്റ്', 'മാധ്യം即时的强影响'),
    ('ടു-സ്റ്റെപ്പ് ഫ്ലോ', 'ഓപീനിയൻ ലീഡർമാർ വഴി'),
    ('കൾട്ടിവേഷൻ', 'ടിവി ദീർഘകാല സ്വാധീനം'),
    ('അജenda സെറ്റിംഗ്', 'എന്ത് ചിന്തിക്കണം'),
    ('ഫ്രെയിമിംഗ്', 'വാർത്തയുടെ ചട്ടക്കൂട്'),
    ('സ്പiral ഓഫ് സൈലൻസ്', 'പരസ്യ അഭിപ്രായം'),
    ('യൂസ് ആൻഡ് ഗ്രatifിക്കേഷൻ', 'ആവശ്യം പൂർത്തിയാക്കൽ'),
    ('സോഷ്യൽ കോഗ്നിറ്റീവ്', 'മാധ്യം വഴി പഠനം'),
    ('പബ്ലിക് സ്ഫിയർ', 'പൊതു ചർച്ചാ മണ്ഡലം'),
    ('ഡിഫ്യൂഷൻ', 'പുതിയ ആശയം പ്രചരണം'),
    ('ഹെഗemony', 'സാംസ്കാരിക ആധിപത്യം'),
    ('ഗേറ്റ്കീപ്പിംഗ്', 'വാർത്ത തിരഞ്ഞെടുക്കൽ'),
    ('പ്രൈമിംഗ്', 'വാർത്തയുടെ ഫ്രെയിം'),
    ('സ്പiral', '少数派沉默'),
    ('മീഡിയ dependency', 'മാധ്യമത്തോടുള്ള ആശ്രയം'),
    ('കൾച്ചർ ഇndustry', 'സാംസ്കാരിക ഉൽപ്പാദനം'),
    ('സെമiotics', 'ചിഹ്നങ്ങളുടെ പഠനം'),
    ('നോർം ക്രിട്ടിക്കൽ', 'സംവാദത്തിന്റെ നിയമം'),
    ('മീഡിയ ലിറ്ററസി', 'മാധ്യമം വിമർശിക്കൽ'),
    ('ഫейк ന്യൂസ്', 'തെറ്റായ വാർത്ത'),
]
MALAYALAM_FIRST: list[tuple[str, str]] = [
    ('മലയാളത്തിലെ ആദ്യ പത്രം', 'രാജ്യസമാചാരം'),
    ('കേരളത്തിലെ ആദ്യ ദൈനികം', 'ദീപിക'),
    ('കേരളത്തിലെ ആദ്യ വൈകുന്നേരപ്പത്രം', 'പ്രദീപം'),
    ('മലയാളത്തിലെ ആദ്യ വനിതാ മാസിക', 'സുഗുണബോധിനി'),
    ('മലയാളത്തിലെ ആദ്യ സാഹിത്യ മാസിക', 'വിദ്യാവിനോദിനി'),
    ('മലയാളത്തിലെ ആദ്യ കാർട്ടൂൺ മാസിക', 'വികടൻ'),
    ('കേരളത്തിലെ ആദ്യ ഇംഗ്ലീഷ് ദിനപത്രം', 'ദി വെസ്റ്റേൺ സ്റ്റാർ'),
    ('മലയാളത്തിലെ ആദ്യ സ്വകാര്യ ടിവി', 'ഏഷ്യാനെറ്റ്'),
    ('കേരളത്തിലെ ആദ്യ കമ്മ്യൂണിറ്റി റേഡിയോ', 'റേഡിയോ മറ്റൊലി'),
    ('കേരളത്തിലെ ആദ്യ സ്വകാര്യ എഫ്എം', 'റേഡിയോ മാംഗോ'),
    ('ജ്ഞാനനിക്ഷേപം ആരംഭിച്ച സ്ഥലം', 'കോട്ടയം'),
    ('CMS പ്രസ്സ്', 'കോട്ടയം'),
    ('തലശ്ശേരി പത്രപ്രവർത്തനം', 'ഹെർമൻ ഗുണ്ടർട്ട്'),
    ('മലയാള മനോരമ ആരംഭം', '1888'),
    ('മാതൃഭൂമി ആരംഭം', '1930'),
    ('ദേശാഭിമാനി ആരംഭം', '1942'),
    ('കേരള കൗമുദി', '1911'),
    ('ഭാഷാപോഷിണി', '1896'),
    ('അൽ അമീൻ', '1924'),
    ('സ്വദേശാഭിമാനി', '1906'),
]
MALAYALAM_FOUNDER: list[tuple[str, str]] = [
    ('ഹെർമൻ ഗുണ്ടർട്ട്', 'രാജ്യസമാചാരം'),
    ('കണ്ടത്തിൽ വർഗീസ് മാപ്പിള', 'മലയാള മനോരമ'),
    ('കെ. പി. കേശവമേനോൻ', 'മാതൃഭൂമി'),
    ('വക്കം അബ്ദുൽ ഖാദർ മൗലവി', 'സ്വദേശാഭിമാനി'),
    ('സി. വി. കുഞ്ഞുരാമൻ', 'കേരള കൗമുദി'),
    ('സി. കൃഷ്ണൻ', 'മിതവാദി'),
    ('മുഹമ്മദ് അബ്ദുൽ റഹ്മാൻ സാഹിബ്', 'അൽ അമീൻ'),
    ('ടി. കെ. മാധവൻ', 'ദേശാഭിമാനി'),
    ('കെ. രാമകൃഷ്ണപിള്ള', 'സ്വദേശാഭിമാനി'),
    ('പി. വി. സാമി', 'മാതൃഭൂമി'),
    ('കെ. കേളപ്പൻ', 'മാതൃഭൂമി'),
    ('കുറൂർ നീലകണ്ഠൻ', 'മാതൃഭൂമി'),
    ('പോത്തൻ ജോസഫ്', 'ദി ഹിന്ദുസ്ഥാൻ ടൈംസ്'),
    ('പി. സായിനാഥ്', 'പി. എസ്. ജേർണലിസം'),
    ('എ. കെ. ഗോപാലൻ', 'ദേശാഭിമാനി'),
    ('എം. വി. രാഘവൻ', 'മാർക്സിസ്റ്റ് പത്രപ്രവർത്തനം'),
    ('എ. ശശീന്ദ്രൻ', 'മാതൃഭൂമി'),
    ('എം. പി. വീരേന്ദrakumar', 'മാതൃഭൂമി'),
    ('എം. എം. മണി', 'മനോരമ'),
    ('എ. കെ. ആന്റണി', 'മനോരമ'),
]
MALAYALAM_PRESS_YEAR: list[tuple[str, str]] = [
    ('രാജ്യസമാചാരം', '1847'),
    ('മലയാള മനോരമ', '1888'),
    ('മാതൃഭൂമി', '1930'),
    ('ദീപിക', '1887'),
    ('കേരള കൗമുദി', '1911'),
    ('സ്വദേശാഭിമാനി', '1906'),
    ('ദേശാഭിമാനി', '1942'),
    ('അൽ അമീൻ', '1924'),
    ('ഭാഷാപോഷിണി', '1896'),
    ('പ്രദീപം', '1934'),
    ('വിദ്യാവിനോദിനി', '1890'),
    ('വികടൻ', '1984'),
    ('സുഗുണബോധിനി', '1904'),
    ('മിതവാദി', '1915'),
    ('ജ്ഞാനനിക്ഷേപം', '1903'),
    ('ഏഷ്യാനെറ്റ്', '1993'),
    ('കൈരളി', '2000'),
    ('സൂര്യ', '1998'),
    ('മനorama ഓൺലൈൻ', '1996'),
    ('മാതൃഭൂമി ഓൺലൈൻ', '1997'),
]
INDIA_PRESS_HISTORY: list[tuple[str, str]] = [
    ('ഇന്ത്യയിലെ ആദ്യ വാർത്താപത്രം', 'ബംഗാൾ ഗസറ്റ്'),
    ('ഇന്ത്യൻ പത്രപ്രവർത്തനത്തിന്റെ പിതാവ്', 'ജെയിംസ് അഗസ്റ്റസ് ഹിക്കി'),
    ('ബംഗാൾ ഗസറ്റ്', '1780'),
    ('ബോംബെ സമാചാർ', '1822'),
    ('ദി ഹിന്ദു', '1878'),
    ('ടൈംസ് ഓഫ് ഇന്ത്യ', '1838'),
    ('അമൃത ബസാർ പത്രിക', '1868'),
    ('ഹിന്ദustan ടൈംസ്', '1924'),
    ('ദി ഇന്ത്യൻ express', '1932'),
    ('ദേശാഭിമാനി', '1942'),
    ('സ്വദേശാഭിമാനി സെൻസർഷിപ്പ്', '1910'),
    ('ഇന്ത്യൻ ഒപ്പീനിയൻ', 'മഹാത്മാഗാന്ധി'),
    ('ഹരിജൻ', 'മഹാത്മാഗാന്ധി'),
    ('യംഗ് ഇന്ത്യ', 'മഹാത്മാഗാന്ധി'),
    ('കേസരി', 'ബാലഗംഗാധര തിലകൻ'),
    ('മറാട്ട', 'ബാലഗംഗാധര തിലകൻ'),
    ('മൂക് നായക്', 'ബി. ആർ. അംബേദ്കർ'),
    ('നാഷണൽ ഹെrald', 'ജവഹർലാൽ നെഹ്റു'),
    ('ഫിലിം ഇന്ത്യ', '1952'),
    ('Rediff.com', '1996'),
]
INDIA_PRESS_PIONEER: list[tuple[str, str]] = [
    ('ജെയിംസ് അഗസ്റ്റസ് ഹിക്കി', 'ബംഗാൽ ഗസറ്റ്'),
    ('രാജാ റാം മോഹൻ റോയ്', 'സമ്വാദ് കൗമുദി'),
    ('ബാലഗംഗാധര തിലകൻ', 'കേസരി'),
    ('മഹാത്മാഗാന്ധി', 'ഹരിജൻ'),
    ('ജവഹർലാൽ നെഹ്റു', 'നാഷണൽ ഹെrald'),
    ('ബി. ആർ. അംബേദ്കർ', 'മൂക് നായക്'),
    ('സുഭാഷ് ചന്ദ്രബോസ്', 'ഫോർward Bloc'),
    ('പോത്തൻ ജോസഫ്', 'പത്രപ്രവർത്തക അവകാശങ്ങൾ'),
    ('ഗോപാലകൃഷ്ണ ഗോഖലെ', 'സുധർമ'),
    ('ലാലാ ലജ്പത് റായ്', 'പഞ്ജാബീ'),
    ('ബിപിൻ ചന്ദ്രപാൽ', 'സ്വദേശ'),
    ('എ. ജി. ഗാർഡിനർ', 'ദി ഹിന്ദു'),
    ('എസ്. സ.adanand', 'ദി ഹിന്ദു'),
    ('രമണാഥ് ഗോയങ്ക', 'ഇന്ത്യൻ express'),
    ('എസ്. മുkherjee', 'ആനന്ദ ബസാർ'),
    ('എം. ജെ. അകbar', 'India Today'),
    ('വിനോദ് മേheta', 'India Today'),
    ('പ്രannoy Roy', 'NDTV'),
    ('രadika Roy', 'NDTV'),
    ('അrnab Goswami', 'Republic TV'),
]
JOURNALISM_TERMS: list[tuple[str, str]] = [
    ('ഗേറ്റ്കീപ്പിംഗ്', 'വാർത്ത തിരഞ്ഞെടുക്കൽ'),
    ('ഫ്രെയിമിംഗ്', 'വാർത്തയുടെ ചട്ടക്കൂട്'),
    ('അജenda സെറ്റിംഗ്', 'പ്രാധാന്യമാക്കൽ'),
    ('ഇൻവേർട്ടഡ് പിരമിഡ്', 'പ്രധാന വിവരം ആദ്യം'),
    ('5Ws and 1H', 'Who What When Where Why How'),
    ('ബൈലൈൻ', 'റിപ്പോർട്ടറുടെ പേര്'),
    ('ഡാറ്റ്\u200cലൈൻ', 'സ്ഥലം-തീയതി'),
    ('ലീഡ്', 'ആദ്യ പ്രധാന വാക്യം'),
    ('ക്രെഡിറ്റ് ലൈൻ', 'ഫോട്ടോഗ്രാഫർ പേര്'),
    ('മാസ്റ്റ്ഹെഡ്', 'പത്രത്തിന്റെ പേര്-ലോഗോ'),
    ('എഡിറ്റോറിയൽ', 'പത്രാധിപരുടെ ആശയം'),
    ('ഒപ്പ്-എഡ്', 'അഭിപ്രായ ലേഖനം'),
    ('ഫീച്ചർ', 'വിശകലനാത്മക ലേഖനം'),
    ('ബ്രേക്കിംഗ് ന്യൂസ്', 'അടിയന്തര വാർത്ത'),
    ('ഹാർഡ് ന്യൂസ്', 'കറന്റ് അഫയേഴ്സ്'),
    ('സോഫ്റ്റ് ന്യൂസ്', 'ലൈഫ് സ്റ്റൈൽ'),
    ('ന്യൂസ് വാല്യൂ', 'പ്രാധാന്യമനുസരിച്ച്'),
    ('ഡെഡ്\u200cലൈൻ', 'അവസാന സമയം'),
    ('സ്ട്രിംഗർ', 'ഫ്രീലാൻസ് റിപ്പോർട്ടർ'),
    ('കറസ\u200cപോണ്ടന്റ്', 'വിദേശ റിപ്പോർട്ടർ'),
]
PRESS_LAWS: list[tuple[str, str]] = [
    ('പ്രസ് കൗൺസിൽ ആക്ട്', '1978'),
    ('പ്രസ് കൗൺസിൽ', '1966'),
    ('പ്രസ് കമ്മീഷൻ', '1952'),
    ('വെrnacular Press Act', '1878'),
    ('Indian Press Act', '1910'),
    ('Censorship Ordinance', '1799'),
    ('Registration of Press Act', '1867'),
    ('Working Journalists Act', '1955'),
    ('Cable TV Networks Act', '1995'),
    ('Prasar Bharati Act', '1990'),
    ('TRAI Act', '1997'),
    ('IT Act 2000', 'സൈബർ മാധ്യമ'),
    ('Article 19(1)(a)', 'സ്വatantra പ്രസം'),
    ('Article 19(2)', 'reasonable restrictions'),
    ('Contempt of Court', 'നിയമസഭാ അവമാനം'),
    ('Official Secrets Act', 'രഹസ്യ വിവരം'),
    ('Defamation', 'അപകീർത്തി'),
    ('Sedition', 'രാജ്യദ്രോഹം'),
    ('RTI Act', '2005'),
    ('Copyright Act', '1957'),
]
PRASAR_BHARATI: list[tuple[str, str]] = [
    ('പ്രസാർ ഭാരതി', '1997'),
    ('ആകാശവാണി', '1936'),
    ('ദൂരദർശൻ', '1959'),
    ('ആകാശവാണി പേര്', '1957'),
    ('ഇന്ത്യയിൽ റേഡിയോ', '1927'),
    ('കളർ ടിവി ഇന്ത്യ', '1982'),
    ('ഏഷ്യൻ ഗെയിംസ് കളർ', '1982'),
    ('Vividh Bharati', '1957'),
    ('FM Gold', '2001'),
    ('AIR News', '24x7'),
    ('DD National', '1959'),
    ('DD News', '2003'),
    ('DD Free Dish', '2014'),
    ('Prasar Bharati CEO', 'CEO'),
    ('All India Radio HQ', 'ന്യൂഡൽഹി'),
    ('Doordarshan Kendra Trivandrum', '1975'),
    ('Community Radio Policy', '2002'),
    ('External Services Division', '1939'),
    ('Akashvani Annual Day', '13 November'),
    ('Broadcasting Day', '23 July'),
]
PCI: list[tuple[str, str]] = [
    ('പ്രസ് കൗൺസിൽ', '1966'),
    ('PCI HQ', 'ന്യൂഡൽഹി'),
    ('PCI Chairman', 'ചെയർമാൻ'),
    ('PCI Members', '28'),
    ('PCI Act', '1978'),
    ('Press Council', 'self-regulatory'),
    ('PCI Ethics', 'Journalist ethics'),
    ('PCI Complaint', 'Press grievance'),
    ('PCI vs Court', 'Advisory body'),
    ('Justice Katju', 'Former PCI Chairman'),
    ('PCI Press Day', '16 November'),
    ('National Press Day', '16 November'),
    ('PCI Newspaper', 'Registered newspapers'),
    ('PCI Magazine', 'Periodicals'),
    ('PCI News Agency', 'PTI UNI'),
    ('PCI Website', 'presscouncil.nic.in'),
    ('PCI Norms', 'Journalistic conduct'),
    ('PCI Warning', 'Advisory power'),
    ('PCI Inquiry', 'Complaint inquiry'),
    ('PCI Annual Report', 'Submitted to Parliament'),
]
TRP_BARC: list[tuple[str, str]] = [
    ('TRP', 'Television Rating Point'),
    ('BARC', 'Broadcast Audience Research Council'),
    ('ABC', 'Audit Bureau of Circulations'),
    ('BARC India', '2015'),
    ('Peoplemeter', 'TRP measurement'),
    ('BAR-O-Meter', 'BARC device'),
    ('Nielsen', 'Former TRP agency'),
    ('TAM Media', 'Former rating'),
    ('INS', 'Indian Newspaper Society'),
    ('RNI', 'Registrar of Newspapers'),
    ('Circulation Audit', 'ABC'),
    ('Readership Survey', 'IRS'),
    ('TRAI', 'Telecom regulator'),
    ('MIB', 'Ministry of I&B'),
    ('ASCI', 'Advertising Standards'),
    ('AAAI', 'Advertising Association'),
    ('DAVP', 'Govt ads'),
    ('Rate Card', 'Ad pricing'),
    ('Column cm', 'Ad unit'),
    ('Paid News', 'Paid content as news'),
]
DIGITAL_MEDIA: list[tuple[str, str]] = [
    ('പോഡ്കാസ്റ്റ്', 'ഡിജിറ്റൽ ഓഡിയോ'),
    ('ബ്ലോഗ്', 'ഓൺലൈൻ ലേഖനം'),
    ('വ്ലോഗ്', 'വീഡിയോ ബ്ലോഗ്'),
    ('മൈക്രോബ്ലോഗിംഗ്', 'Twitter/X'),
    ('ലൈവ് സ്ട്രീമിംഗ്', 'തത്സമയ പ്രക്ഷേപണം'),
    ('പേവോൾ', 'Paid content wall'),
    ('OTT', 'Over The Top'),
    ('Netflix', 'Streaming platform'),
    ('YouTube', 'Video sharing'),
    ('WhatsApp', 'Messaging news'),
    ('Telegram', 'News channels'),
    ('MOJO', 'Mobile journalism'),
    ('Data journalism', 'Data-driven reporting'),
    ('Infographics', 'Visual data'),
    ('Hyperlocal', 'Local digital news'),
    ('Clickbait', 'Sensational headline'),
    ('Viral content', 'Wide sharing'),
    ('Algorithm', 'Content ranking'),
    ('SEO', 'Search optimization'),
    ('CMS', 'Content management'),
]
NEWS_AGENCIES: list[tuple[str, str]] = [
    ('PTI', 'Press Trust of India'),
    ('UNI', 'United News of India'),
    ('ANI', 'Asian News International'),
    ('Reuters', 'UK'),
    ('Associated Press', 'USA'),
    ('AFP', 'France'),
    ('Xinhua', 'China'),
    ('TASS', 'Russia'),
    ('Kyodo', 'Japan'),
    ('DPA', 'Germany'),
    ('PTI HQ', 'ന്യൂഡൽഹി'),
    ('UNI HQ', 'ന്യൂഡൽഹി'),
    ('ANI HQ', 'ന്യൂഡൽഹി'),
    ('Reuters HQ', 'London'),
    ('AP HQ', 'New York'),
    ('AFP HQ', 'Paris'),
    ('BBC', 'UK broadcaster'),
    ('CNN', 'USA news'),
    ('Al Jazeera', 'Qatar'),
    ('Bloomberg', 'Financial news'),
]
BROADCAST_TERMS: list[tuple[str, str]] = [
    ('ടെലിപ്രോംpter', 'Anchor script screen'),
    ('ക്രോമ കീ', 'Green screen'),
    ('വോയ്\u200cസ് ഓവർ', 'Background narration'),
    ('PTC', 'Piece to Camera'),
    ('Byte', 'Field sound bite'),
    ('Sound bite', 'Short clip'),
    ('B-Roll', 'Supplementary footage'),
    ('Anchor', 'News presenter'),
    ('Floor manager', 'Studio coordinator'),
    ('Producer', 'Program producer'),
    ('Foley', 'Sound effects'),
    ('Sync', 'Audio-video match'),
    ('Montage', 'Edited sequence'),
    ('Storyboard', 'Visual plan'),
    ('Telecast', 'TV broadcast'),
    ('Simulcast', 'Same time broadcast'),
    ('Rerun', 'Repeat broadcast'),
    ('Prime time', 'Peak viewing'),
    ('Scroll', 'Ticker news'),
    ('OB Van', 'Outside broadcast'),
]
JOURNALISM_TYPES: list[tuple[str, str]] = [
    ('ഇൻവെസ്റ്റിഗേറ്റീവ്', 'Deep investigation'),
    ('യെല്ലോ ജേർണലിസം', 'Sensational news'),
    ('സിറ്റിസൺ ജേർണലിസം', 'Public reporting'),
    ('ഡാറ്റ ജേർണലിസം', 'Data analysis'),
    ('ഫോട്ടോ ജേർണലിസം', 'Photo reporting'),
    ('സ്പോർട്സ് ജേർണലിസം', 'Sports news'),
    ('പൊളിറ്റിക്കൽ', 'Political reporting'),
    ('ബിസിനസ്', 'Business news'),
    ('Science journalism', 'Science reporting'),
    ('Development journalism', 'Rural development'),
    ('Peace journalism', 'Conflict resolution'),
    ('Gonzo journalism', 'First-person style'),
    ('Tabloid journalism', 'Sensational style'),
    ('Broadcast journalism', 'TV/Radio news'),
    ('Print journalism', 'Newspaper news'),
    ('Online journalism', 'Digital news'),
    ('Feature writing', 'In-depth stories'),
    ('Editorial writing', 'Opinion pieces'),
    ('Crime reporting', 'Crime news'),
    ('Court reporting', 'Legal news'),
]
MASS_MEDIA: list[tuple[str, str]] = [
    ('പത്രം', 'Print media'),
    ('റേഡിയോ', 'Audio broadcast'),
    ('ടെലിവിഷൻ', 'Visual broadcast'),
    ('ഇന്റർനെറ്റ്', 'Digital media'),
    ('സിനിമ', 'Film medium'),
    ('മാഗസിൻ', 'Periodical'),
    ('ബിൽബോർഡ്', 'Outdoor ad'),
    ('പോഡ്കാസ്റ്റ്', 'Digital audio'),
    ('Social media', 'Interactive platform'),
    ('Fourth Estate', 'Media'),
    ('Mass communication', 'Large audience'),
    ('Narrowcasting', 'Target audience'),
    ('Broadcasting', 'Wide transmission'),
    ('Multimedia', 'Multiple formats'),
    ('Cross media', 'Multiple platforms'),
    ('New media', 'Internet-based'),
    ('Traditional media', 'Print/TV/Radio'),
    ('Electronic media', 'TV/Radio'),
    ('Alternative media', 'Non-mainstream'),
    ('Community media', 'Local audience'),
]
ADVERTISING_PR: list[tuple[str, str]] = [
    ('പബ്ലിക് റിലേഷൻസ്', 'Institution image'),
    ('പ്രസ് റിലീസ്', 'Official statement'),
    ('പരസ്യം', 'Paid promotion'),
    ('പബ്ലിസിറ്റി', 'Unpaid attention'),
    ('പ്രൊപഗanda', 'Persuasive messaging'),
    ('Tagline', 'Brand slogan'),
    ('Body copy', 'Ad text'),
    ('Jingle', 'Audio brand'),
    ('Classified ad', 'Small listing'),
    ('Display ad', 'Large ad'),
    ('Ear panel', 'Front page ad'),
    ('Sponsored content', 'Paid article'),
    ('Native advertising', 'Blended ad'),
    ('Brand ambassador', 'Celebrity endorser'),
    ('Market research', 'Consumer study'),
    ('Media planning', 'Ad placement'),
    ('Copywriting', 'Ad text writing'),
    ('Creative brief', 'Ad concept'),
    ('Rate card', 'Ad pricing'),
    ('TRP-based ad', 'Rating-based pricing'),
]
MEDIA_FREEDOM: list[tuple[str, str]] = [
    ('Article 19', 'Freedom of speech'),
    ('World Press Freedom Day', 'May 3'),
    ('Press Freedom Index', 'RSF ranking'),
    ('Fourth Estate', 'Media role'),
    ('Censorship', 'Content restriction'),
    ('Prior restraint', 'Pre-publication ban'),
    ('Gagging order', 'Publication ban'),
    ('Whistleblower', 'Information leak'),
    ('Shield law', 'Source protection'),
    ('Right to Information', 'RTI 2005'),
    ('Public interest', 'Journalism defense'),
    ('Contempt', 'Court disrespect'),
    ('Sedition law', 'IPC 124A'),
    ('Defamation law', 'Reputation harm'),
    ('Privacy law', 'Personal data'),
    ('Hate speech', 'Restricted speech'),
    ('Media trial', 'Prejudicial reporting'),
    ('Ethical journalism', 'Fair reporting'),
    ('Self-regulation', 'Industry norms'),
    ('Press freedom', 'Constitutional right'),
]
PRINT_HISTORY: list[tuple[str, str]] = [
    ('ജോഹannes Gutenberg', 'Printing press'),
    ('Gutenberg Bible', '1455'),
    ('Printing in India', 'Portuguese Goa'),
    ('Serampore Mission Press', '1800'),
    ('Bible Society Press', '1811'),
    ('Woodcut printing', 'Block printing'),
    ('Offset printing', 'Modern method'),
    ('Letterpress', 'Traditional printing'),
    ('Lithography', 'Stone printing'),
    ('Digital printing', 'Computer printing'),
    ('Movable type', 'Gutenberg invention'),
    ('Newspaper printing', 'Daily press'),
    ('Linotype', 'Typesetting machine'),
    ('Phototypesetting', 'Photo method'),
    ('Desktop publishing', 'Computer layout'),
    ('Adobe InDesign', 'Layout software'),
    ('Column cm', 'Newspaper ad unit'),
    ('Broadsheet', 'Large format'),
    ('Tabloid', 'Small format'),
    ('Newsprint', 'Paper type'),
]
SOCIAL_MEDIA: list[tuple[str, str]] = [
    ('Facebook', '2004'),
    ('Twitter/X', '2006'),
    ('YouTube', '2005'),
    ('Instagram', '2010'),
    ('WhatsApp', '2009'),
    ('LinkedIn', '2003'),
    ('TikTok', '2016'),
    ('Snapchat', '2011'),
    ('Orkut', 'Google'),
    ('Google+', 'Google social'),
    ('Telegram', '2013'),
    ('Threads', 'Meta 2023'),
    ('Mark Zuckerberg', 'Facebook'),
    ('Jack Dorsey', 'Twitter'),
    ('Elon Musk', 'X owner'),
    ('Social networking', 'Online community'),
    ('Influencer', 'Social media star'),
    ('Hashtag', 'Topic tag'),
    ('Viral post', 'Wide sharing'),
    ('Fake news spread', 'Misinformation'),
]
MEDIA_ETHICS: list[tuple[str, str]] = [
    ('പ്ലേജിയറിസം', 'Content theft'),
    ('ലിബൽ', 'Written defamation'),
    ('സ്ലാൻഡർ', 'Spoken defamation'),
    ('Paid news', 'Paid reporting'),
    ('Yellow journalism', 'Sensationalism'),
    ('Check facts', 'Verification'),
    ('Source protection', 'Confidentiality'),
    ('Conflict of interest', 'Bias disclosure'),
    ('Sensationalism', 'Exaggeration'),
    ('Privacy invasion', 'Personal harm'),
    ('Sting operation', 'Hidden camera'),
    ('Trial by media', 'Prejudicial coverage'),
    ('Objectivity', 'Neutral reporting'),
    ('Balance', 'Fair coverage'),
    ('Accuracy', 'Correct facts'),
    ('Transparency', 'Open methods'),
    ('Accountability', 'Responsibility'),
    ('Correction', 'Error fix'),
    ('Retraction', 'Withdraw story'),
    ('Code of ethics', 'Professional norms'),
]
NEWSPAPER_LAYOUT: list[tuple[str, str]] = [
    ('ബാനർ ഹെഡ്\u200cലൈൻ', 'Top headline'),
    ('മാസ്റ്റ്ഹെഡ്', 'Paper name/logo'),
    ('ബൈലൈൻ', 'Reporter name'),
    ('Dateline', 'Place-date'),
    ('Lead paragraph', 'Opening'),
    ('Jump line', 'Continued page'),
    ('Masthead info', 'Publisher details'),
    ('Folio', 'Page number'),
    ('Deck', 'Sub-headline'),
    ('Kicker', 'Intro label'),
    ('Pull quote', 'Highlighted quote'),
    ('Caption', 'Photo text'),
    ('Credit line', 'Photo credit'),
    ('Ear panel', 'Side ad'),
    ('Classifieds', 'Small ads'),
    ('Op-ed page', 'Opinion page'),
    ('Front page', 'Page one'),
    ('Center spread', 'Double page'),
    ('Column width', 'Layout measure'),
    ('Above the fold', 'Top half'),
]
FILM_MEDIA_BODIES: list[tuple[str, str]] = [
    ('CBFC', 'Film certification'),
    ('NFDC', 'Film development'),
    ('FTII', 'Film institute Pune'),
    ('SRFTI', 'Kolkata film institute'),
    ('NFAI', 'Film archive Pune'),
    ('Children Film Society', 'Children films'),
    ('Filmfare Awards', 'Popular awards'),
    ('National Film Awards', 'DFF awards'),
    ('DadaSaheb Phalke', 'Lifetime award'),
    ('IFFI', 'Goa film festival'),
    ('Censor board', 'CBFC old name'),
    ('U certificate', 'Universal'),
    ('A certificate', 'Adults only'),
    ('UA certificate', 'Parental guidance'),
    ('S certificate', 'Special class'),
    ('Film certification', 'CBFC role'),
    ('Prasar Bharati', 'Public broadcaster'),
    ('MIB', 'Information Broadcasting'),
    ('ASCI', 'Ad standards'),
    ('Film India', 'First film magazine'),
]
KERALA_MEDIA: list[tuple[str, str]] = [
    ('കേരള പ്രസ് അക്കാദമി', 'കാക്കനാട്'),
    ('Press Academy Kerala', 'Media training'),
    ('Asianet', '1993'),
    ('Kairali TV', '2000'),
    ('Surya TV', '1998'),
    ('Amrita TV', '2005'),
    ('Media One', '2011'),
    ('Manorama News', '2007'),
    ('Mathrubhumi News', '2013'),
    ('24 News', '2019'),
    ('Radio Mango', 'First private FM'),
    ('Club FM', 'Red FM Kerala'),
    ('Radio Mirchi', 'Kerala'),
    ('Radio Mattoli', 'Community radio'),
    ('DD Kerala', 'Trivandrum'),
    ('AIR Trivandrum', '1939'),
    ('Kerala Kaumudi TV', '2017'),
    ('Reporter TV', '2011'),
    ('Flowers TV', '2015'),
    ('Safari TV', 'Documentary'),
]
MEDIA_ABBREV: list[tuple[str, str]] = [
    ('PTI', 'Press Trust of India'),
    ('UNI', 'United News of India'),
    ('PCI', 'Press Council of India'),
    ('TRP', 'Television Rating Point'),
    ('BARC', 'Broadcast Audience Research Council'),
    ('ABC', 'Audit Bureau of Circulations'),
    ('TRAI', 'Telecom Regulatory Authority of India'),
    ('MIB', 'Ministry of Information and Broadcasting'),
    ('ASCI', 'Advertising Standards Council of India'),
    ('CBFC', 'Central Board of Film Certification'),
    ('FTII', 'Film and Television Institute of India'),
    ('NFDC', 'National Film Development Corporation'),
    ('RNI', 'Registrar of Newspapers for India'),
    ('INS', 'Indian Newspaper Society'),
    ('DAVP', 'Directorate of Advertising and Visual Publicity'),
    ('URL', 'Uniform Resource Locator'),
    ('WWW', 'World Wide Web'),
    ('CMS', 'Content Management System'),
    ('SEO', 'Search Engine Optimization'),
    ('OTT', 'Over The Top'),
]
INTERNATIONAL_PRESS: list[tuple[str, str]] = [
    ('Watergate', 'Washington Post'),
    ('Pentagon Papers', 'New York Times'),
    (' Pulitzer Prize', 'Journalism award'),
    ('BBC', 'UK public broadcaster'),
    ('The Guardian', 'UK newspaper'),
    ('New York Times', 'USA newspaper'),
    ('Washington Post', 'USA newspaper'),
    ('The Times', 'UK newspaper'),
    ('Le Monde', 'French newspaper'),
    ('Der Spiegel', 'German magazine'),
    ('WikiLeaks', 'Document leaks'),
    ('Panama Papers', 'Investigative leak'),
    ('Paradise Papers', 'Tax investigation'),
    ('Edward Snowden', 'NSA leaks'),
    ('Daniel Ellsberg', 'Pentagon Papers'),
    ('Bob Woodward', 'Watergate reporter'),
    ('Carl Bernstein', 'Watergate reporter'),
    ('Murdoch', 'News Corp'),
    ('Reuters', 'News agency'),
    ('Associated Press', 'News agency'),
]
COMM_LEVELS: list[tuple[str, str]] = [
    ('ഇൻട്രാപേഴ്സണൽ', 'Self communication'),
    ('ഇന്റർപേഴ്സണൽ', 'Two persons'),
    ('ഗ്രൂപ്പ്', 'Small group'),
    ('പബ്ലിക്', 'Large audience'),
    ('മാസ്', 'Mass media'),
    ('വെർബൽ', 'Words'),
    ('നോൺ-വെർബൽ', 'Body language'),
    ('ഓറൽ', 'Spoken'),
    ('ലിഖിത', 'Written'),
    ('വിഷ്വൽ', 'Visual'),
    ('ഡിജിറ്റൽ', 'Electronic'),
    ('ഫീഡ്ബാക്ക്', 'Response'),
    ('ഒne-way', 'No feedback'),
    ('Two-way', 'Interactive'),
    ('Horizontal', 'Same level'),
    ('Vertical', 'Hierarchy'),
    ('Formal', 'Official'),
    ('Informal', 'Casual'),
    ('Internal', 'Within org'),
    ('External', 'Outside org'),
]
MEDIA_REGULATION: list[tuple[str, str]] = [
    ('TRAI', 'Telecom regulator'),
    ('MIB', 'Broadcast ministry'),
    ('PCI', 'Press self-regulation'),
    ('CBFC', 'Film certification'),
    ('ASCI', 'Ad self-regulation'),
    ('BARC', 'TV ratings'),
    ('ABC', 'Circulation audit'),
    ('RNI', 'Newspaper registration'),
    ('Prasar Bharati', 'Public broadcaster'),
    ('Censor board', 'Film censor'),
    ('Cable TV Act', '1995'),
    ('Prasar Bharati Act', '1990'),
    ('Press Council Act', '1978'),
    ('IT Rules 2021', 'Digital media'),
    ('Fact Check Unit', 'Govt fact check'),
    ('Intermediary rules', 'Social media'),
    ('Content code', 'Broadcast norms'),
    ('Programme code', 'TV rules'),
    ('Advertising code', 'Ad norms'),
    ('Emergency powers', 'Broadcast ban'),
]
DIRECT_FACTS: list[tuple[str, str, list[str], str]] = [
    ("'The Medium is the Message' ആരുടേതാണ്?", 'മാർഷൽ മക്ലൂഹൻ', ['വാൾട്ടർ ലിപ്മാൻ', 'നോം ചോംസ്കി', 'വിൽബർ ശ്രം'], 'medium'),
    ("'Manufacturing Consent' രചിച്ചത്?", 'നോം ചോംസ്കി', ['മാർഷൽ മക്ലൂഹൻ', 'യുർഗൻ ഹേബർമാസ്', 'വാൾട്ടർ ലിപ്മാൻ'], 'medium'),
    ("'Fourth Estate' എന്ന് വിശേഷിപ്പിക്കുന്നത്?", 'മാധ്യമങ്ങൾ', ['നിയമനിർമ്മാണ സഭ', 'നീതിന്യായം', 'ഭരണനിർവ്വഹണം'], 'easy'),
    ('ലോകത്തിലെ ആദ്യ അച്ചടി യന്ത്രം കണ്ടെടുത്തത്?', 'ജോഹന്നസ് ഗുട്ടൻബർഗ്', ['വില്ല്യം കാക്സ്റ്റൺ', 'തോമസ് എഡിസൺ', 'ലൂയി പാസ്ചർ'], 'easy'),
    ('ഇന്ത്യയിലെ ആദ്യ വാർത്താപത്രം?', 'ബംഗാൾ ഗസറ്റ്', ['ബോംബെ സമാചാർ', 'ദി ടൈംസ്', 'ദി ഹിന്ദു'], 'easy'),
    ('കേരളത്തിലെ ആദ്യ ദൈനിക പത്രം?', 'ദീപിക', ['മലയാള മനോരമ', 'മാതൃഭൂമി', 'കേരള കൗമുദി'], 'medium'),
    ('മലയാളത്തിലെ ആദ്യ പത്രം?', 'രാജ്യസമാചാരം', ['ദീപിക', 'മനോരമ', 'ഭാഷാപോഷിണി'], 'easy'),
    ('പ്രസ് കൗൺസിൽ ഇന്ത്യ നിലവിൽ വന്ന വർഷം?', '1966', ['1978', '1952', '1985'], 'medium'),
    ('പ്രസാർ ഭാരതി രൂപീകരിച്ച വർഷം?', '1997', ['1990', '2000', '1982'], 'hard'),
    ("ഓൾ ഇന്ത്യ റേഡiyo 'ആകാശവാണി' പേര്?", '1957', ['1936', '1947', '1965'], 'medium'),
    ('ഇന്ത്യയിൽ ടെലിവിഷൻ ആരംഭിച്ച വർഷം?', '1959', ['1965', '1982', '1972'], 'medium'),
    ('ഇന്ത്യയിൽ കളർ ടിവി ആരംഭിച്ച വർഷം?', '1982', ['1959', '1972', '1991'], 'medium'),
    ('മലയാളത്തിലെ ആദ്യ സ്വകാര്യ ടിവി?', 'ഏഷ്യാനെറ്റ്', ['സൂര്യ', 'കൈരളി', 'അമൃത'], 'easy'),
    ('TRP-ന്റെ പൂർണ്ണരൂപം?', 'Television Rating Point', ['Total Rating Point', 'Telecast Rating Program', 'TV Rating Panel'], 'easy'),
    ('BARC-ന്റെ പൂർണ്ണരൂപം?', 'Broadcast Audience Research Council', ['Broadcast Advertising Research Council', 'Bureau of Audience Rating Council', 'Broadcast Audio Rating Council'], 'medium'),
    ('PTI-യുടെ പൂർണ്ണരൂപം?', 'Press Trust of India', ['Public Television of India', 'Press Times of India', 'People Trust of India'], 'easy'),
    ('ലിബൽ എന്നാൽ?', 'അച്ചടിച്ച അപകീർത്തി', ['സംസാര അപകീർത്തി', 'വാർത്ത മോഷ്ടിക്കൽ', 'വ്യാജ പരസ്യം'], 'medium'),
    ('സ്ലാൻഡർ എന്നാൽ?', 'സംസാര/ഓഡിയോ അപകീർത്തി', ['അച്ചടി അപകീർത്തി', 'പ്ലേജിയറിസം', 'കോപ്പിറൈറ്റ്'], 'medium'),
    ('വിശ്വ പ്രസ് സ്വാതന്ത്ര്യ ദിനം?', 'മേയ് 3', ['ജൂൺ 5', 'നവംബർ 16', 'ജനുവരി 24'], 'medium'),
    ('നാഷണൽ പ്രസ് ദിനം (ഇന്ത്യ)?', 'നവംബർ 16', ['മേയ് 3', 'ജൂൺ 5', 'ഓഗസ്റ്റ് 15'], 'medium'),
    ('SMCR മോഡൽ അവതരിപ്പിച്ചത്?', 'ഡേവിഡ് ബെർലോ', ['ഹാരോൾഡ് ലാസ്വെൽ', 'ഷാനൺ', 'ഫ്രാങ്ക് ഡാൻസ്'], 'hard'),
    ('ഷാനൺ-വീവർ മോഡൽ?', 'ഗണിതശാസ്ത്ര മാതൃക', ['സാമൂഹിക മാതൃക', 'സൈക്കോളജikal', 'രാഷ്ട്രീയ'], 'hard'),
    ('ഹെലിക്സ് മോഡൽ?', 'ഫ്രാങ്ക് ഡാൻസ്', ['ബെർലോ', 'ലാസ്വെൽ', 'ഷാനൺ'], 'hard'),
    ('Hypodermic Needle Theory?', 'Magic Bullet Theory', ['Two-Step Flow', 'Cultivation', 'Agenda Setting'], 'medium'),
    ('Two-Step Flow?', 'പോൾ ലാസർഫെൽഡ്', ['മക്ലൂഹൻ', 'ഗെർബ്നർ', 'മക്ടെയിൽ'], 'hard'),
    ('Cultivation Theory?', 'ജോർഗ്ഗ് ഗെർബ്നർ', ['ലാസർഫെൽഡ്', 'മക്കോംബ്സ്', 'ഹാൾ'], 'hard'),
    ('Agenda Setting?', 'മക്കോംബ്സ്-ഷാ', ['ലാസ്വെൽ', 'ഷാനൺ', 'ചോംസ്കി'], 'hard'),
    ('Global Village?', 'മാർഷൽ മക്ലൂഹൻ', ['വിൽബർ ശ്രം', 'ഹേബർമാസ്', 'ലിപ്മാൻ'], 'medium'),
    ('Public Sphere?', 'യുർഗൻ ഹേബർമാസ്', ['കാൾ മാർക്സ്', 'ഗ്രാംഷി', 'വെബർ'], 'hard'),
    ('Semiotics?', 'ചിഹ്ന പഠനം', ['ഭാഷാ ശാസ്ത്രം', 'മനശ്ശാസ്ത്രം', 'സാമൂഹികശാസ്ത്രം'], 'hard'),
]

def generate_wave30_candidates(existing: set[str], rng: random.Random) -> list[Candidate]:
    out: list[Candidate] = []

    emit_category(out, existing, rng, COMM_MODELS,
        ["'{a}' ആശയവിനിമയ മോഡലുമായി ബന്ധപ്പെട്ട വസ്തുത?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?", "'{a}' മോഡൽ സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ആശയവിനിമയ മോഡൽ?", "'{b}' വിവരമുള്ള കമ്മ്യൂണിക്കേഷൻ മോഡൽ?", "'{b}'-ന് ഏത് മോഡൽ?"],
        [a for a, _ in COMM_MODELS], [b for _, b in COMM_MODELS])

    emit_category(out, existing, rng, COMM_THEORIES,
        ["'{a}' സിദ്ധാന്തം ആരുടേതാണ്?", "'{a}'-യുമായി ബന്ധപ്പെട്ട പ്രധാന സിദ്ധാന്തജ്ഞൻ?", "'{a}' സിദ്ധാന്തത്തിന്റെ പ്രതിപാദകൻ?"],
        ["'{b}' ആരുടെ സിദ്ധാന്തമാണ്?", "'{b}'-ന്റെ പ്രധാന സിദ്ധാന്തം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട സിദ്ധാന്തം?"],
        [a for a, _ in COMM_THEORIES], [b for _, b in COMM_THEORIES])

    emit_category(out, existing, rng, THEORY_MEANING,
        ["'{a}' സിദ്ധാന്തത്തിന്റെ പ്രധാന ആശയം?", "'{a}'-ന്റെ കേന്ദ്ര സങ്കല്പം?", "'{a}' സിദ്ധാന്തം എന്ത് പറയുന്നു?"],
        ["'{b}' ആശയമുള്ള മാധ്യമ സിദ്ധാന്തം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട സിദ്ധാന്തം?", "'{b}' പ്രതിപാദിക്കുന്ന സിദ്ധാന്തം?"],
        [a for a, _ in THEORY_MEANING], [b for _, b in THEORY_MEANING])

    emit_category(out, existing, rng, MALAYALAM_FIRST,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' മലയാള പത്രചരിത്ര വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട മലയാള പത്രചരിത്ര വസ്തുത?", "'{b}' വിവരമുള്ള മലയാള മാധ്യമം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in MALAYALAM_FIRST], [b for _, b in MALAYALAM_FIRST])

    emit_category(out, existing, rng, MALAYALAM_FOUNDER,
        ["'{a}' ഏത് മലയാള പത്രവുമായി ബന്ധപ്പെട്ട വ്യക്തി?", "'{a}'-ന്റെ പ്രധാന പത്രപ്രവർത്തന സംബന്ധം?", "'{a}' ആരംഭിച്ച/സമ്പാദിച്ച പത്രം?"],
        ["'{b}'-ന്റെ സ്ഥാപകൻ/പത്രാധിപർ ആര്?", "'{b}' പത്രവുമായി ബന്ധപ്പെട്ട വ്യക്തി?", "'{b}'-ന് ഏത് വ്യക്തി?"],
        [a for a, _ in MALAYALAM_FOUNDER], [b for _, b in MALAYALAM_FOUNDER])

    emit_category(out, existing, rng, MALAYALAM_PRESS_YEAR,
        ["'{a}' പത്രം സ്ഥാപിതമായ/ആരംഭിച്ച വർഷം?", "'{a}'-ന്റെ സ്ഥാപന വർഷം?", "'{a}' ആരംഭിച്ച വർഷം?"],
        ["'{b}' വർഷം ആരംഭിച്ച മലയാള പത്രം?", "'{b}'-ൽ പ്രസിദ്ധീകരണം ആരംഭിച്ച പത്രം?", "'{b}' വർഷത്തിലെ പ്രധാന മലയാള പത്രം?"],
        [a for a, _ in MALAYALAM_PRESS_YEAR], [b for _, b in MALAYALAM_PRESS_YEAR])

    emit_category(out, existing, rng, INDIA_PRESS_HISTORY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' ഇന്ത്യൻ പത്രചരിത്ര വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഇന്ത്യൻ പത്രചരിത്ര വസ്തുത?", "'{b}' വിവരമുള്ള ഇന്ത്യൻ പത്രം/സംഭവം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in INDIA_PRESS_HISTORY], [b for _, b in INDIA_PRESS_HISTORY])

    emit_category(out, existing, rng, INDIA_PRESS_PIONEER,
        ["'{a}' ഏത് പത്രപ്രവർത്തന സംബന്ധത്തിലാണ്?", "'{a}'-ന്റെ പ്രധാന പത്രപ്രവർത്തന സംഭാവന?", "'{a}'-യുമായി ബന്ധപ്പെട്ട പത്രം/സംഭവം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഇന്ത്യൻ പത്രനായകൻ?", "'{b}' സംബന്ധിച്ച പ്രധാന വ്യക്തി?", "'{b}'-ന് ഏത് വ്യക്തി?"],
        [a for a, _ in INDIA_PRESS_PIONEER], [b for _, b in INDIA_PRESS_PIONEER])

    emit_category(out, existing, rng, JOURNALISM_TERMS,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' എന്ന പദം എന്താണ്?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള പത്രപ്രവർത്തന പദം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട ജേർണലിസം പദം?", "'{b}'-ന് ഏത് പദം?"],
        [a for a, _ in JOURNALISM_TERMS], [b for _, b in JOURNALISM_TERMS])

    emit_category(out, existing, rng, PRESS_LAWS,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' പത്ര/മാധ്യമ നിയമ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട പത്ര/മാധ്യമ നിയമം?", "'{b}' വിവരമുള്ള മാധ്യമ നിയമം?", "'{b}'-ന് ഏത് നിയമം?"],
        [a for a, _ in PRESS_LAWS], [b for _, b in PRESS_LAWS])

    emit_category(out, existing, rng, PRASAR_BHARATI,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' പ്രേഷണ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട പ്രേഷണ വസ്തുത?", "'{b}' വിവരമുള്ള പ്രസാർ ഭാരതി/ആകാശവാണി/ദൂരദർശൻ?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in PRASAR_BHARATI], [b for _, b in PRASAR_BHARATI])

    emit_category(out, existing, rng, PCI,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' പ്രസ് കൗൺസിൽ/PCI വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട PCI/പ്രസ് കൗൺസിൽ വസ്തുത?", "'{b}' വിവരമുള്ള PCI?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in PCI], [b for _, b in PCI])

    emit_category(out, existing, rng, TRP_BARC,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' TRP/BARC/ABC വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട TRP/റേറ്റിംഗ്/പ്രചാരണ വസ്തുത?", "'{b}' വിവരമുള്ള BARC/ABC?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in TRP_BARC], [b for _, b in TRP_BARC])

    emit_category(out, existing, rng, DIGITAL_MEDIA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' ഡിജിറ്റൽ മാധ്യമ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഡിജിറ്റൽ മാധ്യമം?", "'{b}' വിവരമുള്ള ഡിജിറ്റൽ മാധ്യമ പദം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in DIGITAL_MEDIA], [b for _, b in DIGITAL_MEDIA])

    emit_category(out, existing, rng, NEWS_AGENCIES,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' വാർത്താ ഏജൻസി വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട വാർത്താ ഏജൻസി?", "'{b}' വിവരമുള്ള വാർത്താ ഏജൻസി?", "'{b}'-ന് ഏത് ഏജൻസി?"],
        [a for a, _ in NEWS_AGENCIES], [b for _, b in NEWS_AGENCIES])

    emit_category(out, existing, rng, BROADCAST_TERMS,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' പ്രക്ഷേപണ പദം എന്താണ്?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള പ്രക്ഷേപണ പദം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട ടിവി/റേഡിയോ പദം?", "'{b}'-ന് ഏത് പദം?"],
        [a for a, _ in BROADCAST_TERMS], [b for _, b in BROADCAST_TERMS])

    emit_category(out, existing, rng, JOURNALISM_TYPES,
        ["'{a}'-ന്റെ പ്രധാന സവിശേഷത?", "'{a}' ജേർണലിസം തരം എന്താണ്?", "'{a}'-ന്റെ വ്യാഖ്യാനം?"],
        ["'{b}' അർത്ഥമുള്ള ജേർണലിസം തരം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട റിപ്പോർട്ടിംഗ് രീതി?", "'{b}'-ന് ഏത് ജേർണലിസം?"],
        [a for a, _ in JOURNALISM_TYPES], [b for _, b in JOURNALISM_TYPES])

    emit_category(out, existing, rng, MASS_MEDIA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' മാസ് മീഡിയ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട മാസ് മീഡിയ?", "'{b}' വിവരമുള്ള മാധ്യമം?", "'{b}'-ന് ഏത് മാധ്യമം?"],
        [a for a, _ in MASS_MEDIA], [b for _, b in MASS_MEDIA])

    emit_category(out, existing, rng, ADVERTISING_PR,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' പരസ്യ/PR പദം എന്താണ്?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള പരസ്യ/PR പദം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട മാർക്കറ്റിംഗ് പദം?", "'{b}'-ന് ഏത് പദം?"],
        [a for a, _ in ADVERTISING_PR], [b for _, b in ADVERTISING_PR])

    emit_category(out, existing, rng, MEDIA_FREEDOM,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' മാധ്യമ സ്വാതന്ത്ര്യ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട മാധ്യമ സ്വാതന്ത്ര്യം?", "'{b}' വിവരമുള്ള ഭരണഘടന/അവകാശം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in MEDIA_FREEDOM], [b for _, b in MEDIA_FREEDOM])

    emit_category(out, existing, rng, PRINT_HISTORY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' അച്ചടി/മുദ്രണ ചരിത്ര വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട അച്ചടി/മുദ്രണ ചരിത്രം?", "'{b}' വിവരമുള്ള മുദ്രണ സംഭവം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in PRINT_HISTORY], [b for _, b in PRINT_HISTORY])

    emit_category(out, existing, rng, SOCIAL_MEDIA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' സോഷ്യൽ മീഡിയ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട സോഷ്യൽ മീഡിയ?", "'{b}' വിവരമുള്ള പ്ലാറ്റ്ഫോം?", "'{b}'-ന് ഏത് പ്ലാറ്റ്ഫോം?"],
        [a for a, _ in SOCIAL_MEDIA], [b for _, b in SOCIAL_MEDIA])

    emit_category(out, existing, rng, MEDIA_ETHICS,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' മാധ്യമ നൈതികത പദം?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള മാധ്യമ നൈതികത/നിയമ പദം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട പത്രപ്രവർത്തന കുറ്റം?", "'{b}'-ന് ഏത് പദം?"],
        [a for a, _ in MEDIA_ETHICS], [b for _, b in MEDIA_ETHICS])

    emit_category(out, existing, rng, NEWSPAPER_LAYOUT,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' പത്ര ലേഔട്ട് പദം?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള പത്ര ലേഔട്ട് പദം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട പത്ര ഘടകം?", "'{b}'-ന് ഏത് പദം?"],
        [a for a, _ in NEWSPAPER_LAYOUT], [b for _, b in NEWSPAPER_LAYOUT])

    emit_category(out, existing, rng, FILM_MEDIA_BODIES,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' സിനിമ/മാധ്യമ സ്ഥാപന വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട സിനിമ/മാധ്യമ സ്ഥാപനം?", "'{b}' വിവരമുള്ള സർട്ടിഫിക്കേഷൻ/സ്ഥാപനം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in FILM_MEDIA_BODIES], [b for _, b in FILM_MEDIA_BODIES])

    emit_category(out, existing, rng, KERALA_MEDIA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' കേരള മാധ്യമ വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട കേരള മാധ്യമം?", "'{b}' വിവരമുള്ള കേരള ചാനൽ/റേഡിയോ?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in KERALA_MEDIA], [b for _, b in KERALA_MEDIA])

    emit_category(out, existing, rng, MEDIA_ABBREV,
        ["'{a}' എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം?", "'{a}'-ന്റെ വിപുലീകരണം?", "'{a}' എന്തിനെ സൂചിപ്പിക്കുന്നു?"],
        ["'{b}' പൂർണ്ണരൂപമുള്ള മാധ്യമ സംക്ഷേപം?", "'{b}' ഏത് ചുരുക്കെഴുത്തിൽ?", "'{b}'-ന് ഏത് സംക്ഷേപം?"],
        [a for a, _ in MEDIA_ABBREV], [b for _, b in MEDIA_ABBREV], english=True)

    emit_category(out, existing, rng, INTERNATIONAL_PRESS,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' അന്താരാഷ്ട്ര പത്രപ്രവർത്തന വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട അന്താരാഷ്ട്ര പത്രസംഭവം?", "'{b}' വിവരമുള്ള പ്രശസ്ത പത്രം/സംഭവം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in INTERNATIONAL_PRESS], [b for _, b in INTERNATIONAL_PRESS])

    emit_category(out, existing, rng, COMM_LEVELS,
        ["'{a}'-ന്റെ അർത്ഥം/വ്യാഖ്യാനം?", "'{a}' ആശയവിനിമയ തലം?", "'{a}'-ന്റെ പ്രധാന സവിശേഷത?"],
        ["'{b}' അർത്ഥമുള്ള ആശയവിനിമയ തലം?", "'{b}'-യുമായി ബന്ധപ്പെട്ട കമ്മ്യൂണിക്കേഷൻ?", "'{b}'-ന് ഏത് തലം?"],
        [a for a, _ in COMM_LEVELS], [b for _, b in COMM_LEVELS])

    emit_category(out, existing, rng, MEDIA_REGULATION,
        ["'{a}'-ന്റെ പ്രധാന വിവരം?", "'{a}' മാധ്യമ നിയന്ത്രണ സ്ഥാപന വസ്തുത?", "'{a}' സംബന്ധിച്ച വിവരം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട മാധ്യമ നിയന്ത്രണ സ്ഥാപനം?", "'{b}' വിവരമുള്ള നിയന്ത്രക സ്ഥാപനം?", "'{b}'-ന് ഏത്?"],
        [a for a, _ in MEDIA_REGULATION], [b for _, b in MEDIA_REGULATION])

    emit_direct(out, existing, rng, DIRECT_FACTS)
    return out


if __name__ == "__main__":
    print(len(generate_wave30_candidates(set(), random.Random(0))))
