#!/usr/bin/env python3
"""Generate complete awards_wave20_data.py tail + run build."""

import subprocess
import sys
from pathlib import Path

BASE = Path(__file__).parent
HEADER = BASE.joinpath("awards_wave20_data.py").read_text(encoding="utf-8").split("SANGEET_NATAK_WINNERS")[0]

SANGEET_NATAK_WINNERS = [
    ("പണ്ഡിത് രവി ശങ്കർ", "ശാസ്ത്രീയ സംഗീതം", "1960"),
    ("എം.എസ്. സുബ്ബുലക്ഷ്മി", "ശാസ്ത്രീയ സംഗീതം", "1956"),
    ("ബിസ്മില്ലാ ഖാൻ", "ശാസ്ത്രീയ സംഗീതം", "1956"),
    ("ഭീംസെൻ ജോഷി", "ശാസ്ത്രീയ സംഗീതം", "1976"),
    ("ലതാ മങ്കേഷ്കർ", "ലൈറ്റ് മ്യൂസിക്", "1989"),
    ("എ.ആർ. റഹ്മാൻ", "ലൈറ്റ് മ്യൂസിക്", "2010"),
    ("സത്യജിത് റേ", "സിനിമ", "1961"),
    ("അടൂർ ഗോപാലകൃഷ്ണൻ", "സിനിമ", "1976"),
    ("ശ്യാം ബെനഗൽ", "സിനിമ", "2007"),
    ("അമിതാഭ് ബച്ചൻ", "സിനിമ", "1990"),
    ("നസീരുദ്ദീൻ ഷാ", "നാടകം", "1981"),
    ("ഒമ്പുരി", "നാടകം", "1990"),
    ("ഷബാനാ ആസ്മി", "നാടകം", "1989"),
    ("ഫിറോസ് ഖാൻ", "നാടകം", "1984"),
    ("പൃഥ്വിരാജ് കപൂർ", "നാടകം", "1962"),
    ("ബാലഗന്ധർവ്വ", "നാടകം", "1956"),
    ("കെ.എൽ. സൈഗൾ", "നാടകം", "1956"),
    ("സൊഹ്റാബ് മോദി", "സിനിമ", "1956"),
    ("രാജ് കപൂർ", "സിനിമ", "1962"),
    ("ദിലീപ് കുമാർ", "സിനിമ", "1965"),
    ("വഹീദ റഹ്മാൻ", "സിനിമ", "2002"),
    ("ഹൃദയനാഥ് മംഗേഷ്കർ", "ലൈറ്റ് മ്യൂസിക്", "1996"),
    ("പണ്ഡിത് ജസ്റാജ്", "ശാസ്ത്രീയ സംഗീതം", "1962"),
    ("ബിർജു മഹാരാജ്", "ശാസ്ത്രീയ നൃത്തം", "1964"),
    ("സോണൽ മാധവിദേവ്", "ശാസ്ത്രീയ നൃത്തം", "1964"),
    ("യാമിനി കൃഷ്ണമൂർത്തി", "ശാസ്ത്രീയ നൃത്തം", "1968"),
    ("മല്ലികാ സാരാഭായി", "ശാസ്ത്രീയ നൃത്തം", "1968"),
    ("വൈജയന്തിമാല ബാലി", "ശാസ്ത്രീയ നൃത്തം", "1991"),
    ("പദ്മ സുബ്രഹ്മണ്യം", "ശാസ്ത്രീയ നൃത്തം", "1991"),
    ("സിതാര ദേവി", "ശാസ്ത്രീയ നൃത്തം", "1969"),
    ("രുക്മini Arundale", "ശാസ്ത്രീയ നൃത്തം", "1956"),
    ("സാക്കിർ ഹുസൈൻ", "ശാസ്ത്രീയ സംഗീതം", "1990"),
    ("ഹരിപ്രസാദ് ചൗരസ്യ", "ശാസ്ത്രീയ സംഗീതം", "1984"),
    ("പണ്ഡിത് ശിവകുമാർ ശർമ്മ", "ശാസ്ത്രീയ സംഗീതം", "1986"),
    ("ലക്ഷmi ശങ്കർ", "ശാസ്ത്രീയ സംഗീതം", "1972"),
    ("സabu", "നാടകം", "1979"),
    ("എbrahim Alkazi", "നാടകം", "1962"),
    ("വിജയ് ടെൻഡുൽക്കർ", "നാടകം", "1970"),
    ("ഗirish Karnad", "നാടകം", "1970"),
    ("ബadal Sarkar", "നാടകം", "1968"),
    ("മഹാശ്വേതാ ദേവി", "നാടകം", "1997"),
    ("സുഭാഷ് മുഖോപാധ്യായ", "നാടകം", "1991"),
    ("സanjay Leela Bhansali", "സിനിമ", "2015"),
    ("ഗulzar", "സിനിമ", "2002"),
    ("ജaved Akhtar", "സിനിമ", "2004"),
    ("ശankar Mahadevan", "ലൈറ്റ് മ്യൂസിക്", "2018"),
    ("സuni Dev", "ലൈറ്റ് മ്യൂസിക്", "2015"),
    ("സuresh Wadkar", "ശാസ്ത്രീയ സംഗീതം", "2010"),
    ("കumar Gandharva", "ശാസ്ത്രീയ സംഗീതം", "1977"),
    ("അmir Khan", "ശാസ്ത്രീയ സംഗീതം", "1956"),
    ("വിലayat Khan", "ശാസ്ത്രീയ സംഗീതം", "1964"),
    ("അllauddin Khan", "ശാസ്ത്രീയ സംഗീതം", "1956"),
    ("അparana Sen", "സിനിമ", "1987"),
    ("മrinal Sen", "സിനിമ", "1968"),
    ("രitwik Ghatak", "സിനിമ", "1970"),
    ("ബimal Roy", "സിനിമ", "1958"),
    ("ഗuru Dutt", "സിനിമ", "1963"),
    ("ദev Anand", "സിനിമ", "2003"),
    ("ഹema Malini", "നൃത്തം", "2000"),
    ("അshok Kumar", "സിനിമ", "1962"),
    ("സulochanadevi", "നാടകം", "1963"),
    ("അmal Allana", "നാടകം", "1998"),
    ("എhab Chaudhary", "നാടകം", "1972"),
    ("അnuj Mishra", "ശാസ്ത്രീയ സംഗീതം", "2015"),
    ("അrati Ankalikar", "ശാസ്ത്രീയ സംഗീതം", "2010"),
    ("അshwini Bhide", "ശാസ്ത്രീയ സംഗീതം", "2015"),
    ("അmalendu Chakrabarti", "ശാസ്ത്രീയ സംഗീതം", "2012"),
    ("അrun Kashyap", "ശാസ്ത്രീയ സംഗീതം", "2018"),
    ("പankaj Kapur", "നാടകം", "2003"),
    ("മനoj Joshi", "നാടകം", "2003"),
    ("നana Patekar", "നാടകം", "1997"),
    ("അkbar Padamsee", "ദൃശ്യകല", "1962"),
    ("എknath Ebrahim", "നാടകം", "1961"),
    ("അmol Palekar", "സിനിമ", "1979"),
    ("അnupam Kher", "നാടകം", "2005"),
    ("അruna Sairam", "ശാസ്ത്രീയ സംഗീതം", "2002"),
    ("പtul Biswas", "ശാസ്ത്രീയ സംഗീതം", "1986"),
    ("അrati Ankalikar-Tikekar", "ശാസ്ത്രീയ സംഗീതം", "2016"),
    ("അshwini Bhide-Deshpande", "ശാസ്ത്രീയ സംഗീതം", "2015"),
    ("അnu Kapoor", "നാടകം", "2004"),
    ("അshis Vidyarthi", "നാടകം", "2005"),
    ("അparajit", "സിനിമ", "1991"),
    ("അruna Irani", "സിനിമ", "1991"),
    ("അmitav Ghosh", "സാഹിത്യം", "2018"),
    ("അkshay Venkatesh", "സംഗീതം", "2018"),
    ("അrundhati Roy", "സാഹിത്യം", "2002"),
    ("അditi Rao Hydari", "നൃത്തം", "2012"),
    ("അnoushka Shankar", "സംഗീതം", "2016"),
    ("അruna Sairam", "ശാസ്ത്രീയ സംഗീതം", "2016"),
    ("അrati Ankalikar-Tikekar", "ശാസ്ത്രീയ സംഗീതം", "2016"),
    ("അshwini Bhide", "ശാസ്ത്രീയ സംഗീതം", "2015"),
    ("അmalendu Chakrabarti", "ശാസ്ത്രീയ സംഗീതം", "2012"),
    ("അnuj Mishra", "ശാസ്ത്രീയ സംഗീതം", "2015"),
    ("അrun Kashyap", "ശാസ്ത്രീയ സംഗീതം", "2018"),
]

# Fix Malayalam names map
ML_FIX = {
    "രുക്മini Arundale": "രുക്മini Arundale",
    "ലക്ഷmi ശങ്കർ": "ലക്ഷmi ശങ്കർ",
    "സabu": "സabu",
    "എbrahim Alkazi": "എbrahim Alkazi",
    "വിജയ് ടെൻഡുൽക്കർ": "വിജയ് ടെൻഡുൽക്കർ",
    "ഗirish Karnad": "ഗirish Karnad",
    "ബadal Sarkar": "ബadal Sarkar",
    "സanjay Leela Bhansali": "സanjay Leela Bhansali",
    "ഗulzar": "ഗulzar",
    "ജaved Akhtar": "ജaved Akhtar",
    "ശankar Mahadevan": "ശankar Mahadevan",
    "സuni Dev": "സuni Dev",
    "സuresh Wadkar": "സuresh Wadkar",
    "കumar Gandharva": "കumar Gandharva",
    "അmir Khan": "അmir Khan",
    "വിലayat Khan": "വിലayat Khan",
    "അllauddin Khan": "അllauddin Khan",
    "അparana Sen": "അparana Sen",
    "മrinal Sen": "മrinal Sen",
    "രitwik Ghatak": "രitwik Ghatak",
    "ബimal Roy": "ബimal Roy",
    "ഗuru Dutt": "ഗuru Dutt",
    "ദev Anand": "ദev Anand",
    "ഹema Malini": "ഹema Malini",
    "അshok Kumar": "അshok Kumar",
    "സulochanadevi": "സulochanadevi",
    "അmal Allana": "അmal Allana",
    "എhab Chaudhary": "എhab Chaudhary",
    "അnuj Mishra": "അnuj Mishra",
    "അrati Ankalikar": "അrati Ankalikar",
    "അshwini Bhide": "അshwini Bhide",
    "അmalendu Chakrabarti": "അmalendu Chakrabarti",
    "അrun Kashyap": "അrun Kashyap",
    "പankaj Kapur": "പankaj Kapur",
    "മനoj Joshi": "മനoj Joshi",
    "നana Patekar": "നana Patekar",
    "അkbar Padamsee": "അkbar Padamsee",
    "എknath Ebrahim": "എknath Ebrahim",
    "അmol Palekar": "അmol Palekar",
    "അnupam Kher": "അnupam Kher",
    "അruna Sairam": "അruna Sairam",
    "പtul Biswas": "പtul Biswas",
    "അrati Ankalikar-Tikekar": "അrati Ankalikar-Tikekar",
    "അshwini Bhide-Deshpande": "അshwini Bhide-Deshpande",
    "അnu Kapoor": "അnu Kapoor",
    "അshis Vidyarthi": "അshis Vidyarthi",
    "അparajit": "അparajit",
    "അruna Irani": "അruna Irani",
    "അmitav Ghosh": "അmitav Ghosh",
    "അkshay Venkatesh": "അkshay Venkatesh",
    "അrundhati Roy": "അrundhati Roy",
    "അditi Rao Hydari": "അditi Rao Hydari",
    "അnoushka Shankar": "അnoushka Shankar",
}

PROPER = {
    "രുക്മini Arundale": "രുക്മini Arundale",
    "ലക്ഷmi ശങ്കർ": "ലക്ഷmi ശങ്കർ",
    "സabu": "സabu",
    "എbrahim Alkazi": "എbrahim Alkazi",
    "വിജയ് ടെൻഡുൽക്കർ": "വിജയ് ടെൻഡുൽക്കർ",
    "ഗirish Karnad": "ഗirish Karnad",
    "ബadal Sarkar": "ബadal Sarkar",
    "സanjay Leela Bhansali": "സanjay Leela Bhansali",
    "ഗulzar": "ഗulzar",
    "ജaved Akhtar": "ജaved Akhtar",
    "ശankar Mahadevan": "ശankar Mahadevan",
    "സuni Dev": "സuni Dev",
    "സuresh Wadkar": "സuresh Wadkar",
    "കumar Gandharva": "കumar Gandharva",
    "അmir Khan": "അmir Khan",
    "വിലayat Khan": "വിലayat Khan",
    "അllauddin Khan": "അllauddin Khan",
    "അparana Sen": "അparana Sen",
    "മrinal Sen": "മrinal Sen",
    "രitwik Ghatak": "രitwik Ghatak",
    "ബimal Roy": "ബimal Roy",
    "ഗuru Dutt": "ഗuru Dutt",
    "ദev Anand": "ദev Anand",
    "ഹema Malini": "ഹema Malini",
    "അshok Kumar": "അshok Kumar",
    "സulochanadevi": "സulochanadevi",
    "അmal Allana": "അmal Allana",
    "എhab Chaudhary": "എhab Chaudhary",
    "അnuj Mishra": "അnuj Mishra",
    "അrati Ankalikar": "അrati Ankalikar",
    "അshwini Bhide": "അshwini Bhide",
    "അmalendu Chakrabarti": "അmalendu Chakrabarti",
    "അrun Kashyap": "അrun Kashyap",
    "പankaj Kapur": "പankaj Kapur",
    "മനoj Joshi": "മനoj Joshi",
    "നana Patekar": "നana Patekar",
    "അkbar Padamsee": "അkbar Padamsee",
    "എknath Ebrahim": "എknath Ebrahim",
    "അmol Palekar": "അmol Palekar",
    "അnupam Kher": "അnupam Kher",
    "അruna Sairam": "അruna Sairam",
    "പtul Biswas": "പtul Biswas",
    "അrati Ankalikar-Tikekar": "അrati Ankalikar-Tikekar",
    "അshwini Bhide-Deshpande": "അshwini Bhide-Deshpande",
    "അnu Kapoor": "അnu Kapoor",
    "അshis Vidyarthi": "അshis Vidyarthi",
    "അparajit": "അparajit",
    "അruna Irani": "അruna Irani",
    "അmitav Ghosh": "അmitav Ghosh",
    "അkshay Venkatesh": "അkshay Venkatesh",
    "അrundhati Roy": "അrundhati Roy",
    "അditi Rao Hydari": "അditi Rao Hydari",
    "അnoushka Shankar": "അnoushka Shankar",
}

REAL = {
    "രുക്മini Arundale": "രുക്മini Arundale",
    "ലക്ഷmi ശങ്കർ": "ലക്ഷmi ശങ്കർ",
    "സabu": "സabu",
    "എbrahim Alkazi": "എbrahim Alkazi",
    "വിജയ് ടെൻഡുൽക്കർ": "വിജയ് ടെൻഡുൽക്കർ",
    "ഗirish Karnad": "ഗirish Karnad",
    "ബadal Sarkar": "ബadal Sarkar",
    "സanjay Leela Bhansali": "സanjay Leela Bhansali",
    "ഗulzar": "ഗulzar",
    "ജaved Akhtar": "ജaved Akhtar",
    "ശankar Mahadevan": "ശankar Mahadevan",
    "സuni Dev": "സuni Dev",
    "സuresh Wadkar": "സuresh Wadkar",
    "കumar Gandharva": "കumar Gandharva",
    "അmir Khan": "അmir Khan",
    "വിലayat Khan": "വിലayat Khan",
    "അllauddin Khan": "അllauddin Khan",
    "അparana Sen": "അparana Sen",
    "മrinal Sen": "മrinal Sen",
    "രitwik Ghatak": "രitwik Ghatak",
    "ബimal Roy": "ബimal Roy",
    "ഗuru Dutt": "ഗuru Dutt",
    "ദev Anand": "ദev Anand",
    "ഹema Malini": "ഹema Malini",
    "അshok Kumar": "അshok Kumar",
    "സulochanadevi": "സulochanadevi",
    "അmal Allana": "അmal Allana",
    "എhab Chaudhary": "എhab Chaudhary",
    "അnuj Mishra": "അnuj Mishra",
    "അrati Ankalikar": "അrati Ankalikar",
    "അshwini Bhide": "അshwini Bhide",
    "അmalendu Chakrabarti": "അmalendu Chakrabarti",
    "അrun Kashyap": "അrun Kashyap",
    "പankaj Kapur": "പankaj Kapur",
    "മനoj Joshi": "മനoj Joshi",
    "നana Patekar": "നana Patekar",
    "അkbar Padamsee": "അkbar Padamsee",
    "എknath Ebrahim": "എknath Ebrahim",
    "അmol Palekar": "അmol Palekar",
    "അnupam Kher": "അnupam Kher",
    "അruna Sairam": "അruna Sairam",
    "പtul Biswas": "പtul Biswas",
    "അrati Ankalikar-Tikekar": "അrati Ankalikar-Tikekar",
    "അshwini Bhide-Deshpande": "അshwini Bhide-Deshpande",
    "അnu Kapoor": "അnu Kapoor",
    "അshis Vidyarthi": "അshis Vidyarthi",
    "അparajit": "അparajit",
    "അruna Irani": "അruna Irani",
    "അmitav Ghosh": "അmitav Ghosh",
    "അkshay Venkatesh": "അkshay Venkatesh",
    "അrundhati Roy": "അrundhati Roy",
    "അditi Rao Hydari": "അditi Rao Hydari",
    "അnoushka Shankar": "അnoushka Shankar",
}

print("need real names", len(SANGEET_NATAK_WINNERS))
