#!/usr/bin/env python3
"""Wave 30 Indian industries facts — 30 Malayalam PSC topic types."""

from __future__ import annotations

import random

from refill_common import Candidate
from wave30_emit import emit_category, emit_direct

INDUSTRIAL_POLICY: list[tuple[str, str]] = [('ദേശീയ നിർമ്മാണ നയം 2011', 'ജിഡിപിയിൽ 25% ലക്ഷ്യം'),
 ('ദേശീയ നിർമ്മാണ നയം 2011', '10 കോടി തൊഴിൽ സൃഷ്ടി'),
 ('ഇന്ത്യൻ നയം 1956', 'പൊതുമേഖലാ പ്രാധാന്യം'),
 ('ഇന്ത്യൻ നയം 1991', 'ഉദാരീകരണം'),
 ('NIMZ നയം', '2011'),
 ('ഇന്ത്യൻ നയം 1948', 'മിശ്ര സമ്പദ്വ്യവസ്ഥ'),
 ('ഇന്ത്യൻ നയം 1977', 'ചെറുകിട വ്യവസായ പ്രോത്സാഹനം'),
 ('ഇന്ത്യൻ നയം 1980', 'വിപുലീകരണം'),
 ('ഇന്ത്യൻ നയം 1985', 'സാങ്കേതികവിദ്യാ കൈമാറ്റം'),
 ('ഇന്ത്യൻ നയം 1991', 'എൽ.പി.ജി. നയം'),
 ('ഇന്ത്യൻ നയം 1991', 'ലൈസൻസ് രാജ് അവസാനം'),
 ('ഇന്ത്യൻ നയം 1956', 'ഷെഡ്യൂൾ A/B/C വർഗ്ഗീകരണം'),
 ('ദേശീയ നിർമ്മാണ നയം', '100 മില്യൺ തൊഴിൽ'),
 ('NIMZ', '5000 ഹെക്ടർ മിനിമം'),
 ('ദേശീയ വ്യവസായ കോറിഡോർ പരിപാടി', 'DPIIT നോഡൽ'),
 ('ദേശീയ വ്യവസായ കോറിഡോർ പരിപാടി', 'NICDC'),
 ('ഇന്ത്യൻ നയം 1991', 'MRTP നിയമം പരിഷ്കരണം'),
 ('ഇന്ത്യൻ നയം 1948', 'വ്യവസായ വികസന ബോർഡ്'),
 ('ഇന്ത്യൻ നയം 1956', 'ഇരുപതാം ഭരണഘടനാ ഭേദഗതി'),
 ('ഇന്ത്യൻ നയം 1977', 'FFSI സ്ഥാപനം'),
 ('ഇന്ത്യൻ നയം 1980', 'എക്സ്പോർട്ട് പ്രോസസ്സിംഗ് സോൺ'),
 ('ഇന്ത്യൻ നയം 1985', 'MODVAT'),
 ('ഇന്ത്യൻ നയം 1991', '1991 ജൂലൈ'),
 ('ദേശീയ നിർമ്മാണ നയം', '2011'),
 ('ഇന്ത്യൻ നയം 1991', 'വിദേശ നിക്ഷേപം സ്വതന്ത്രം'),
 ('ഇന്ത്യൻ നയം 1956', 'സാമൂഹിക നിയന്ത്രണം'),
 ('ഇന്ത്യൻ നയം 1991', 'പൊതുമേഖലാ പുനഃസംഘടന'),
 ('NIMZ', 'ഒറ്റ സ്ഥല വികസനം'),
 ('ദേശീയ നിർമ്മാണ നയം', 'NIMZ സൃഷ്ടി'),
 ('ഇന്ത്യൻ നയം 1956', 'ആദ്യ പഞ്ചവത്സര പദ്ധതി അടിസ്ഥാനം')]
MAKE_IN_INDIA: list[tuple[str, str]] = [('മേക്ക് ഇൻ ഇന്ത്യ', '2014 സെപ്റ്റംബർ 25'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'സിംഹം ചിഹ്നം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', '25 മേഖലാ ശ്രദ്ധ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'വാണിജ്യ & വ്യവസായ മന്ത്രാലയം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'നിർമ്മാണം & സേവനങ്ങൾ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'വിദേശ നിക്ഷേപം ആകർഷണം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഉത്പാദനക്ഷമത വർദ്ധന'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ജോബ് ക്രിയേഷൻ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഡിജിറ്റൽ ലോകം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഇൻവെസ്റ്റ് ഇന്ത്യ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'സ്റ്റാർട്ട്-അപ്പ് ഇന്ത്യ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'സ്കിൽ ഇന്ത്യ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'നരേന്ദ്ര മോദി ആരംഭിച്ചത്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'വിദേശ നിക്ഷേപം എളുപ്പമാക്കൽ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഇൻഫ്രാസ്ട്രക്ചർ വികസനം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഡിഫൻസ് മേഖലാ FDI'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'റെയിൽവേ FDI'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'മെഡിക്കൽ ഡിവൈസസ്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഓട്ടോമൊബൈൽ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഇലക്ട്രോണിക്സ്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ടെക്സ്റ്റൈൽ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഫുഡ് പ്രോസസ്സിംഗ്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ആയുർവേദം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'റിയൽ എസ്റ്റേറ്റ് FDI'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', '100% FDI റൂട്ട്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഇ-ബിസ് പോർട്ടൽ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ലോഗോ സ്പർശിക്കുന്ന സിംഹം'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഗ്ലോബൽ മാനുഫാക്ചറിംഗ് ഹബ്'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'ഇൻവെസ്റ്റർ സേവന കേന്ദ്രങ്ങൾ'),
 ('മേക്ക് ഇൻ ഇന്ത്യ', 'സിംഗിൾ വിൻഡോ ക്ലിയറൻസ്')]
PLI_SCHEME: list[tuple[str, str]] = [('PLI മൊബൈൽ നിർമ്മാണം', '2020 ആദ്യ മേഖല'),
 ('PLI മൊബൈൽ നിർമ്മാണം', '₹40951 കോടി'),
 ('PLI ഫാർമാസ്യൂട്ടിക്കൽസ്', 'API & ഡ്രഗ് ഇന്റർമീഡിയറ്റ്സ്'),
 ('PLI ഓട്ടോമൊബൈൽ', 'ഇലക്ട്രിക് വാഹനങ്ങൾ'),
 ('PLI ടെക്സ്റ്റൈൽ', 'മാൻ-മേഡ് ഫൈബർ'),
 ('PLI ഫുഡ് പ്രോസസ്സിംഗ്', '2020'),
 ('PLI സോളാർ PV മോഡ്യൂൾസ്', '2020'),
 ('PLI വൈറ്റ് ഗുഡ്സ്', 'AC & LED'),
 ('PLI സ്പെഷ്യൽ സ്റ്റീൽ', '2020'),
 ('PLI ഇലക്ട്രോണിക്സ്', '2020'),
 ('PLI ഡ്രോണുകൾ', '2021'),
 ('PLI സെമികണ്ടക്ടർ', '2021'),
 ('PLI ബാറ്ററി സ്റ്റോറേജ്', '2021'),
 ('PLI ടോയ്', '2020'),
 ('PLI ടെക്സ്റ്റൈൽ', 'ടെക്നിക്കൽ ടെക്സ്റ്റൈൽ'),
 ('PLI ഫാർമാസ്യൂട്ടിക്കൽസ്', '₹15000 കോടി'),
 ('PLI ഓട്ടോമൊബൈൽ', '₹25938 കോടി'),
 ('PLI സോളാർ', '₹4500 കോടി'),
 ('PLI വൈറ്റ് ഗുഡ്സ്', '₹6238 കോടി'),
 ('PLI ഇലക്ട്രോണിക്സ്', '₹5000 കോടി'),
 ('PLI ടെക്സ്റ്റൈൽ', '₹10683 കോടി'),
 ('PLI ഫുഡ് പ്രോസസ്സിംഗ്', '₹10900 കോടി'),
 ('PLI സ്പെഷ്യൽ സ്റ്റീൽ', '₹6322 കോടി'),
 ('PLI ഡ്രോണുകൾ', '₹120 കോടി'),
 ('PLI സെമികണ്ടക്ടർ', '₹76000 കോടി'),
 ('PLI ബാറ്ററി', '₹18100 കോടി'),
 ('PLI', 'Production Linked Incentive'),
 ('PLI', 'ഉത്പാദനം അടിസ്ഥാനമാക്കിയുള്ള പ്രോത്സാഹനം'),
 ('PLI', 'DPIIT നോഡൽ'),
 ('PLI', '5-7 വർഷ കാലാവധി')]
MSME_CATEGORY: list[tuple[str, str]] = [('മൈക്രോ എന്റർപ്രൈസ്', 'നിക്ഷേപം ₹1 കോടി വരെ'),
 ('സ്മോൾ എന്റർപ്രൈസ്', 'നിക്ഷേപം ₹10 കോടി വരെ'),
 ('മീഡിയം എന്റർപ്രൈസ്', 'നിക്ഷേപം ₹50 കോടി വരെ'),
 ('മൈക്രോ എന്റർപ്രൈസ്', 'വിറ്റുവരവ് ₹5 കോടി വരെ'),
 ('സ്മോൾ എന്റർപ്രൈസ്', 'വിറ്റുവരവ് ₹50 കോടി വരെ'),
 ('മീഡിയം എന്റർപ്രൈസ്', 'വിറ്റുവരവ് ₹250 കോടി വരെ'),
 ('എം.എസ്.എം.ഇ', '2020 പരിഷ്കരണം'),
 ('എം.എസ്.എം.ഇ', 'നിക്ഷേപവും വിറ്റുവരവും അടിസ്ഥാനം'),
 ('ഉദ്യമി', 'ഒറ്റ ഉടമസ്ഥൻ/പാർട്ണർഷിപ്പ്'),
 ('ചെറുകിട വ്യവസായി', '50 തൊഴിലാളികൾ വരെ'),
 ('വില്ലേജ് എന്റർപ്രൈസ്', 'ഗ്രാമീണ മേഖള'),
 ('കുടീര വ്യവസായി', 'വീട്ടുവഴി നിർമ്മാണം'),
 ('എം.എസ്.എം.ഇ', 'ജിഡിപിയിൽ 30% സംഭാവന'),
 ('എം.എസ്.എം.ഇ', 'കയറ്റുമതിയിൽ 45%'),
 ('എം.എസ്.എം.ഇ', 'തൊഴിലിൽ 11 കോടി+'),
 ('എം.എസ്.എം.ഇ', '6.3 കോടി യൂണിറ്റുകൾ'),
 ('എം.എസ്.എം.ഇ', 'ഉദ്യം പോർട്ടൽ'),
 ('ഉദ്യം', '2020 രജിസ്ട്രേഷൻ'),
 ('ZED സർട്ടിഫിക്കേഷൻ', 'ഗുണനിലവാര മേമ്പാട്'),
 ('ചെറുകിട വ്യവസായി', '₹1 കോടി നിക്ഷേപ പരിധി'),
 ('എം.എസ്.എം.ഇ', 'കൈമാറ്റ വിലയിരുത്തൽ അടിസ്ഥാനം'),
 ('എം.എസ്.എം.ഇ', 'സേവന മേഖള ഉൾപ്പെടുന്നു'),
 ('എം.എസ്.എം.ഇ', 'വ്യാപാര മേഖള ഉൾപ്പെടുന്നു'),
 ('എം.എസ്.എം.ഇ', 'നിർമ്മാണ മേഖള ഉൾപ്പെടുന്നു'),
 ('എം.എസ്.എം.ഇ', 'MSME Development Act 2006'),
 ('എം.എസ്.എം.ഇ', '2020 ഭേദഗതി'),
 ('മൈക്രോ എന്റർപ്രൈസ്', 'ചെറിയ നിക്ഷേപം'),
 ('സ്മോൾ എന്റർപ്രൈസ്', 'ഇടത്തരം നിക്ഷേപം'),
 ('മീഡിയം എന്റർപ്രൈസ്', 'വലിയ നിക്ഷേപം'),
 ('എം.എസ്.എം.ഇ', 'ആധുനികീകരണം & സാങ്കേതികവിദ്യ')]
MSME_INSTITUTION: list[tuple[str, str]] = [('SIDBI', 'എം.എസ്.എം.ഇ ധനസഹായി'),
 ('NSIC', 'ചെറുകിട വ്യവസായി സഹായി'),
 ('KVIC', 'ഗ്രാമീണ വ്യവസായി'),
 ('DC-MSME', 'കേന്ദ്ര വകുപ്പ്'),
 ('NABARD', 'ഗ്രാമീണ വികസന ധനം'),
 ('MUDRA', 'ചെറുകിട വায়്പ'),
 ('CGTMSE', 'വায়്പാ ഗ്യാരന്റി'),
 ('CLCSS', 'സാങ്കേതികവിദ്യാ അപ്ഗ്രേഡേഷൻ'),
 ('PMEGP', 'സംരംഭകത്വ പദ്ധതി'),
 ('SFURTI', 'പാരമ്പര്യ വ്യവസായി ക്ലസ്റ്റർ'),
 ('ASPIRE', 'സംരംഭകത്വ പരിപാടി'),
 ('RAMP', 'എം.എസ്.എം.ഇ പരിഷ്കരണം'),
 ('CHAMPIONS', 'എം.എസ്.എം.ഇ പോർട്ടൽ'),
 ('Udyamimitra', 'വায়്പാ മാർഗ്ഗനിർദ്ദേശം'),
 ('SIDBI', '1990 സ്ഥാപനം'),
 ('NSIC', '1955 സ്ഥാപനം'),
 ('KVIC', '1956 സ്ഥാപനം'),
 ('DC-MSME', 'വാണിജ്യ & വ്യവസായി മന്ത്രാലയം'),
 ('SIDBI', 'ചെറുകിട വ്യവസായി വികസന ബാങ്ക്'),
 ('NSIC', 'റോ മെറ്റീരിയൽ & മാർക്കറ്റിംഗ്'),
 ('KVIC', 'ഖാദി & വില്ലേജ് ഇൻഡസ്ട്രി'),
 ('MUDRA', 'ശിശു/കിഷോർ/തരുണ് വায়്പ'),
 ('CGTMSE', 'കൊളാറ്ററൽ ഫ്രീ വায়്പ'),
 ('PMEGP', 'ഖാദി & വില്ലേജ് ഇൻഡസ്ട്രി'),
 ('SFURTI', 'പാരമ്പര്യ കരകുശಲ ക്ലസ്റ്റർ'),
 ('ASPIRE', 'ഗ്രാമീണ സംരംഭകത്വം'),
 ('RAMP', '2022 ആരംഭം'),
 ('CHAMPIONS', '2020 ആരംഭം'),
 ('NABARD', 'കാർഷിക & ഗ്രാമീണ വികസനം'),
 ('DC-MSME', 'നയം & പരിപാലനം')]
SEZ_POLICY: list[tuple[str, str]] = [('SEZ നയം', '2000 ഏപ്രിൽ'),
 ('SEZ നിയമം', '2005'),
 ('കാന്ദ്ല EPZ', '1965 ആദ്യം'),
 ('കാന്ദ്ല EPZ', 'ഗുജറാത്ത്'),
 ('SEZ', '100% FDI അനുവാദം'),
 ('SEZ', 'നികുതി ആനുകൂல്യങ്ങൾ'),
 ('SEZ', 'കസ്റ്റംസ് ഫ്രീ'),
 ('SEZ', 'വിദേശ വ്യാപാര മേഖള'),
 ('SEZ', 'DPIIT നോഡൽ'),
 ('SEZ', '5000 ഹെക്ടർ വരെ'),
 ('SEZ', 'സിംഗിൾ/മൾട്ടി പ്രൊഡക്റ്റ്'),
 ('SEZ', 'IT/ITES SEZ'),
 ('SEZ', 'ബയോ-ടെക് SEZ'),
 ('SEZ', 'മൾട്ടി-സർവീസ് SEZ'),
 ('SEZ', 'എക്സ്പോർട്ട് ഓറിയന്റഡ്'),
 ('SEZ', 'ഇൻഫ്രാസ്ട്രക്ചർ ഡെവൽപ്പർ'),
 ('SEZ', 'കോ-ഡെവൽപ്പർ'),
 ('SEZ', 'യൂണിറ്റ് അഡ്മിനിസ്ട്രേഷൻ'),
 ('SEZ', 'Development Commissioner'),
 ('SEZ', 'സംസ്ഥാന സർക്കാർ പങ്ക്'),
 ('SEZ', 'കൊച്ചി SEZ'),
 ('SEZ', 'നോയിഡ SEZ'),
 ('SEZ', 'ശ്രീ സിറ്റി SEZ'),
 ('SEZ', 'മഹീന്ദ്ര വേൾഡ് സിറ്റി'),
 ('SEZ', 'ഫോർട്രാൻസ്'),
 ('SEZ', 'സന്തകൃഷ്ണ SEZ'),
 ('SEZ', 'വിശാഖപട്ടണം SEZ'),
 ('SEZ', 'കാന്ദ്ല SEZ'),
 ('SEZ', 'സൂറത്ത് SEZ'),
 ('SEZ', 'EPZ പരിഷ്കരണം')]
PSU_SECTOR: list[tuple[str, str]] = [('BHEL', 'Power equipment'),
 ('HAL', 'Aerospace/Defence'),
 ('SAIL', 'Steel'),
 ('ONGC', 'Oil and gas exploration'),
 ('NTPC', 'Power generation'),
 ('IOCL', 'Oil refining/marketing'),
 ('Coal India', 'Coal mining'),
 ('GAIL', 'Natural gas'),
 ('NHPC', 'Hydro power'),
 ('BEL', 'Defence electronics'),
 ('BEML', 'Heavy equipment'),
 ('MIDHANI', 'Special metals/alloys'),
 ('NLC India', 'Lignite mining/power'),
 ('SCI', 'Shipping'),
 ('HPCL', 'Oil marketing'),
 ('BPCL', 'Oil marketing'),
 ('NALCO', 'Aluminium'),
 ('NMDC', 'Iron ore'),
 ('ECIL', 'Electronics'),
 ('HCL', 'Copper'),
 ('MOIL', 'Manganese'),
 ('ITI', 'Telecom equipment'),
 ('MTNL', 'Telecom'),
 ('BSNL', 'Telecom'),
 ('Cochin Shipyard', 'Shipbuilding'),
 ('Mazagon Dock', 'Ships/submarines'),
 ('GRSE', 'Warships'),
 ('Goa Shipyard', 'Shipbuilding'),
 ('Hindustan Shipyard', 'Shipbuilding'),
 ('BDL', 'Guided missiles')]
PSU_HQ: list[tuple[str, str]] = [('BHEL', 'New Delhi'),
 ('HAL', 'ബെംഗളൂരു'),
 ('SAIL', 'New Delhi'),
 ('ONGC', 'New Delhi'),
 ('NTPC', 'New Delhi'),
 ('IOCL', 'New Delhi'),
 ('Coal India', 'Kolkata'),
 ('GAIL', 'New Delhi'),
 ('NHPC', 'Faridabad'),
 ('BEL', 'ബെംഗളൂരു'),
 ('BEML', 'ബെംഗളൂരു'),
 ('MIDHANI', 'Hyderabad'),
 ('NLC India', 'Neyveli'),
 ('SCI', 'Mumbai'),
 ('HPCL', 'Mumbai'),
 ('BPCL', 'Mumbai'),
 ('NALCO', 'Bhubaneswar'),
 ('NMDC', 'Hyderabad'),
 ('ECIL', 'Hyderabad'),
 ('HCL', 'Ranchi'),
 ('MOIL', 'Nagpur'),
 ('ITI', 'ബെംഗളൂരു'),
 ('MTNL', 'New Delhi'),
 ('BSNL', 'New Delhi'),
 ('Cochin Shipyard', 'Kochi'),
 ('Mazagon Dock', 'Mumbai'),
 ('GRSE', 'Kolkata'),
 ('Goa Shipyard', 'Vasco da Gama'),
 ('Hindustan Shipyard', 'Visakhapatnam'),
 ('BDL', 'Hyderabad')]
CORRIDORS: list[tuple[str, str]] = [('DMIC', '1500 കി.മീ.'),
 ('DMIC', 'ദില്ലി-മുംബൈ'),
 ('DMIC', '6 സംസ്ഥാനങ്ങൾ'),
 ('അമൃത്സർ-കൊൽക്കത്ത കോറിഡോർ', 'ഈസ്റ്റേൺ DFC'),
 ('ചെന്നൈ-ബെംഗളൂരു കോറിഡോർ', 'ഈസ്റ്റ് കോസ്റ്റ് ഇക്കണോമിക് കോറിഡോർ'),
 ('വിശാഖപട്ടണം-ചെന്നൈ കോറിഡോർ', 'ആന്ധ്രപ്രദേശ്'),
 ('ബെംഗളൂരു-മുംബൈ കോറിഡോർ', 'കർണാടക & മഹാരാഷ്ട്ര'),
 ('ബിളാസ്പൂർ-ദുർഗാപൂർ കോറിഡോർ', 'ഛത്തീസ്ഗഢ് & പശ്ചിമബംഗാൾ'),
 ('ഹൈദരാബാദ്-ബെംഗളൂരു കോറിഡോർ', 'ഇൽക്ട്രോണിക്സ് & ഐടി'),
 ('ഈസ്റ്റ് കോസ്റ്റ് ഇക്കണോമിക് കോറിഡോർ', 'വിശാഖ-ചെന്നൈ'),
 ('NICDP', 'DPIIT നോഡൽ'),
 ('NICDC', 'അടിസ്ഥാന സൗകര്യ വികസനം'),
 ('DMIC', 'അടിസ്ഥാന സൗകര്യ ക്ലസ്റ്റർ'),
 ('DMIC', 'വ്യാവസായിിക നഗരങ്ങൾ'),
 ('DMIC', 'റോഡ് & റെയിൽ കണക്ടിവിറ്റി'),
 ('അമൃത്സർ-കൊൽക്കത്ത കോറിഡോർ', 'പഞ്ചാബ്-ബംഗാൾ'),
 ('ചെന്നൈ-ബെംഗളൂരു കോറിഡോർ', 'തമിഴ്നാട്-കർണാടക'),
 ('വിശാഖപട്ടണം-ചെന്നൈ കോറിഡോർ', 'കോസ്റ്റൽ ബെൽറ്റ്'),
 ('ബെംഗളൂരു-മുംബൈ കോറിഡോർ', 'പശ്ചിമ തീരം'),
 ('ബിളാസ്പൂർ-ദുർഗാപൂർ കോറിഡോർ', 'മിനറൽ കോറിഡോർ'),
 ('ഹൈദരാബാദ്-ബെംഗളൂരു കോറിഡോർ', 'ദക്ഷിണേന്ത്യ'),
 ('DMIC', 'വാണിജ്യ & വ്യവസായി മന്ത്രാലയം'),
 ('NICDP', '2016 ആരംഭം'),
 ('DMIC', 'ജപ്പാൻ സഹകരണം'),
 ('DMIC', '₹100 ലക്ഷം കോടി ലക്ഷ്യം'),
 ('അമൃത്സർ-കൊൽക്കത്ത കോറിഡോർ', 'അഗ്രോ & ടെക്സ്റ്റൈൽ'),
 ('ചെന്നൈ-ബെംഗളൂരു കോറിഡോർ', 'ഓട്ടോ & ഇൽക്ട്രോണിക്സ്'),
 ('വിശാഖപട്ടണം-ചെന്നൈ കോറിഡോർ', 'പോർട്ട് ലിങ്ക്'),
 ('ബെംഗളൂരു-മുംബൈ കോറിഡോർ', 'ഫാർമ & ഐടി'),
 ('NICDC', 'SPV'),
 ('NICDP', '11 ഇൻഡസ്ട്രിയൽ കോറിഡോറുകൾ')]
COMMODITY_BOARD_HQ: list[tuple[str, str]] = [('സ്പൈസസ് ബോർഡ്', 'കൊച്ചി'),
 ('റബ്ബർ ബോർഡ്', 'കോട്ടയം'),
 ('ടീ ബോർഡ്', 'കൊൽക്കത്ത'),
 ('കോഫി ബോർഡ്', 'ബെംഗളൂരു'),
 ('കോയർ ബോർഡ്', 'കൊച്ചി'),
 ('ടോബാക്കോ ബോർഡ്', 'ഗുണ്ടൂർ'),
 ('സെൻട്രൽ സിൽക് ബോർഡ്', 'ബെംഗളൂരു'),
 ('ചവറുക ബോർഡ്', 'കൊൽക്കത്ത'),
 ('പരുത്തി ഉപദേശക ബോർഡ്', 'മുംബൈ'),
 ('തേങ്ങാ വികസന ബോർഡ്', 'കൊച്ചി'),
 ('എണ്ണക്കുരു & പയർ ബോർഡ്', 'ഇന്ദോർ'),
 ('ദേശീയ ഉദ്യാന ബോർഡ്', 'ഗുരുഗ്രാം'),
 ('കാഷ്യൂ എക്സ്പോർട്ട് പ്രമോഷൻ കൗൺസിൽ', 'കൊച്ചി'),
 ('മത്സ്യ ഉൽപ്പന്ന എക്സ്പോർട്ട് വികസന അതോറിറ്റി', 'കൊച്ചി'),
 ('കാർഷിക-പ്രോസസ്ഡ് ഫുഡ് എക്സ്പോർട്ട്', 'ന്യൂ ഡൽഹി'),
 ('കരകുശല കയറ്റുമതി പ്രമോഷൻ കൗൺസിൽ', 'ന്യൂ ഡൽഹി'),
 ('കയറ്റുമതി പരിശോധന കൗൺസിൽ', 'ന്യൂ ഡൽഹി'),
 ('എല്ലാ ഇന്ത്യ കരകുശല ബോർഡ്', 'ന്യൂ ഡൽഹി'),
 ('സ്പൈസസ് ബോർഡ്', 'എറണാകുളം'),
 ('റബ്ബർ ബോർഡ്', 'കോട്ടയം ജില്ല'),
 ('ടീ ബോർഡ്', 'പശ്ചിമബംഗാൾ'),
 ('കോഫി ബോർഡ്', 'കർണാടക'),
 ('കോയർ ബോർഡ്', 'കേരളം'),
 ('ടോബാക്കോ ബോർഡ്', 'ആന്ധ്രപ്രദേശ്'),
 ('സെൻട്രൽ സിൽക് ബോർഡ്', 'കർണാടക'),
 ('ചവറുക ബോർഡ്', 'പശ്ചിമബംഗാൾ'),
 ('പരുത്തി ഉപദേശക ബോർഡ്', 'മഹാരാഷ്ട്ര'),
 ('തേങ്ങാ വികസന ബോർഡ്', 'കേരളം'),
 ('എണ്ണക്കുരു & പയർ ബോർഡ്', 'മധ്യപ്രദേശ്'),
 ('ദേശീയ ഉദ്യാന ബോർഡ്', 'ഹരിയാന')]
COMMODITY_PRODUCT: list[tuple[str, str]] = [('സ്പൈസസ് ബോർഡ്', 'സുഗന്ധവ്യഞ്ജനങ്ങൾ'),
 ('റബ്ബർ ബോർഡ്', 'റബ്ബർ'),
 ('ടീ ബോർഡ്', 'ചായ'),
 ('കോഫി ബോർഡ്', 'കാപ്പി'),
 ('കോയർ ബോർഡ്', 'കയർ'),
 ('ടോബാക്കോ ബോർഡ്', 'പുകയില'),
 ('സെൻട്രൽ സിൽക് ബോർഡ്', 'പട്ട്'),
 ('ചവറുക ബോർഡ്', 'ചവറുക'),
 ('പരുത്തി ഉപദേശക ബോർഡ്', 'പരുത്തി'),
 ('തേങ്ങാ വികസന ബോർഡ്', 'തേങ്ങ'),
 ('എണ്ണക്കുരു & പയർ ബോർഡ്', 'എണ്ണക്കുരു & പയർ'),
 ('ദേശീയ ഉദ്യാന ബോർഡ്', 'പൂതോട്ടം'),
 ('കാഷ്യൂ എക്സ്പോർട്ട് പ്രമോഷൻ കൗൺസിൽ', 'Malabar nut'),
 ('മത്സ്യ ഉൽപ്പന്ന എക്സ്പോർട്ട് വികസന അതോറിറ്റി', 'മത്സ്യം'),
 ('കാർഷിക-പ്രോസസ്ഡ് ഫുഡ് എക്സ്പോർട്ട്', 'കാർഷിക-പ്രോസസ്ഡ്'),
 ('കരകുശല കയറ്റുമതി പ്രമോഷൻ കൗൺസിൽ', 'കരകുശല വസ്തുക്കൾ'),
 ('കയറ്റുമതി പരിശോധന കൗൺസിൽ', 'കയറ്റുമതി നിയന്ത്രണം'),
 ('എല്ലാ ഇന്ത്യ കരകുശല ബോർഡ്', 'കരകുശലം'),
 ('സ്പൈസസ് ബോർഡ്', 'മസാലകൾ'),
 ('റബ്ബർ ബോർഡ്', 'ലാറ്റക്സ്'),
 ('ടീ ബോർഡ്', 'ചായ ഉൽപ്പന്നം'),
 ('കോഫി ബോർഡ്', 'റോബസ്റ്റ'),
 ('കോയർ ബോർഡ്', 'കയർ നിർമ്മാണം'),
 ('ടോബാക്കോ ബോർഡ്', 'വിറ്റുപുകയില'),
 ('സെൻട്രൽ സിൽക് ബോർഡ്', 'രേഷ്മ'),
 ('ചവറുക ബോർഡ്', 'ചവറുപ്പിർ'),
 ('പരുത്തി ഉപദേശക ബോർഡ്', 'പരുത്തി നൂൽ'),
 ('തേങ്ങാ വികസന ബോർഡ്', 'തേങ്ങാപ്പം'),
 ('എണ്ണക്കുരു & പയർ ബോർഡ്', 'എണ്ണക്കുരു'),
 ('ദേശീയ ഉദ്യാന ബോർഡ്', 'പൂക്കൾ'),
 ('കാഷ്യൂ എക്സ്പോർട്ട് പ്രമോഷൻ കൗൺസിൽ', 'Malabar nut')]
REFINERIES: list[tuple[str, str]] = [('Jamnagar Refinery', 'Reliance'),
 ('Jamnagar Refinery', 'ഏറ്റവും വലിയ'),
 ('Panipat Refinery', 'IOCL'),
 ('Panipat Refinery', 'Haryana'),
 ('Kochi Refinery', 'BPCL'),
 ('Kochi Refinery', 'Kerala'),
 ('Vadinar Refinery', 'Nayara Energy'),
 ('Vadinar Refinery', 'Gujarat'),
 ('Digboi Refinery', 'First refinery'),
 ('Digboi Refinery', 'Assam'),
 ('Numaligarh Refinery', 'NRL'),
 ('Numaligarh Refinery', 'Assam'),
 ('Paradip Refinery', 'IOCL'),
 ('Paradip Refinery', 'Odisha'),
 ('Barauni Refinery', 'IOCL'),
 ('Barauni Refinery', 'Bihar'),
 ('Haldia Refinery', 'IOC'),
 ('Haldia Refinery', 'West Bengal'),
 ('Mangalore Refinery', 'MRPL'),
 ('Mangalore Refinery', 'Karnataka'),
 ('Visakh Refinery', 'HPCL'),
 ('Visakh Refinery', 'Andhra Pradesh'),
 ('Mathura Refinery', 'IOCL'),
 ('Mathura Refinery', 'Uttar Pradesh'),
 ('Bina Refinery', 'BPCL'),
 ('Bina Refinery', 'Madhya Pradesh'),
 ('Tatipaka Refinery', 'ONGC'),
 ('Tatipaka Refinery', 'Andhra Pradesh'),
 ('Manali Refinery', 'CPCL'),
 ('Manali Refinery', 'Tamil Nadu')]
MAJOR_PORTS: list[tuple[str, str]] = [('ജെ.എൻ.പി.ടി.', 'ഏറ്റവും വലിയ കണ്ടെയ്\u200cനർ തുറമുഖം'),
 ('ജെ.എൻ.പി.ടി.', 'മഹാരാഷ്ട്ര'),
 ('മുണ്ട്ര തുറമുഖം', 'ഏറ്റവും വലിയ സ്വകാര്യ തുറമുഖം'),
 ('മുണ്ട്ര തുറമുഖം', 'ഗുജറാത്ത്'),
 ('ചെന്നൈ തുറമുഖം', 'തമിഴ്നാട്'),
 ('കൊച്ചി തുറമുഖം', 'കേരളം'),
 ('വിശാഖ തുറമുഖം', 'ആന്ധ്രപ്രദേശ്'),
 ('കൊൽക്കത്ത തുറമുഖം', 'പശ്ചിമബംഗാൾ'),
 ('പാരദീപ് തുറമുഖം', 'ഒഡിഷ'),
 ('കാന്ദ്ല തുറമുഖം', 'ഗുജറാത്ത്'),
 ('മുംബൈ തുറമുഖം', 'മഹാരാഷ്ട്ര'),
 ('എന്നോർ തുറമുഖം', 'തമിഴ്നാട്'),
 ('തൂത്തുക്കുദി തുറമുഖം', 'തമിഴ്നാട്'),
 ('മോർമുഗാവോ തുറമുഖം', 'ഗോവ'),
 ('ന്യൂ മംഗലൂർ തുറമുഖം', 'കർണാടക'),
 ('ഹാൽദിയ തുറമുഖം', 'പശ്ചിമബംഗാൾ'),
 ('ദീൻദയാൽ തുറമുഖം', 'കാന്ദ്ല'),
 ('വി.ഒ. ചിദമ്പരനാർ', 'തൂത്തുക്കുദി'),
 ('കൊച്ചി പോർട്ട് ട്രസ്റ്റ്', 'കേരളം'),
 ('ചെന്നൈ പോർട്ട് ട്രസ്റ്റ്', 'തമിഴ്നാട്'),
 ('ജawaharlal Nehru Port', 'മഹാരാഷ്ട്ര'),
 ('മundra Port', 'ഗുജറാത്ത്'),
 ('വിശാഖപട്ടണം പോർട്ട്', 'കിഴക്കൻ തീരം'),
 ('കolkata Port', 'ഹൂഗ്ലി'),
 ('പaradip Port', 'ഒഡിഷ'),
 ('കandla Port', 'ഗുജറാത്ത്'),
 ('മumbai Port', 'മഹാരാഷ്ട്ര'),
 ('എnnore Port', 'തമിഴ്നാട്'),
 ('തuticorin Port', 'തമിഴ്നാട്'),
 ('മormugao Port', 'ഗോവ')]
CLUSTER_NICKNAME: list[tuple[str, str]] = [('ബെംഗളൂരു', 'ഇന്ത്യയുടെ സിലിക്കൺ വാലി'),
 ('ചെന്നൈ', 'ഇന്ത്യയുടെ ഡിട്രോയിറ്റ്'),
 ('മുംബൈ', 'വാണിജ്യ തലസ്ഥാനം'),
 ('സൂറത്ത്', 'വജ്ര നഗരം'),
 ('ജയ്പൂർ', 'പിങ്ക് സിറ്റി'),
 ('ഹൈദരാബാദ്', 'ബൾക്ക് ഡ്രഗ് തൽസ്ഥാനം'),
 ('കാൻപൂർ', 'ലെതർ സിറ്റി'),
 ('തിരുപ്പൂർ', 'നിറ്റ്വെയർ നഗരം'),
 ('മോറാദാബാദ്', 'പിത്തള നഗരം'),
 ('ഫരീദാബാദ്', 'ഓട്ടോമൊബൈൽ ഹബ്'),
 ('പുണെ', 'ഓട്ടോമൊബൈൽ & IT'),
 ('അഹമദാബാദ്', 'ടെക്സ്റ്റൈൽ & ഡയമണ്ട്'),
 ('ലുധിയാന', 'മെഷീൻ ടൂൾസ്'),
 ('കൊച്ചി', 'സുഗന്ധവ്യഞ്ജന ഹബ്'),
 ('കൊൽക്കത്ത', 'കിഴക്കൻ ഇന്ത്യ ഹബ്'),
 ('നോയിഡ', 'ഇലക്ട്രോണിക്സ് ഹബ്'),
 ('ഗurgaon', 'IT & BPO'),
 ('വിശാഖപട്ടണം', 'ഉരുക്ക് & തുറമുഖ നഗരം'),
 ('രourkela', 'ഉരുക്ക് നഗരം'),
 ('ഭilai', 'ഉരുക്ക് പ്ലാന്റ് നഗരം'),
 ('ജamshedpur', 'ഉരുക്ക് നഗരം'),
 ('കanpur', 'ലെതർ ക്ലസ്റ്റർ'),
 ('ബെംഗളൂരു', 'IT തലസ്ഥാനം'),
 ('ചennai', 'ഓട്ടോ ഹബ്'),
 ('സurat', 'വജ്രം മുറിക്കൽ'),
 ('ഹyderabad', 'ഫാർമ തലസ്ഥാനം'),
 ('തiruppur', 'നിറ്റ്വെയർ കയറ്റുമതി'),
 ('മoradabad', 'പിത്തള കരകുശലം'),
 ('പune', 'ഓട്ടോമൊബൈൽ നിർമ്മാണം'),
 ('അhmedabad', 'ടെക്സ്റ്റൈൽ ഹബ്')]
CLUSTER_SPECIALTY: list[tuple[str, str]] = [('തിരുപ്പൂർ', 'നിറ്റ്വെയർ'),
 ('സൂറത്ത്', 'വജ്രം'),
 ('മോറാദാബാദ്', 'പിത്തള'),
 ('കാൻപൂർ', 'തുകൽ'),
 ('വാരanasi', 'പട്ട്'),
 ('ഭopal', 'ഭാരമുള്ള ഇലക്ട്രിക്കൽസ്'),
 ('രourkela', 'ഉരുക്ക്'),
 ('ഭilai', 'ഉരുക്ക്'),
 ('ജamshedpur', 'ഉരുക്ക്'),
 ('ഹൈദരാബാദ്', 'ബൾക്ക് ഡ്രഗ്'),
 ('ബaddi', 'ഫാർമ'),
 ('അhmedabad', 'ടെക്സ്റ്റൈൽ'),
 ('ലudhiana', 'സൈക്കിളുകൾ'),
 ('അgra', 'പാദരക്ഷ'),
 ('ഫirozabad', 'ഗ്ലാസ് ബാങ്ങിളുകൾ'),
 ('കolhapur', 'കോലhapuri ചappal'),
 ('പanipat', 'ടെക്സ്റ്റൈൽ'),
 ('ഇndore', 'ഓട്ടോമൊബൈൽ'),
 ('ചandigarh', 'ലൈറ്റ് എഞ്ചിനീയറിംഗ്'),
 ('കochi', 'കപ്പൽ നിർമ്മാണം'),
 ('വisakhapatnam', 'ഉരുക്ക് & കപ്പൽ'),
 ('നagpur', 'ഓറഞ്ച് & ടെക്സ്റ്റൈൽ'),
 ('കanpur', 'ലെതർ ഉൽപ്പന്നങ്ങൾ'),
 ('മoradabad', 'പിത്തള കരകുശലം'),
 ('തiruppur', 'നിറ്റ്വെയർ കയറ്റുമതി'),
 ('സurat', 'സിന്തetic ടെക്സ്റ്റൈൽ'),
 ('ജodhpur', 'കരകുശലം'),
 ('കashmir', 'പരിപ്പുകൾ'),
 ('അhmedabad', 'ഡെനിം'),
 ('പune', 'ഓട്ടോമൊബൈൽ'),
 ('ചennai', 'ഓട്ടോമൊബൈൽ അസംബ്ലി')]
HANDICRAFTS: list[tuple[str, str]] = [('മോറാദാബാദ്', 'പിത്തള'),
 ('വാരanasi', 'പട്ട്'),
 ('ജodhpur', 'തുകൽ'),
 ('കashmir', 'പരിപ്പുകൾ'),
 ('അgra', 'മാർബിൾ ഇൻലേ'),
 ('ഫirozabad', 'ഗ്ലാസ്'),
 ('സaharanpur', 'മരം കൊത്ത്'),
 ('കutch', 'എംബroidery'),
 ('പuri', 'അപ്ലിക്ക്'),
 ('ഭubaneswar', 'പattachitra'),
 ('കonark', 'കല്ല് കൊത്ത്'),
 ('മadhubani', 'ചിത്രങ്ങൾ'),
 ('ബardhaman', 'Dokra'),
 ('മanipur', 'Kauna craft'),
 ('നagaland', 'Naga shawls'),
 ('മizoram', 'Bamboo'),
 ('അssam', 'പട്ട്'),
 ('കerala', 'കയർ ഉൽപ്പന്നങ്ങൾ'),
 ('തamil Nadu', 'വെങ്കല പ്രതിമകൾ'),
 ('രajasthan', 'Blue pottery'),
 ('Gujarat', 'Bandhani'),
 ('Punjab', 'Phulkari'),
 ('West Bengal', 'Kantha'),
 ('Odisha', 'Silver filigree'),
 ('Uttar Pradesh', 'Chikan work'),
 ('Himachal', 'Woolen shawls'),
 ('Karnataka', 'Sandalwood'),
 ('Maharashtra', 'Warli art'),
 ('Bihar', 'Sujini embroidery'),
 ('Tripura', 'Cane & bamboo')]
TEXTILES: list[tuple[str, str]] = [('തിരുപ്പൂർ', 'നിറ്റ്വെയർ'),
 ('സൂറത്ത്', 'സynthetics'),
 ('കanpur', 'Cotton'),
 ('അhmedabad', 'Denim'),
 ('പanipat', 'Home textiles'),
 ('ഭagalpur', 'Silk'),
 ('ഇchalkaranji', 'Powerloom'),
 ('Coimbatore', 'Spinning'),
 ('Erode', 'Turmeric & textiles'),
 ('Tirupur', 'Knitwear exports'),
 ('Ludhiana', 'Woolen'),
 ('Bhiwandi', 'Powerloom'),
 ('Solapur', 'Chaddar'),
 ('Kolhapur', 'Cotton'),
 ('Malwa', 'Cotton belt'),
 ('Surat', 'Man-made fibre'),
 ('Varanasi', 'Banarasi silk'),
 ('Kanchipuram', 'Silk sarees'),
 ('Pochampally', 'Ikat'),
 ('Chanderi', 'Silk-cotton'),
 ('Maheshwar', 'Handloom'),
 ('Balarampur', 'Jute'),
 ('Kolkata', 'Jute mills'),
 ('Mumbai', 'Cotton mills legacy'),
 ('Ahmedabad', 'Textile mills'),
 ('Coimbatore', 'Yarn'),
 ('Madurai', 'Handloom'),
 ('Rajasthan', 'Block print'),
 ('Gujarat', 'Patola'),
 ('West Bengal', 'Muslin heritage')]
PHARMA: list[tuple[str, str]] = [('ഹൈദരാബാദ്', 'Bulk drugs'),
 ('ബaddi', 'Formulations'),
 ('അhmedabad', 'API'),
 ('വisakhapatnam', 'Pharma SEZ'),
 ('പune', 'Formulations'),
 ('മumbai', 'Pharma HQ'),
 ('Chennai', 'Vaccines'),
 ('Goa', 'Pharma units'),
 ('Indore', 'Pharma park'),
 ('Hyderabad', 'Vaccine hub'),
 ('Telangana', 'Pharma policy'),
 ('Gujarat', 'Pharma cluster'),
 ('Maharashtra', 'Pharma exports'),
 ('Karnataka', 'Biotech'),
 ('Tamil Nadu', 'Pharma'),
 ('Uttarakhand', 'Pharma hub'),
 ('Himachal', 'Tax incentives'),
 ('Sikkim', 'Pharma units'),
 ('Delhi NCR', 'Pharma marketing'),
 ('Ankleshwar', 'API'),
 ('Vapi', 'Bulk drugs'),
 ('Baddi', 'Contract manufacturing'),
 ('Hyderabad', 'Genome Valley'),
 ('Ahmedabad', 'Pharma formulations'),
 ('Visakh', 'Pharma city'),
 ('Mumbai', 'Pharma R&D'),
 ('Pune', 'Vaccine manufacturing'),
 ('Bangalore', 'Biotech'),
 ('Chennai', 'Pharma exports'),
 ('India', 'Pharmacy of the world')]
DEFENCE_PSUS: list[tuple[str, str]] = [('HAL', 'Aircraft'),
 ('BEL', 'Defence electronics'),
 ('BDL', 'Missiles'),
 ('BEML', 'Earth movers'),
 ('MDL', 'Submarines'),
 ('GRSE', 'Warships'),
 ('GSL', 'Patrol vessels'),
 ('HSL', 'Ship repair'),
 ('DDPD', 'Ordnance factories'),
 ('Mazagon Dock', 'Warships'),
 ('Cochin Shipyard', 'Aircraft carrier'),
 ('Bharat Forge', 'Artillery'),
 ('HAL', 'Tejas'),
 ('BEL', 'Radars'),
 ('BDL', 'Akash missile'),
 ('BEML', 'Tatra vehicles'),
 ('MDL', 'Scorpene subs'),
 ('GRSE', 'Frigates'),
 ('GSL', 'Offshore patrol'),
 ('HSL', 'Visakhapatnam'),
 ('HAL', 'Dhruv helicopter'),
 ('BEL', 'Sonar systems'),
 ('BDL', 'Pinaka'),
 ('BEML', 'Rail coaches'),
 ('MDL', 'Mumbai'),
 ('GRSE', 'Kolkata'),
 ('HAL', 'Bangalore HQ'),
 ('BEL', 'Bangalore'),
 ('BDL', 'Hyderabad')]
FIRST_MILLS: list[tuple[str, str]] = [('ആദ്യ കോട്ടൺ മിൽ', '1854'),
 ('ആദ്യ കോട്ടൺ മിൽ', 'മുംബൈ'),
 ('ആദ്യ ജൂട് മിൽ', '1855'),
 ('ആദ്യ ജൂട് മിൽ', 'റിശ്ര'),
 ('ടാറ്റാ സ്റ്റീൽ', '1907'),
 ('ടാറ്റാ സ്റ്റീൽ', 'ജാംഷേഡ്പൂർ'),
 ('ആദ്യ റിഫൈനറി', 'ഡിഗ്ബോയ്'),
 ('ആദ്യ റിഫൈനറി', '1901'),
 ('ആദ്യ IT പാർക്ക്', 'SEEPZ'),
 ('ആദ്യ IT പാർക്ക്', 'മുംബൈ'),
 ('ആദ്യ EPZ', 'കാന്ദ്ല'),
 ('ആദ്യ EPZ', '1965'),
 ('ആദ്യ സ്റ്റീൽ പ്ലാന്റ്', 'ടാറ്റാ'),
 ('ആദ്യ സ്റ്റീൽ പ്ലാന്റ്', '1907'),
 ('ആദ്യ ഓട്ടോമൊബൈൽ', 'ഹിന്ദുസ്ഥാൻ മോട്ടോഴ്സ്'),
 ('ആദ്യ ഓട്ടോമൊബൈൽ', '1942'),
 ('ആദ്യ ടെക്സ്റ്റൈൽ മിൽ', 'മumbai'),
 ('ആദ്യ സarkar steel', 'ഭilai'),
 ('ആദ്യ സarkar steel', '1959'),
 ('SAIL', '1954'),
 ('BHEL', '1964'),
 ('NTPC', '1975'),
 ('ONGC', '1956'),
 ('Indian Oil', '1959'),
 ('HMT', '1953'),
 ('BEL', '1954'),
 ('HAL', '1940'),
 ('Maruti', '1983'),
 ('TISCO', 'Jamshedpur'),
 ('First jute mill', 'Rishra'),
 ('First cotton mill', 'Mumbai')]
COOPERATIVE: list[tuple[str, str]] = [('ആമുൽ', 'പാലുൽപ്പന്നങ്ങൾ'),
 ('ആമുൽ', 'ആനന്ദ്'),
 ('IFFCO', 'വളം'),
 ('NAFED', 'കാർഷിക മാർക്കറ്റിംഗ്'),
 ('KRIBHCO', 'വളം'),
 ('NCUI', 'സഹകരണ സംഘടന'),
 ('NDDB', 'Dairy development'),
 ('GCMMF', 'Amul federation'),
 ('Kerala Co-op Bank', 'Banking'),
 ('Uralungal LAB', 'Construction co-op'),
 ('Indian Coffee House', 'Coffee co-op'),
 ('Lijjat Papad', 'Women co-op'),
 ('SEWA', 'Self-employed women'),
 ('Sahakar Bharati', 'Co-op movement'),
 ('Amul', 'White Revolution'),
 ('IFFCO', 'Kalol Gujarat'),
 ('NAFED', 'Oilseeds marketing'),
 ('KRIBHCO', 'Fertilizer co-op'),
 ('NDDB', 'Operation Flood'),
 ('GCMMF', 'Anand model'),
 ('Cooperative sugar', 'Maharashtra'),
 ('Milk co-ops', 'Gujarat'),
 ('Fishermen co-ops', 'Kerala'),
 ('Handloom co-ops', 'Tamil Nadu'),
 ('Urban co-op banks', 'Maharashtra'),
 ('Credit co-ops', 'Karnataka'),
 ('Amul', 'Dr Verghese Kurien'),
 ('IFFCO', 'Farmers co-op'),
 ('NAFED', 'Central nodal agency'),
 ('KRIBHCO', 'Krishak Bharati')]
ODOP: list[tuple[str, str]] = [('One District One Product', '2018'),
 ('ODOP', 'Commerce Ministry'),
 ('Varanasi', 'Banarasi silk'),
 ('Moradabad', 'Brassware'),
 ('Bhadohi', 'Carpets'),
 ('Kanpur', 'Leather'),
 ('Agra', 'Footwear'),
 ('Lucknow', 'Chikan'),
 ('Saharanpur', 'Wood craft'),
 ('Meerut', 'Sports goods'),
 ('Kerala', 'Coir'),
 ('Tamil Nadu', 'Brass'),
 ('Gujarat', 'Bandhani'),
 ('Rajasthan', 'Blue pottery'),
 ('Odisha', 'Pattachitra'),
 ('West Bengal', 'Kantha'),
 ('Assam', 'Muga silk'),
 ('Kashmir', 'Pashmina'),
 ('Punjab', 'Phulkari'),
 ('Himachal', 'Shawls'),
 ('Uttarakhand', 'Handicrafts'),
 ('ODOP', 'Export promotion'),
 ('ODOP', 'District branding'),
 ('ODOP', 'MSME linkage'),
 ('ODOP', 'GI products focus'),
 ('ODOP', 'State participation'),
 ('ODOP', 'E-commerce linkage'),
 ('ODOP', 'Skill development'),
 ('ODOP', 'Marketing support'),
 ('ODOP', 'District specific product'),
 ('ODOP', '2018 launch')]
RENEWABLE_ENERGY: list[tuple[str, str]] = [('SECI', 'Solar trading'),
 ('IREDA', 'Green finance'),
 ('NTPC Renewable', 'Solar/wind'),
 ('NHPC', 'Hydro power'),
 ('SJVN', 'Hydro'),
 ('Green Energy Corridor', 'Grid integration'),
 ('National Solar Mission', '2010'),
 ('National Wind Mission', 'Wind power'),
 ('PM-KUSUM', 'Solar pumps'),
 ('FAME', 'EV adoption'),
 ('PLI solar', 'PV modules'),
 ('Green Hydrogen Mission', '2023'),
 ('Offshore wind policy', 'Coastal wind'),
 ('RPO', 'Renewable purchase obligation'),
 ('CERC', 'Tariff regulation'),
 ('MNRE', 'Nodal ministry'),
 ('SECI', 'Central nodal agency'),
 ('IREDA', '1987 establishment'),
 ('Solar park scheme', 'Large solar'),
 ('Wind-solar hybrid', 'Hybrid parks'),
 ('Biomass power', 'Rural energy'),
 ('Small hydro', 'Below 25 MW'),
 ('Rooftop solar', 'Urban solar'),
 ('Koyna', 'Maharashtra hydro'),
 ('Tehri', 'Uttarakhand hydro'),
 ('Sardar Sarovar', 'Gujarat hydro'),
 ('NHPC', 'Faridabad HQ'),
 ('SJVN', 'Shimla HQ'),
 ('SECI', 'New Delhi'),
 ('IREDA', 'New Delhi')]
SHIPYARDS: list[tuple[str, str]] = [('Cochin Shipyard', 'Kochi'),
 ('Mazagon Dock', 'Mumbai'),
 ('GRSE', 'Kolkata'),
 ('Goa Shipyard', 'Vasco da Gama'),
 ('Hindustan Shipyard', 'Visakhapatnam'),
 ('Cochin Shipyard', 'Aircraft carrier'),
 ('Mazagon Dock', 'Destroyers'),
 ('GRSE', 'Frigates'),
 ('Goa Shipyard', 'Offshore patrol'),
 ('HSL', 'Ship repair'),
 ('Cochin Shipyard', 'PSU'),
 ('Mazagon Dock', 'Submarines'),
 ('GRSE', 'PSU Kolkata'),
 ('Goa Shipyard', 'PSU Goa'),
 ('Hindustan Shipyard', 'PSU Vizag'),
 ('Cochin Shipyard', '1981'),
 ('Mazagon Dock', '1934'),
 ('GRSE', '1934'),
 ('Goa Shipyard', '1957'),
 ('Hindustan Shipyard', '1952'),
 ('Cochin Shipyard', 'Largest PSU shipyard'),
 ('MDL', 'Mumbai submarines'),
 ('CSL', 'IAC Vikrant'),
 ('GRSE', 'Anti-submarine warfare'),
 ('GSL', 'Goa patrol vessels'),
 ('HSL', 'Visakh repair'),
 ('Shipbuilding financial aid', '2016'),
 ('Make in India ships', 'Defence'),
 ('Sagarmala', 'Port-led development'),
 ('Cochin Shipyard', 'Export ships')]
STEEL_PLANTS: list[tuple[str, str]] = [('Bhilai Steel Plant', 'SAIL'),
 ('Bokaro Steel Plant', 'SAIL'),
 ('Rourkela Steel Plant', 'SAIL'),
 ('Durgapur Steel Plant', 'SAIL'),
 ('Burnpur IISCO', 'SAIL'),
 ('Tata Steel Jamshedpur', 'Private'),
 ('Vizag Steel (RINL)', 'PSU'),
 ('JSW Steel', 'Private'),
 ('Essar Steel', 'Private'),
 ('Bhilai', 'Chhattisgarh'),
 ('Bokaro', 'Jharkhand'),
 ('Rourkela', 'Odisha'),
 ('Durgapur', 'West Bengal'),
 ('Jamshedpur', 'Jharkhand'),
 ('Visakhapatnam', 'Andhra Pradesh'),
 ('SAIL', '1954'),
 ('TISCO', '1907'),
 ('RINL', '1982'),
 ('Bhilai', 'USSR collaboration'),
 ('Bokaro', 'Soviet help'),
 ('Rourkela', 'German collaboration'),
 ('Durgapur', 'British collaboration'),
 ('Steel Authority', 'Maharatna'),
 ('National Steel Policy', '2017'),
 ('Domestic steel capacity', '150 MT target'),
 ('Pellet plants', 'Iron ore'),
 ('Coking coal import', 'Steel input'),
 ('Jamshedpur', 'First integrated plant'),
 ('Visakh', 'Coastal plant'),
 ('SAIL', 'New Delhi HQ')]
AUTOMOBILE: list[tuple[str, str]] = [('Maruti Suzuki', 'Gurgaon/Manesar'),
 ('Hyundai', 'Chennai'),
 ('Tata Motors', 'Pune/Jamshedpur'),
 ('Mahindra', 'Chennai/Pune'),
 ('Honda', 'Rajasthan'),
 ('Toyota', 'Karnataka'),
 ('Ford (legacy)', 'Chennai'),
 ('Renault-Nissan', 'Chennai'),
 ('Ashok Leyland', 'Chennai'),
 ('TVS', 'Hosur'),
 ('Bajaj Auto', 'Pune'),
 ('Hero', 'Gurgaon'),
 ('Royal Enfield', 'Chennai'),
 ('Force Motors', 'Pune'),
 ('Chennai', 'Detroit of India'),
 ('Pune', 'Auto hub'),
 ('Gurgaon', 'Maruti hub'),
 ('Sanand', 'Gujarat auto'),
 ('Hosur', 'Two-wheeler'),
 ('Pantnagar', 'Uttarakhand'),
 ('Automotive PLI', '2020'),
 ('FAME II', 'EV subsidy'),
 ('National Automotive Policy', 'Draft'),
 ('Auto components', 'Chennai cluster'),
 ('EV manufacturing', 'Tamil Nadu'),
 ('Battery PLI', '2021'),
 ('Maruti', '1983 JV'),
 ('Hyundai', '1996'),
 ('Tata Nano', 'Sanand'),
 ('Auto export hub', 'Chennai port'),
 ('Make in India auto', 'FDI')]
PETROCHEMICAL: list[tuple[str, str]] = [('Panipat', 'Haryana hub'),
 ('Dahej', 'Gujarat'),
 ('Hazira', 'Gujarat'),
 ('Haldia', 'West Bengal'),
 ('Vadodara', 'Gujarat'),
 ('Nagapattinam', 'Tamil Nadu'),
 ('Paradip', 'Odisha'),
 ('Mangalore', 'Karnataka'),
 ('Bongaigaon', 'Assam'),
 ('Auraiya', 'Uttar Pradesh'),
 ('GAIL', 'Gas pipeline'),
 ('ONGC petro', 'Dahej'),
 ('Reliance Jamnagar', 'Integrated refinery-petrochemical'),
 ('IOCL Panipat', 'Naphtha cracker'),
 ('BPCL Kochi', 'Propylene derivatives'),
 ('Haldia Petrochemicals', 'West Bengal'),
 ('Gujarat PCPIR', 'Dahej-Vadodara'),
 ('Visakh PCPIR', 'Andhra'),
 ('Paradip PCPIR', 'Odisha'),
 ('CMTC', 'Chemicals ministry'),
 ('Petrochemical industry', 'Import substitution'),
 ('Polymer production', 'Reliance leader'),
 ('Fertilizer from petrochemical', 'Ammonia'),
 ('LPG bottling', 'IOCL/HPCL'),
 ('Bitumen', 'Road construction'),
 ('Lubricants', 'IOCL'),
 ('Synthetic rubber', 'Petrochemical'),
 ('PTA/PET', 'Polyester chain'),
 ('Methanol', 'Chemical feedstock'),
 ('Panipat refinery', 'Northern hub')]
NODAL_AGENCY: list[tuple[str, str]] = [('Make in India', 'DPIIT'),
 ('PLI scheme', 'DPIIT'),
 ('NICDP', 'DPIIT'),
 ('Industrial corridors', 'NICDC'),
 ('SEZ policy', 'DPIIT'),
 ('Startup India', 'DPIIT'),
 ('MSME policy', 'Ministry of MSME'),
 ('Udyam registration', 'MSME Ministry'),
 ('National Manufacturing Policy', 'DPIIT'),
 ('FAME', 'Heavy Industries'),
 ('National Steel Policy', 'Steel Ministry'),
 ('Coal India', 'Coal Ministry'),
 ('ONGC', 'Petroleum Ministry'),
 ('NTPC', 'Power Ministry'),
 ('Renewable energy', 'MNRE'),
 ('Green Hydrogen Mission', 'MNRE'),
 ('ODOP', 'Commerce Ministry'),
 ('Export promotion', 'DGFT'),
 ('STPI', 'Electronics & IT'),
 ('Software exports', 'MEITY'),
 ('Pharma policy', 'Chemicals & Fertilizers'),
 ('Textile policy', 'Textile Ministry'),
 ('Defence production', 'Defence Ministry'),
 ('Shipbuilding policy', 'Shipping Ministry'),
 ('Automotive policy', 'Heavy Industries'),
 ('Food processing', 'Food Processing Ministry'),
 ('Khadi & Village', 'MSME Ministry'),
 ('Coir board', 'MSME Ministry'),
 ('National Industrial Corridor', 'DPIIT'),
 ('Invest India', 'DPIIT')]
ABBREVIATIONS: list[tuple[str, str]] = [('DPIIT', 'Department for Promotion of Industry and Internal Trade'),
 ('MSME', 'Micro Small and Medium Enterprises'),
 ('SEZ', 'Special Economic Zone'),
 ('PLI', 'Production Linked Incentive'),
 ('PSU', 'Public Sector Undertaking'),
 ('SAIL', 'Steel Authority of India Limited'),
 ('BHEL', 'Bharat Heavy Electricals Limited'),
 ('HAL', 'Hindustan Aeronautics Limited'),
 ('ONGC', 'Oil and Natural Gas Corporation'),
 ('NTPC', 'National Thermal Power Corporation'),
 ('IOCL', 'Indian Oil Corporation Limited'),
 ('GAIL', 'Gas Authority of India Limited'),
 ('NIMZ', 'National Investment and Manufacturing Zone'),
 ('NICDC', 'National Industrial Corridor Development Corporation'),
 ('NICDP', 'National Industrial Corridor Development Programme'),
 ('DMIC', 'Delhi Mumbai Industrial Corridor'),
 ('EPZ', 'Export Processing Zone'),
 ('STPI', 'Software Technology Parks of India'),
 ('KVIC', 'Khadi and Village Industries Commission'),
 ('SIDBI', 'Small Industries Development Bank of India'),
 ('NSIC', 'National Small Industries Corporation'),
 ('MUDRA', 'Micro Units Development and Refinance Agency'),
 ('ODOP', 'One District One Product'),
 ('SECI', 'Solar Energy Corporation of India'),
 ('IREDA', 'Indian Renewable Energy Development Agency'),
 ('MRPL', 'Mangalore Refinery and Petrochemicals Limited'),
 ('HPCL', 'Hindustan Petroleum Corporation Limited'),
 ('BPCL', 'Bharat Petroleum Corporation Limited'),
 ('NRL', 'Numaligarh Refinery Limited'),
 ('RINL', 'Rashtriya Ispat Nigam Limited')]
DIRECT_FACTS: list[tuple[str, str, list[str], str]] = [('മേക്ക് ഇൻ ഇന്ത്യ ലോഗോയിലെ മൃഗം?', 'സിംഹം', ['പുലി', 'ആന', 'മയിൽ'], 'easy'),
 ('ദില്ലി-മുംബൈ വ്യവസായി കോറിഡോറിന്റെ ഏകദേശ ദൈർഘ്യം?',
  '1500 കി.മീ.',
  ['500 കി.മീ.', '3000 കി.മീ.', '200 കി.മീ.'],
  'hard'),
 ('ചെന്നൈ-ബെംഗളൂരു വ്യവസായി കോറിഡോർ ഏതിന്റെ ഭാഗമാണ്?',
  'ഈസ്റ്റ് കോസ്റ്റ് ഇക്കണോമിക് കോറിഡോർ',
  ['DMIC മാത്രം', 'ഒന്നുമില്ല', 'ഹിമാലയൻ കോറിഡോർ'],
  'hard'),
 ('അമൃത്സർ-കൊൽക്കത്ത വ്യവസായി കോറിഡോർ ഏതിനൊപ്പം വിന്യസിച്ചിരിക്കുന്നു?',
  'ഈസ്റ്റേൺ ഡെഡിക്കേറ്റഡ് ഫ്രൈറ്റ് കോറിഡോർ',
  ['വെസ്റ്റേൺ DFC മാത്രം', 'കോസ്റ്റൽ റോഡ്', 'ഒന്നുമില്ല'],
  'hard'),
 ('വിശാഖപട്ടണം-ചെന്നൈ വ്യവസായി കോറിഡോർ പ്രധാനമായും ഏത് സംസ്ഥാനത്തിൽ?',
  'ആന്ധ്രപ്രദേശ്',
  ['പഞ്ചാബ്', 'രാജസ്ഥാൻ', 'കേരളം'],
  'hard'),
 ('ബെംഗളൂരു-മുംബൈ വ്യവസായി കോറിഡോർ ഏത് സംസ്ഥാനങ്ങൾ ഉൾക്കൊള്ളുന്നു?',
  'കർണാടകയും മഹാരാഷ്ട്രയും',
  ['കേരളം മാത്രം', 'അസം മാത്രം', 'പഞ്ചാബ് മാത്രം'],
  'hard'),
 ('ദേശീയ നിർമ്മാണ നയത്തിന്റെ ജിഡിപി ലക്ഷ്യം?', '25%', ['10%', '50%', '5%'], 'hard'),
 ("ഫാർമ മേഖല 'ലോകത്തിന്റെ ഫാർമസി' എന്ന് ഏത് രാജ്യത്തെ സൂചിപ്പിക്കുന്നു?",
  'ഇന്ത്യ',
  ['അമേരിക്ക', 'ജപ്പാൻ', 'ബ്രസീൽ'],
  'medium'),
 ('ബെംഗളൂരു ഐടി നാഗരികതയുടെ വിളിപ്പേര്?',
  'ഇന്ത്യയുടെ സിലിക്കൺ വാലി',
  ['ഇന്ത്യയുടെ ഡിട്രോയിറ്റ്', 'സ്റ്റീൽ നഗരം', 'പിങ്ക് നഗരം'],
  'easy'),
 ('ഇന്ത്യയുടെ ഡിട്രോയിറ്റ് എന്ന് സാധാരണയായി ഏതിനെ സൂചിപ്പിക്കുന്നു?',
  'ചെന്നൈ (ഓട്ടോമൊബൈൽ)',
  ['ജയ്പൂർ', 'ഷിമ്ല', 'പണാജി'],
  'medium'),
 ('ഇന്ത്യയിലെ ഏറ്റവും വലിയ റിഫൈനറി (ജാംനഗർ) ഉടമസ്ഥൻ?', 'റിലയൻസ്', ['ONGC മാത്രം', 'SAIL', 'HAL'], 'medium'),
 ('സ്റ്റീൽ അതോറിറ്റി ഓഫ് ഇന്ത്യ ആസ്ഥാനം?', 'ന്യൂ ഡൽഹി', ['മുംബൈ', 'കൊൽക്കത്ത', 'ചെന്നൈ'], 'hard'),
 ('ഹിന്ദുസ്ഥാൻ ഏരോനോട്ടിക്സ് ലിമിറ്റഡ് (HAL) ആസ്ഥാനം?', 'ബെംഗളൂരു', ['മുംബൈ', 'ഡൽഹി', 'കൊൽക്കത്ത'], 'medium'),
 ('ഭാരത് ഇലക്ട്രോണിക്സ് ലിമിറ്റഡ് (BEL) ആസ്ഥാനം?', 'ബെംഗളൂരു', ['മുംബൈ', 'ചെന്നൈ', 'കൊൽക്കത്ത'], 'hard'),
 ('നാഷണൽ അൽമിനിയം കമ്പനി (NALCO) ആസ്ഥാനം?', 'ഭുവനേശ്വർ', ['ഡൽഹി', 'മുംബൈ', 'ചെന്നൈ'], 'hard'),
 ('ഹിന്ദുസ്ഥാൻ പെട്രോളിയം ആസ്ഥാന നഗരം?', 'മുംബൈ', ['ഡൽഹി', 'ചെന്നൈ', 'കൊൽക്കത്ത'], 'hard'),
 ('മാരുതി സുസുക്കി നിർമ്മാണം പ്രധാനമായും എവിടെ?', 'ഹരിയാന/ഗുജറാത്ത്', ['കേരളം', 'അസം മാത്രം', 'ഗോവ മാത്രം'], 'medium'),
 ('ടാറ്റാ സ്റ്റീൽ പ്രധാന പ്ലാന്റ് എവിടെ?', 'ജാംഷേഡ്പൂർ', ['ജയ്പൂർ', 'ഷിമ്ല', 'പണാജി'], 'medium'),
 ('തിരുപ്പൂർ ഏതിന് പ്രസിദ്ധമാണ്?', 'നിറ്റ്വെയർ കയറ്റുമതി', ['കൽക്കരി', 'എണ്ണ ശുദ്ധീകരണം', 'അന്തരീക്ഷം'], 'hard'),
 ('ഇന്ത്യയിലെ വജ്രം മുറിക്കൽ കേന്ദ്രം?', 'സൂറത്ത്', ['ജയ്പൂർ മാത്രം', 'ഷിമ്ല', 'പണാജി'], 'hard'),
 ('തുകൽ വ്യവസായി കേന്ദ്രം?', 'കാൻപൂർ/ചെന്നൈ', ['ഷിമ്ല', 'ഗംഗ്ടോക്', 'പണാജി'], 'hard'),
 ('SEZ നയം ഇന്ത്യയിൽ പ്രഖ്യാപിച്ച വർഷം?', '2000', ['1990', '2010', '1985'], 'hard'),
 ('PLI പദ്ധതിയുടെ ആദ്യ മേഖള?', 'മൊബൈൽ നിർമ്മാണം', ['കൽക്കരി', 'മത്സ്യബന്ധനം', 'സിനിമ'], 'hard'),
 ('ദേശീയ വ്യവസായി കോറിഡോർ വികസന പരിപാടിയുടെ നോഡൽ?',
  'DPIIT',
  ['പ്രതിരോധ മന്ത്രാലയം', 'വിദേശകാര്യം', 'ആഭ്യന്തരം'],
  'hard'),
 ('ഖാദി & വില്ലേജ് ഇൻഡസ്ട്രി കമ്മീഷൻ (KVIC) എന്തിനാണ്?',
  'ഗ്രാമീണ വ്യവസായി',
  ['പ്രതിരോധം', 'അന്തരീക്ഷം', 'സിനിമ മാത്രം'],
  'medium'),
 ('കയർ വ്യവസായി പ്രധാന സംസ്ഥാനം?', 'കേരളം', ['പഞ്ചാബ്', 'രാജസ്ഥാൻ', 'ഹിമാചൽ'], 'easy'),
 ('സ്പൈസസ് ബോർഡ് ആസ്ഥാനം?', 'കൊച്ചി', ['ഡൽഹി', 'മുംബൈ', 'ചെന്നൈ'], 'hard'),
 ('റബ്ബർ ബോർഡ് ആസ്ഥാനം?', 'കോട്ടയം', ['ഡൽഹി', 'മുംബൈ', 'ചെന്നൈ'], 'hard'),
 ('ടീ ബോർഡ് ആസ്ഥാനം?', 'കൊൽക്കത്ത', ['കൊച്ചി', 'ഡൽഹി', 'ചെന്നൈ'], 'hard'),
 ('കോഫി ബോർഡ് ആസ്ഥാനം?', 'ബെംഗളൂരു', ['കൊച്ചി', 'ഡൽഹി', 'മുംബൈ'], 'hard'),
 ('കരകുശല വസ്തുക്കളുടെ പ്രധാന കയറ്റുമതി വസ്തു?',
  'കൈത്തെയ്യുന്ന പരിപ്പുകൾ/വസ്ത്രങ്ങൾ',
  ['കൽക്കരി', 'എണ്ണ മാത്രം', 'ഇരുമ്പ് അയിര് മാത്രം'],
  'hard'),
 ('കപ്പൽ നിർമ്മാണ പ്രധാന പി.എസ്.യു.?', 'കൊച്ചി ഷിപ്പ്യാർഡ്', ['SAIL', 'Coal India', 'NTPC'], 'hard'),
 ('ഭാരത് ഹെവി ഇലക്ട്രിക്കൽസിന്റെ പ്രധാന ഉൽപ്പന്നം?',
  'വിദ്യുത് നിലയ ഉപകരണങ്ങൾ',
  ['വിമാനവാഹിനികൾ മാത്രം', 'മൊബൈൽ ഫോണുകൾ മാത്രം', 'കാറുകൾ മാത്രം'],
  'medium'),
 ('ഇന്ത്യയിലെ ആദ്യ എക്സ്പോർട്ട് പ്രോസസ്സിംഗ് സോൺ?', 'കാന്ദ്ല', ['കൊച്ചി', 'ഡൽഹി', 'ചെന്നൈ'], 'hard'),
 ('ഹൈദരാബാദ് ഫാർമ ക്ലസ്റ്ററിന്റെ വിളിപ്പേര്?',
  'ബൾക്ക് ഡ്രഗ് തൽസ്ഥാനം',
  ['സ്റ്റീൽ നഗരം', 'പിങ്ക് നഗരം', 'നീല നഗരം'],
  'hard'),
 ('SIDBI എന്തിനാണ്?', 'എം.എസ്.എം.ഇ ധനസഹായി', ['പ്രതിരോധം മാത്രം', 'അന്തരീക്ഷം മാത്രം', 'സിനിമ മാത്രം'], 'medium'),
 ('മേക്ക് ഇൻ ഇന്ത്യ ആരംഭിച്ച വർഷം?', '2014', ['2013', '2015', '2016'], 'easy'),
 ('ഇന്ത്യയിലെ ആദ്യ കോട്ടൺ മിൽ സ്ഥാപിതമായ സ്ഥലം?', 'മുംബൈ', ['കൊൽക്കത്ത', 'ചെന്നൈ', 'അഹമദാബാദ്'], 'hard'),
 ('ഇന്ത്യയിലെ ആദ്യ ജൂട് മിൽ സ്ഥാപിതമായ സ്ഥലം?', 'റിശ്ര', ['മുംബൈ', 'കാൻപൂർ', 'അഹമദാബാദ്'], 'hard'),
 ('ടാറ്റാ സ്റ്റീൽ (TISCO) സ്ഥാപിതമായ വർഷം?', '1907', ['1854', '1947', '1956'], 'hard'),
 ('ആമുൽ സഹകരണ സംഘടനയുടെ സ്ഥലം?', 'ആനന്ദ്', ['അഹമദാബാദ്', 'മുംബൈ', 'പുണെ'], 'medium'),
 ('ODOP പദ്ധതി ആരംഭിച്ച വർഷം?', '2018', ['2014', '2020', '2016'], 'hard'),
 ('ODOP പദ്ധതിയുടെ നോഡൽ മന്ത്രാലയം?', 'വാണിജ്യ & വ്യവസായി മന്ത്രാലയം', ['കൃഷി', 'പ്രതിരോധം', 'ആരോഗ്യം'], 'hard'),
 ('SECI എന്തിനാണ്?', 'സോളാർ ഊർജ വ്യാപാരം', ['കൽക്കരി ഖനനം', 'ഉരുക്ക്', 'ടെക്സ്റ്റൈൽ'], 'hard'),
 ('IREDA എന്തിനാണ്?', 'പുതുനവീകരണ ഊർജ ധനസഹായി', ['കൽക്കരി', 'എണ്ണ', 'ഫാർമ'], 'hard'),
 ('മോറാദാബാദ് ഏതിന് പ്രസിദ്ധമാണ്?', 'പിത്തള കരകുശല വസ്തുക്കൾ', ['വജ്രം', 'നിറ്റ്വെയർ', 'ഫാർമ'], 'hard'),
 ('സൂറത്ത് ഏതിന് പ്രസിദ്ധമാണ്?', 'വജ്രം മുറിക്കൽ', ['ഉരുക്ക്', 'കപ്പൽ', 'ഫാർമ'], 'hard'),
 ('പണിപ്പൂർ ഏതിന് പ്രസിദ്ധമാണ്?', 'പെട്രോകെമിക്കൽ', ['കയർ', 'ടീ', 'കാപ്പി'], 'hard'),
 ('ജെ.എൻ.പി.ടി. (നവാ ഷേവ) ഏത് സംസ്ഥാനത്തിൽ?', 'മഹാരാഷ്ട്ര', ['ഗുജറാത്ത്', 'കേരളം', 'തമിഴ്നാട്'], 'medium'),
 ('മുണ്ട്ര തുറമുഖം ഏത് സംസ്ഥാനത്തിൽ?', 'ഗുജറാത്ത്', ['മഹാരാഷ്ട്ര', 'കേരളം', 'ആന്ധ്രപ്രദേശ്'], 'medium'),
 ('STPI സ്ഥാപിതമായ വർഷം?', '1991', ['1980', '2005', '2015'], 'hard'),
 ('NIMZ നയ വർഷം?', '2011', ['2000', '2015', '1990'], 'hard'),
 ('ഇന്ത്യൻ ഓയിൽ റിഫൈനറികളുടെ എണ്ണം (ഏകദേശം)?', '10+', ['2', '50', '100'], 'hard'),
 ('പൂണെ/ചെന്നൈ ഓട്ടോമൊബൈൽ ക്ലസ്റ്റർ ബന്ധപ്പെട്ട വ്യവസായി?',
  'ഓട്ടോമൊബൈൽ നിർമ്മാണം',
  ['കയർ', 'ടീ മാത്രം', 'സുഗന്ധവ്യഞ്ജനങ്ങൾ മാത്രം'],
  'easy'),
 ('ഇന്ത്യയിലെ ആദ്യ EPZ/SEZ?', 'കാന്ദ്ല', ['കൊച്ചി', 'ചെന്നൈ', 'നോയിഡ'], 'hard'),
 ('ഇന്ത്യയിലെ ഏറ്റവും വലിയ സിംഗിൾ-സൈറ്റ് റിഫൈനറി?', 'ജാംനഗർ (റിലയൻസ്)', ['പണിപ്പൂർ', 'കൊച്ചി', 'വഡിനാർ'], 'medium'),
 ('ചിറ്റaranjan ലോക്കോമോട്ടീവ് വർക്ക്സ് എന്ത് നിർമ്മിക്കുന്നു?',
  'ലോക്കോമോട്ടീവുകൾ',
  ['വിമാനങ്ങൾ', 'കപ്പലുകൾ മാത്രം', 'മൊബൈൽ ഫോണുകൾ'],
  'hard'),
 ('ഇന്ത്യയുടെ ആദ്യ സ്റ്റീൽ പ്ലാന്റ്?', 'ജാംഷേഡ്പൂർ (ടാറ്റാ)', ['ഭിലായി', 'രൗർക്കെൽ', 'ദുർഗാപൂർ'], 'hard'),
 ('അമുൽ സംബന്ധിച്ച വിപ്ലവം?', 'വെള്ള വിപ്ലവം', ['പച്ച വിപ്ലവം', 'നീല വിപ്ലവം', 'സ്വർണ്ണ വിപ്ലവം'], 'medium'),
 ('ഇന്ത്യയിലെ ആദ്യ കോട്ടൺ മിൽ സ്ഥാപിത വർഷം?', '1854', ['1907', '1947', '1956'], 'hard'),
 ('ഇന്ത്യയിലെ ആദ്യ ജൂട് മിൽ സ്ഥാപിത വർഷം?', '1855', ['1854', '1907', '1947'], 'hard'),
 ('ഇന്ത്യയിലെ ആദ്യ റിഫൈനറി?', 'ഡിഗ്ബോയ് (അസാം)', ['ജാംനഗർ', 'പണിപ്പൂർ', 'കൊച്ചി'], 'hard'),
 ('ഇന്ത്യയിലെ ആദ്യ ഓട്ടോമൊബൈൽ ഫാക്ടറി?', 'ഹിന്ദുസ്ഥാൻ മോട്ടോഴ്സ് (പോംപെ)', ['മാരുതി', 'ടാറ്റാ', 'മഹീന്ദ്ര'], 'hard'),
 ('ഇന്ത്യയിലെ ആദ്യ സ്റ്റീൽ പ്ലാന്റ് സ്ഥാപകൻ?', 'ജംശേദ്ജി ടാറ്റാ', ['ജവാഹർലാൽ നെഹ്റു', 'ദാമോദർ', 'ബിർള'], 'hard'),
 ('ഇന്ത്യയുടെ ആദ്യ IT പാർക്ക്?', 'SEEPZ (മുംബൈ)', ['ഇലക്ട്രോണിക് സിറ്റി', 'HITEC സിറ്റി', 'ഐ.ടി.പി.എൽ'], 'hard')]


def generate_wave30_candidates(existing: set[str], rng: random.Random) -> list[Candidate]:
    out: list[Candidate] = []
    # വ്യവസായ നയം
    emit_category(out, existing, rng, INDUSTRIAL_POLICY,
        ["'{a}'-ന്റെ പ്രധാന ലക്ഷ്യം/സവിശേഷത ഏത്?", "'{a}' സംബന്ധിച്ച പ്രധാന വസ്തുത?"],
        ["'{b}' ലക്ഷ്യമിട്ട വ്യവസായ നയം/പരിപാടി ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട വ്യവസായ നയം ഏത്?"],
        [a for a, _ in INDUSTRIAL_POLICY], [b for _, b in INDUSTRIAL_POLICY])

    # മേക്ക് ഇൻ ഇന്ത്യ
    emit_category(out, existing, rng, MAKE_IN_INDIA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' സംബന്ധിച്ച വസ്തുത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട മേക്ക് ഇൻ ഇന്ത്യ വസ്തുത?", "'{b}' സംബന്ധിച്ച മേക്ക് ഇൻ ഇന്ത്യ വിവരം ഏത്?"],
        [a for a, _ in MAKE_IN_INDIA], [b for _, b in MAKE_IN_INDIA])

    # PLI പദ്ധതി
    emit_category(out, existing, rng, PLI_SCHEME,
        ["'{a}' PLI പദ്ധതിയുടെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ PLI സംബന്ധ വസ്തുത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട PLI മേഖല/പദ്ധതി ഏത്?", "'{b}' PLI സംബന്ധിച്ച വസ്തുത ഏത്?"],
        [a for a, _ in PLI_SCHEME], [b for _, b in PLI_SCHEME])

    # എം.എസ്.എം.ഇ
    emit_category(out, existing, rng, MSME_CATEGORY,
        ["'{a}' എം.എസ്.എം.ഇ വിഭാഗത്തിന്റെ പ്രധാന പരിധി ഏത്?", "'{a}'-ന്റെ നിക്ഷേപ/വിഭാഗ വിവരം?"],
        ["'{b}' പരിധിയുള്ള എം.എസ്.എം.ഇ വിഭാഗം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട എം.എസ്.എം.ഇ വിഭാഗം?"],
        [a for a, _ in MSME_CATEGORY], [b for _, b in MSME_CATEGORY])

    # എം.എസ്.എം.ഇ സ്ഥാപനങ്ങൾ
    emit_category(out, existing, rng, MSME_INSTITUTION,
        ["'{a}'-ന്റെ പ്രധാന പ്രവർത്തനം ഏത്?", "'{a}' എന്തിനാണ്?"],
        ["'{b}' ലക്ഷ്യം നേടുന്ന എം.എസ്.എം.ഇ സ്ഥാപനം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട സ്ഥാപനം ഏത്?"],
        [a for a, _ in MSME_INSTITUTION], [b for _, b in MSME_INSTITUTION])

    # SEZ
    emit_category(out, existing, rng, SEZ_POLICY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' SEZ സംബന്ധ വസ്തുത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട SEZ/EPZ വസ്തുത ഏത്?", "'{b}' SEZ സംബന്ധിച്ച വിവരം ഏത്?"],
        [a for a, _ in SEZ_POLICY], [b for _, b in SEZ_POLICY])

    # പൊതുമേഖലാ സ്ഥാപന മേഖല
    emit_category(out, existing, rng, PSU_SECTOR,
        ["'{a}' പി.എസ്.യു.യുടെ പ്രധാന മേഖല ഏത്?", "'{a}' ഏത് മേഖലയിൽ പ്രവർത്തിക്കുന്നു?"],
        ["'{b}' മേഖലയിലെ പ്രധാന പി.എസ്.യു. ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട പി.എസ്.യു. ഏത്?"],
        [a for a, _ in PSU_SECTOR], [b for _, b in PSU_SECTOR], english=True)

    # പി.എസ്.യു. ആസ്ഥാനം
    emit_category(out, existing, rng, PSU_HQ,
        ["'{a}'-ന്റെ ആസ്ഥാന നഗരം ഏത്?", "'{a}' എവിടെ സ്ഥിതി ചെയ്യുന്നു?"],
        ["'{b}' ഏത് പി.എസ്.യു./സ്ഥാപനത്തിന്റെ ആസ്ഥാനമാണ്?", "'{b}'-ലുള്ള പ്രധാന വ്യവസായ സ്ഥാപനം ഏത്?"],
        [a for a, _ in PSU_HQ], [b for _, b in PSU_HQ], english=True)

    # വ്യവസായ കോറിഡോറുകൾ
    emit_category(out, existing, rng, CORRIDORS,
        ["'{a}' വ്യവസായ കോറിഡറിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ ദൈർഘ്യം/സംസ്ഥാനം/ബന്ധം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട വ്യവസായ കോറിഡോർ ഏത്?", "'{b}' വിവരമുള്ള വ്യവസായ കോറിഡോർ ഏത്?"],
        [a for a, _ in CORRIDORS], [b for _, b in CORRIDORS])

    # കമോഡിറ്റി ബോർഡ് ആസ്ഥാനം
    emit_category(out, existing, rng, COMMODITY_BOARD_HQ,
        ["'{a}'-ന്റെ ആസ്ഥാന നഗരം ഏത്?", "'{a}' എവിടെ സ്ഥിതി ചെയ്യുന്നു?"],
        ["'{b}' ഏത് കമോഡിറ്റി ബോർഡിന്റെ ആസ്ഥാനമാണ്?", "'{b}'-ലുള്ള കമോഡിറ്റി ബോർഡ് ഏത്?"],
        [a for a, _ in COMMODITY_BOARD_HQ], [b for _, b in COMMODITY_BOARD_HQ])

    # കമോഡിറ്റി ബോർഡ് ഉൽപ്പന്നം
    emit_category(out, existing, rng, COMMODITY_PRODUCT,
        ["'{a}' ഏത് ഉൽപ്പന്ന/മേഖലാ ബോർഡാണ്?", "'{a}'-ന്റെ പ്രധാന ഉൽപ്പന്ന മേഖല?"],
        ["'{b}' മേഖല നിയന്ത്രിക്കുന്ന ബോർഡ് ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട കമോഡിറ്റി ബോർഡ്?"],
        [a for a, _ in COMMODITY_PRODUCT], [b for _, b in COMMODITY_PRODUCT])

    # റിഫൈനറികൾ
    emit_category(out, existing, rng, REFINERIES,
        ["'{a}' റിഫൈനറിയുടെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ സ്ഥാനം/ഉടമസ്ഥൻ?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട റിഫൈനറി ഏത്?", "'{b}' വിവരമുള്ള റിഫൈനറി ഏത്?"],
        [a for a, _ in REFINERIES], [b for _, b in REFINERIES], english=True)

    # തുറമുഖങ്ങൾ
    emit_category(out, existing, rng, MAJOR_PORTS,
        ["'{a}' തുറമുഖത്തിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ പ്രാധാന്യം/സ്ഥാനം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട പ്രധാന തുറമുഖം ഏത്?", "'{b}' വിവരമുള്ള തുറമുഖം ഏത്?"],
        [a for a, _ in MAJOR_PORTS], [b for _, b in MAJOR_PORTS])

    # വ്യവസായ ക്ലസ്റ്റർ വിളിപ്പേര്
    emit_category(out, existing, rng, CLUSTER_NICKNAME,
        ["'{a}' നഗരത്തിന്റെ വ്യവസായ വിളിപ്പേര് ഏത്?", "'{a}' ഏത് മേഖലയുടെ കേന്ദ്രമാണ്?"],
        ["'{b}' വിളിപ്പേരുള്ള നഗരം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട നഗരം ഏത്?"],
        [a for a, _ in CLUSTER_NICKNAME], [b for _, b in CLUSTER_NICKNAME])

    # വ്യവസായ ക്ലസ്റ്റർ പ്രത്യേകത
    emit_category(out, existing, rng, CLUSTER_SPECIALTY,
        ["'{a}' ക്ലസ്റ്ററിന്റെ പ്രധാന ഉൽപ്പന്നം/മേഖല ഏത്?", "'{a}'-ന്റെ പ്രത്യേകത?"],
        ["'{b}' ഉൽപ്പന്നത്തിന്റെ പ്രധാന ക്ലസ്റ്റർ നഗരം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട ക്ലസ്റ്റർ?"],
        [a for a, _ in CLUSTER_SPECIALTY], [b for _, b in CLUSTER_SPECIALTY])

    # കരകുശല വ്യവസായം
    emit_category(out, existing, rng, HANDICRAFTS,
        ["'{a}' കരകുശല കേന്ദ്രത്തിന്റെ പ്രധാന ഉൽപ്പന്നം ഏത്?", "'{a}'-ന്റെ പ്രത്യേകത?"],
        ["'{b}' ഉൽപ്പന്നത്തിന്റെ പ്രധാന കരകുശല കേന്ദ്രം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട കരകുശല നഗരം?"],
        [a for a, _ in HANDICRAFTS], [b for _, b in HANDICRAFTS])

    # വസ്ത്ര വ്യവസായം
    emit_category(out, existing, rng, TEXTILES,
        ["'{a}' വസ്ത്ര കേന്ദ്രത്തിന്റെ പ്രധാന ഉൽപ്പന്നം ഏത്?", "'{a}'-ന്റെ വസ്ത്ര പ്രത്യേകത?"],
        ["'{b}' വസ്ത്ര ഉൽപ്പന്നത്തിന്റെ പ്രധാന കേന്ദ്രം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട വസ്ത്ര നഗരം?"],
        [a for a, _ in TEXTILES], [b for _, b in TEXTILES])

    # ഫാർമ വ്യവസായം
    emit_category(out, existing, rng, PHARMA,
        ["'{a}' ഫാർമ കേന്ദ്രത്തിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ ഫാർമ പ്രത്യേകത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഫാർമ കേന്ദ്രം ഏത്?", "'{b}' ഫാർമ വിവരമുള്ള നഗരം ഏത്?"],
        [a for a, _ in PHARMA], [b for _, b in PHARMA])

    # പ്രതിരോധ പി.എസ്.യു.
    emit_category(out, existing, rng, DEFENCE_PSUS,
        ["'{a}' പ്രതിരോധ പി.എസ്.യു.യുടെ പ്രധാന ഉൽപ്പന്നം ഏത്?", "'{a}' ഏത് മേഖലയിൽ?"],
        ["'{b}' ഉൽപ്പന്നം നിർമ്മിക്കുന്ന പ്രതിരോധ പി.എസ്.യു. ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട പ്രതിരോധ സ്ഥാപനം?"],
        [a for a, _ in DEFENCE_PSUS], [b for _, b in DEFENCE_PSUS], english=True)

    # ഇന്ത്യയിലെ ആദ്യ ഫാക്ടറികൾ
    emit_category(out, existing, rng, FIRST_MILLS,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' സ്ഥാപന വർഷം/സ്ഥലം?"],
        ["'{b}' വർഷം/സ്ഥലത്ത് സ്ഥാപിതമായ ആദ്യ ഫാക്ടറി ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട ആദ്യ വ്യവസായ സ്ഥാപനം?"],
        [a for a, _ in FIRST_MILLS], [b for _, b in FIRST_MILLS])

    # സഹകരണ മേഖല
    emit_category(out, existing, rng, COOPERATIVE,
        ["'{a}' സഹകരണ സ്ഥാപനത്തിന്റെ പ്രധാന പ്രവർത്തനം ഏത്?", "'{a}' എന്തിനാണ്?"],
        ["'{b}' ലക്ഷ്യം നേടുന്ന സഹകരണ സ്ഥാപനം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട സഹകരണ സംഘടന?"],
        [a for a, _ in COOPERATIVE], [b for _, b in COOPERATIVE])

    # ODOP പദ്ധതി
    emit_category(out, existing, rng, ODOP,
        ["'{a}' ജില്ലയുടെ/സംസ്ഥാനത്തിന്റെ ODOP ഉൽപ്പന്നം ഏത്?", "'{a}'-ന്റെ ODOP വസ്തു?"],
        ["'{b}' ODOP ഉൽപ്പന്നമുള്ള ജില്ല/സംസ്ഥാനം ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട ODOP ജില്ല?"],
        [a for a, _ in ODOP], [b for _, b in ODOP])

    # പുതുനവീകരണ ഊർജ വ്യവസായം
    emit_category(out, existing, rng, RENEWABLE_ENERGY,
        ["'{a}'-ന്റെ പ്രധാന പ്രവർത്തനം ഏത്?", "'{a}' പുതുനവീകരണ ഊർജ സംബന്ധ വസ്തുത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട പുതുനവീകരണ ഊർജ സ്ഥാപനം ഏത്?", "'{b}' ലക്ഷ്യമുള്ള ഊർജ സ്ഥാപനം ഏത്?"],
        [a for a, _ in RENEWABLE_ENERGY], [b for _, b in RENEWABLE_ENERGY])

    # കപ്പൽ നിർമ്മാണം
    emit_category(out, existing, rng, SHIPYARDS,
        ["'{a}' കപ്പൽയാർഡിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ സ്ഥാനം/ഉൽപ്പന്നം?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട കപ്പൽയാർഡ് ഏത്?", "'{b}' വിവരമുള്ള കപ്പൽ നിർമ്മാണ കേന്ദ്രം?"],
        [a for a, _ in SHIPYARDS], [b for _, b in SHIPYARDS])

    # ഉരുക്ക് പ്ലാന്റുകൾ
    emit_category(out, existing, rng, STEEL_PLANTS,
        ["'{a}' ഉരുക്ക് പ്ലാന്റിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ സ്ഥാനം/ഉടമ?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഉരുക്ക് പ്ലാന്റ് ഏത്?", "'{b}' വിവരമുള്ള ഉരുക്ക് നിർമ്മാണ കേന്ദ്രം?"],
        [a for a, _ in STEEL_PLANTS], [b for _, b in STEEL_PLANTS])

    # ഓട്ടോമൊബൈൽ വ്യവസായം
    emit_category(out, existing, rng, AUTOMOBILE,
        ["'{a}' ഓട്ടോമൊബൈൽ കമ്പനിയുടെ പ്രധാന നിർമ്മാണ കേന്ദ്രം ഏത്?", "'{a}'-ന്റെ പ്രധാന പ്ലാന്റ്?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട ഓട്ടോമൊബൈൽ നിർമ്മാണ കേന്ദ്രം ഏത്?", "'{b}' നഗരത്തിലെ ഓട്ടോമൊബൈൽ കമ്പനി ഏത്?"],
        [a for a, _ in AUTOMOBILE], [b for _, b in AUTOMOBILE])

    # പെട്രോകെമിക്കൽ
    emit_category(out, existing, rng, PETROCHEMICAL,
        ["'{a}' പെട്രോകെമിക്കൽ കേന്ദ്രത്തിന്റെ പ്രധാന വിവരം ഏത്?", "'{a}'-ന്റെ സ്ഥാനം/പ്രത്യേകത?"],
        ["'{b}'-യുമായി ബന്ധപ്പെട്ട പെട്രോകെമിക്കൽ കേന്ദ്രം ഏത്?", "'{b}' വിവരമുള്ള പെട്രോകെമിക്കൽ ഹബ്?"],
        [a for a, _ in PETROCHEMICAL], [b for _, b in PETROCHEMICAL])

    # നോഡൽ ഏജൻസി
    emit_category(out, existing, rng, NODAL_AGENCY,
        ["'{a}' പരിപാടിയുടെ നോഡൽ ഏജൻസി/മന്ത്രാലയം ഏത്?", "'{a}' ഏത് വകുപ്പിന് കീഴിൽ?"],
        ["'{b}' നോഡൽ ഏജൻസിയുള്ള വ്യവസായ പരിപാടി ഏത്?", "'{b}'-യുമായി ബന്ധപ്പെട്ട വ്യവസായ പരിപാടി?"],
        [a for a, _ in NODAL_AGENCY], [b for _, b in NODAL_AGENCY], english=True)

    # സംക്ഷേപങ്ങൾ
    emit_category(out, existing, rng, ABBREVIATIONS,
        ["'{a}' എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം ഏത്?", "'{a}'-ന്റെ വിപുലീകരണം?"],
        ["'{b}' പൂർണ്ണരൂപമുള്ള വ്യവസായ സംക്ഷേപം ഏത്?", "'{b}' ഏത് സംക്ഷേപത്തിൽ?"],
        [a for a, _ in ABBREVIATIONS], [b for _, b in ABBREVIATIONS], english=True)

    emit_direct(out, existing, rng, DIRECT_FACTS)
    return out


if __name__ == "__main__":
    print(len(generate_wave30_candidates(set(), random.Random(0))))
