"""Malayalam translation data for Kerala PSC quiz malayalamization."""

ID_OVERRIDES = {'ca_2026_06_016': {'question': "2026 ജൂണിൽ കേരള സർക്കാർ പ്രഖ്യാപിച്ച 'ഹരിത കേരളം' പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം എന്ത്?", 'options': ['ചലച്ചിത്ര നിർമ്മാണം', 'സംരക്ഷണ പ്രവർത്തനം', 'നഗരങ്ങളിൽ വൃക്ഷത്തൈകൾ നട്ടുപിടിപ്പിക്കൽ', 'ആണവ ഗവേഷണം'], 'answer': 'നഗരങ്ങളിൽ വൃക്ഷത്തൈകൾ നട്ടുപിടിപ്പിക്കൽ'}, 'ca_2026_06_017': {'question': '2026 ജൂണിൽ ISRO-യുടെ വാണിജ്യ ശാഖ IN-SPACe-ന്റെ പ്രധാന ലക്ഷ്യം എന്ത്?', 'options': ['NASA-യുമായി ലയിപ്പിക്കൽ', 'സ്വകാര്യ ബഹിരാകാശ മേഖലയെ സഹായിക്കൽ', 'ചലച്ചിത്രോത്സവം', 'കരിമ്പ് കയറ്റുമതി'], 'answer': 'സ്വകാര്യ ബഹിരാകാശ മേഖലയെ സഹായിക്കൽ'}, 'ca_2026_06_018': {'question': '2026 ജൂണിൽ കേരള ബജറ്റ് സെഷൻ നടന്ന സ്ഥലം ഏത്?', 'options': ['കൊച്ചി', 'തിരുവനന്തപുരം നിയമസഭ', 'ന്യൂഡൽഹി', 'മുംബൈ'], 'answer': 'തിരുവനന്തപുരം നിയമസഭ'}, 'ca_2026_06_019': {'question': '2026 ജൂണിൽ GST Council യോഗത്തിന്റെ പ്രധാന ചർച്ചാവിഷയം എന്ത്?', 'options': ['ചലച്ചിത്ര പുരസ്കാരം', 'നിരക്ക് പരിഷ്ക്കരണവും അനുസരണവും', 'ആണവ പരീക്ഷണം', 'ബഹിരാകാശ ദൗത്യം'], 'answer': 'നിരക്ക് പരിഷ്ക്കരണവും അനുസരണവും'}, 'ca_2026_06_020': {'question': '2026 ജൂണിൽ കേരളത്തിലെ മഴക്കാലം ആരംഭം പ്രഖ്യാപിക്കുന്ന സ്ഥാപനം ഏത്?', 'options': ['ECI', 'IMD', 'ISRO', 'DRDO'], 'answer': 'IMD'}, 'ca_2026_06_021': {'question': '2026 ജൂൺ അവധിക്ക് ശേഷം കേരളത്തിലെ വിദ്യാലയങ്ങൾ വീണ്ടും തുറക്കുന്നത് സാധാരണയായി എപ്പോൾ?', 'options': ['ഡിസംബർ', 'ജൂൺ ആദ്യ ആഴ്ച', 'മാർച്ച് മാത്രം', 'ജനുവരി'], 'answer': 'ജൂൺ ആദ്യ ആഴ്ച'}, 'ca_2026_06_022': {'question': '2026 ജൂണിൽ FIFA Club World Cup-ന്റെ ആതിഥ്യ രാജ്യം ഏത്?', 'options': ['ഖത്തർ', 'ഇന്ത്യ', 'ബ്രാസീൽ', 'യുഎസ്എ'], 'answer': 'യുഎസ്എ'}, 'ca_2026_06_023': {'question': 'പാരീസ് കാലാവസ്ഥാ ഉടമ്പടിയുടെ ആഗോള വിലയിരുത്തൽ തുടരുന്ന UN സംഘടന ഏത്?', 'options': ['IMF', 'UNFCCC', 'WHO', 'WTO'], 'answer': 'UNFCCC'}, 'ca_2026_06_024': {'question': '2026 ജൂണിൽ കേരള റിസ്പോൺസിബിൾ ടൂറിസം മിഷന്റെ പ്രധാന ലക്ഷ്യം എന്ത്?', 'options': ['പരിസ്ഥിതി സൗഹൃദ ടൂറിസം', 'കൽക്കരി ഖനനം', 'ചലച്ചിത്രം മാത്രം', 'പ്രതിരോധം'], 'answer': 'പരിസ്ഥിതി സൗഹൃദ ടൂറിസം'}, 'ca_2026_06_025': {'question': '2026 ജൂണിൽ ഇന്ത്യയുടെ UPI അന്താരാഷ്ട്ര വിപുലീകരണ പങ്കാളി പ്രദേശം ഏത്?', 'options': ['അന്റാർട്ടിക്ക', 'മദ്ധ്യേഷ്യ/ഏഷ്യ', 'ചന്ദ്രൻ', 'ഒന്നുമില്ല'], 'answer': 'മദ്ധ്യേഷ്യ/ഏഷ്യ'}, 'ca_2026_06_026': {'question': 'KFON (Kerala Fibre Optic Network) പദ്ധതിയുടെ ലക്ഷ്യം എന്ത്?', 'options': ['പ്രതിരോധം മാത്രം', 'കൽക്കരി കയിക്കയം', 'ചലച്ചിത്രം മാത്രം', 'എല്ലാവർക്കും ഇന്റർനെറ്റ് കണക്റ്റിവിറ്റി'], 'answer': 'എല്ലാവർക്കും ഇന്റർനെറ്റ് കണക്റ്റിവിറ്റി'}, 'ca_2026_06_027': {'question': 'NEP നടപ്പാക്കൽ പരിശോധന നടത്തുന്നത് ആര്?', 'options': ['കേന്ദ്രവും സംസ്ഥാനങ്ങളും', 'കേരളം മാത്രം', 'സ്വകാര്യ സ്കൂളുകൾ മാത്രം', 'ഒന്നുമില്ല'], 'answer': 'കേന്ദ്രവും സംസ്ഥാനങ്ങളും'}, 'ca_2026_06_028': {'question': '2026 ജൂണിൽ കേരള ആനക്കൂട്ടം എണ്ണം നടത്തുന്ന വകുപ്പ് ഏത്?', 'options': ['തുറമുഖ അധികൃതർ', 'വന വകുപ്പ്', 'പോലീസ് മാത്രം', 'ചലച്ചിത്ര ബോർഡ്'], 'answer': 'വന വകുപ്പ്'}, 'ca_2026_06_029': {'question': 'India-Middle East-Europe Economic Corridor (IMEC) ചർച്ച ചെയ്ത ഫോറം ഏത്?', 'options': ['സ്കൂൾ PTA', 'G20 ബന്ധപ്പെട്ട ഫോറങ്ങൾ', 'ഒന്നുമില്ല', 'പഞ്ചായത്ത്'], 'answer': 'G20 ബന്ധപ്പെട്ട ഫോറങ്ങൾ'}, 'ca_2026_06_030': {'question': 'Kerala Startup Mission-ന്റെ പ്രധാന പരിപാടി ഏത്?', 'options': ['Huddle Global/IGS', 'Oscars', 'Wimbledon', 'ഒന്നുമില്ല'], 'answer': 'Huddle Global/IGS'}, 'ca_2026_06_031': {'question': 'ECI സംസ്ഥാന തിരഞ്ഞെടുപ്പ് കാലക്രമം തയ്യാറാക്കുന്നത് എങ്ങനെ?', 'options': ['പഞ്ചായത്ത് ഒരിക്കലും', 'കലണ്ടർ പ്രകാരം വിവിധ സംസ്ഥാനങ്ങൾ', 'ഒന്നുമില്ല', 'കേരളം എപ്പോഴും ജൂണിൽ'], 'answer': 'കലണ്ടർ പ്രകാരം വിവിധ സംസ്ഥാനങ്ങൾ'}, 'ca_2026_06_032': {'question': '2026 ജൂണിൽ കേരള തീരദേശ കരിമ്പ് നിയന്ത്രണം നടത്തുന്നത് ആര്?', 'options': ['DRDO', 'PWDയും തീരദേശ അധികൃതരും', 'ചലച്ചിത്ര ബോർഡ്', 'ISRO മാത്രം'], 'answer': 'PWDയും തീരദേശ അധികൃതരും'}, 'ca_2026_06_033': {'question': 'National Green Tribunal-ന്റെ കേസുകൾ പ്രധാനമായും എന്തിനെ സംബന്ധിച്ച്?', 'options': ['ചലച്ചിത്ര പുരസ്കാരം', 'ഒന്നുമില്ല', 'കായികം', 'പരിസ്ഥിതി ലംഘനങ്ങൾ'], 'answer': 'പരിസ്ഥിതി ലംഘനങ്ങൾ'}, 'ca_2026_06_034': {'question': 'India semiconductor mission fabs-ന്റെ പുരോഗതി എവിടെ?', 'options': ['കേരളം മാത്രം', 'ഒന്നുമില്ല', 'ഗുജറാത്ത്/ഇന്ത്യൻ സൈറ്റുകൾ', 'അന്റാർട്ടിക്ക'], 'answer': 'ഗുജറാത്ത്/ഇന്ത്യൻ സൈറ്റുകൾ'}, 'ca_2026_06_035': {'question': '2026 ജൂണിൽ കേരള കൃഷി വകുപ്പ് മഴക്കാല വിള തയ്യാറെടുപ്പ് എന്തിനാണ്?', 'options': ['ശീതകാല കായികം', 'മഴക്കാല വിള തയ്യാറെടുപ്പ്', 'ഒന്നുമില്ല', 'ചലച്ചിത്രോത്സവം'], 'answer': 'മഴക്കാല വിള തയ്യാറെടുപ്പ്'}, 'ca_2026_06_036': {'question': 'ആയുഷ്മാൻ ഭാരത് പരിരക്ഷാ വിപുലീകരണം എന്തുമായി ബന്ധപ്പെട്ടതാണ്?', 'options': ['ആരോഗ്യ ഇൻഷുറൻസ് ലാഭാർഥികൾ', 'റോഡുകൾ', 'ചലച്ചിത്രം', 'പ്രതിരോധം'], 'answer': 'ആരോഗ്യ ഇൻഷുറൻസ് ലാഭാർഥികൾ'}, 'ca_2026_06_037': {'question': 'Kerala Police Cyber Dome-ന്റെ പ്രധാന ലക്ഷ്യം എന്ത്?', 'options': ['കൽക്കരി ഖനനം', 'ചലച്ചിത്രം', 'ആനക്കൂട്ടം എണ്ണം', 'സൈബർ ക്രൈം തടയൽ'], 'answer': 'സൈബർ ക്രൈം തടയൽ'}, 'ca_2026_06_038': {'question': 'ഇന്ത്യയുടെ നവീകരണ ഊർജ്ജ സ്ഥാപിത ശേഷിയുടെ ആഗോള റാങ്ക്?', 'options': ['100-ാം മാത്രം', 'അവസാനം', 'മുൻനിരയിലെ 4-ാം', 'പട്ടികയിൽ ഇല്ല'], 'answer': 'മുൻനിരയിലെ 4-ാം'}, 'ca_2026_06_039': {'question': 'Kochi Metro-യുടെ വിപുലീകരണ വാർത്തകൾ പ്രധാനമായും എന്തിനെ സംബന്ധിച്ച്?', 'options': ['ദില്ലി മെട്രോ', 'ഒന്നുമില്ല', 'ലണ്ടൻ ട്യൂബ്', 'ആലുവ-തൃപ്പൂണിത്തുറ കോറിഡോർ ഘട്ടങ്ങൾ'], 'answer': 'ആലുവ-തൃപ്പൂണിത്തുറ കോറിഡോർ ഘട്ടങ്ങൾ'}, 'ca_2026_06_040': {'question': 'കേരള സ്ത്രീകൾക്കുള്ള കായിക ലീഗ് പദ്ധതി?', 'options': ['ഒന്നുമില്ല', 'ഗോൽഫ് മാത്രം', 'ഫുട്ബോൾ/ക്രിക്കറ്റ് ലീഗുകൾ', 'വിദേശത്ത് ചെസ് മാത്രം'], 'answer': 'ഫുട്ബോൾ/ക്രിക്കറ്റ് ലീഗുകൾ'}}

EXACT_MAP = {
    '10 feet': '10 അടി',
    '100 days': '100 ദിവസം',
    '100th only': '100-ാം മാത്രം',
    '12 feet': '12 അടി',
    '150 days': '150 ദിവസം',
    '155-163 g': '155-163 ഗ്രാം',
    '1896 Athens': '1896 ഏതൻസ്',
    '1900 Paris': '1900 പാരീസ്',
    '1924 Paris': '1924 പാരീസ്',
    '1936 Berlin': '1936 ബെർലിൻ',
    '1962 war': '1962 യുദ്ധം',
    '1965 war': '1965 യുദ്ധം',
    '1971 war': '1971 യുദ്ധം',
    '2 years': '2 വർഷത്തിലൊരിക്കൽ',
    '200 days': '200 ദിവസം',
    '2012 London': '2012 ലണ്ടൻ',
    '2016 Rio': '2016 റിയോ',
    '2021 Tokyo': '2021 ടോക്കിയോ',
    '2024 Paris': '2024 പാരീസ്',
    '2026 ജൂണിൽ FIFA Club World Cup host country?': '2026 ജൂണിൽ FIFA Club World Cup-ന്റെ ആതിഥ്യ രാജ്യം ഏത്?',
    '2026 ജൂണിൽ GST Council meeting-ന്റെ പ്രധാന ചർച്ചാവിഷയം?': '2026 ജൂണിൽ GST Council യോഗത്തിന്റെ പ്രധാന ചർച്ചാവിഷയം എന്ത്?',
    '2026 ജൂണിൽ കerala സ്കൂളുകൾ reopening സാധാരണയായി?': '2026 ജൂൺ അവധിക്ക് ശേഷം കerala-യിലെ വിദ്യാലയങ്ങൾ വീണ്ടും തുറക്കുന്നത് സാധാരണയായി എപ്പോൾ?',
    '3 years': '3 വർഷത്തിലൊരിക്കൽ',
    '4 years': '4 വർഷത്തിലൊരിക്കൽ',
    '5 years': '5 വർഷത്തിലൊരിക്കൽ',
    '50 days': '50 ദിവസം',
    '8 feet': '8 അടി',
    '9 feet': '9 അടി',
    'ASEAN members count?': 'ASEAN അംഗങ്ങളുടെ എണ്ണം?',
    'AYUSH systems promotion': 'ആയുഷ് വ്യവസ്ഥകളുടെ പ്രോത്സാഹനം',
    'Aadhaar project launched in?': 'ആധാർ പദ്ധതി ആരംഭിച്ച വർഷം?',
    'Action and consequence': 'കർമ്മവും പരിണാമവും',
    'Aditya-L1 സൗര്യ ദൗത്യം launch year?': 'ആദിത്യ-L1 സൗര്യ ദൗത്യം വിക്ഷേപണ വർഷം?',
    'Adjective': 'വിശേഷണം',
    'Administrators': 'ഭരണാധികാരികൾ',
    'Advaita means?': 'അദ്വൈതത്തിന്റെ അർത്ഥം?',
    'Aerospace/Defence': 'വൈമാനിക/പ്രതിരോധം',
    'Agasthyarkoodam': 'അഗസ്ത്യകൂടം',
    'Agriculture development scheme': 'കാർഷിക വികസന പദ്ധതി',
    'Ahmedabad': 'അഹമദാബാദ്',
    'Akshara in Malayalam means?': 'അക്ഷരത്തിന്റെ അർത്ഥം?',
    'Alappuzha': 'ആലപ്പുഴ',
    'All major ICC trophies': 'എല്ലാ പ്രധാന ICC ട്രോഫികളും',
    'Aluva-Thripunithura corridor phases': 'ആലുവ-തൃപ്പൂണിത്തുറ കോറിഡോർ ഘട്ടങ്ങൾ',
    'Anamudi': 'ആനമുടി',
    'Andhra Pradesh': 'ആന്ധ്രപ്രദേശ്',
    'Anganwadi services under which scheme?': 'അംഗൻവാടി സേവനങ്ങൾ ഏത് പദ്ധതിക്ക് കീഴിൽ?',
    'Anganwadi/nutrition infrastructure': 'അംഗൻവാടി/പോഷകാഹാര അടിസ്ഥാന സൗകര്യങ്ങൾ',
    'Ankara': 'അങ്കാറ',
    'Antarctica': 'അന്റാർട്ടിക്ക',
    'Antyodaya Anna Yojana for?': 'അംത്യോദയ അന്ന യോജന എന്തിനാണ്?',
    'Archery': 'വില്ലുവെട്ട്',
    'Argentina': 'അർജന്റീന',
    'Arjuna Award is given for?': 'Arjuna Award എന്തിനാണ് നൽകുന്നത്?',
    'Article 370 abrogation date?': 'ആർട്ടിക്കിൾ 370 റദ്ദാക്കിയ തീയതി?',
    'Asian Development Bank HQ?': 'ഏഷ്യൻ ഡെവലപ്മെന്റ് ബാങ്ക് ആസ്ഥാനം?',
    'Asian Games 2023 held in?': '2023 Asian Games venue?',
    'Assam': 'അസം',
    'Atal Tunnel (Rohtang) inaugurated in?': 'അടൽ സുരംഗ് (റോഹ്താങ്) ഉദ്ഘാടനം ചെയ്ത വർഷം?',
    'Athens': 'ഏതൻസ്',
    'Athletics': 'ട്രാക്ക്-ഫീൽഡ്',
    'Athletics only': 'ട്രാക്ക്-ഫീൽഡ് മാത്രം',
    'Australia': 'ഓസ്ട്രേലിയ',
    'Australian Open surface (main)?': 'Australian Open surface?',
    'Automobile cluster Pune/Chennai associated industry?': 'പൂണെ/ചെന്നൈ ഓട്ടോമൊബൈൽ ക്ലസ്റ്റർ ബന്ധപ്പെട്ട വ്യവസായം?',
    'Automobile manufacturing': 'ഓട്ടോമൊബൈൽ നിർമ്മാണം',
    'Ayushman only': 'ആയുഷ്മാൻ മാത്രം',
    'BJP and allies like BDJS': 'BJP-യും BDJS പോലുള്ള സഖ്യകക്ഷികളും',
    'BRICS 2024 expanded new members include?': 'BRICS 2024 വിപുലീകരണ പുതിയ അംഗങ്ങൾ?',
    'BRICS original members before expansion?': 'BRICS-ന്റെ യഥാർത്ഥ അംഗങ്ങൾ?',
    'Badminton': 'ബാഡ്മിന്റൺ',
    'Badminton player P.V. Sindhu Olympic medal colour 2020?': 'P.V. Sindhu-യുടെ 2020 ഒളിമ്പിക് മെഡൽ നിറം?',
    'Badminton shuttlecock material traditionally?': 'Shuttlecock material?',
    'Balyakalasakhi': 'ബാല്യകാലസഖി',
    'Bangkok': 'ബാങ്കോക്ക്',
    "Basheer's famous novel about childhood love?": 'ബഷീറിന്റെ ബാല്യപ്രണയത്തെ കുറിച്ചുള്ള പ്രശസ്ത നോവൽ?',
    'Bengaluru': 'ബെംഗളൂരു',
    'Bern': 'ബേൺ',
    'Bhagavad Gita part of?': 'ഗീത ഏതിന്റെ ഭാഗമാണ്?',
    'Bhagirathi': 'ഭാഗീരഥി',
    'Bhakra Nangal dam on river?': 'ഭക്രാ നംഗൽ അണക്കെട്ട് ഏത് നദിയിൽ?',
    'Bharat Electronics Limited (BEL) HQ?': 'BEL ആസ്ഥാനം?',
    'Bharat Heavy Electricals major product?': 'ഭാരത് ഹെവി ഇലക്ട്രിക്കൽസിന്റെ പ്രധാന ഉൽപ്പന്നം?',
    'Bharathapuzha': 'ഭാരതപുഴ',
    'Bihar': 'ബിഹാർ',
    'Birmingham': 'ബർമിംഗ്ഹാം',
    'Blue Revolution relates to?': 'നീലവിപ്ലവം എന്തുമായി ബന്ധപ്പെട്ടത്?',
    'Blue city': 'നീല നഗരം',
    'Boxing': 'ബോക്സിംഗ്',
    'Brahman and Atman': 'ബ്രഹ്മവും ആത്മാവും',
    'Brasilia': 'ബ്രസീലിയ',
    'Brazil': 'ബ്രാസീൽ',
    'Brisbane': 'ബ്രിസ്ബേൻ',
    'Bronze': 'വെങ്കലം',
    'Buddhism': 'ബുദ്ധമതം',
    'Buenos Aires': 'ബ്യൂണസ് ഐറിസ്',
    'Bulk drug capital': 'ബൾക്ക് ഡ്രഗ് തലസ്ഥാനം',
    'C. Achutha Menon ministry known for?': 'സി. അച്യുത മേനൻ മന്ത്രിത്വം എന്തിന് പ്രസിദ്ധം?',
    'COVID orphaned children': 'കോവിഡ് അനാഥരായ കുട്ടികൾ',
    'Canberra': 'കാൻബെറ',
    'Capital of Argentina?': 'അർജന്റീനയുടെ തലസ്ഥാനം?',
    'Capital of Australia?': 'ഓസ്ട്രേലിയയുടെ തലസ്ഥാനം?',
    'Capital of Bangladesh?': 'ബംഗ്ലാദേശിന്റെ തലസ്ഥാനം?',
    'Capital of Bhutan?': 'ഭൂട്ടാനിന്റെ തലസ്ഥാനം?',
    'Capital of Brazil?': 'ബ്രസീലിന്റെ തലസ്ഥാനം?',
    'Capital of Canada?': 'കാനഡയുടെ തലസ്ഥാനം?',
    'Capital of China?': 'ചൈനയുടെ തലസ്ഥാനം?',
    'Capital of France?': 'ഫ്രാൻസിന്റെ തലസ്ഥാനം?',
    'Capital of Germany?': 'ജർമ്മനിയുടെ തലസ്ഥാനം?',
    'Capital of Greece?': 'ഗ്രീസിന്റെ തലസ്ഥാനം?',
    'Capital of Italy?': 'ഇറ്റലിയുടെ തലസ്ഥാനം?',
    'Capital of Japan?': 'ജപ്പാനിന്റെ തലസ്ഥാനം?',
    'Capital of Maldives?': 'മാലിദ്വീപിന്റെ തലസ്ഥാനം?',
    'Capital of Mexico?': 'മെക്സിക്കോയുടെ തലസ്ഥാനം?',
    'Capital of Nepal?': 'നേപ്പാളിന്റെ തലസ്ഥാനം?',
    'Capital of New Zealand?': 'ന്യൂസിലൻഡിന്റെ തലസ്ഥാനം?',
    'Capital of Pakistan?': 'പാക്കിസ്ഥാനിന്റെ തലസ്ഥാനം?',
    'Capital of Russia?': 'റഷ്യയുടെ തലസ്ഥാനം?',
    'Capital of Spain?': 'സ്പെയിന്റെ തലസ്ഥാനം?',
    'Capital of Sri Lanka?': 'ശ്രീലങ്കയുടെ തലസ്ഥാനം?',
    'Capital of Switzerland?': 'സ്വിറ്സർലാന്റിന്റെ തലസ്ഥാനം?',
    'Capital of Thailand?': 'തായ്ലാന്റിന്റെ തലസ്ഥാനം?',
    'Capital of Turkey?': 'തുർക്കിയുടെ തലസ്ഥാനം?',
    'Captain Cool': 'ക്യാപ്റ്റൻ കൂൾ',
    'Caregivers of bedridden patients': 'പടുക്കിൽ കിടക്കുന്ന രോഗികളുടെ പരിചരകർ',
    'Carpet': 'പരിപ്പ്',
    'Cashless treatment': 'പണമില്ലാത്ത ചികിത്സ',
    'Caste hierarchy': 'ജാതി ശ്രേണി',
    'Centre and states': 'കേന്ദ്രവും സംസ്ഥാനങ്ങളും',
    'Chaliyar': 'ചാലിയാർ',
    'Chandrayaan-1 launched in?': 'ചന്ദ്രയാൻ-1 വിക്ഷേപണ വർഷം?',
    'Chandrayaan-3 ചന്ദ്രനിൽ soft landing നടത്തിയ വർഷം?': 'ചന്ദ്രയാൻ-3 ചന്ദ്രനിൽ സോഫ്റ്റ് ലാൻഡിംഗ് നടത്തിയ വർഷം?',
    'Chembra': 'ചെമ്പ്ര',
    'Chemmeen': 'ചെമ്മീൻ',
    'Chemmeen author?': 'ചെമ്മീൻ രചയിതാവ്?',
    'Chennai': 'ചെന്നൈ',
    'Chennai (automobile)': 'ചെന്നൈ (ഓട്ടോമൊബൈൽ)',
    'Chennai Super Kings': 'ചെന്നൈ സൂപ്പർ കിംഗ്സ്',
    'Chess: Viswanathan Anand became World Champion first in?': 'Viswanathan Anand ലോക чемпионായത്?',
    'China': 'ചൈന',
    'Citius only': 'സിറ്റിയസ് മാത്രം',
    'Citizenship Amendment Act passed in?': 'പൗരത്വ ഭേദഗതി നിയമം പാസാക്കിയ വർഷം?',
    'Clay': 'കളിമൺ',
    'Coaches': 'പരിശീലകർ',
    'Coal mining': 'കൽക്കരി ഖനനം',
    'Coal transport': 'കൽക്കരി കയിക്കയം',
    'Cochin Shipyard': 'കൊച്ചി ഷിപ്പ്യാർഡ്',
    'Coffee Board HQ?': 'കോഫി ബോർഡ് ആസ്ഥാനം?',
    'Coir industry major state?': 'കയർ വ്യവസായത്തിന്റെ പ്രധാന സംസ്ഥാനം?',
    'Colonial rule': 'കോളനി ഭരണം',
    'Commonwealth Games 2022 held in?': '2022 Commonwealth Games venue?',
    'Community mental health': 'സാമൂഹിക മാനസികാരോഗ്യം',
    'Community organisation of women': 'സ്ത്രീകളുടെ സാമൂഹിക സംഘടന',
    'Confucius origin country?': 'കൺഫ്യൂഷ്യസിന്റെ ഉത്ഭവ രാജ്യം?',
    'Construction workers welfare': 'നിർമ്മാണ തൊഴിലാളികളുടെ ക്ഷേമം',
    'Consumer Affairs/Food & PD': 'ഉപഭോക്തൃ കാര്യങ്ങൾ/ഭക്ഷ്യവും പൊതുവിതരണവും',
    'Cricket': 'ക്രിക്കറ്റ്',
    'Cricket pitch length in yards?': 'Cricket pitch length?',
    'Cricket: Test match maximum days?': 'ടെസ്റ്റ് മത്സരത്തിന്റെ പരമാവധി ദിവസങ്ങൾ?',
    'Cricket: maximum overs in T20 match per side?': 'T20-യിൽ ഒരു പക്ഷത്തിന് പരമാവധി ഓവറുകൾ?',
    'Cyber crime prevention': 'സൈബർ ക്രൈം തടയൽ',
    'Dairy': 'പാൽ ഉൽപ്പാദനം',
    'Davis Cup is associated with?': 'Davis Cup?',
    'Defence': 'പ്രതിരോധം',
    'Defence Research and Development Organisation (DRDO) HQ?': 'DRDO ആസ്ഥാനം?',
    'Defence electronics': 'പ്രതിരോധ ഇലക്ട്രോണിക്സ്',
    'Defence only': 'പ്രതിരോധം മാത്രം',
    'Delhi': 'ഡൽഹി',
    'Delhi Metro started operations in?': 'ഡൽഹി മെട്രോ പ്രവർത്തനം ആരംഭിച്ച വർഷം?',
    'Delhi metro': 'ദില്ലി മെട്രോ',
    'Detroit of India': 'ഇന്ത്യയുടെ ഡിട്രോയിറ്റ്',
    'Detroit of India often refers to?': 'ഇന്ത്യയുടെ ഡിട്രോയിറ്റ് എന്ന് സാധാരണയായി ഏതിനെ സൂചിപ്പിക്കുന്നു?',
    'Dhaka': 'ഢാക്ക',
    'Dialectical questioning': 'വാദവിവാദ പരിശോധന',
    'Digital education during COVID': 'കോവിഡ് കാലത്തെ ഡിജിറ്റൽ വിദ്യാഭ്യാസം',
    'Discus Throw': 'ഡിസ്കസ് തൂക്കൽ',
    'Dismissal of first EMS ministry': 'ആദ്യ ഇ.എം.എസ് മന്ത്രിത്വത്തിന്റെ പിരിച്ചുവിടൽ',
    'Dravidian': 'ദ്രാവിഡ',
    'Dronacharya Award is given to?': 'Dronacharya Award ആർക്കാണ് നൽകുന്നത്?',
    'Dualism': 'ദ്വൈതം',
    'Dvaita means?': 'ദ്വൈതത്തിന്റെ അർത്ഥം?',
    'ECI state elections schedule prepare ചെയ്യുന്നത്?': 'ECI സംസ്ഥാന തിരഞ്ഞെടുപ്പ് കാലക്രമം തയ്യാറാക്കുന്നത് എങ്ങനെ?',
    'Educational concessions': 'വിദ്യാഭ്യാസ ഇളവുകൾ',
    'Eggs': 'മുട്ട',
    'Egypt': 'ഈജിപ്ത്',
    'Elderly care services': 'വയോജന പരിചരണ സേവനങ്ങൾ',
    'Elephant': 'ആന',
    'Elephant census': 'ആനക്കൂട്ടം എണ്ണം',
    'Emergency declared by Indira Gandhi in?': 'ഇന്ദിരാ ഗാന്ധി അടിയന്തിരാവസ്ഥ പ്രഖ്യാപിച്ച വർഷം?',
    'Empiricism emphasizes?': 'അനുഭവവാദം എന്തിനെ ഊന്നിപ്പറയുന്നു?',
    'End-of-life care': 'ജീവിതാവസാന പരിചരണം',
    'England': 'ഇംഗ്ലണ്ട്',
    'Environmental violations': 'പരിസ്ഥിതി ലംഘനങ്ങൾ',
    'Experience as knowledge source': 'അനുഭവം അറിവിന്റെ ഉറവിടം',
    'Export Processing Zone first in India?': 'ഇന്ത്യയിലെ ആദ്യ എക്സ്പോർട്ട് പ്രോസസ്സിംഗ് സോൺ?',
    'FIFA World Cup 2022 venue country?': '2022 FIFA World Cup-ന്റെ ആതിഥ്യ രാജ്യം?',
    'FIFA World Cup 2022 winner?': '2022 FIFA World Cup-ന്റെ വിജയി?',
    'Fame': 'പ്രശസ്തി',
    "Farmers' credit needs": 'കർഷകരുടെ വായ്പാ ആവശ്യങ്ങൾ',
    'Faster, Higher, Stronger': 'വേഗം, ഉയരം, ശക്തി',
    'Faster, Higher, Stronger - Together': 'വേഗം, ഉയരം, ശക്തി — ഒന്നിച്ച്',
    'Father of Malayalam language': 'മലയാള ഭാഷയുടെ പിതാവ്',
    'Feather': 'തൂവൽ',
    'Film': 'ചലച്ചിത്രം',
    'Film artists': 'ചലച്ചിത്ര കലാകാരന്മാർ',
    'Film awards': 'ചലച്ചിത്ര പുരസ്കാരം',
    'Film board': 'ചലച്ചിത്ര ബോർഡ്',
    'Film festival': 'ചലച്ചിത്രോത്സവം',
    'Film only': 'ചലച്ചിത്രം മാത്രം',
    'First Indian in space?': 'ഇന്ത്യയുടെ ആദ്യ ബഹിരാകാശയാത്രികൻ?',
    'First Pokhran nuclear test (Smiling Buddha)?': 'ആദ്യ പോഖ്രാൻ ആണവ പരീക്ഷണം (സ്മൈലിംഗ് ബുദ്ധ)?',
    'First President of India?': 'ഇന്ത്യയുടെ ആദ്യ രാഷ്ട്രപതി?',
    'Fisheries': 'മത്സ്യബന്ധനം',
    'Five years': 'ഓരോ അഞ്ച് വർഷത്തിലും',
    'Flying Sikh': 'ഫ്ലൈയിംഗ് സിഖ്',
    'Food security': 'ഭക്ഷ്യ സുരക്ഷ',
    'Football': 'ഫുട്ബോൾ',
    'Football and cricket': 'ഫുട്ബോളും ക്രിക്കറ്റും',
    'Football goal width in metres (approx)?': 'Football goal width?',
    'Football/cricket leagues': 'ഫുട്ബോൾ/ക്രിക്കറ്റ് ലീഗുകൾ',
    'Football: FIFA World Cup held every?': 'FIFA World Cup എത്ര വർഷത്തിലൊ once?',
    'Forest Department': 'വന വകുപ്പ്',
    'Four Noble Truths belong to?': 'നാല് ആര്യസത്യങ്ങൾ ഏതിനുള്ളതാണ്?',
    'France': 'ഫ്രാൻസ്',
    'Free food grains during crisis': 'പ്രതിസന്ധി കാലത്ത് സൗജന്യ ഭക്ഷ്യധാന്യങ്ങൾ',
    'G20 Summit 2023 venue?': 'G20 സമ്മേളനം 2023 വേദി?',
    'G20 related forums': 'G20 ബന്ധപ്പെട്ട ഫോറങ്ങൾ',
    "Gaganyaan is India's?": 'ഗഗന്യാൻ ഇന്ത്യയുടെ എന്താണ്?',
    'Ganga': 'ഗംഗ',
    'Germany': 'ജർമ്മനി',
    'Gitanjali': 'ഗീതാഞ്ജലി',
    'Glasgow': 'ഗ്ലാസ്ഗോ',
    'Goa': 'ഗോവ',
    'God of Small Things author?': 'ഗോഡ് ഓഫ് സ്മോൾ തിങ്ങ്സ് രചയിതാവ്?',
    'Godan': 'ഗോദാൻ',
    'Godavari': 'ഗോദാവരി',
    'Gold': 'സ്വർണ്ണം',
    'Gold Coast': 'ഗോൾഡ് കോസ്റ്റ്',
    'Golden Revolution relates to?': 'സ്വർണവിപ്ലവം എന്തുമായി ബന്ധപ്പെട്ടത്?',
    'Grama Panchayat, Block, District': 'ഗ്രാമ പഞ്ചായത്ത്, ബ്ലോക്ക്, ജില്ല',
    'Grass': 'പുലു',
    'Greece': 'ഗ്രീസ്',
    'Green Revolution in India associated with?': 'ഇന്ത്യയിലെ പച്ചവിപ്ലവം ആരുമായി ബന്ധപ്പെട്ടത്?',
    'Greenfield International Stadium located in?': 'Greenfield International Stadium സ്ഥിതി ചെയ്യുന്നത്?',
    'Guangzhou': 'ഗുവാങ്ചൗ',
    'Gujarat': 'ഗുജറാത്ത്',
    'Gujarat/India sites': 'ഗുജറാത്ത്/ഇന്ത്യൻ സൈറ്റുകൾ',
    'Hamlet': 'ഹാംലെറ്റ്',
    'Handmade carpets/textiles': 'കൈത്തെയ്യുന്ന പരിപ്പുകൾ/വസ്ത്രങ്ങൾ',
    'Hangzhou': 'ഹാങ്ചൺ',
    'Hard court': 'ഹാർഡ് കോർട്ട്',
    'Harry Potter author?': 'ഹാരി പോട്ടർ രചയിതാവ്?',
    'Haryana': 'ഹരിയാന',
    'Haryana Hurricane': 'ഹരിയാന ഹറിക്കേൻ',
    'Haryana/Gujarat': 'ഹരിയാന/ഗുജറാത്ത്',
    'Health assistance': 'ആരോഗ്യ സഹായം',
    'Health insurance beneficiaries': 'ആരോഗ്യ ഇൻഷുറൻസ് ലാഭാർഥികൾ',
    'Heavy equipment': 'ഭാരമുള്ള ഉപകരണങ്ങൾ',
    'Height of basketball hoop from floor?': 'Basketball hoop height?',
    'Highest peak in Kerala?': 'കേരളത്തിലെ ഏറ്റവും ഉയർന്ന ശിഖരം?',
    'Himachal': 'ഹിമാചൽ',
    'Hinduism only': 'ഹിന്ദുമതം മാത്രം',
    'Hindustan Aeronautics Limited (HAL) HQ?': 'HAL ആസ്ഥാനം?',
    'Hindustan Petroleum HQ city?': 'ഹിന്ദുസ്ഥാൻ പെട്രോളിയം ആസ്ഥാന നഗരം?',
    'Hockey': 'ഹോക്കി',
    'Hockey only': 'ഹോക്കി മാത്രം',
    'Hockey: India won Olympic gold first in?': 'India-യുടെ ആദ്യ Olympic ഹockey സ്വർണ്ണം?',
    'Homer wrote?': 'ഹോമർ എഴുതിയത്?',
    'Horticulture': 'തോട്ടiculture',
    'Human spaceflight programme': 'മനുഷ്യ ബഹിരാകാശ ദൗത്യ പരിപാടി',
    'Hydro power': 'ജലവിദ്യുത്',
    'ICC Cricket World Cup 2023 final venue?': '2023 ICC Cricket World Cup അന്തിമ മത്സര വേദി?',
    'ICC Cricket World Cup 2023 winner?': '2023 ICC Cricket World Cup-ന്റെ വിജയി?',
    'IPL trophy winner 2024?': '2024 IPL-ന്റെ വിജയി?',
    'ISRO founded in?': 'ISRO സ്ഥാപിത വർഷം?',
    'ISRO only': 'ISRO മാത്രം',
    'IT industry hub Bengaluru nickname?': 'ബെംഗളൂരു ഐടി നാഗരികതയുടെ വിളിപ്പേര്?',
    'Idukki arch dam': 'ഇടുക്കി ആർച്ച് അണക്കെട്ട്',
    'Idukki arch dam on river?': 'ഇടുക്കി ആർച്ച് അണക്കെട്ട് ഏത് നദിയിൽ?',
    'Iliad and Odyssey': 'ഇലിയഡും ഒഡിസിയും',
    'Incheon': 'ഇഞ്ചിയോൺ',
    'Indeclinable particle': 'അവ്യയം',
    'India G20 presidency year?': 'ഇന്ത്യയുടെ G20 അധ്യക്ഷത വർഷം?',
    'India renewable energy installed capacity global rank?': 'ഇന്ത്യയുടെ നവീകരണ ഊർജ്ജ സ്ഥാപിത ശേഷിയുടെ ആഗോള റാങ്ക്?',
    "India's first PM from BJP?": 'ഇന്ത്യയുടെ ആദ്യ BJP പ്രധാനമന്ത്രി?',
    "India's first nuclear reactor?": 'ഇന്ത്യയുടെ ആദ്യ ആണവ റിയാക്ടർ?',
    "India's first satellite Aryabhata launched in?": 'ആര്യഭട്ട ആദ്യ ഉപഗ്രഹം വിക്ഷേപിച്ച വർഷം?',
    "India's largest state by area?": 'ഇന്ത്യയിലെ ഏറ്റവും വലിയ സംസ്ഥാനം?',
    "India's longest dam Hirakud on river?": 'ഇന്ത്യയിലെ ഏറ്റവും നീണ്ട അണക്കെട്ട് ഹീരാക്കുൾ ഏത് നദിയിൽ?',
    "India's longest serving PM?": 'ഇന്ത്യയുടെ ഏറ്റവും കൂടുതൽ കാലം പ്രധാനമന്ത്രിയായവർ?',
    "India's most populous state?": 'ഇന്ത്യയിലെ ഏറ്റവും ജനസംഖ്യയുള്ള സംസ്ഥാനം?',
    "India's smallest state by area?": 'ഇന്ത്യയിലെ ഏറ്റവും ചെറിയ സംസ്ഥാനം?',
    'India-China war year?': 'ഇന്ത്യ-ചൈന യുദ്ധ വർഷം?',
    'Indian Space Research Organisation (ISRO) HQ?': 'ISRO ആസ്ഥാനം?',
    'Integrated infrastructure planning': 'സമഗ്ര അടിസ്ഥാന സൗകര്യ ആസൂത്രണം',
    'International Atomic Energy Agency monitors?': 'അന്താരാഷ്ട്ര അണുവിദ്യു ഏജൻസി നിരീക്ഷിക്കുന്നത്?',
    'International Court of Justice seat?': 'അന്താരാഷ്ട്ര നീതി ന്യായാധിപസഭ ആസ്ഥാനം?',
    'International Monetary Fund members count (approx)?': 'IMF അംഗങ്ങളുടെ എണ്ണം (ഏകദേശം)?',
    'Islamabad': 'ഇസ്ലാമാബാദ്',
    'Jainism': 'ജൈനമതം',
    'Jaipur': 'ജയ്പ്പൂർ',
    'Jakarta': 'ജക്കാർത്ത',
    'Jammu and Kashmir bifurcated into UTs in?': 'ജമ്മു-കാശ്മീർ യൂണിയൻ ടെറിട്ടറികളായി വിഭജിച്ച വർഷം?',
    'Jamshedpur': 'ജാംഷെഡ്പൂർ',
    'Javelin Throw': 'അമ്പെറിങ്ങ്',
    'Jawaharlal Nehru Stadium (Kochi) primarily used for?': 'ജawaharlal നehru സ്റadium (കochi) പ്രധാനമായി എന്തിനാണ്?',
    'Kabaddi': 'കബഡി',
    'Kaloor, Kochi': 'കലൂർ, കൊച്ചി',
    'Kandla': 'കാന്ദ്ല',
    'Kapil Dev led India to World Cup in?': 'Kapil Dev India-യെ World Cup-il nayichath?',
    'Kargil War year?': 'കാർഗിൽ യുദ്ധ വർഷം?',
    'Kargil war': 'കാർഗിൽ യുദ്ധം',
    'Kariavattom, Thiruvananthapuram': 'കരിയാവട്ടം, തിരുവനന്തപുരം',
    'Karma theory implies?': 'കർമ്മ സിദ്ധാന്തം സൂചിപ്പിക്കുന്നത്?',
    'Karnataka': 'കർണാടക',
    'Karnataka and Maharashtra': 'കർണാടകയും മഹാരാഷ്ട്രയും',
    'Kathmandu': 'കാഠ്മണ്ഡു',
    'Kerala': 'കേരളം',
    'Kerala Assembly seats?': 'കേരള നിയമസഭാ സീറ്റുകളുടെ എണ്ണം?',
    'Kerala Blasters FC plays in which league?': 'കേരള ബ്ലാസ്റ്റേഴ്സ് FC ഏത് ലീഗിൽ കളിക്കുന്നു?',
    'Kerala Kudumbashree is?': 'കേരള കുടുംബശ്രീ എന്താണ്?',
    'Kerala athlete Jesna Jacob associated with?': 'Jesna Jacob associated with?',
    'Kerala formed as state on?': 'കേരളം സംസ്ഥാനമായി രൂപീകരിച്ച തീയതി?',
    'Kerala has how many Lok Sabha seats?': 'കേരളത്തിലെ ലോക്സഭാ സീറ്റുകളുടെ എണ്ണം?',
    'Kerala has how many Rajya Sabha seats?': 'കേരളത്തിലെ രാജ്യസഭാ സീറ്റുകളുടെ എണ്ണം?',
    'Kerala local self-government three-tier includes?': 'കേരള സ്വയംഭരണ ത്രിതല സംവിധാനത്തിൽ ഉൾപ്പെടുന്നത്?',
    'Kerala only': 'കേരളം മാത്രം',
    "Kerala women's league sports initiative?": 'കerala സ്ത്രീകൾക്കുള്ള കായിക ലീഗ് പദ്ധതി?',
    'Khadi and Village Industries Commission (KVIC) for?': 'KVIC എന്തിനാണ്?',
    'Khasakkinte Ithihasam': 'ഖസാക്കിന്റെ ഇതിഹാസം',
    'Kilippattu literary form means?': 'കിലിപ്പാട്ട് സാഹിത്യ രൂപത്തിന്റെ അർത്ഥം?',
    'Kisan Credit Card scheme primarily for?': 'കിസാൻ ക്രെഡിറ്റ് കാർഡ് പദ്ധതി പ്രധാനമായും ആർക്ക്?',
    'Knitwear exports': 'നിറ്റ്വെയർ കയറ്റുമതി',
    'Kochi': 'കൊച്ചി',
    'Kochi Metro extension news typically covers?': 'Kochi Metro-യുടെ വിപുലീകരണ വാർത്തകൾ പ്രധാനമായും എന്തിനെ സംബന്ധിച്ച്?',
    'Kolkata': 'കൊൽക്കത്ത',
    'Kolkata Knight Riders': 'കൊൽക്കത്ത നൈറ്റ് റൈഡേഴ്സ്',
    'Kozhikode': 'കോഴിക്കോട്',
    'Kriya in Malayalam grammar?': 'ക്രിയയുടെ അർത്ഥം?',
    'Kumar Sangakkara': 'കുമാർ സംഗക്കാര',
    'LDF acronym stands for?': 'LDF എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം?',
    'Lahore Declaration signed in?': 'ലാഹോർ പ്രഖ്യാപനം ഒപ്പുവെച്ച വർഷം?',
    'Land reforms implementation': 'ഭൂമി പരിഷ്കരണ നടപ്പാക്കൽ',
    'Largest refinery in India (Jamnagar) owned by?': 'ഇന്ത്യയിലെ ഏറ്റവും വലിയ റിഫൈനറി (ജാംനഗർ) ഉടമസ്ഥൻ?',
    'Last': 'അവസാനം',
    'Left Democratic Front': 'ഇടത് ജനാധിപത്യ മുന്നണി',
    'Letter/syllable unit': 'അക്ഷര/അക്ഷര യൂണിറ്റ്',
    'Liberation': 'മോക്ഷം',
    'Life': 'ജീവിതകാലം',
    'Life Mission/LIFE': 'ലൈഫ് മിഷൻ/LIFE',
    'Lignite mining/power': 'ലിഗ്നൈറ്റ് ഖനനം/വിദ്യുത്',
    'Lion': 'സിംഹം',
    'Little Master': 'ലിറ്റിൽ മാസ്റ്റർ',
    'Local panchayat': 'പഞ്ചായത്ത്',
    'London': 'ലണ്ടൻ',
    'London tube': 'ലണ്ടൻ ട്യൂബ്',
    'Long Jump': 'നീണ്ട ചാട്ടം',
    'Long jump/Athletics': 'നീണ്ട ചാട്ടം/ട്രാക്ക്-ഫീൽഡ്',
    'Longest river in India (within India length)?': 'ഇന്ത്യയിലെ ഏറ്റവും നീണ്ട നദി?',
    'Longest river in Kerala?': 'കേരളത്തിലെ ഏറ്റവും നീണ്ട നദി?',
    'Los Angeles': 'ലോസ് ആഞ്ചൽസ്',
    'MGNREGA-യിൽ guaranteed days of employment?': 'MGNREGA-യിൽ ഉറപ്പുനൽകിയ തൊഴിൽ ദിവസങ്ങൾ?',
    'MS Dhoni ICC trophies as captain (all formats)?': 'MS Dhoni captain-ന് ലഭിച്ച ICC trophies?',
    'MSME finance': 'എം.എസ്.എം.ഇ ധനസഹായം',
    'MT Vasudevan Nair famous novel?': 'എം.ടി വാസുദേവൻ നായരുടെ പ്രശസ്ത നോവൽ?',
    'Machine tools (legacy)': 'യന്ത്ര ഉപകരണങ്ങൾ (പാരമ്പര്യം)',
    'Madhya Pradesh': 'മധ്യപ്രദേശ്',
    'Madrid': 'മാഡ്രിഡ്',
    'Mahabharata author traditionally?': 'മഹാഭാരതത്തിന്റെ പാരമ്പര്യ രചയിതാവ്?',
    'Mahanadi': 'മഹാനദി',
    'Maharashtra': 'മഹാരാഷ്ട്ര',
    'Major Dhyan Chand Khel Ratna': 'മേജർ ധ്യാൻ ചന്ദ് ഖേൽ രത്ന',
    'Make in India logo animal?': 'മേക്ക് ഇൻ ഇന്ത്യ ലോഗോയിലെ മൃഗം?',
    'Malappuram': 'മലപ്പുറം',
    'Malayalam and Sanskrit': 'മലയാളവും സംസ്കൃതവും',
    'Malayalam belongs to which language family?': 'മലയാളം ഏത് ഭാഷാ കുടുംബത്തിലാണ് പെടുന്നത്?',
    'Malayalam-English mix colloquial': 'മലയാളം-ഇംഗ്ലീഷ് മിശ്രിത സംഭാഷണം',
    'Male': 'മാലെ',
    'Mangalyaan (Mars Orbiter Mission) launch year?': 'മംഗളയാൻ (Mars Orbiter Mission) വിക്ഷേപണ വർഷം?',
    'Manglish refers to?': 'മാങ്ലിഷ് സൂചിപ്പിക്കുന്നത്?',
    'Manipravalam combines?': 'മണിപ്രവാളം സംയോജിപ്പിക്കുന്നത്?',
    'Mars mission': 'ചൊവ്വ ദൗത്യം',
    'Maruti Suzuki manufacturing primarily in?': 'മാരുതി സുസുക്കി നിർമ്മാണം പ്രധാനമായും എവിടെ?',
    'Materialism': 'ഭൗതികവാദം',
    'Maternity benefit scheme': 'മാതൃത്വ നേട്ട പദ്ധതി',
    'Maximum players in football team on field?': 'Football team on field players?',
    'Medical treatment assistance': 'ചികിത്സാ സഹായം',
    'Meesapulimala': 'മീസപ്പുലിമല',
    'Mexico City': 'മെക്സിക്കോ സിറ്റി',
    'Micro food enterprises': 'സൂക്ഷ്മ ഭക്ഷ്യ സംരംഭങ്ങൾ',
    'Mid-Day Meal scheme national launch year?': 'മിഡ്-ഡേ മീൽ പദ്ധതി ദേശീയ ആരംഭ വർഷം?',
    'Middle East/Asia': 'മദ്ധ്യേഷ്യ/ഏഷ്യ',
    'Milkha Singh nickname?': 'Milkha Singh-ന്റെ വിളിപ്പേര്?',
    'Minimum age to become MLA in Kerala?': 'കേരളത്തിൽ MLA ആകാനുള്ള കുറഞ്ഞ പ്രായം?',
    'Mobile manufacturing': 'മൊബൈൽ നിർമ്മാണം',
    'Moksha in Indian philosophy means?': 'മോക്ഷത്തിന്റെ അർത്ഥം?',
    'Monism': 'ഏകത്വവാദം',
    'Monsoon cropping season': 'മഴക്കാല വിള തയ്യാറെടുപ്പ്',
    'Moon': 'ചന്ദ്രൻ',
    'Mumbai': 'മുംബൈ',
    'Mumbai Indians': 'മുംബൈ ഇന്ത്യൻസ്',
    'Muthanga': 'മുത്തങ്ങ',
    'NDA in Kerala includes?': 'കേരളത്തിലെ NDA-യിൽ ഉൾപ്പെടുന്നവർ?',
    'NRHM and NUHM': 'NRHM-ഉം NUHM-ഉം',
    'Naalukettu': 'നാലുകെട്ട്',
    'Narmada': 'നർമ്മദ',
    'National Aluminium Company (NALCO) HQ?': 'NALCO ആസ്ഥാനം?',
    'National Games 2025 host state (scheduled)?': '2025 National Games host state?',
    'National Green Tribunal cases often on?': 'National Green Tribunal-ന്റെ കേസുകൾ പ്രധാനമായും എന്തിനെ സംബന്ധിച്ച്?',
    'National Health Mission subsumed which missions?': 'നാഷണൽ ഹെൽത്ത് മിഷൻ ഏത് മിഷനുകൾ ഉൾക്കൊണ്ടു?',
    'Natural gas': 'പ്രകൃതി വാതകം',
    'Navigation satellite': 'നാവിഗേഷൻ ഉപഗ്രഹം',
    'Neeraj Chopra Olympic gold event?': 'നീരജ് ചോപ്രയുടെ ഒളിമ്പിക് സ്വർണ്ണ മത്സര ഇനം?',
    'Neeraj Chopra Olympic gold year?': 'നീരജ് ചോപ്രയുടെ ഒളിമ്പിക് സ്വർണ്ണം ലഭിച്ച വർഷം?',
    'New Delhi': 'ന്യൂഡൽഹി',
    'New Development Bank (BRICS bank) HQ?': 'ന്യൂ ഡെവലപ്മെന്റ് ബാങ്ക് ആസ്ഥാനം?',
    'New Parliament building inaugurated in?': 'പുതിയ പാർലമെന്റ് കെട്ടിടം ഉദ്ഘാടനം ചെയ്ത വർഷം?',
    'New Zealand': 'ന്യൂസിലൻഡ്',
    'Nihilism': 'ശൂന്യവാദം',
    'Non-duality': 'അദ്വൈതം',
    'None': 'ഒന്നുമില്ല',
    'North-East development': 'വടക്കുകിഴക്കൻ വികസനം',
    'Not in list': 'പട്ടികയിൽ ഇല്ല',
    'Noun/subject word': 'നാമം/വിഷയ പദം',
    'OV Vijayan famous novel?': 'ഒ.വി വിജയന്റെ പ്രശസ്ത നോവൽ?',
    'Oil and gas exploration': 'എണ്ണ-ഗ്യാസ് പര്യവേക്ഷണം',
    'Oil refining/marketing': 'എണ്ണ ശുദ്ധീകരണം/വിപണനം',
    'Oilseeds': 'എണ്ണയിട വിത്തുകൾ',
    'Old age, widow, disability pensions': 'വാർദ്ധക്യ, വിധവ, വികലാംഗ പെൻഷനുകൾ',
    'Olympic flame tradition started in?': 'Olympic flame tradition ആരംഭിച്ചത്?',
    "Olympic motto 'Citius, Altius, Fortius' means?": "ഒളിമ്പിക് മുദ്രാവാക്യം 'Citius, Altius, Fortius'-ന്റെ അർത്ഥം?",
    'Olympic rings colours count?': 'Olympic rings count?',
    'One Nation One Ration Card launched in?': 'വൺ നേഷൻ വൺ റേഷൻ കാർഡ് ആരംഭിച്ച വർഷം?',
    'One Nation One Ration Card under which ministry?': 'വൺ നേഷൻ വൺ റേഷൻ കാർഡ് ഏത് മന്ത്രിത്വത്തിന് കീഴിൽ?',
    'One caste, one religion, one god for man': 'ഒരു ജാതി, ഒരു മതം, മനുഷ്യന് ഒരു ദൈവം',
    'One year': 'ഒരു വർഷം',
    'Only NRHM': 'NRHM മാത്രം',
    'Only NUHM': 'NUHM മാത്രം',
    'Only ODI': 'ODI മാത്രം',
    'Only T20': 'T20 മാത്രം',
    'Only Test': 'ടെസ്റ്റ് മാത്രം',
    'Only chess abroad': 'വിദേശത്ത് ചെസ് മാത്രം',
    'Only golf': 'ഗോൽഫ് മാത്രം',
    'Only grammar': 'വ്യാകരണം മാത്രം',
    'Only politics': 'രാജ്യം മാത്രം',
    'Only rituals': 'ചടങ്ങുകൾ മാത്രം',
    'Only weapons': 'ആയുധങ്ങൾ മാത്രം',
    'Operation Blue Star year?': 'ഓപ്പറേഷൻ ബ്ലൂ സ്റ്റാർ വർഷം?',
    'Orphaned children education support': 'അനാഥ കുട്ടികളുടെ വിദ്യാഭ്യാസ പിന്തുണ',
    'Oscars': 'ഓസ്കാർ അവാർഡുകൾ',
    'Ottawa': 'ഒട്ടാവ',
    'Outstanding sportspersons': 'മികച്ച കായിക താരങ്ങൾ',
    'PM Awas Yojana-Urban target year originally?': 'PM ആവാസ് യോജന-നഗര ലക്ഷ്യ വർഷം (യഥാർത്ഥത്തിൽ)?',
    'PM Daksh Yojana for?': 'PM ദക്ഷ് യോജന എന്തിനാണ്?',
    'PM DevINE for?': 'PM DevINE എന്തിനാണ്?',
    'PM Fasal Bima Yojana launched?': 'PM ഫസൽ ബീമാ യോജന ആരംഭിച്ച വർഷം?',
    'PM Garib Kalyan Anna Yojana provides?': 'PM ഗരീബ് കല്യാൺ അന്ന യോജന നൽകുന്നത്?',
    'PM Gati Shakti launched in?': 'PM ഗതി ശക്തി ആരംഭിച്ച വർഷം?',
    'PM Gati Shakti master plan related to?': 'PM ഗതി ശക്തി മാസ്റ്റർ പ്ലാൻ എന്തുമായി ബന്ധപ്പെട്ടത്?',
    'PM Matru Vandana Yojana is?': 'PM മാതൃ വന്ദന യോജന എന്താണ്?',
    'PM POSHAN Shakti Nirman related to?': 'PM പോഷൺ ശക്തി നിർമ്മാണം എന്തുമായി ബന്ധപ്പെട്ടത്?',
    'PM SHRI schools scheme for?': 'PM ശ്രീ സ്കൂൾ പദ്ധതി എന്തിനാണ്?',
    'PM eVIDYA for?': 'PM ഇ-വിദ്യ എന്തിനാണ്?',
    'PM-KISAN-ൽ annual benefit per farmer?': 'PM-KISAN-ൽ കർഷകന് വാർഷിക നേട്ടം?',
    'PM-KMY (Kisan Maan Dhan) for?': 'PM-KMY (കിസാൻ മാൻ ധൻ) എന്തിനാണ്?',
    'POSHAN Abhiyaan target to reduce?': 'പോഷൺ അഭിയാൻ ലക്ഷ്യം കുറയ്ക്കേണ്ടത്?',
    'PT Usha is associated with?': 'P.T. Usha ഏത് മേഖലയുമായി ബന്ധപ്പെട്ടിരിക്കുന്നു?',
    'PWD and coastal authority': 'PWDയും തീരദേശ അധികൃതരും',
    'Pacha Malayalam means?': 'പച്ച മലയാളത്തിന്റെ അർത്ഥം?',
    'Palakkad': 'പാലക്കാട്',
    'Pamba': 'പമ്പ',
    'Paris': 'പാരീസ്',
    'Paris Climate Agreement stocktake cycle continue ചെയ്യുന്ന UN body?': 'പാരീസ് കാലാവസ്ഥാ ഉടമ്പടിയുടെ ആഗോള വിലയിരുത്തൽ തുടരുന്ന UN സംഘടന ഏത്?',
    'Parrot song/narrative verse': 'തത്തയുടെ പാട്ട്/ആഖ്യാന കവിത',
    'Peaceful nuclear use': 'സമാധാനപരമായ അണുവിദ്യു ഉപയോഗം',
    'Peacock': 'മയിൽ',
    'Pension for small farmers': 'ചെറുകിട കർഷകർക്ക് പെൻഷൻ',
    'Periyar': 'പെരിയാർ',
    'Pharma cluster Hyderabad nicknamed?': 'ഹൈദരാബാദ് ഫാർമ ക്ലസ്റ്ററിന്റെ വിളിപ്പേര്?',
    "Pharma sector 'Pharmacy of the World' refers to?": "'ലോകത്തിന്റെ ഫാർമസി' എന്ന് ഏത് രാജ്യത്തെ സൂചിപ്പിക്കുന്നു?",
    'Pink City': 'പിങ്ക് നഗരം',
    'Planning Commission replaced by NITI Aayog on?': 'പ്ലാനിംഗ് കമ്മീഷൻ NITI ആയോഗ് പകരംവെച്ച തീയതി?',
    'Plastic only': 'പ്ലാസ്റ്റിക് മാത്രം',
    'Play Fair': 'നീതിയുപയോഗിച്ച് കളിക്കുക',
    'Players': 'കളിക്കാർ',
    'Pluralism': 'ബഹുത്വവാദം',
    'Pokhran-II nuclear tests year?': 'പോഖ്രാൻ-II ആണവ പരീക്ഷണ വർഷം?',
    'Police only': 'പോലീസ് മാത്രം',
    'Poorest families': 'ഏറ്റവും ദരിദ്ര കുടുംബങ്ങൾ',
    'Port authority': 'തുറമുഖ അധികൃതർ',
    'Power': 'ശക്തി',
    'Power equipment': 'വിദ്യുത് ഉപകരണങ്ങൾ',
    'Power generation': 'വിദ്യുത് ഉൽപ്പാദനം',
    'Power plant equipment': 'വിദ്യുത് നിലയ ഉപകരണങ്ങൾ',
    'Prathipadam means?': 'പ്രതിപദത്തിന്റെ അർത്ഥം?',
    'Private schools only': 'സ്വകാര്യ സ്കൂളുകൾ മാത്രം',
    'Production Linked Incentive (PLI) scheme announced in?': 'പ്രൊഡക്ഷൻ ലിങ്ക്ഡ് ഇൻസെന്റിവ് (PLI) പദ്ധതി പ്രഖ്യാപിച്ച വർഷം?',
    'Punjab': 'പഞ്ചാബ്',
    'Pure/clean Malayalam usage': 'ശുദ്ധ മലയാള ഉപയോഗം',
    'PwD welfare': 'വികലാംഗ ക്ഷേമം',
    'Qatar': 'ഖത്തർ',
    'Rajasthan': 'രാജസ്ഥാൻ',
    'Rajiv Gandhi Khel Ratna renamed as?': 'Rajiv Gandhi Khel Ratna-യുടെ പുതിയ പേര്?',
    'Rajiv Gandhi assassination year?': 'രാജീവ് ഗാന്ധി വധിച്ച വർഷം?',
    'Ramayana author traditionally?': 'രാമായണത്തിന്റെ പാരമ്പര്യ രചയിതാവ്?',
    'Ranji Trophy is associated with?': 'Ranji Trophy?',
    'Rationalism emphasizes?': 'യുക്തിവാദം എന്തിനെ ഊന്നിപ്പറയുന്നു?',
    'Reason as primary knowledge source': 'യുക്തി പ്രാഥമിക അറിവിന്റെ ഉറവിടം',
    'Red Cross (ICRC) headquarters?': 'റെഡ് ക്രോസ് (ICRC) ആസ്ഥാനം?',
    'Reliance': 'റിലയൻസ്',
    'Ricky Ponting': 'റിക്കി പോണ്ടിംഗ്',
    'Right to Education Act enacted in?': 'വിദ്യാഭ്യാസ അവകാശ നിയമം പ്രാബല്യത്തിൽ വന്ന വർഷം?',
    'Right to Information Act enacted in?': 'വിവരാവകാശ നിയമം പ്രാബല്യത്തിൽ വന്ന വർഷം?',
    'Roads': 'റോഡുകൾ',
    'Rome': 'റോം',
    'Rubber': 'റബ്ബർ',
    'Rubber Board HQ?': 'റബ്ബർ ബോർഡ് ആസ്ഥാനം?',
    'Rural industries': 'ഗ്രാമീണ വ്യവസായങ്ങൾ',
    'Rural property ownership records': 'ഗ്രാമീണ സ്വത്ത് ഉടമസ്ഥത രേഖകൾ',
    'Russia': 'റഷ്യ',
    'SAARC members count?': 'SAARC അംഗങ്ങളുടെ എണ്ണം?',
    'SC/ST and women entrepreneurs': 'എസ്.സി/എസ്.ടി, സ്ത്രീ സംരംഭകർ',
    'Sachin Tendulkar': 'സച്ചിൻ ടെൻഡുൽക്കർ',
    'Sand': 'മണൽ',
    'Santosh Trophy is associated with?': 'Santosh Trophy?',
    'Sardar Sarovar dam on river?': 'സർദാർ സരോവർ അണക്കെട്ട് ഏത് നദിയിൽ?',
    'School PTA': 'സ്കൂൾ PTA',
    'Scientists': 'ശാസ്ത്രജ്ഞർ',
    'Shakespeare wrote?': 'ഷേക്സ്പിയർ എഴുതിയത്?',
    'Shimla Agreement signed after?': 'ഷിംലാ ഉടമ്പടി ഏത് യുദ്ധത്തിന് ശേഷം?',
    'Shipbuilding major PSU?': 'കപ്പൽ നിർമ്മാണ പ്രധാന പൊതുമേഖലാ സ്ഥാപനം?',
    'Shipping': 'കപ്പൽ കയറ്റുമതി',
    'Shot Put': 'ഷോട്ട് പുട്ട്',
    'Siachen conflict began in?': 'സിയാച്ചി സംഘർഷം ആരംഭിച്ച വർഷം?',
    'Sikhism only': 'സിഖ് മതം മാത്രം',
    'Silicon Valley of India': 'ഇന്ത്യയുടെ സിലിക്കൺ വാലി',
    'Silver': 'വെള്ളി',
    'Skill development of youth': 'യുവാക്കളുടെ കഴിവ് വികസനം',
    'Small Industries Development Bank of India (SIDBI) for?': 'SIDBI എന്തിനാണ്?',
    'Social equality': 'സാമൂഹിക സമത്വം',
    'Socratic method is?': 'സോക്രട്ടിക് രീതി എന്താണ്?',
    'Soil Health Card scheme launched?': 'മണ്ണിന്റെ ആരോഗ്യ കാർഡ് പദ്ധതി ആരംഭിച്ച വർഷം?',
    'South Africa': 'ദക്ഷിണാഫ്രിക്ക',
    'Space': 'ബഹിരാകാശം',
    'Space launch': 'ബഹിരാകാശ ദൗത്യം',
    'Special metals/alloys': 'പ്രത്യേക ലോഹങ്ങൾ/ലേഹകങ്ങൾ',
    'Spices Board HQ?': 'സ്പൈസസ് ബോർഡ് ആസ്ഥാനം?',
    'Sri Narayana Guru Kerala philosophy emphasized?': 'ശ്രീ നാരായണ ഗുരു എന്ത് ഊന്നിപ്പറഞ്ഞു?',
    'Stand Up India for?': 'സ്റ്റാൻഡ് അപ്പ് ഇന്ത്യ എന്തിനാണ്?',
    'Stand Up India launched in?': 'സ്റ്റാൻഡ് അപ്പ് ഇന്ത്യ ആരംഭിച്ച വർഷം?',
    'Steel': 'ഉരുക്ക്',
    'Steel Authority of India headquarters?': 'സ്റ്റീൽ അതോറിറ്റി ഓഫ് ഇന്ത്യ ആസ്ഥാനം?',
    'Steel City': 'സ്റ്റീൽ നഗരം',
    'Street vendors': 'തെരുവ് വ്യാപാരികൾ',
    'Stunting and malnutrition': 'കುണ്ടിവളർച്ചയും പോഷകാഹാര കുറവും',
    'Sun mission': 'സൂര്യ ദൗത്യം',
    'Sunrisers Hyderabad': 'സൺറൈസേഴ്സ് ഹൈദരാബാദ്',
    'Supplementary nutrition, immunization': 'പൂരക പോഷകാഹാരം, പ്രതിരോധ കുത്തിവയ്പ്പ്',
    'Sustainable tourism': 'പരിസ്ഥിതി സൗഹൃദ ടൂറിസം',
    'Sutlej': 'സത്ലജ്',
    'Swimming': 'നീന്തൽ',
    'Synthetic': 'സിന്തറ്റിക്',
    'Table Tennis': 'ടേബിൾ ടെന്നീസ്',
    'Tashkent Agreement after?': 'താഷ്കന്റ് ഉടമ്പടി ഏത് യുദ്ധത്തിന് ശേഷം?',
    'Tata Steel major plant at?': 'ടാറ്റാ സ്റ്റീൽ പ്രധാന പ്ലാന്റ് എവിടെ?',
    'Tea Board HQ?': 'ടീ ബോർഡ് ആസ്ഥാനം?',
    'Tehri dam on river?': 'തെഹ്രി അണക്കെട്ട് ഏത് നദിയിൽ?',
    'Ten years': 'പത്ത് വർഷം',
    'Tennis': 'ടെന്നീസ്',
    'Thakazhi Sivasankara Pillai famous novel?': 'തകഴി ശിവശങ്കര പിള്ളയുടെ പ്രശസ്ത നോവൽ?',
    'Thimphu': 'തിംഫു',
    'Thiruvananthapuram': 'തിരുവനന്തപുരം',
    'Thomas Cup is associated with?': 'Thomas Cup?',
    'Thrissur': 'തൃശ്ശൂർ',
    'Thunchath Ezhuthachan title?': 'തുഞ്ചത്ത് എഴുത്തച്ഛന്റെ ബിരുദം?',
    'Tiger': 'പുലി',
    'Tokyo': 'ടോക്കിയോ',
    'Top 4': 'മുൻനിരയിലെ 4-ാം',
    'Traditional artisans/craftspeople': 'പരമ്പരാഗത കരകുശലികൾ',
    'Trafficking victims rehabilitation': 'കടത്തുകാരുടെ പീഡന ഇരകളുടെ പുനर्वാസം',
    'UDAN regional connectivity scheme launched in?': 'UDAN പ്രാദേശിക കണക്റ്റിവിറ്റി പദ്ധതി ആരംഭിച്ച വർഷം?',
    'UDF acronym stands for?': 'UDF എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം?',
    'UN General Assembly President elected for?': 'UN പൊതുസഭാ അധ്യക്ഷൻ തിരഞ്ഞെടുക്കുന്ന കാലാവധി?',
    'UN Security Council permanent members count?': 'UN സുരക്ഷാ കൗൺസിലിലെ സ്ഥിരം അംഗങ്ങളുടെ എണ്ണം?',
    'US Open surface type (main)?': 'US Open surface?',
    'Umpires': 'അംപയർമാർ',
    'United Democratic Front': 'യുണൈറ്റഡ് ഡെമോക്രാറ്റിക് ഫ്രണ്ട്',
    'Unity, Faith, Discipline': 'ഐക്യം, വിശ്വാസം, അച്ചടക്കം',
    'Upgrading schools to exemplary status': 'സ്കൂളുകൾ മാതൃകാ സ്ഥിതിയിലേക്ക് ഉയർത്തൽ',
    'Uttar Pradesh': 'ഉത്തരപ്രദേശ്',
    'Uttarakhand': 'ഉത്തരാഖണ്ഡ്',
    'Vasco da Gama': 'വാസ്കോ ഡ ഗാമ',
    'Verb': 'ക്രിയ',
    'Vimochana Samaram (1959) resulted in?': 'വിമോചന സമരം (1959) ഫലമായി എന്ത് സംഭവിച്ചു?',
    'Virat Kohli': 'വിരാട് കോഹ്ലി',
    'Visakhapatnam': 'വിശാഖപട്ടണം',
    'Visheshanam means?': 'വിശേഷണത്തിന്റെ അർത്ഥം?',
    'Volleyball': 'വോളിബോൾ',
    'War and Peace author?': 'വാർ ആൻഡ് പീസ് രചയിതാവ്?',
    'Waste management': 'മാലിന്യ നിയന്ത്രണം',
    'Water conservation': 'ജല സംരക്ഷണം',
    'Wealth': 'സമ്പത്ത്',
    'Weight of cricket ball (approx)?': 'Cricket ball weight?',
    'Weightlifting': 'ഭാരോദ്വഹനം',
    'Wellington': 'വെല്ലിംഗ്ടൺ',
    'West Bengal': 'പശ്ചിമബംഗാൾ',
    'Wheat': 'ഗോതമ്പ്',
    'White Revolution associated with?': 'വെള്ളവിപ്ലവം ആരുമായി ബന്ധപ്പെട്ടത്?',
    'Wimbledon': 'വിംബിൾഡൺ',
    'Wimbledon is played on which surface?': 'Wimbledon ഏത് surface-il?',
    'Winter sports': 'ശീതകാല കായികം',
    'Women affected by violence': 'അതിക്രമത്തിന് ഇരയായ സ്ത്രീകൾ',
    'Women workplace harassment complaints': 'സ്ത്രീകളുടെ ജോലിസ്ഥല പീഡന പരാതികൾ',
    'Wood': 'മരം',
    "Working women's children": 'ജോലി ചെയ്യുന്ന സ്ത്രീകളുടെ കുട്ടികൾ',
    'World Trade Organization replaced?': 'വേൾഡ് ട്രേഡ് ഓർഗനൈസേഷൻ പകരംവെച്ചത്?',
    'Wrestling': 'മല്ലയുദ്ധം',
    'Writers': 'എഴുത്തുകാർ',
    'Youth Olympics എന്താണ്?': 'യുവ ഒളിമ്പിക്സ് എന്താണ്?',
    'cases': 'കേസുകൾ',
    'coverage expansion': 'പരിരക്ഷാ വിപുലീകരണം',
    'global rank': 'ആഗോള റാങ്ക്',
    'global stocktake': 'ആഗോള സ്റ്റോക്ക് ടേക്ക്',
    'initiative': 'സംരംഭം',
    'internet connectivity': 'ഇന്റർനെറ്റ് കണക്റ്റിവിറ്റി',
    'schedule': 'ഷെഡ്യൂൾ',
    'എല്ലാവർക്കും internet connectivity': 'എല്ലാവർക്കും ഇന്റർനെറ്റ് കണക്റ്റിവിറ്റി',
    'ഏറ്റവും കൂടുതൽ ODI runs scorer?': 'ഏറ്റവും കൂടുതൽ ODI റൺസ് നേടിയ താരം?',
    'ഏറ്റവും കൂടുതൽ ടെസ്റ്റ് സെഞ്ചuries scored Sachin Tendulkar?': 'ഏറ്റവും കൂടുതൽ ടെസ്റ്റ് സെഞ്ചuries നേടിയത് സച്ചിൻ ടെൻഡുൽക്കർ?',
    'നിരക്ക്/revision/compliance': 'നിരക്ക് പരിഷ്ക്കരണവും അനുസരണവും',
    'സinem പുരസ്കാരം': 'ചലച്ചിത്ര പുരസ്കാരം',
}
