#!/usr/bin/env python3
"""Wave 30 national schemes facts — 30 Malayalam PSC topic types."""

from __future__ import annotations

import random

from refill_common import Candidate
from wave30_emit import emit_category, emit_direct



LAUNCH_YEAR: list[tuple[str, str]] = [
    ("PM Jan Dhan Yojana", "2014"),
    ("PM Fasal Bima Yojana", "2016"),
    ("PM Awas Yojana (നഗരം)", "2015"),
    ("PM Awas Yojana (ഗ്രാമീണ്)", "2016"),
    ("PM Ujjwala Yojana", "2016"),
    ("PM-KISAN", "2019"),
    ("Ayushman Bharat PM-JAY", "2018"),
    ("Beti Bachao Beti Padhao", "2015"),
    ("MGNREGA", "2005"),
    ("Mission Indradhanush", "2014"),
    ("Digital India", "2015"),
    ("Skill India Mission", "2015"),
    ("Swachh Bharat Mission", "2014"),
    ("PM Mudra Yojana", "2015"),
    ("Stand-Up India", "2016"),
    ("DDUGJY", "2015"),
    ("Saubhagya", "2017"),
    ("Jal Jeevan Mission", "2019"),
    ("PM SVANidhi", "2020"),
    ("PM Matsya Sampada Yojana", "2020"),
    ("PM Vishwakarma", "2023"),
    ("PM Surya Ghar", "2024"),
    ("National Green Hydrogen Mission", "2023"),
    ("Smart Cities Mission", "2015"),
    ("UDAN", "2017"),
    ("PM-KUSUM", "2019"),
    ("POSHAN Abhiyaan", "2018"),
    ("AMRUT", "2015"),
    ("Atal Pension Yojana", "2015"),
    ("PM Jeevan Jyoti Bima Yojana", "2015"),
]

MINISTRY: list[tuple[str, str]] = [
    ("PM Jan Dhan Yojana", "ധനകാര്യ മന്ത്രാലയം"),
    ("PM Fasal Bima Yojana", "കൃഷി മന്ത്രാലയം"),
    ("PM Awas Yojana", "വാസസ്ഥല മന്ത്രാലയം"),
    ("Ayushman Bharat PM-JAY", "ആരോഗ്യ മന്ത്രാലയം"),
    ("MGNREGA", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("Jal Jeevan Mission", "ജല ശക്തി മന്ത്രാലയം"),
    ("PM Ujjwala Yojana", "പെട്രോളിയം & പ്രകൃതി വാതക മന്ത്രാലയം"),
    ("Skill India Mission", "കാജ് & ഉദ്യോഗ സൃഷ്ടി മന്ത്രാലയം"),
    ("Digital India", "ഇലക്ട്രോണിക്സ് & ഐ.ടി. മന്ത്രാലയം"),
    ("PM Mudra Yojana", "ധനകാര്യ മന്ത്രാലയം"),
    ("PM-KISAN", "കൃഷി മന്ത്രാലയം"),
    ("Swachh Bharat Mission", "ജല ശക്തി മന്ത്രാലയം"),
    ("PM SVANidhi", "വാസസ്ഥല മന്ത്രാലയം"),
    ("PM Matsya Sampada Yojana", "മത്സ്യബന്ധന മന്ത്രാലയം"),
    ("UDAN", "പൗരവ്യവഹാര മന്ത്രാലയം"),
    ("Smart Cities Mission", "വാസസ്ഥല മന്ത്രാലയം"),
    ("PM-KUSUM", "പുതുനവീകരണ ഊർജ മന്ത്രാലയം"),
    ("National Green Hydrogen Mission", "പുതുനവീകരണ ഊർജ മന്ത്രാലയം"),
    ("POSHAN Abhiyaan", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("Stand-Up India", "ധനകാര്യ മന്ത്രാലയം"),
    ("BharatNet", "ഇലക്ട്രോണിക്സ് & ഐ.ടി. മന്ത്രാലയം"),
    ("Mission Indradhanush", "ആരോഗ്യ മന്ത്രാലയം"),
    ("AMRUT", "വാസസ്ഥല മന്ത്രാലയം"),
    ("HRIDAY", "വാസസ്ഥല മന്ത്രാലയം"),
    ("PM Gati Shakti", "വാണിജ്യ & വ്യവസായ മന്ത്രാലയം"),
    ("PM SHRI", "വിദ്യാഭ്യാസ മന്ത്രാലയം"),
    ("PM eBus Sewa", "പൗരവ്യവഹാര മന്ത്രാലയം"),
    ("PM Vishwakarma", "കാജ് & ഉദ്യോഗ സൃഷ്ടി മന്ത്രാലയം"),
    ("PM Surya Ghar", "പുതുനവീകരണ ഊർജ മന്ത്രാലയം"),
    ("PM Internship Scheme", "കാജ് & ഉദ്യോഗ സൃഷ്ടി മന്ത്രാലയം"),
]

SECTOR: list[tuple[str, str]] = [
    ("PM Fasal Bima Yojana", "വിള ഇൻഷുറൻസ്"),
    ("PM Ujjwala Yojana", "എൽ.പി.ജി. വിതരണം"),
    ("Jal Jeevan Mission", "കുടിവെള്ള വിതരണം"),
    ("Saubhagya", "ഗൃഹവൈദ്യുതീകരണം"),
    ("Ayushman Bharat PM-JAY", "ആരോഗ്യ ഇൻഷുറൻസ്"),
    ("MGNREGA", "തൊഴിൽ ഗ്യാരന്റി"),
    ("PM Jan Dhan Yojana", "സാമ്പത്തിക ഉൾപ്പെടുത്തൽ"),
    ("PM Mudra Yojana", "ചെറുകിട വ്യവസായ വായ്പ"),
    ("PM Awas Yojana", "വീട് നിർമ്മാണം"),
    ("Skill India Mission", "കൗശല വികസനം"),
    ("Digital India", "ഡിജിറ്റൽ ഉൾപ്പെടുത്തൽ"),
    ("Swachh Bharat Mission", "ശുചിത്വം"),
    ("PM-KISAN", "കർഷക വരുമാന സഹായം"),
    ("Mission Indradhanush", "വാക്സിനേഷൻ"),
    ("UDAN", "വിമാനയാന സബ്സിഡി"),
    ("PM Matsya Sampada Yojana", "മത്സ്യബന്ധനം"),
    ("PM-KUSUM", "കാർഷിക സോളാർ ഊർജ"),
    ("POSHAN Abhiyaan", "പോഷകാഹാരം"),
    ("Stand-Up India", "സംരംഭകത്വം"),
    ("BharatNet", "ബ്രോഡ്ബാൻഡ് കണക്ടിവിറ്റി"),
    ("Smart Cities Mission", "നഗര വികസനം"),
    ("AMRUT", "നഗര അടിസ്ഥാന സൗകര്യം"),
    ("SVAMITVA", "ഗ്രാമീണ ഭൂമി രേഖ"),
    ("PM SVANidhi", "തെരുവ് വ്യാപാരി വായ്പ"),
    ("National Green Hydrogen Mission", "ഹരിത ഹൈഡ്രജൻ"),
    ("PM Surya Ghar", "ഗൃഹ സോളാർ"),
    ("PM Vishwakarma", "പാരമ്പര്യ കരകുശല"),
    ("PM Gati Shakti", "അടിസ്ഥാന സൗകര്യ ഏകീകരണം"),
    ("PM SHRI", "സ്കൂൾ നവീകരണം"),
    ("PM eBus Sewa", "ഇലക്ട്രിക് ബസ്"),
]

BENEFICIARY: list[tuple[str, str]] = [
    ("PM Jan Dhan Yojana", "ബാങ്ക് അക്കൗണ്ട് ഇല്ലാത്തവർ"),
    ("PM Fasal Bima Yojana", "കർഷകർ"),
    ("PM Ujjwala Yojana", "ബി.പി.എൽ. കുടുംബങ്ങൾ"),
    ("PM-KISAN", "ചെറുകിട/അതിർത്തി കർഷകർ"),
    ("Ayushman Bharat PM-JAY", "ദരിദ്ര/ഇടത്തരം കുടുംബങ്ങൾ"),
    ("MGNREGA", "ഗ്രാമീണ തൊഴിലാളികൾ"),
    ("PM Mudra Yojana", "ചെറുകിട/മൈക്രോ യൂണിറ്റുകൾ"),
    ("PM Awas Yojana", "ഭവനരഹിതർ"),
    ("Stand-Up India", "എസ്.സി./എസ്.ടി./വനിതാ സംരംഭകർ"),
    ("Atal Pension Yojana", "അൺഓർഗനൈസ്ഡ് തൊഴിലാളികൾ"),
    ("PM Jeevan Jyoti Bima Yojana", "18–50 വയസ്സുള്ളവർ"),
    ("PM Suraksha Bima Yojana", "18–70 വയസ്സുള്ളവർ"),
    ("Beti Bachao Beti Padhao", "പെൺകുട്ടികൾ"),
    ("Sukanya Samriddhi Yojana", "പെൺകുട്ടികൾ"),
    ("PM SVANidhi", "തെരുവ് വ്യാപാരികൾ"),
    ("PM Vishwakarma", "പാരമ്പര്യ കരകുശലർ"),
    ("PM Surya Ghar", "ഗൃഹസ്ഥർ"),
    ("PM-KUSUM", "കർഷകർ"),
    ("PM-KMY", "ചെറുകിട കർഷകർ"),
    ("SVAMITVA", "ഗ്രാമീണ ഭൂമി ഉടമകൾ"),
    ("PM FME", "മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ് യൂണിറ്റുകൾ"),
    ("PM Daksh", "യുവാക്കൾ"),
    ("PM eVIDYA", "വിദ്യാർത്ഥികൾ"),
    ("PM SHRI", "സ്കൂൾ വിദ്യാർത്ഥികൾ"),
    ("PM Janman", "പി.വി.ടി.ജി. സമുദായങ്ങൾ"),
    ("PM Internship Scheme", "യുവ തൊഴിൽ തേടുന്നവർ"),
    ("PM eBus Sewa", "നഗര യാത്രക്കാർ"),
    ("National Green Hydrogen Mission", "ഊർജ മേഖല"),
    ("Vibrant Villages Programme", "അതിർത്തി ഗ്രാമങ്ങൾ"),
    ("PM Garib Kalyan Anna Yojana", "ദരിദ്ര കുടുംബങ്ങൾ"),
]

FULL_FORM: list[tuple[str, str]] = [
    ("PM-JAY", "പ്രധാനമന്ത്രി ജന ആരോഗ്യ യോജന"),
    ("PM-KISAN", "പ്രധാനമന്ത്രി കിസാൻ സമ്മാൻ നിധി"),
    ("PMJDY", "പ്രധാനമന്ത്രി ജനധൻ യോജന"),
    ("PMSBY", "പ്രധാനമന്ത്രി സുരക്ഷാ ബീമാ യോജന"),
    ("PMJJBY", "പ്രധാനമന്ത്രി ജീവൻ ജ്യോതി ബീമാ യോജന"),
    ("PMFBY", "പ്രധാനമന്ത്രി ഫസൽ ബീമാ യോജന"),
    ("PMAY", "പ്രധാനമന്ത്രി ആവാസ് യോജന"),
    ("PMMY", "പ്രധാനമന്ത്രി മുദ്രാ യോജന"),
    ("DDUGJY", "ദീൻദയാൽ ഉപാധ്യായ ഗ്രാം ജ്യോതി യോജന"),
    ("PMGSY", "പ്രധാനമന്ത്രി ഗ്രാമീണ സഡക് യോജന"),
    ("PMUY", "പ്രധാനമന്ത്രി ഉജ്ജ്വല യോജന"),
    ("PM-KUSUM", "പ്രധാനമന്ത്രി കിസാൻ ഉർജാ സുരക്ഷാ യോജന"),
    ("PM-KMY", "പ്രധാനമന്ത്രി കിസാൻ മാൻ ധൻ യോജന"),
    ("PMMVY", "പ്രധാനമന്ത്രി മാതൃ വന്ദന യോജന"),
    ("PMJAY", "പ്രധാനമന്ത്രി ജന ആരോഗ്യ യോജന"),
    ("PM POSHAN", "പ്രധാനമന്ത്രി പോഷൺ അഭിയാൻ"),
    ("PM SVANidhi", "പ്രധാനമന്ത്രി തെരുവ് വ്യാപാരി ആത്മനിർഭർ നിധി"),
    ("PM FME", "പ്രധാനമന്ത്രി ഫോർമലൈസേഷൻ ഓഫ് മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ്"),
    ("PM SHRI", "പ്രധാനമന്ത്രി സ്കൂൾസ് ഫോർ റൈസിംഗ് ഇൻഫ്രാസ്ട്രക്ചർ"),
    ("PM Gati Shakti", "പ്രധാനമന്ത്രി ഗതി ശക്തി"),
    ("PM eVIDYA", "പ്രധാനമന്ത്രി ഇ-വിദ്യ"),
    ("PM WANI", "പ്രധാനമന്ത്രി വൈ-ഫൈ ആക്സസ് നെറ്റ്വർക്ക് ഇന്റർഫേസ്"),
    ("PM CARES", "പ്രധാനമന്ത്രി കെയേഴ്സ്"),
    ("PM Daksh", "പ്രധാനമന്ത്രി ദക്ഷ്"),
    ("PM DevINE", "പ്രധാനമന്ത്രി വികസിത് നോർത്ത് ഈസ്റ്റ് ഇൻവെസ്റ്റ്മെന്റ് പ്ലാൻ"),
    ("PM MITRA", "പ്രധാനമന്ത്രി ഇന്റഗ്രേറ്റഡ് ടെക്സ്റ്റൈൽ റീജിയൺ ആൻഡ് അപ്ലൈഡ്"),
    ("PM Surya Ghar", "പ്രധാനമന്ത്രി സൂര്യ ഘർ മുഫ്ത് ബിജ്ലി യോജന"),
    ("PM Janman", "പ്രധാനമന്ത്രി ജന്ജാതി ആദിവാസി ന്യായ മഹാഅഭിയാൻ"),
    ("PM Internship", "പ്രധാനമന്ത്രി ഇന്റേൺഷിപ്പ് സ്കീം"),
    ("PM eBus Sewa", "പ്രധാനമന്ത്രി ഇ-ബസ് സേവ"),
]

BUDGET: list[tuple[str, str]] = [
    ("PM-JAY", "₹5 ലക്ഷം/കുടുംബം/വർഷം"),
    ("PM-KISAN", "₹6000/വർഷം"),
    ("PM Ujjwala Yojana", "₹1600 സബ്സിഡി/സിലിണ്ടർ"),
    ("MGNREGA", "100 ദിവസം തൊഴിൽ"),
    ("PM Mudra Shishu", "₹50000 വരെ"),
    ("PMJJBY", "₹2 ലക്ഷം"),
    ("PMSBY", "₹2 ലക്ഷം"),
    ("PM Matsya Sampada", "₹20000 കോടി"),
    ("Jal Jeevan Mission", "₹3.6 ലക്ഷം കോടി"),
    ("PM SVANidhi", "₹10000 വരെ"),
    ("PM Vishwakarma", "₹3 ലക്ഷം വരെ"),
    ("PM Surya Ghar", "₹78000 സബ്സിഡി"),
    ("PM FME", "₹10 ലക്ഷം/യൂണിറ്റ്"),
    ("PM-KUSUM", "₹34400 കോടി"),
    ("National Infrastructure Pipeline", "₹111 ലക്ഷം കോടി"),
    ("PM Gati Shakti", "₹100 ലക്ഷം കോടി+"),
    ("PM SHRI", "₹27360 കോടി"),
    ("PM eBus Sewa", "₹5761 കോടി"),
    ("National Green Hydrogen Mission", "₹19744 കോടി"),
    ("PM Garib Kalyan Anna", "5 കിലോ അരി+1 കിലോ ഗോതമ്പ്"),
    ("PMMVY", "₹5000"),
    ("Stand-Up India", "₹10 ലക്ഷം–1 കോടി"),
    ("PM Daksh", "₹500/ദിവസം സ്റ്റൈപ്പൻഡ്"),
    ("PM Internship", "₹5000/മാസം"),
    ("PM Janman", "₹24100 കോടി"),
    ("Vibrant Villages", "₹4800 കോടി"),
    ("Atal Pension Yojana", "₹1000–5000/മാസം പെൻഷൻ"),
    ("Sukanya Samriddhi", "₹250/വർഷം മുതൽ"),
    ("PM MITRA", "₹4200 കോടി പ്ലാൻഡ്"),
    ("PM DevINE", "₹7400 കോടി"),
]

DBT: list[tuple[str, str]] = [
    ("PM-KISAN", "നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്"),
    ("PM Ujjwala", "നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്"),
    ("PMMVY", "നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്"),
    ("PM Jan Dhan", "ബാങ്ക് അക്കൗണ്ട് വഴി"),
    ("PM Fasal Bima", "ബാങ്ക്/ഓൺലൈൻ"),
    ("PM Awas", "ബാങ്ക് അക്കൗണ്ട് വഴി"),
    ("PM SVANidhi", "ഡിജിറ്റൽ പേമെന്റ്"),
    ("PM Vishwakarma", "ബാങ്ക് വഴി"),
    ("PM Surya Ghar", "സബ്സിഡി ഡിജിറ്റൽ ട്രാൻസ്ഫർ"),
    ("PM Garib Kalyan Anna", "റേഷൻ കാർഡ്/ഓൺഓആർസി"),
    ("PMJJBY", "ഓട്ടോ-ഡെബിറ്റ്"),
    ("PMSBY", "ഓട്ടോ-ഡെബിറ്റ്"),
    ("Atal Pension", "ബാങ്ക് അക്കൗണ്ട്"),
    ("PM-KMY", "പെൻഷൻ ഫണ്ട് വഴി"),
    ("One Nation One Ration Card", "ഓൺഓആർസി/പോർട്ടബിൾ റേഷൻ"),
    ("PM Daksh", "സർക്കാർ അക്കൗണ്ട്"),
    ("PM Internship", "ഇപിഎഫ്ഒ/ബാങ്ക്"),
    ("PM FME", "ബാങ്ക് വായ്പ+സബ്സിഡി"),
    ("PM MITRA", "പ്ലാൻഡ് ലിങ്ക് ഇൻസെന്റിവ്"),
    ("PM DevINE", "കേന്ദ്ര അനുവദനം"),
    ("PM SHRI", "സംസ്ഥാന-കേന്ദ്ര ഫണ്ട്"),
    ("PM eBus Sewa", "വിഎഗ്എഫ്/സബ്സിഡി"),
    ("National Green Hydrogen", "പ്ലാൻഡ് ലിങ്ക്"),
    ("PM Janman", "കേന്ദ്ര-സംസ്ഥാന ഫണ്ട്"),
    ("Vibrant Villages", "കേന്ദ്ര ഫണ്ട്"),
    ("PM WANI", "പി.പി.പി. മോഡൽ"),
    ("PM eVIDYA", "ഓൺലൈൻ പ്ലാറ്റ്ഫോം"),
    ("ABDM", "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി"),
    ("PM CARES", "ഓൺലൈൻ ദാനം"),
    ("PM Gati Shakti", "ഡിജിറ്റൽ പ്ലാറ്റ്ഫോം"),
    ("PM POSHAN", "ആംഗൻവാടി/സ്കൂൾ വഴി"),
]

PARENT_MISSION: list[tuple[str, str]] = [
    ("PMJJBY", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("PMSBY", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("Atal Pension", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("PM Awas Gramin", "PMAY"),
    ("PM Awas Urban", "PMAY"),
    ("PM-JAY", "Ayushman Bharat"),
    ("PM eVIDYA", "Digital India"),
    ("PM WANI", "Digital India"),
    ("ABDM", "Ayushman Bharat Digital Mission"),
    ("PM SHRI", "NEP 2020"),
    ("PM Gati Shakti", "National Infrastructure Pipeline"),
    ("PM MITRA", "Make in India"),
    ("PM FME", "Aatmanirbhar Bharat"),
    ("PM SVANidhi", "Aatmanirbhar Bharat"),
    ("PM Vishwakarma", "Aatmanirbhar Bharat"),
    ("PM Surya Ghar", "National Solar Mission"),
    ("PM-KUSUM", "National Solar Mission"),
    ("POSHAN", "National Nutrition Mission"),
    ("Mission Indradhanush", "Universal Immunization Programme"),
    ("UDAN", "Regional Connectivity Scheme"),
    ("AMRUT", "Smart Cities Mission"),
    ("HRIDAY", "Smart Cities Mission"),
    ("PM Daksh", "Skill India"),
    ("PM eBus Sewa", "FAME India"),
    ("National Green Hydrogen", "National Hydrogen Mission"),
    ("PM Janman", "PM JANMAN"),
    ("Vibrant Villages", "Border Area Development"),
    ("PM Internship", "Skill India"),
    ("PM DevINE", "North-East Special Package"),
    ("PM Garib Kalyan Anna", "PM Garib Kalyan Package"),
]

STATE_FIRST: list[tuple[str, str]] = [
    ("PM Jan Dhan", "മധ്യപ്രദേശ്"),
    ("PM Ujjwala", "ഉത്തർപ്രദേശ്"),
    ("PM Fasal Bima", "കർണാടക"),
    ("Ayushman Bharat", "ഛത്തീസ്ഗഢ്"),
    ("Jal Jeevan Mission", "മണിപ്പൂർ"),
    ("PM-KISAN", "ഉത്തർപ്രദേശ്"),
    ("One Nation One Ration Card", "ആന്ധ്രാപ്രദേശ്"),
    ("PM SVANidhi", "മധ്യപ്രദേശ്"),
    ("PM Vishwakarma", "ഉത്തർപ്രദേശ്"),
    ("PM Surya Ghar", "ഉത്തർപ്രദേശ്"),
    ("Smart Cities Mission", "ഭുവനേശ്വർ"),
    ("UDAN", "ഷില്ലോം"),
    ("MGNREGA", "ആന്ധ്രാപ്രദേശ്"),
    ("Mission Indradhanush", "രാജസ്ഥാൻ"),
    ("Digital India", "കർണാടക"),
    ("Skill India", "രാജസ്ഥാൻ"),
    ("Swachh Bharat", "റായ്ബറേലി"),
    ("PM Mudra", "ഉത്തർപ്രദേശ്"),
    ("Stand-Up India", "മഹാരാഷ്ട്ര"),
    ("PM SHRI", "തമിഴ്നാട്"),
    ("PM Gati Shakti", "ഉത്തർപ്രദേശ്"),
    ("PM eBus Sewa", "കേരളം"),
    ("National Green Hydrogen", "ഗുജറാത്ത്"),
    ("PM Janman", "ഒഡിഷ"),
    ("Vibrant Villages", "അരുണാചൽ പ്രദേശ്"),
    ("PM Internship", "മഹാരാഷ്ട്ര"),
    ("PM DevINE", "അസം"),
    ("PM MITRA", "തമിഴ്നാട്"),
    ("SVAMITVA", "ഉത്തരാഖണ്ഡ്"),
    ("PM FME", "ഉത്തർപ്രദേശ്"),
]

LEGAL_BASIS: list[tuple[str, str]] = [
    ("MGNREGA", "MGNREGA നിയമം 2005"),
    ("National Food Security Act", "2013 നിയമം"),
    ("PM-JAY", "Ayushman Bharat Mission"),
    ("PM Awas", "PMAY മിഷൻ"),
    ("PM Fasal Bima", "PMFBY മാർഗനിർദ്ദേശം"),
    ("PM Jan Dhan", "PMJDY മിഷൻ"),
    ("PM Ujjwala", "PMUY മിഷൻ"),
    ("PM-KISAN", "PM-KISAN മിഷൻ"),
    ("Right to Education", "RTE നിയമം 2009"),
    ("National Health Mission", "NHM മിഷൻ"),
    ("ICDS", "ICDS മിഷൻ"),
    ("NSAP", "NSAP മിഷൻ"),
    ("PMMVY", "PMMVY മിഷൻ"),
    ("Stand-Up India", "Stand-Up India മിഷൻ"),
    ("PM Mudra", "PMMY മിഷൻ"),
    ("Digital India", "Digital India പ്രോഗ്രാം"),
    ("Skill India", "Skill India Mission"),
    ("Swachh Bharat", "Swachh Bharat Mission"),
    ("Jal Jeevan Mission", "JJM മിഷൻ"),
    ("PM SVANidhi", "PM SVANidhi മിഷൻ"),
    ("PM Vishwakarma", "PM Vishwakarma മിഷൻ"),
    ("PM Surya Ghar", "PM Surya Ghar മിഷൻ"),
    ("National Green Hydrogen", "National Green Hydrogen Mission"),
    ("PM Gati Shakti", "PM Gati Shakti Master Plan"),
    ("PM SHRI", "PM SHRI Scheme"),
    ("PM eBus Sewa", "PM eBus Sewa Scheme"),
    ("PM Internship", "PM Internship Scheme"),
    ("PM Janman", "PM JANMAN Mission"),
    ("Vibrant Villages", "VVP Guidelines"),
]

NODAL: list[tuple[str, str]] = [
    ("PM Fasal Bima", "കൃഷി മന്ത്രാലയം"),
    ("PM Awas", "വാസസ്ഥല മന്ത്രാലയം"),
    ("PM-JAY", "NHA"),
    ("PM-KISAN", "കൃഷി മന്ത്രാലയം"),
    ("MGNREGA", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("Jal Jeevan Mission", "JJM"),
    ("Digital India", "MeitY"),
    ("Skill India", "NSDC"),
    ("PM Mudra", "SIDBI"),
    ("Stand-Up India", "SIDBI"),
    ("PM SVANidhi", "HUDCO"),
    ("PM Matsya Sampada", "Fisheries Dept"),
    ("UDAN", "AAI"),
    ("Smart Cities", "MoHUA"),
    ("PM-KUSUM", "MNRE"),
    ("POSHAN", "WCD Ministry"),
    ("Mission Indradhanush", "MoHFW"),
    ("BharatNet", "BSNL/BBNL"),
    ("PM Gati Shakti", "Logistics Division"),
    ("PM SHRI", "DoSE"),
    ("PM Vishwakarma", "MSDE"),
    ("PM Surya Ghar", "MNRE"),
    ("National Green Hydrogen", "MNRE"),
    ("PM eBus Sewa", "MoHUA"),
    ("PM Internship", "DoE"),
    ("PM Janman", "MoTA"),
    ("Vibrant Villages", "MoHA"),
    ("PM DevINE", "DoNER"),
    ("PM MITRA", "Textiles Ministry"),
    ("SVAMITVA", "DoLR"),
    ("ABDM", "NHA"),
]

PREDECESSOR: list[tuple[str, str]] = [
    ("PM Fasal Bima", "NAIS/MAIS"),
    ("PM Awas Urban", "JNNURM"),
    ("PM Awas Gramin", "IAY/Indira Awas"),
    ("PM-JAY", "RSBY"),
    ("PM Ujjwala", "PAHAL"),
    ("PM Jan Dhan", "Swabhiman"),
    ("PM-KISAN", "PM-KISAN pilot 2018"),
    ("MGNREGA", "SGRY/NREG"),
    ("Jal Jeevan Mission", "NRWDP"),
    ("Saubhagya", "DDUGJY"),
    ("DDUGJY", "RGGVY"),
    ("PMGSY", "CRSP"),
    ("POSHAN", "ICDS+"),
    ("National Health Mission", "NRHM+NUHM"),
    ("Skill India", "DDU-GKY"),
    ("Digital India", "National e-Governance Plan"),
    ("Swachh Bharat", "Nirmal Bharat"),
    ("PM Mudra", "MUDRA Bank concept"),
    ("Stand-Up India", "Startup India complement"),
    ("PM SVANidhi", "PM Street Vendor scheme"),
    ("PM Vishwakarma", "Hunar Se Rozgar"),
    ("PM Surya Ghar", "Rooftop Solar Scheme"),
    ("PM-KUSUM", "Off-grid solar"),
    ("Smart Cities", "JNNURM"),
    ("AMRUT", "JNNURM"),
    ("UDAN", "Regional Air Connectivity"),
    ("PM Gati Shakti", "PMGS/NIP"),
    ("PM SHRI", "Model Schools"),
    ("PM eBus Sewa", "FAME II"),
    ("National Green Hydrogen", "National Hydrogen Energy Mission"),
]

INSURANCE: list[tuple[str, str]] = [
    ("PMJJBY", "₹2 ലക്ഷം"),
    ("PMSBY", "₹2 ലക്ഷം"),
    ("PM Fasal Bima", "വിള നഷ്ട പരിരക്ഷ"),
    ("PM-JAY", "₹5 ലക്ഷം/വർഷം"),
    ("PM Suraksha extended", "₹2 ലക്ഷം"),
    ("PM Jeevan Jyoti", "₹2 ലക്ഷം"),
    ("PM Fasal Bima premium", "കർഷകർ 2% മാത്രം"),
    ("PM Fasal Bima Kharif", "കൃഷി സീസൺ പരിരക്ഷ"),
    ("PM Fasal Bima Rabi", "റാബി സീസൺ പരിരക്ഷ"),
    ("PM-JAY secondary care", "സെക്കൻഡറി+ടെർഷ്യറി"),
    ("PM-JAY tertiary", "ടെർഷ്യറി ചികിത്സ"),
    ("PM-JAY pre-existing", "മുൻരോഗം ഉൾപ്പെടെ"),
    ("PMJJBY age", "18–50 വയസ്"),
    ("PMSBY age", "18–70 വയസ്"),
    ("PM Fasal Bima crop loss", "സ്വാഭാവിക ദുരന്തം"),
    ("PM Fasal Bima post-harvest", "പോസ്റ്റ് ഹാർവെസ്റ്റ്"),
    ("PM Fasal Bima localized", "പ്രാദേശിക കാലാവസ്ഥ"),
    ("PM Fasal Bima prevented sowing", "വിത്തിടൽ തടസ്സം"),
    ("PM-JAY hospitalization", "ആശുപത്രി ചെലവ്"),
    ("PM-JAY packages", "1500+ പാക്കേജുകൾ"),
    ("PM-JAY empaneled", "സർക്കാർ+സ്വകാര്യം"),
    ("PM-JAY portability", "ഓൾ ഇന്ത്യ"),
    ("PM Fasal Bima PMFBY", "PMFBY 2016 മുതൽ"),
    ("PM-JAY launch", "2018 സെപ്റ്റംബർ"),
    ("PMJJBY annual premium", "₹436"),
    ("PMSBY annual premium", "₹20"),
    ("PM Fasal Bima govt share", "കേന്ദ്ര+സംസ്ഥാന സബ്സിഡി"),
    ("PM-JAY beneficiaries", "50 കോടി ലക്ഷ്യം"),
    ("PM Fasal Bima technology", "റിമോട്ട് സെൻസിംഗ്+ഡ്രോൺ"),
    ("Ayushman CAPF", "₹5 ലക്ഷം"),
    ("RSBY predecessor", "₹30000 പരിരക്ഷ"),
    ("PM Fasal Bima yield", "വിളവ് നഷ്ട പരിരക്ഷ"),
]

LOAN_LIMIT: list[tuple[str, str]] = [
    ("PM Mudra Shishu", "₹50000 വരെ"),
    ("PM Mudra Kishore", "₹50000–5 ലക്ഷം"),
    ("PM Mudra Tarun", "₹5–10 ലക്ഷം"),
    ("Stand-Up India", "₹10 ലക്ഷം–1 കോടി"),
    ("PM SVANidhi", "₹10000"),
    ("PM SVANidhi 2nd", "₹20000"),
    ("PM Vishwakarma", "₹3 ലക്ഷം വരെ"),
    ("PM Vishwakarma collateral", "കോളാറ്ററൽ രഹിതം"),
    ("PM FME", "₹10 ലക്ഷം"),
    ("PM MITRA", "₹4200 കോടി പ്ലാൻഡ്"),
    ("PM Daksh", "₹500/ദിവസം"),
    ("PM Internship", "₹5000/മാസം"),
    ("Kisan Credit Card", "കാർഷിക വായ്പ"),
    ("PMMY total", "₹20 ലക്ഷം കോടി ലക്ഷ്യം"),
    ("Stand-Up India tenure", "7 വർഷം"),
    ("PM SVANidhi tenure", "1 വർഷം"),
    ("PM Vishwakarma toolkit", "ഉപകരണ സഹായം"),
    ("PM FME credit", "2% പലിശ സബ്സിഡി"),
    ("PM Mudra collateral", "കോളാറ്ററൽ രഹിതം"),
    ("PM SVANidhi interest", "7% സബ്സിഡി"),
    ("PM Vishwakarma training", "5–7 ദിവസം+6 മാസം"),
    ("PM Mudra women", "68% വനിതാ സംരംഭകർ"),
    ("PM SVANidhi digital", "QR കോഡ് സഹായം"),
    ("Stand-Up India margin", "25% മാർജിൻ"),
    ("PM FME seed", "35% ഗ്രാൻ്റ്"),
    ("PM MITRA plug", "പ്ലഗ് ആൻഡ് പ്ലേ"),
    ("PM Daksh training", "3 മാസം"),
    ("PM Internship companies", "500+ കമ്പനികൾ"),
    ("PM Vishwakarma loan", "₹1 ലക്ഷം കോളാറ്ററൽ രഹിതം"),
    ("PM Mudra NBFC", "NBFC/MFI വഴി"),
]

TARGET_COUNT: list[tuple[str, str]] = [
    ("PM-JAY", "50 കോടി"),
    ("PM Jan Dhan", "എല്ലാ കുടുംബങ്ങൾ"),
    ("PM Ujjwala", "8 കോടി+ കുടുംബങ്ങൾ"),
    ("Swachh Bharat", "ഓപ്പൺ ഡിഫെക്കേഷൻ ഫ്രീ"),
    ("Jal Jeevan Mission", "എല്ലാ ഗ്രാമങ്ങൾ 2024"),
    ("PM Awas Urban", "2 കോടി വീടുകൾ"),
    ("PM Awas Gramin", "2.95 കോടി വീടുകൾ"),
    ("PM-KISAN", "14 കോടി കർഷകർ"),
    ("Digital India", "എല്ലാ ഗ്രാമങ്ങളും ഡിജിറ്റൽ"),
    ("Skill India", "40 കോടി പേർ"),
    ("Smart Cities", "100 നഗരങ്ങൾ"),
    ("UDAN", "100+ വിമാനത്താവളങ്ങൾ"),
    ("PM Mudra", "10 കോടി+ വായ്പകൾ"),
    ("MGNREGA", "5 കോടി+ കുടുംബങ്ങൾ"),
    ("POSHAN", "എല്ലാ ജില്ലകളും"),
    ("Mission Indradhanush", "90%+ പൂർണ്ണ ഇമ്മ്യൂനൈസേഷൻ"),
    ("PM SVANidhi", "50 ലക്ഷം വ്യാപാരികൾ"),
    ("PM Vishwakarma", "30 ലക്ഷം കരകുശലർ"),
    ("PM Surya Ghar", "1 കോടി ഗൃഹങ്ങൾ"),
    ("National Green Hydrogen", "5 MMT/വർഷം"),
    ("PM SHRI", "14500+ സ്കൂളുകൾ"),
    ("PM Gati Shakti", "16 മന്ത്രാലയങ്ങൾ"),
    ("PM eBus Sewa", "10000+ ബസുകൾ"),
    ("PM Internship", "1 കോടി ഇന്റേൺഷിപ്പ്"),
    ("PM Janman", "PVTG 75 ജനത"),
    ("Vibrant Villages", "2967 ഗ്രാമങ്ങൾ"),
    ("PM DevINE", "നോർത്ത്-ഈസ്റ്റ് 8 സംസ്ഥാനങ്ങൾ"),
    ("PM MITRA", "7 മെഗാ ടെക്സ്റ്റൈൽ പാർക്ക്"),
    ("BharatNet", "2.5 ലക്ഷം ഗ്രാമ പഞ്ചായത്തുകൾ"),
    ("PM Garib Kalyan Anna", "80 കോടി+"),
]

FUNDING: list[tuple[str, str]] = [
    ("MGNREGA", "കേന്ദ്ര 100% ശമ്പളം"),
    ("PM-JAY", "കേന്ദ്ര-സംസ്ഥാന 60:40"),
    ("PM Awas Urban", "കേന്ദ്ര-സംസ്ഥാന 60:40"),
    ("PM Awas Gramin", "കേന്ദ്ര 60% സംസ്ഥാന 40%"),
    ("PM Fasal Bima", "കേന്ദ്ര-സംസ്ഥാന പ്രീമിയം"),
    ("Jal Jeevan Mission", "കേന്ദ്ര-സംസ്ഥാന 50:50"),
    ("PM-KISAN", "കേന്ദ്ര 100%"),
    ("PM Ujjwala", "കേന്ദ്ര 100%"),
    ("Smart Cities", "കേന്ദ്ര-സംസ്ഥാന 50:50"),
    ("AMRUT", "കേന്ദ്ര-സംസ്ഥാന 50:50"),
    ("UDAN", "വിഎഗ്എഫ്+സബ്സിഡി"),
    ("PM Mudra", "REFINANCE മോഡൽ"),
    ("Stand-Up India", "ബാങ്ക് വായ്പ"),
    ("PM SVANidhi", "കേന്ദ്ര-ULB"),
    ("PM Vishwakarma", "കേന്ദ്ര 100%"),
    ("PM Surya Ghar", "കേന്ദ്ര 60%"),
    ("National Green Hydrogen", "കേന്ദ്ര PLI"),
    ("PM SHRI", "കേന്ദ്ര-സംസ്ഥാന"),
    ("PM Gati Shakti", "കേന്ദ്ര+സംസ്ഥാന+PSU"),
    ("PM eBus Sewa", "വിഎഗ്എഫ്"),
    ("PM Internship", "കേന്ദ്ര CSR"),
    ("PM Janman", "കേന്ദ്ര-സംസ്ഥാന"),
    ("Vibrant Villages", "കേന്ദ്ര 100%"),
    ("PM DevINE", "കേന്ദ്ര 100%"),
    ("PM MITRA", "കേന്ദ്ര+സംസ്ഥാന+സ്വകാര്യം"),
    ("SVAMITVA", "കേന്ദ്ര-സംസ്ഥാന"),
    ("BharatNet", "യുഎസ്ഒഫ്+കേന്ദ്ര"),
    ("POSHAN", "കേന്ദ്ര-സംസ്ഥാന"),
    ("Mission Indradhanush", "കേന്ദ്ര-സംസ്ഥാന"),
    ("PM Garib Kalyan Anna", "കേന്ദ്ര 100%"),
]

PORTAL: list[tuple[str, str]] = [
    ("PM-KISAN", "pmkisan.gov.in"),
    ("PM Jan Dhan", "jansuraksha.gov.in"),
    ("PM Fasal Bima", "pmfby.gov.in"),
    ("PM Awas", "pmaymis.gov.in"),
    ("PM-JAY", "pmjay.gov.in"),
    ("MGNREGA", "nrega.nic.in"),
    ("PM Mudra", "mudra.org.in"),
    ("PM Ujjwala", "pmuy.gov.in"),
    ("Jal Jeevan Mission", "jaljeevanmission.gov.in"),
    ("Digital India", "digitalindia.gov.in"),
    ("Skill India", "skillindia.gov.in"),
    ("Swachh Bharat", "sbm.gov.in"),
    ("PM SVANidhi", "pmsvanidhi.mohua.gov.in"),
    ("PM Vishwakarma", "pmvishwakarma.gov.in"),
    ("PM Surya Ghar", "pmsuryaghar.gov.in"),
    ("UDAN", "civilaviation.gov.in"),
    ("Smart Cities", "smartcities.gov.in"),
    ("PM Gati Shakti", "pmgatishakti.gov.in"),
    ("PM SHRI", "pmshrischools.education.gov.in"),
    ("ABDM", "abdm.gov.in"),
    ("PM eVIDYA", "diksha.gov.in"),
    ("PM WANI", "wani.gov.in"),
    ("One Nation One Ration", "nfsa.gov.in"),
    ("PM Internship", "pminternship.mca.gov.in"),
    ("PM Janman", "tribal.nic.in"),
    ("Vibrant Villages", "mha.gov.in"),
    ("National Green Hydrogen", "mnre.gov.in"),
    ("PM eBus Sewa", "mohua.gov.in"),
    ("PM Daksh", "skillindia.gov.in"),
    ("PM DevINE", "doner.gov.in"),
]

PM_LAUNCHED: list[tuple[str, str]] = [
    ("PM Jan Dhan", "നരേന്ദ്ര മോദി"),
    ("PM Fasal Bima", "നരേന്ദ്ര മോദി"),
    ("PM Awas", "നരേന്ദ്ര മോദി"),
    ("PM Ujjwala", "നരേന്ദ്ര മോദി"),
    ("PM-KISAN", "നരേന്ദ്ര മോദി"),
    ("Ayushman Bharat", "നരേന്ദ്ര മോദി"),
    ("Digital India", "നരേന്ദ്ര മോദി"),
    ("Skill India", "നരേന്ദ്ര മോദി"),
    ("Swachh Bharat", "നരേന്ദ്ര മോദി"),
    ("PM Mudra", "നരേന്ദ്ര മോദി"),
    ("MGNREGA", "മനമോഹൻ സിംഗ്"),
    ("Mission Indradhanush", "നരേന്ദ്ര മോദി"),
    ("Beti Bachao Beti Padhao", "നരേന്ദ്ര മോദി"),
    ("Smart Cities", "നരേന്ദ്ര മോദി"),
    ("AMRUT", "നരേന്ദ്ര മോദി"),
    ("UDAN", "നരേന്ദ്ര മോദി"),
    ("PM SVANidhi", "നരേന്ദ്ര മോദി"),
    ("PM Vishwakarma", "നരേന്ദ്ര മോദി"),
    ("PM Surya Ghar", "നരേന്ദ്ര മോദി"),
    ("National Green Hydrogen", "നരേന്ദ്ര മോദി"),
    ("PM Gati Shakti", "നരേന്ദ്ര മോദി"),
    ("PM SHRI", "നരേന്ദ്ര മോദി"),
    ("PM eBus Sewa", "നരേന്ദ്ര മോദി"),
    ("PM Internship", "നരേന്ദ്ര മോദി"),
    ("PM Janman", "നരേന്ദ്ര മോദി"),
    ("Vibrant Villages", "നരേന്ദ്ര മോദി"),
    ("Jal Jeevan Mission", "നരേന്ദ്ര മോദി"),
    ("PM-KUSUM", "നരേന്ദ്ര മോദി"),
    ("POSHAN Abhiyaan", "നരേന്ദ്ര മോദി"),
    ("DDUGJY", "നരേന്ദ്ര മോദി"),
]

UMBRELLA: list[tuple[str, str]] = [
    ("PMJJBY", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("PMSBY", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("Atal Pension", "ജന സുരക്ഷാ പദ്ധതികൾ"),
    ("PM Awas Gramin", "PMAY"),
    ("PM Awas Urban", "PMAY"),
    ("PM-JAY", "Ayushman Bharat"),
    ("PM eVIDYA", "Digital India"),
    ("PM WANI", "Digital India"),
    ("ABDM", "Ayushman Bharat Digital Mission"),
    ("PM SHRI", "NEP 2020"),
    ("PM Gati Shakti", "National Infrastructure Pipeline"),
    ("PM MITRA", "Make in India"),
    ("PM FME", "Aatmanirbhar Bharat"),
    ("PM SVANidhi", "Aatmanirbhar Bharat"),
    ("PM Vishwakarma", "Aatmanirbhar Bharat"),
    ("PM Surya Ghar", "National Solar Mission"),
    ("PM-KUSUM", "National Solar Mission"),
    ("POSHAN", "National Nutrition Mission"),
    ("Mission Indradhanush", "Universal Immunization"),
    ("UDAN", "RCS"),
    ("AMRUT", "Smart Cities"),
    ("HRIDAY", "Smart Cities"),
    ("PM Daksh", "Skill India"),
    ("PM eBus Sewa", "FAME India"),
    ("National Green Hydrogen", "National Hydrogen Mission"),
    ("PM Janman", "PM JANMAN"),
    ("Vibrant Villages", "Border Development"),
    ("PM Internship", "Skill India"),
    ("PM DevINE", "North-East Package"),
    ("PM Garib Kalyan Anna", "PM Garib Kalyan"),
]

WOMEN: list[tuple[str, str]] = [
    ("Beti Bachao Beti Padhao", "പെൺകുട്ടികളുടെ സംരക്ഷണം"),
    ("Sukanya Samriddhi", "പെൺകുട്ടിയുടെ ഭാവി സമ്പാദ്യം"),
    ("PMMVY", "മാതൃ സംരക്ഷണ നേട്ടം"),
    ("Stand-Up India", "വനിതാ സംരംഭകത്വം"),
    ("PM Ujjwala", "വനിതാ ആരോഗ്യ സംരക്ഷണം"),
    ("PM Awas", "വനിതാ ഭവന ഉടമസ്ഥത"),
    ("PM Mudra", "വനിതാ സംരംഭകത്വം"),
    ("PM SHRI", "പെൺകുട്ടികളുടെ വിദ്യാഭ്യാസം"),
    ("One Stop Centre Sakhi", "ഹിംസയെ നേരിടുന്ന വനിത"),
    ("Ujjawala Trafficking", "കടത്തുകാരുടെ പുനരധിവാസം"),
    ("National Creche", "ജോലിക്കാരായ വനിത"),
    ("PM POSHAN", "ഗർഭിണി+ശിശു പോഷകാഹാരം"),
    ("PM SVANidhi", "വനിതാ തെരുവ് വ്യാപാരികൾ"),
    ("PM Vishwakarma", "വനിതാ കരകുശലർ"),
    ("PM Jan Dhan", "വനിതാ സാമ്പത്തിക ഉൾപ്പെടുത്തൽ"),
    ("PM-JAY", "മാതൃ+ശിശു ആരോഗ്യം"),
    ("PM eVIDYA", "പെൺകുട്ടികളുടെ ഓൺലൈൻ വിദ്യാഭ്യാസം"),
    ("PM Daksh", "യുവതി കൗശലം"),
    ("PM Internship", "യുവതി തൊഴിൽ"),
    ("PM Surya Ghar", "ഗൃഹിണി ഊർജ സ്വാതന്ത്ര്യം"),
    ("PM Garib Kalyan Anna", "ഗർഭിണി+മുലയൂട്ടുന്ന വനിത"),
    ("She-Box", "ഔദ്യോഗിക പീഡന പരാതി"),
    ("Working Women Hostel", "താമസ സൗകര്യം"),
    ("Mahila Police Volunteer", "സുരക്ഷാ സഹായം"),
    ("PM Matru Vandana", "മാതൃ ആരോഗ്യം"),
    ("Gender Budgeting", "ലിംഗ സമത"),
    ("PM Ujjwala 2.0", "മിഗ്രന്റ് കുടുംബങ്ങൾ"),
    ("PM Awas Urban women", "സംയുക്ത ഉടമസ്ഥത"),
    ("PM Mudra women share", "68% വനിതാ വായ്പ"),
    ("PM SHRI girls toilet", "പെൺകുട്ടികൾക്ക് ശുചിമുറി"),
]

RURAL: list[tuple[str, str]] = [
    ("MGNREGA", "100 ദിവസം തൊഴിൽ"),
    ("PM Awas Gramin", "പാക്കാ വീട്"),
    ("Jal Jeevan Mission", "എല്ലാ ഗ്രാമങ്ങൾക്കും കുടിവെള്ളം"),
    ("PMGSY", "ഗ്രാമീണ റോഡ്"),
    ("DDUGJY", "ഗ്രാമീണ വൈദ്യുതീകരണം"),
    ("Saubhagya", "എല്ലാ ഗൃഹങ്ങൾക്കും വൈദ്യുതി"),
    ("SVAMITVA", "ഗ്രാമീണ ഭൂമി രേഖ"),
    ("PM-KISAN", "കർഷക വരുമാനം"),
    ("PM Fasal Bima", "വിള നഷ്ട പരിരക്ഷ"),
    ("PM-KUSUM", "കാർഷിക സോളാർ"),
    ("PM FME", "ഗ്രാമീണ ഫുഡ് പ്രോസസ്സിംഗ്"),
    ("DAY-NRLM", "സ്വയം സഹായ ഗ്രൂപ്പ്"),
    ("National Rural Livelihood", "ഗ്രാമീണ തൊഴിൽ"),
    ("PM Jan Dhan", "ഗ്രാമീണ ബാങ്കിംഗ്"),
    ("BharatNet", "ഗ്രാമീണ ബ്രോഡ്ബാൻഡ്"),
    ("Soil Health Card", "മണ്ണിന്റെ ആരോഗ്യം"),
    ("Kisan Credit Card", "സമയോചിത കാർഷിക വായ്പ"),
    ("PM-KMY", "കർഷക പെൻഷൻ"),
    ("RKVY", "കാർഷിക വികസനം"),
    ("PM Matsya Sampada", "മത്സ്യബന്ധന വികസനം"),
    ("PM Vishwakarma", "ഗ്രാമീണ കരകുശല"),
    ("Vibrant Villages", "അതിർത്തി ഗ്രാമ വികസനം"),
    ("PM Garib Kalyan Anna", "ഗ്രാമീണ ഭക്ഷ്യ സുരക്ഷ"),
    ("National Food Security", "റേഷൻ സുരക്ഷ"),
    ("PM Janman", "PVTG ഗ്രാമ വികസനം"),
    ("PM Daksh", "ഗ്രാമീണ യുവ കൗശലം"),
    ("PM Surya Ghar rural", "ഗ്രാമീണ സോളാർ"),
    ("PM Ujjwala rural", "ഗ്രാമീണ എൽ.പി.ജി."),
    ("PM Awas Gramin toilet", "ശുചിമുറി ഉൾപ്പെടെ"),
    ("MGNREGA asset", "ജല സംരക്ഷണം"),
]

URBAN: list[tuple[str, str]] = [
    ("PM Awas Urban", "നഗര ഭവനരഹിതർക്ക് വീട്"),
    ("Smart Cities Mission", "നഗര നവീകരണം"),
    ("AMRUT", "നഗര അടിസ്ഥാന സൗകര്യം"),
    ("HRIDAY", "പൈതൃക നഗരങ്ങൾ"),
    ("UDAN", "നഗര വിമാന ബന്ധം"),
    ("PM SVANidhi", "നഗര തെരുവ് വ്യാപാരം"),
    ("PM eBus Sewa", "നഗര ഇലക്ട്രിക് ബസ്"),
    ("Metro Rail projects", "മെട്രോ റെയിൽ"),
    ("Swachh Bharat Urban", "നഗര ശുചിത്വം"),
    ("AMRUT 2.0", "നഗര ജല സംരക്ഷണം"),
    ("Smart City SPV", "നഗര വികസന ഏജൻസി"),
    ("PM Gati Shakti urban", "നഗര ലോജിസ്റ്റിക്സ്"),
    ("PM SHRI urban schools", "നഗര സ്കൂൾ നവീകരണം"),
    ("PM MITRA", "നഗര ടെക്സ്റ്റൈൽ പാർക്ക്"),
    ("PM WANI", "പബ്ലിക് വൈ-ഫി"),
    ("Digital India urban", "നഗര ഡിജിറ്റൽ"),
    ("PM Mudra urban", "നഗര സംരംഭകത്വം"),
    ("Stand-Up India urban", "നഗര സംരംഭകത്വം"),
    ("PM Awas CLSS", "നഗര വായ്പ സബ്സിഡി"),
    ("AMRUT water", "നഗര കുടിവെള്ളം"),
    ("Smart City lighthouse", "മാതൃക നഗരം"),
    ("PM eBus green", "നഗര കാർബൺ കുറയ്ക്കൽ"),
    ("HRIDAY Varanasi", "വാരണാസി പൈതൃകം"),
    ("AMRUT sewerage", "നഗര മലിനജലം"),
    ("Smart City IoT", "സ്മാർട്ട് സെൻസർ"),
    ("PM Awas in-situ", "നഗര പുനര്വാസം"),
    ("PM SVANidhi urban local", "നഗര സ്ഥാനിക സ്വയംഭരണം"),
    ("Metro Neo", "ലഘു മെട്രോ"),
    ("PM Gati Shakti multimodal", "നഗര ട്രാൻസ്പോർട്ട് ഹബ്"),
    ("AMRUT parks", "നഗര പാർക്ക്"),
]

AGRI: list[tuple[str, str]] = [
    ("PM Fasal Bima", "വിള ഇൻഷുറൻസ്"),
    ("PM-KISAN", "കർഷക വരുമാന സഹായം"),
    ("PM-KUSUM", "കാർഷിക സോളാർ പമ്പ്"),
    ("PM FME", "ഫുഡ് പ്രോസസ്സിംഗ്"),
    ("PM Matsya Sampada", "മത്സ്യ ഉൽപ്പാദനം"),
    ("Soil Health Card", "മണ്ണിന്റെ ആരോഗ്യം"),
    ("Kisan Credit Card", "കാർഷിക വായ്പ"),
    ("PM-KMY", "കർഷക പെൻഷൻ"),
    ("RKVY", "കാർഷിക വികസനം"),
    ("National Mission Oil Palm", "എഡിബിൾ ഓയിൽ പാം"),
    ("PM Aasha", "വിപണി വില സ്ഥിരത"),
    ("e-NAM", "ആഗ്രി വിപണി"),
    ("Paramparagat Krishi", "ജൈവ കൃഷി"),
    ("PMKSY", "ജല സേചനം"),
    ("National Livestock Mission", "കന്നുകാലി വികസനം"),
    ("Blue Revolution", "മത്സ്യബന്ധനം"),
    ("PM Fasal Bima crop", "പ്രധാന വിളകൾ"),
    ("PM-KISAN instalment", "₹2000/തവണ"),
    ("PM-KUSUM component A", "ഗ്രിഡ് കണക്ടഡ് സോളാർ"),
    ("PM-KUSUM component B", "സ്റ്റാൻഡ് അലോൺ പമ്പ്"),
    ("PM-KUSUM component C", "സോളാർ പമ്പ്"),
    ("PM FME micro", "മൈക്രോ ഫുഡ് യൂണിറ്റ്"),
    ("PM Matsya infrastructure", "മത്സ്യ തുറമുഖം"),
    ("RKVY RAFTAAR", "കാർഷിക നവീകരണം"),
    ("National Bamboo Mission", "മുള വികസനം"),
    ("Horticulture Mission", "തോട്ടക്കൃഷി"),
    ("PM Aasha MSP", "MSP+20%"),
    ("PM Fasal Bima tech", "ഡ്രോൺ+സാറ്റലൈറ്റ്"),
    ("PM-KISAN exclusion", "വരുമാന നികുതി ദാതാക്കൾ"),
    ("PM FME cluster", "ഫുഡ് ക്ലസ്റ്റർ"),
]

HEALTH: list[tuple[str, str]] = [
    ("Ayushman Bharat PM-JAY", "ആരോഗ്യ ഇൻഷുറൻസ്"),
    ("Mission Indradhanush", "വാക്സിനേഷൻ"),
    ("National Health Mission", "ആരോഗ്യ സേവനം"),
    ("PM Ayushman CAPF", "CAPF ആരോഗ്യം"),
    ("ABDM", "ഡിജിറ്റൽ ഹെൽത്ത്"),
    ("PM Ayushman Health Infra", "ആരോഗ്യ അടിസ്ഥാന സൗകര്യം"),
    ("PM POSHAN", "പോഷകാഹാരം"),
    ("PMMVY", "മാതൃ സംരക്ഷണം"),
    ("National Ayush Mission", "ആയുർവേദം"),
    ("PMSSY", "മെഡിക്കൽ കോളേജ്"),
    ("PM Ayushman wellness", "വെൽനസ് സെന്റർ"),
    ("PM eSanjeevani", "ടെലിമെഡിസിൻ"),
    ("PM Ayushman Health ID", "ആരോഗ്യ ഐഡി"),
    ("National TB Elimination", "ക്ഷയരോഗ നിർമാർജനം"),
    ("National AIDS Control", "എയ്ഡ്സ് നിയന്ത്രണം"),
    ("PM Ayushman free drugs", "സൗജന്യ മരുന്ന്"),
    ("PM Ayushman free test", "സൗജന്യ പരിശോധന"),
    ("PM Ayushman dialysis", "ഡയാലിസിസ്"),
    ("PM Ayushman PMJAY package", "1500+ പാക്കേജ്"),
    ("Mission Indradhanush 4.0", "പൂർണ്ണ ഇമ്മ്യൂനൈസേഷൻ"),
    ("PM Ayushman portability", "ഓൾ ഇന്ത്യ ചികിത്സ"),
    ("National Digital Health", "ഹെൽത്ത് റെക്കോർഡ്"),
    ("PM Ayushman secondary", "സെക്കൻഡറി ആശുപത്രി"),
    ("PM Ayushman tertiary", "ടെർഷ്യറി ആശുപത്രി"),
    ("PM Ayushman empaneled", "സർക്കാർ+സ്വകാര്യം"),
    ("PM Ayushman 5 lakh", "₹5 ലക്ഷം പരിരക്ഷ"),
    ("PM POSHAN tracker", "പോഷൺ ട്രാക്കർ"),
    ("PMMVY 5000", "₹5000 മാതൃ നേട്ടം"),
    ("National Health Policy 2017", "സാർവത്രിക ആരോഗ്യം"),
    ("PM Ayushman launch 2018", "2018 സെപ്റ്റംബർ"),
]

EDUCATION: list[tuple[str, str]] = [
    ("PM SHRI", "മാതൃക സ്കൂൾ"),
    ("PM eVIDYA", "ഓൺലൈൻ വിദ്യാഭ്യാസം"),
    ("Samagra Shiksha", "സമഗ്ര വിദ്യാഭ്യാസം"),
    ("Mid-Day Meal", "ഭോജന പദ്ധതി"),
    ("RTE Act", "ഉചിത+നിർബന്ധിത വിദ്യാഭ്യാസം"),
    ("NEP 2020", "വിദ്യാഭ്യാസ നയം"),
    ("DIKSHA", "ഡിജിറ്റൽ വിദ്യാഭ്യാസം"),
    ("SWAYAM", "ഓൺലൈൻ കോഴ്സ്"),
    ("PM POSHAN school", "സ്കൂൾ പോഷകാഹാരം"),
    ("Beti Bachao education", "പെൺകുട്ടി വിദ്യാഭ്യാസം"),
    ("PM Daksh", "യുവ കൗശലം"),
    ("PM Internship", "യുവ തൊഴിൽ പരിശീലനം"),
    ("National Scholarship Portal", "വിദ്യാഭ്യാസ സ്കോളർഷിപ്പ്"),
    ("PM eVIDYA DTH", "ഡിജിറ്റൽ ടിവി ചാനൽ"),
    ("PM eVIDYA radio", "രേഡിയോ വിദ്യാഭ്യാസം"),
    ("PM SHRI NEP aligned", "NEP അനുസൃത സ്കൂൾ"),
    ("PM eVIDYA one class", "ഒരു ചാനൽ ഒരു തരം"),
    ("PM SHRI green school", "ഹരിത സ്കൂൾ"),
    ("Samagra Shiksha integrated", "SSA+RMSA+TE"),
    ("Mid-Day Meal nutrition", "പോഷകാഹാര മാനദണ്ഡം"),
    ("RTE 25% EWS", "സാമ്പത്തിക പിന്നോക്ക വിഭാഗം"),
    ("NEP multidisciplinary", "ബഹു-വിഷയ പഠനം"),
    ("DIKSHA teacher", "അധ്യാപക പരിശീലനം"),
    ("SWAYAM MOOC", "സൗജന്യ ഓൺലൈൻ കോഴ്സ്"),
    ("PM SHRI lab", "ലാബ്+ലൈബ്രറി"),
    ("PM eVIDYA special", "പ്രത്യേക ആവശ്യകത"),
    ("National Education Policy", "2030 ലക്ഷ്യം"),
    ("PM Daksh apprenticeship", "അപ്രന്റിസ്ഷിപ്പ്"),
    ("PM Internship 5000", "₹5000/മാസം"),
    ("PM SHRI 14500 schools", "14500+ സ്കൂൾ"),
]

HOUSING: list[tuple[str, str]] = [
    ("PM Awas Urban", "നഗര ഭവനരഹിതർക്ക് വീട്"),
    ("PM Awas Gramin", "ഗ്രാമീണ ഭവനരഹിതർക്ക് വീട്"),
    ("PM Awas CLSS", "വായ്പ സബ്സിഡി"),
    ("PM Awas in-situ slum", "താവുകള പുനര്വാസം"),
    ("PM Awas beneficiary led", "സ്വയം നിർമ്മാണം"),
    ("PM Awas affordable rental", "വാടക വീട്"),
    ("PM Awas technology", "നവീന നിർമ്മാണ സാങ്കേതികവിദ്യ"),
    ("PM Awas women ownership", "സംയുക്ത ഉടമസ്ഥത"),
    ("PM Awas Gramin IAY", "Indira Awas പരിഷ്കാരം"),
    ("PM Awas Urban JNNURM", "JNNURM പരിഷ്കാരം"),
    ("PM Awas 2 crore urban", "2 കോടി ലക്ഷ്യം"),
    ("PM Awas 2.95 crore gramin", "2.95 കോടി ലക്ഷ്യം"),
    ("PM Awas PMAY-U", "നഗര ഘടകം"),
    ("PM Awas PMAY-G", "ഗ്രാമീണ ഘടകം"),
    ("PM Awas subsidy", "₹2.5 ലക്ഷം വരെ"),
    ("PM Awas toilet", "ശുചിമുറി ഉൾപ്പെടെ"),
    ("PM Awas LPG", "എൽ.പി.ജി. കണക്ഷൻ"),
    ("PM Awas electricity", "വൈദ്യുതി കണക്ഷൻ"),
    ("PM Awas convergence", "MGNREGA+Swachh"),
    ("PM Awas geo tag", "ജിയോ ടാഗിംഗ്"),
    ("PM Awas MIS", "pmaymis.gov.in"),
    ("PM Awas 2022 target urban", "2022 ലക്ഷ്യം"),
    ("PM Awas Gramin 2024", "2024 ലക്ഷ്യം"),
    ("PM Awas cost sharing", "കേന്ദ്ര-സംസ്ഥാന"),
    ("PM Awas plinth", "പ്ലിന്ത് മാത്രം"),
    ("PM Awas full house", "പൂർണ്ണ വീട്"),
    ("PM Awas tribal", "വനവാസി പ്രദേശം"),
    ("PM Awas hilly", "പർവത പ്രദേശം"),
    ("PM Awas coastal", "തീരദേശം"),
    ("PM Awas north-east", "വടക്കുകിഴക്കൻ സംസ്ഥാനം"),
]

EMPLOYMENT: list[tuple[str, str]] = [
    ("MGNREGA", "100 ദിവസം തൊഴിൽ"),
    ("Skill India", "കൗശല വികസനം"),
    ("PM Mudra", "സ്വയം തൊഴിൽ"),
    ("Stand-Up India", "സംരംഭകത്വം"),
    ("PM Daksh", "അപ്രന്റിസ്ഷിപ്പ്"),
    ("PM Internship", "ഇന്റേൺഷിപ്പ്"),
    ("PM Vishwakarma", "പാരമ്പര്യ തൊഴിൽ"),
    ("Startup India", "സ്റ്റാർട്ടപ്പ്"),
    ("Make in India", "നിർമ്മാണ തൊഴിൽ"),
    ("PLI scheme", "നിർമ്മാണ തൊഴിൽ"),
    ("PM MITRA", "ടെക്സ്റ്റൈൽ തൊഴിൽ"),
    ("PM eBus Sewa", "ഗ്രീൻ ജോബ്"),
    ("National Rural Livelihood", "സ്വയം സഹായ തൊഴിൽ"),
    ("DDU-GKY", "യുവ തൊഴിൽ"),
    ("PM SVANidhi", "തെരുവ് വ്യാപാര തൊഴിൽ"),
    ("PM FME", "ഫുഡ് പ്രോസസ്സിംഗ് തൊഴിൽ"),
    ("PM Matsya Sampada", "മത്സ്യ തൊഴിൽ"),
    ("PM Gati Shakti", "ഇൻഫ്രാ തൊഴിൽ"),
    ("PM SHRI", "വിദ്യാഭ്യാസ തൊഴിൽ"),
    ("PM eVIDYA", "ഡിജിറ്റൽ തൊഴിൽ"),
    ("PM WANI", "വൈ-ഫി തൊഴിൽ"),
    ("PM Surya Ghar", "സോളാർ തൊഴിൽ"),
    ("National Green Hydrogen", "ഹരിത ഊർജ തൊഴിൽ"),
    ("PM DevINE", "നോർത്ത്-ഈസ്റ്റ് തൊഴിൽ"),
    ("PM Janman", "PVTG തൊഴിൽ"),
    ("Vibrant Villages", "അതിർത്തി തൊഴിൽ"),
    ("PM Garib Kalyan", "താൽക്കാലിക തൊഴിൽ"),
    ("Atal Innovation", "നവീന തൊഴിൽ"),
    ("PM Daksh stipend", "₹500/ദിവസം"),
    ("PM Internship 1 crore", "1 കോടി ഇന്റേൺഷിപ്പ്"),
]

DIGITAL: list[tuple[str, str]] = [
    ("Digital India", "ഡിജിറ്റൽ ഉൾപ്പെടുത്തൽ"),
    ("BharatNet", "ഗ്രാമീണ ബ്രോഡ്ബാൻഡ്"),
    ("PM Jan Dhan", "ഡിജിറ്റൽ ബാങ്കിംഗ്"),
    ("UPI", "ഡിജിറ്റൽ പേമെന്റ്"),
    ("PM WANI", "പബ്ലിക് വൈ-ഫി"),
    ("ABDM", "ഡിജിറ്റൽ ഹെൽത്ത്"),
    ("PM eVIDYA", "ഡിജിറ്റൽ വിദ്യാഭ്യാസം"),
    ("DIKSHA", "ഡിജിറ്റൽ പഠനം"),
    ("DigiLocker", "ഡിജിറ്റൽ ഡോക്യുമെന്റ്"),
    ("UMANG", "ഡിജിറ്റൽ ഗവൺമെന്റ്"),
    ("PM Gati Shakti", "ഡിജിറ്റൽ പ്ലാനിംഗ്"),
    ("CoWIN", "വാക്സിൻ ഡിജിറ്റൽ"),
    ("Aarogya Setu", "ആരോഗ്യ ട്രാക്കിംഗ്"),
    ("eSanjeevani", "ടെലിമെഡിസിൻ"),
    ("ONORC", "ഡിജിറ്റൽ റേഷൻ"),
    ("PM SVANidhi QR", "QR പേമെന്റ്"),
    ("PM Surya Ghar portal", "സോളാർ പോർട്ടൽ"),
    ("PM-KISAN portal", "കർഷക പോർട്ടൽ"),
    ("PM Fasal Bima app", "വിള ഇൻഷുറൻസ് ആപ്പ്"),
    ("PM Awas MIS", "വീട് പോർട്ടൽ"),
    ("PM Mudra online", "ഓൺലൈൻ വായ്പ"),
    ("GeM", "ഓൺലൈൻ PROCUREMENT"),
    ("e-Hospital", "ആശുപത്രി ഓൺലൈൻ"),
    ("e-Office", "കാഗതരഹിത ഭരണം"),
    ("SVAMITVA drone", "ഡ്രോൺ സർവേ"),
    ("PM Gati Shakti GIS", "ജിയോ-സ്പേഷ്യൽ"),
    ("India Stack", "ഡിജിറ്റൽ ഇൻഫ്രാ"),
    ("COWIN certificate", "ഡിജിറ്റൽ സർട്ടിഫിക്കറ്റ്"),
    ("PM Internship portal", "ഇന്റേൺഷിപ്പ് പോർട്ടൽ"),
    ("PM Vishwakarma portal", "കരകുശല പോർട്ടൽ"),
]

ENV_ENERGY: list[tuple[str, str]] = [
    ("PM Ujjwala", "ശുദ്ധ ഇന്ധനം"),
    ("PM Surya Ghar", "സോളാർ ഊർജ"),
    ("PM-KUSUM", "കാർഷിക സോളാർ"),
    ("National Green Hydrogen", "ഹരിത ഹൈഡ്രജൻ"),
    ("FAME India", "ഇലക്ട്രിക് വാഹനം"),
    ("PM eBus Sewa", "ഇലക്ട്രിക് ബസ്"),
    ("SAUBHAGYA", "വൈദ്യുതീകരണം"),
    ("DDUGJY", "ഗ്രാമീണ വൈദ്യുതി"),
    ("National Solar Mission", "സോളാർ ലക്ഷ്യം"),
    ("National Wind Mission", "കാറ്റ് ഊർജ"),
    ("PM Gati Shakti green", "ഹരിത ലോജിസ്റ്റിക്സ്"),
    ("Swachh Bharat", "മാലിന്യ നിർമാർജനം"),
    ("Namami Gange", "ഗംഗാ ശുദ്ധീകരണം"),
    ("National Afforestation", "വനം വർദ്ധന"),
    ("PM SHRI green school", "ഹരിത സ്കൂൾ"),
    ("PM Surya Ghar 300 unit", "300 യൂണിറ്റ് സൗജന്യം"),
    ("National Green Hydrogen 5MMT", "5 MMT/വർഷം"),
    ("PM Ujjwala clean fuel", "കമ്മി പുക"),
    ("PM-KUSUM solar pump", "ഡീസൽ കുറയ്ക്കൽ"),
    ("FAME II", "EV സബ്സിഡി"),
    ("PM eBus zero emission", "പൂജ്യം ഉത്സർജനം"),
    ("National Hydrogen Energy", "ഹൈഡ്രജൻ മിഷൻ"),
    ("PM Surya Ghar rooftop", "ഗൃഹ മേൽക്കൂര"),
    ("National Biofuel", "ബയോഫ്യൂവൽ"),
    ("PM Gati Shakti energy", "ഊർജ കോറിഡോർ"),
    ("Solar park scheme", "സോളാർ പാർക്ക്"),
    ("Off-grid solar", "ഓഫ്-ഗ്രിഡ് സോളാർ"),
    ("PM Ujjwala 2.0 migrant", "മിഗ്രന്റ് കുടുംബം"),
    ("National Green Hydrogen PLI", "നിർമ്മാണ സബ്സിഡി"),
    ("PM Surya Ghar central subsidy", "₹78000 സബ്സിഡി"),
]

RECENT: list[tuple[str, str]] = [
    ("PM Vishwakarma", "പാരമ്പര്യ കരകുശല സഹായം"),
    ("PM Surya Ghar", "ഗൃഹ സോളാർ സൗജന്യ വൈദ്യുതി"),
    ("National Green Hydrogen Mission", "ഹരിത ഹൈഡ്രജൻ ഉൽപ്പാദനം"),
    ("PM Janman", "PVTG സമഗ്ര വികസനം"),
    ("PM Internship Scheme", "1 കോടി ഇന്റേൺഷിപ്പ്"),
    ("PM eBus Sewa", "10000 ഇലക്ട്രിക് ബസ്"),
    ("Vibrant Villages Programme", "അതിർത്തി ഗ്രാമ വികസനം"),
    ("PM SHRI", "മാതൃക സ്കൂൾ നവീകരണം"),
    ("PM Gati Shakti", "അടിസ്ഥാന സൗകര്യ ഏകീകരണം"),
    ("PM DevINE", "നോർത്ത്-ഈസ്റ്റ് നിക്ഷേപം"),
    ("PM MITRA", "മെഗാ ടെക്സ്റ്റൈൽ പാർക്ക്"),
    ("PM FME Phase II", "മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ്"),
    ("PM SVANidhi 2.0", "രണ്ടാം തവണ വായ്പ"),
    ("PM Ujjwala 2.0", "മിഗ്രന്റ് കുടുംബങ്ങൾ"),
    ("PM Garib Kalyan Anna extension", "ഭക്ഷ്യ സുരക്ഷ തുടർച്ച"),
    ("PM Ayushman CAPF", "CAPF ആരോഗ്യ പരിരക്ഷ"),
    ("PM Daksh expansion", "അപ്രന്റിസ്ഷിപ്പ് വിപുലീകരണം"),
    ("PM WANI expansion", "പബ്ലിക് വൈ-ഫി വിപുലീകരണം"),
    ("ABDM nationwide", "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി"),
    ("PM eVIDYA expansion", "ഓൺലൈൻ വിദ്യാഭ്യാസ വിപുലീകരണം"),
    ("National Edible Oil Mission", "എഡിബിൾ ഓയിൽ സ്വയംപര്യാപ്തത"),
    ("PM-KUSUM expansion", "കാർഷിക സോളാർ വിപുലീകരണം"),
    ("PM Awas Urban extension", "2024 വീട് ലക്ഷ്യം"),
    ("PM Awas Gramin extension", "2024 ഗ്രാമീണ ലക്ഷ്യം"),
    ("PM Mudra expansion", "₹20 ലക്ഷം കോടി ലക്ഷ്യം"),
    ("PM-KISAN 17th instalment", "കർഷക വരുമാന തുടർച്ച"),
    ("PM Fasal Bima 2024", "വിള ഇൻഷുറൻസ് തുടർച്ച"),
    ("PM-JAY 50 crore target", "50 കോടി ആരോഗ്യ പരിരക്ഷ"),
    ("PM Surya Ghar 2024 launch", "1 കോടി ഗൃഹ ലക്ഷ്യം"),
    ("PM Vishwakarma 2023 launch", "30 ലക്ഷം കരകുശലർ"),
]

DIRECT_FACTS: list[tuple[str, str, list[str], str]] = [
    ("MGNREGA-യിൽ ഗ്യാരന്റി ചെയ്യുന്ന തൊഴിൽ ദിവസങ്ങൾ എത്ര?", "100 ദിവസം", ["50 ദിവസം", "150 ദിവസം", "200 ദിവസം"], "medium"),
    ("PM-JAY-ൽ ഒരു കുടുംബത്തിന് വാർഷിക ആരോഗ്യ പരിരക്ഷ എത്ര?", "₹5 ലക്ഷം", ["₹1 ലക്ഷം", "₹2 ലക്ഷം", "₹10 ലക്ഷം"], "easy"),
    ("PM-KISAN-ൽ ഒരു കർഷകന് വർഷത്തിൽ ലഭിക്കുന്ന തുക എത്ര?", "₹6000", ["₹4000", "₹8000", "₹12000"], "medium"),
    ("PM Ujjwala-യിൽ ഒരു എൽ.പി.ജി. സിലിണ്ടറിന് കേന്ദ്ര സബ്സിഡി എത്ര?", "₹1600", ["₹500", "₹2500", "₹5000"], "hard"),
    ("PM Mudra ഷിഷു വിഭാഗത്തിലെ വായ്പാ പരിധി എത്ര?", "₹50000 വരെ", ["₹10000", "₹2 ലക്ഷം", "₹10 ലക്ഷം"], "medium"),
    ("PM Jeevan Jyoti Bima Yojana-യുടെ ഇൻഷുറൻസ് പരിരക്ഷ എത്ര?", "₹2 ലക്ഷം", ["₹50000", "₹5 ലക്ഷം", "₹10 ലക്ഷം"], "easy"),
    ("PM Suraksha Bima Yojana-യുടെ വാർഷിക പ്രീമിയം എത്ര?", "₹20", ["₹100", "₹500", "₹1000"], "medium"),
    ("PMMVY-യിൽ ഗർഭിണിക്ക് ലഭിക്കുന്ന തുക എത്ര?", "₹5000", ["₹1000", "₹50000", "₹500"], "medium"),
    ("PM Awas Yojana-യിൽ നഗര ഭവന സബ്സിഡി പരിധി ഏതാണ്ട് എത്ര?", "₹2.5 ലക്ഷം", ["₹50000", "₹10 ലക്ഷം", "₹50 ലക്ഷം"], "hard"),
    ("PM Fasal Bima Yojana-യിൽ കർഷകർ നൽകേണ്ട പ്രീമിയം (സാധാരണ) എത്ര ശതമാനം?", "2%", ["10%", "25%", "50%"], "hard"),
    ("Jal Jeevan Mission-ന്റെ ലക്ഷ്യം ഏത് വർഷം വരെ?", "2024", ["2020", "2026", "2030"], "medium"),
    ("Smart Cities Mission-ൽ ഉൾപ്പെടുത്തിയ നഗരങ്ങളുടെ എണ്ണം എത്ര?", "100", ["50", "200", "500"], "medium"),
    ("PM Surya Ghar-ൽ ഒരു കുടുംബത്തിന് കേന്ദ്ര സബ്സിഡി ഏതാണ്ട് എത്ര?", "₹78000", ["₹10000", "₹2 ലക്ഷം", "₹5000"], "hard"),
    ("National Green Hydrogen Mission-ന്റെ 2030 ലക്ഷ്യം എത്ര MMT?", "5 MMT", ["1 MMT", "10 MMT", "20 MMT"], "hard"),
    ("PM Vishwakarma-യിൽ കോളാറ്ററൽ രഹിത വായ്പാ പരിധി ഏതാണ്ട് എത്ര?", "₹1 ലക്ഷം", ["₹10000", "₹10 ലക്ഷം", "₹50 ലക്ഷം"], "hard"),
    ("PM SVANidhi-യിൽ തെരുവ് വ്യാപാരിക്ക് ആദ്യ വായ്പ എത്ര?", "₹10000", ["₹5000", "₹50000", "₹1 ലക്ഷം"], "medium"),
    ("PM Internship Scheme-ൽ ഇന്റേണിന് മാസ സ്റ്റൈപ്പൻഡ് എത്ര?", "₹5000", ["₹1000", "₹15000", "₹500"], "hard"),
    ("PM Daksh-ൽ പരിശീലന കാലയളവിൽ ദിവസേന സ്റ്റൈപ്പൻഡ് എത്ര?", "₹500", ["₹100", "₹2000", "₹50"], "hard"),
    ("PM FME-യിൽ ഒരു യൂണിറ്റിന് പരമാവധി സഹായം എത്ര?", "₹10 ലക്ഷം", ["₹1 ലക്ഷം", "₹50 ലക്ഷം", "₹1 കോടി"], "hard"),
    ("PM SHRI-യിൽ നവീകരിക്കുന്ന സ്കൂളുകളുടെ എണ്ണം ഏതാണ്ട് എത്ര?", "14500+", ["500", "5000", "50000"], "hard"),
    ("PM Gati Shakti-യിൽ ഏകീകരിച്ച മന്ത്രാലയങ്ങളുടെ എണ്ണം എത്ര?", "16", ["5", "25", "50"], "hard"),
    ("PM eBus Sewa-യുടെ ലക്ഷ്യം എത്ര ഇലക്ട്രിക് ബസുകൾ?", "10000+", ["1000", "50000", "100"], "hard"),
    ("Vibrant Villages Programme-ൽ ഉൾപ്പെടുത്തിയ ഗ്രാമങ്ങളുടെ എണ്ണം ഏതാണ്ട് എത്ര?", "2967", ["500", "10000", "100"], "hard"),
    ("PM Janman-ന്റെ ലക്ഷ്യ പ്രാഥമിക വംശജ ജനത എത്ര?", "75", ["25", "150", "500"], "hard"),
    ("PM MITRA-യിൽ സ്ഥാപിക്കാനുള്ള മെഗാ ടെക്സ്റ്റൈൽ പാർക്കുകളുടെ എണ്ണം എത്ര?", "7", ["3", "15", "30"], "hard"),
    ("PM Garib Kalyan Anna Yojana-യിൽ ഓരോ വ്യക്തിക്ക് ലഭിക്കുന്ന അരി എത്ര കിലോ?", "5 കിലോ", ["2 കിലോ", "10 കിലോ", "1 കിലോ"], "medium"),
    ("One Nation One Ration Card-ന്റെ പോർട്ടബിലിറ്റി ലക്ഷ്യം എത്ര കോടി?", "81 കോടി", ["10 കോടി", "150 കോടി", "5 കോടി"], "hard"),
    ("PM POSHAN Abhiyaan-ന്റെ പ്രധാന ലക്ഷ്യം ഏത്?", "കുഞ്ഞുപ്രായ പോഷകാഹാര കുറവ് കുറയ്ക്കൽ", ["റോഡ് നിർമ്മാണം", "വിമാനത്താവളം", "കൽക്കരി ഖനനം"], "medium"),
    ("Mission Indradhanush-ന്റെ പ്രധാന ലക്ഷ്യം ഏത്?", "പൂർണ്ണ ഇമ്മ്യൂനൈസേഷൻ", ["വീട് നിർമ്മാണം", "കാർഷിക വായ്പ", "വിമാന സബ്സിഡി"], "easy"),
    ("UDAN പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "പ്രാദേശിക വിമാന ബന്ധം", ["കാർഷിക ഇൻഷുറൻസ്", "ഗൃഹവൈദ്യുതീകരണം", "വിദ്യാഭ്യാസ സ്കോളർഷിപ്പ്"], "easy"),
]

POOL_SCHEMES: list[str] = [
    "PM Jan Dhan Yojana",
    "PM Fasal Bima Yojana",
    "PM Awas Yojana (നഗരം)",
    "PM Awas Yojana (ഗ്രാമീണ്)",
    "PM Ujjwala Yojana",
    "PM-KISAN",
    "Ayushman Bharat PM-JAY",
    "Beti Bachao Beti Padhao",
    "MGNREGA",
    "Mission Indradhanush",
    "Digital India",
    "Skill India Mission",
    "Swachh Bharat Mission",
    "PM Mudra Yojana",
    "Stand-Up India",
    "DDUGJY",
    "Saubhagya",
    "Jal Jeevan Mission",
    "PM SVANidhi",
    "PM Matsya Sampada Yojana",
    "PM Vishwakarma",
    "PM Surya Ghar",
    "National Green Hydrogen Mission",
    "Smart Cities Mission",
    "UDAN",
    "PM-KUSUM",
    "POSHAN Abhiyaan",
    "AMRUT",
    "Atal Pension Yojana",
    "PM Jeevan Jyoti Bima Yojana",
    "PM Awas Yojana",
    "BharatNet",
    "HRIDAY",
    "PM Gati Shakti",
    "PM SHRI",
    "PM eBus Sewa",
    "PM Internship Scheme",
    "SVAMITVA",
    "PM Suraksha Bima Yojana",
    "Sukanya Samriddhi Yojana",
    "PM-KMY",
    "PM FME",
    "PM Daksh",
    "PM eVIDYA",
    "PM Janman",
    "Vibrant Villages Programme",
    "PM Garib Kalyan Anna Yojana",
    "PM-JAY",
    "PM Mudra Shishu",
    "PMJJBY",
    "PMSBY",
    "PM Matsya Sampada",
    "National Infrastructure Pipeline",
    "PM Garib Kalyan Anna",
    "PMMVY",
    "PM Internship",
    "Vibrant Villages",
    "Sukanya Samriddhi",
    "PM MITRA",
    "PM DevINE",
    "PM Ujjwala",
    "PM Jan Dhan",
    "PM Fasal Bima",
    "PM Awas",
    "Atal Pension",
    "One Nation One Ration Card",
    "National Green Hydrogen",
    "PM WANI",
    "ABDM",
    "PM CARES",
    "PM POSHAN",
    "PM Awas Gramin",
    "PM Awas Urban",
    "POSHAN",
    "Ayushman Bharat",
    "Skill India",
    "Swachh Bharat",
    "PM Mudra",
    "National Food Security Act",
    "Right to Education",
    "National Health Mission",
    "ICDS",
    "NSAP",
    "Smart Cities",
    "PMGSY",
    "PM Suraksha extended",
    "PM Jeevan Jyoti",
    "PM Fasal Bima premium",
    "PM Fasal Bima Kharif",
    "PM Fasal Bima Rabi",
    "PM-JAY secondary care",
    "PM-JAY tertiary",
    "PM-JAY pre-existing",
    "PMJJBY age",
    "PMSBY age",
    "PM Fasal Bima crop loss",
    "PM Fasal Bima post-harvest",
    "PM Fasal Bima localized",
    "PM Fasal Bima prevented sowing",
    "PM-JAY hospitalization",
    "PM-JAY packages",
    "PM-JAY empaneled",
    "PM-JAY portability",
    "PM Fasal Bima PMFBY",
    "PM-JAY launch",
    "PMJJBY annual premium",
    "PMSBY annual premium",
    "PM Fasal Bima govt share",
    "PM-JAY beneficiaries",
    "PM Fasal Bima technology",
    "Ayushman CAPF",
    "RSBY predecessor",
    "PM Fasal Bima yield",
    "PM Mudra Kishore",
    "PM Mudra Tarun",
    "PM SVANidhi 2nd",
    "PM Vishwakarma collateral",
    "Kisan Credit Card",
    "PMMY total",
    "Stand-Up India tenure",
    "PM SVANidhi tenure",
    "PM Vishwakarma toolkit",
    "PM FME credit",
    "PM Mudra collateral",
    "PM SVANidhi interest",
    "PM Vishwakarma training",
    "PM Mudra women",
    "PM SVANidhi digital",
    "Stand-Up India margin",
    "PM FME seed",
    "PM MITRA plug",
    "PM Daksh training",
    "PM Internship companies",
    "PM Vishwakarma loan",
    "PM Mudra NBFC",
    "One Nation One Ration",
]

POOL_YEARS: list[str] = [
    "2005",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
    "2023",
    "2024",
]

POOL_MINISTRIES: list[str] = [
    "ആരോഗ്യ മന്ത്രാലയം",
    "ഇലക്ട്രോണിക്സ് & ഐ.ടി. മന്ത്രാലയം",
    "കാജ് & ഉദ്യോഗ സൃഷ്ടി മന്ത്രാലയം",
    "കൃഷി മന്ത്രാലയം",
    "ഗ്രാമീണ വികസന മന്ത്രാലയം",
    "ജല ശക്തി മന്ത്രാലയം",
    "ധനകാര്യ മന്ത്രാലയം",
    "പുതുനവീകരണ ഊർജ മന്ത്രാലയം",
    "പെട്രോളിയം & പ്രകൃതി വാതക മന്ത്രാലയം",
    "പൗരവ്യവഹാര മന്ത്രാലയം",
    "മത്സ്യബന്ധന മന്ത്രാലയം",
    "വനിതാ & ശിശു വികസന മന്ത്രാലയം",
    "വാണിജ്യ & വ്യവസായ മന്ത്രാലയം",
    "വാസസ്ഥല മന്ത്രാലയം",
    "വിദ്യാഭ്യാസ മന്ത്രാലയം",
]

POOL_SECTORS: list[str] = [
    "അടിസ്ഥാന സൗകര്യ ഏകീകരണം",
    "ആരോഗ്യ ഇൻഷുറൻസ്",
    "ഇലക്ട്രിക് ബസ്",
    "എൽ.പി.ജി. വിതരണം",
    "കാർഷിക സോളാർ ഊർജ",
    "കുടിവെള്ള വിതരണം",
    "കൗശല വികസനം",
    "കർഷക വരുമാന സഹായം",
    "ഗൃഹ സോളാർ",
    "ഗൃഹവൈദ്യുതീകരണം",
    "ഗ്രാമീണ ഭൂമി രേഖ",
    "ചെറുകിട വ്യവസായ വായ്പ",
    "ഡിജിറ്റൽ ഉൾപ്പെടുത്തൽ",
    "തെരുവ് വ്യാപാരി വായ്പ",
    "തൊഴിൽ ഗ്യാരന്റി",
    "നഗര അടിസ്ഥാന സൗകര്യം",
    "നഗര വികസനം",
    "പാരമ്പര്യ കരകുശല",
    "പോഷകാഹാരം",
    "ബ്രോഡ്ബാൻഡ് കണക്ടിവിറ്റി",
    "മത്സ്യബന്ധനം",
    "വാക്സിനേഷൻ",
    "വിമാനയാന സബ്സിഡി",
    "വിള ഇൻഷുറൻസ്",
    "വീട് നിർമ്മാണം",
    "ശുചിത്വം",
    "സംരംഭകത്വം",
    "സാമ്പത്തിക ഉൾപ്പെടുത്തൽ",
    "സ്കൂൾ നവീകരണം",
    "ഹരിത ഹൈഡ്രജൻ",
]

POOL_BENEFICIARIES: list[str] = [
    "18–50 വയസ്സുള്ളവർ",
    "18–70 വയസ്സുള്ളവർ",
    "അതിർത്തി ഗ്രാമങ്ങൾ",
    "അൺഓർഗനൈസ്ഡ് തൊഴിലാളികൾ",
    "ഊർജ മേഖല",
    "എസ്.സി./എസ്.ടി./വനിതാ സംരംഭകർ",
    "കർഷകർ",
    "ഗൃഹസ്ഥർ",
    "ഗ്രാമീണ തൊഴിലാളികൾ",
    "ഗ്രാമീണ ഭൂമി ഉടമകൾ",
    "ചെറുകിട കർഷകർ",
    "ചെറുകിട/അതിർത്തി കർഷകർ",
    "ചെറുകിട/മൈക്രോ യൂണിറ്റുകൾ",
    "തെരുവ് വ്യാപാരികൾ",
    "ദരിദ്ര കുടുംബങ്ങൾ",
    "ദരിദ്ര/ഇടത്തരം കുടുംബങ്ങൾ",
    "നഗര യാത്രക്കാർ",
    "പാരമ്പര്യ കരകുശലർ",
    "പി.വി.ടി.ജി. സമുദായങ്ങൾ",
    "പെൺകുട്ടികൾ",
    "ബാങ്ക് അക്കൗണ്ട് ഇല്ലാത്തവർ",
    "ബി.പി.എൽ. കുടുംബങ്ങൾ",
    "ഭവനരഹിതർ",
    "മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ് യൂണിറ്റുകൾ",
    "യുവ തൊഴിൽ തേടുന്നവർ",
    "യുവാക്കൾ",
    "വിദ്യാർത്ഥികൾ",
    "സ്കൂൾ വിദ്യാർത്ഥികൾ",
]

POOL_ABBREV: list[str] = [
    "DDUGJY",
    "PM CARES",
    "PM Daksh",
    "PM DevINE",
    "PM FME",
    "PM Gati Shakti",
    "PM Internship",
    "PM Janman",
    "PM MITRA",
    "PM POSHAN",
    "PM SHRI",
    "PM SVANidhi",
    "PM Surya Ghar",
    "PM WANI",
    "PM eBus Sewa",
    "PM eVIDYA",
    "PM-JAY",
    "PM-KISAN",
    "PM-KMY",
    "PM-KUSUM",
    "PMAY",
    "PMFBY",
    "PMGSY",
    "PMJAY",
    "PMJDY",
    "PMJJBY",
    "PMMVY",
    "PMMY",
    "PMSBY",
    "PMUY",
]

POOL_FULL_FORMS: list[str] = [
    "ദീൻദയാൽ ഉപാധ്യായ ഗ്രാം ജ്യോതി യോജന",
    "പ്രധാനമന്ത്രി ആവാസ് യോജന",
    "പ്രധാനമന്ത്രി ഇ-ബസ് സേവ",
    "പ്രധാനമന്ത്രി ഇ-വിദ്യ",
    "പ്രധാനമന്ത്രി ഇന്റഗ്രേറ്റഡ് ടെക്സ്റ്റൈൽ റീജിയൺ ആൻഡ് അപ്ലൈഡ്",
    "പ്രധാനമന്ത്രി ഇന്റേൺഷിപ്പ് സ്കീം",
    "പ്രധാനമന്ത്രി ഉജ്ജ്വല യോജന",
    "പ്രധാനമന്ത്രി കിസാൻ ഉർജാ സുരക്ഷാ യോജന",
    "പ്രധാനമന്ത്രി കിസാൻ മാൻ ധൻ യോജന",
    "പ്രധാനമന്ത്രി കിസാൻ സമ്മാൻ നിധി",
    "പ്രധാനമന്ത്രി കെയേഴ്സ്",
    "പ്രധാനമന്ത്രി ഗതി ശക്തി",
    "പ്രധാനമന്ത്രി ഗ്രാമീണ സഡക് യോജന",
    "പ്രധാനമന്ത്രി ജന ആരോഗ്യ യോജന",
    "പ്രധാനമന്ത്രി ജനധൻ യോജന",
    "പ്രധാനമന്ത്രി ജന്ജാതി ആദിവാസി ന്യായ മഹാഅഭിയാൻ",
    "പ്രധാനമന്ത്രി ജീവൻ ജ്യോതി ബീമാ യോജന",
    "പ്രധാനമന്ത്രി തെരുവ് വ്യാപാരി ആത്മനിർഭർ നിധി",
    "പ്രധാനമന്ത്രി ദക്ഷ്",
    "പ്രധാനമന്ത്രി പോഷൺ അഭിയാൻ",
    "പ്രധാനമന്ത്രി ഫസൽ ബീമാ യോജന",
    "പ്രധാനമന്ത്രി ഫോർമലൈസേഷൻ ഓഫ് മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ്",
    "പ്രധാനമന്ത്രി മാതൃ വന്ദന യോജന",
    "പ്രധാനമന്ത്രി മുദ്രാ യോജന",
    "പ്രധാനമന്ത്രി വികസിത് നോർത്ത് ഈസ്റ്റ് ഇൻവെസ്റ്റ്മെന്റ് പ്ലാൻ",
    "പ്രധാനമന്ത്രി വൈ-ഫൈ ആക്സസ് നെറ്റ്വർക്ക് ഇന്റർഫേസ്",
    "പ്രധാനമന്ത്രി സുരക്ഷാ ബീമാ യോജന",
    "പ്രധാനമന്ത്രി സൂര്യ ഘർ മുഫ്ത് ബിജ്ലി യോജന",
    "പ്രധാനമന്ത്രി സ്കൂൾസ് ഫോർ റൈസിംഗ് ഇൻഫ്രാസ്ട്രക്ചർ",
]

POOL_AMOUNTS: list[str] = [
    "100 ദിവസം തൊഴിൽ",
    "5 കിലോ അരി+1 കിലോ ഗോതമ്പ്",
    "₹10 ലക്ഷം/യൂണിറ്റ്",
    "₹10 ലക്ഷം–1 കോടി",
    "₹100 ലക്ഷം കോടി+",
    "₹10000 വരെ",
    "₹1000–5000/മാസം പെൻഷൻ",
    "₹111 ലക്ഷം കോടി",
    "₹1600 സബ്സിഡി/സിലിണ്ടർ",
    "₹19744 കോടി",
    "₹2 ലക്ഷം",
    "₹20000 കോടി",
    "₹24100 കോടി",
    "₹250/വർഷം മുതൽ",
    "₹27360 കോടി",
    "₹3 ലക്ഷം വരെ",
    "₹3.6 ലക്ഷം കോടി",
    "₹34400 കോടി",
    "₹4200 കോടി പ്ലാൻഡ്",
    "₹4800 കോടി",
    "₹5 ലക്ഷം/കുടുംബം/വർഷം",
    "₹500/ദിവസം സ്റ്റൈപ്പൻഡ്",
    "₹5000",
    "₹5000/മാസം",
    "₹50000 വരെ",
    "₹5761 കോടി",
    "₹6000/വർഷം",
    "₹7400 കോടി",
    "₹78000 സബ്സിഡി",
]

POOL_DBT: list[str] = [
    "ആംഗൻവാടി/സ്കൂൾ വഴി",
    "ഇപിഎഫ്ഒ/ബാങ്ക്",
    "ഓട്ടോ-ഡെബിറ്റ്",
    "ഓൺഓആർസി/പോർട്ടബിൾ റേഷൻ",
    "ഓൺലൈൻ ദാനം",
    "ഓൺലൈൻ പ്ലാറ്റ്ഫോം",
    "കേന്ദ്ര അനുവദനം",
    "കേന്ദ്ര ഫണ്ട്",
    "കേന്ദ്ര-സംസ്ഥാന ഫണ്ട്",
    "ഡിജിറ്റൽ പേമെന്റ്",
    "ഡിജിറ്റൽ പ്ലാറ്റ്ഫോം",
    "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി",
    "നേരിട്ട് ബാങ്ക് അക്കൗണ്ടിലേക്ക്",
    "പി.പി.പി. മോഡൽ",
    "പെൻഷൻ ഫണ്ട് വഴി",
    "പ്ലാൻഡ് ലിങ്ക്",
    "പ്ലാൻഡ് ലിങ്ക് ഇൻസെന്റിവ്",
    "ബാങ്ക് അക്കൗണ്ട്",
    "ബാങ്ക് അക്കൗണ്ട് വഴി",
    "ബാങ്ക് വഴി",
    "ബാങ്ക് വായ്പ+സബ്സിഡി",
    "ബാങ്ക്/ഓൺലൈൻ",
    "റേഷൻ കാർഡ്/ഓൺഓആർസി",
    "വിഎഗ്എഫ്/സബ്സിഡി",
    "സംസ്ഥാന-കേന്ദ്ര ഫണ്ട്",
    "സബ്സിഡി ഡിജിറ്റൽ ട്രാൻസ്ഫർ",
    "സർക്കാർ അക്കൗണ്ട്",
]

POOL_PARENTS: list[str] = [
    "Aatmanirbhar Bharat",
    "Ayushman Bharat",
    "Ayushman Bharat Digital Mission",
    "Border Area Development",
    "Digital India",
    "FAME India",
    "Make in India",
    "NEP 2020",
    "National Hydrogen Mission",
    "National Infrastructure Pipeline",
    "National Nutrition Mission",
    "National Solar Mission",
    "North-East Special Package",
    "PM Garib Kalyan Package",
    "PM JANMAN",
    "PMAY",
    "Regional Connectivity Scheme",
    "Skill India",
    "Smart Cities Mission",
    "Universal Immunization Programme",
    "ജന സുരക്ഷാ പദ്ധതികൾ",
]

POOL_STATES: list[str] = [
    "അരുണാചൽ പ്രദേശ്",
    "അസം",
    "ആന്ധ്രാപ്രദേശ്",
    "ഉത്തരാഖണ്ഡ്",
    "ഉത്തർപ്രദേശ്",
    "ഒഡിഷ",
    "കേരളം",
    "കർണാടക",
    "ഗുജറാത്ത്",
    "ഛത്തീസ്ഗഢ്",
    "തമിഴ്നാട്",
    "ഭുവനേശ്വർ",
    "മണിപ്പൂർ",
    "മധ്യപ്രദേശ്",
    "മഹാരാഷ്ട്ര",
    "രാജസ്ഥാൻ",
    "റായ്ബറേലി",
    "ഷില്ലോം",
]

POOL_LAWS: list[str] = [
    "2013 നിയമം",
    "Ayushman Bharat Mission",
    "Digital India പ്രോഗ്രാം",
    "ICDS മിഷൻ",
    "JJM മിഷൻ",
    "MGNREGA നിയമം 2005",
    "NHM മിഷൻ",
    "NSAP മിഷൻ",
    "National Green Hydrogen Mission",
    "PM Gati Shakti Master Plan",
    "PM Internship Scheme",
    "PM JANMAN Mission",
    "PM SHRI Scheme",
    "PM SVANidhi മിഷൻ",
    "PM Surya Ghar മിഷൻ",
    "PM Vishwakarma മിഷൻ",
    "PM eBus Sewa Scheme",
    "PM-KISAN മിഷൻ",
    "PMAY മിഷൻ",
    "PMFBY മാർഗനിർദ്ദേശം",
    "PMJDY മിഷൻ",
    "PMMVY മിഷൻ",
    "PMMY മിഷൻ",
    "PMUY മിഷൻ",
    "RTE നിയമം 2009",
    "Skill India Mission",
    "Stand-Up India മിഷൻ",
    "Swachh Bharat Mission",
    "VVP Guidelines",
]

POOL_NODAL: list[str] = [
    "AAI",
    "BSNL/BBNL",
    "DoE",
    "DoLR",
    "DoNER",
    "DoSE",
    "Fisheries Dept",
    "HUDCO",
    "JJM",
    "Logistics Division",
    "MNRE",
    "MSDE",
    "MeitY",
    "MoHA",
    "MoHFW",
    "MoHUA",
    "MoTA",
    "NHA",
    "NSDC",
    "SIDBI",
    "Textiles Ministry",
    "WCD Ministry",
    "കൃഷി മന്ത്രാലയം",
    "ഗ്രാമീണ വികസന മന്ത്രാലയം",
    "വാസസ്ഥല മന്ത്രാലയം",
]

POOL_PREDECESSORS: list[str] = [
    "CRSP",
    "DDU-GKY",
    "DDUGJY",
    "FAME II",
    "Hunar Se Rozgar",
    "IAY/Indira Awas",
    "ICDS+",
    "JNNURM",
    "MUDRA Bank concept",
    "Model Schools",
    "NAIS/MAIS",
    "NRHM+NUHM",
    "NRWDP",
    "National Hydrogen Energy Mission",
    "National e-Governance Plan",
    "Nirmal Bharat",
    "Off-grid solar",
    "PAHAL",
    "PM Street Vendor scheme",
    "PM-KISAN pilot 2018",
    "PMGS/NIP",
    "RGGVY",
    "RSBY",
    "Regional Air Connectivity",
    "Rooftop Solar Scheme",
    "SGRY/NREG",
    "Startup India complement",
    "Swabhiman",
]

POOL_INSURANCE: list[str] = [
    "1500+ പാക്കേജുകൾ",
    "18–50 വയസ്",
    "18–70 വയസ്",
    "2018 സെപ്റ്റംബർ",
    "50 കോടി ലക്ഷ്യം",
    "PMFBY 2016 മുതൽ",
    "ആശുപത്രി ചെലവ്",
    "ഓൾ ഇന്ത്യ",
    "കൃഷി സീസൺ പരിരക്ഷ",
    "കേന്ദ്ര+സംസ്ഥാന സബ്സിഡി",
    "കർഷകർ 2% മാത്രം",
    "ടെർഷ്യറി ചികിത്സ",
    "പോസ്റ്റ് ഹാർവെസ്റ്റ്",
    "പ്രാദേശിക കാലാവസ്ഥ",
    "മുൻരോഗം ഉൾപ്പെടെ",
    "റാബി സീസൺ പരിരക്ഷ",
    "റിമോട്ട് സെൻസിംഗ്+ഡ്രോൺ",
    "വിത്തിടൽ തടസ്സം",
    "വിള നഷ്ട പരിരക്ഷ",
    "വിളവ് നഷ്ട പരിരക്ഷ",
    "സെക്കൻഡറി+ടെർഷ്യറി",
    "സ്വാഭാവിക ദുരന്തം",
    "സർക്കാർ+സ്വകാര്യം",
    "₹2 ലക്ഷം",
    "₹20",
    "₹30000 പരിരക്ഷ",
    "₹436",
    "₹5 ലക്ഷം",
    "₹5 ലക്ഷം/വർഷം",
]

POOL_LOANS: list[str] = [
    "1 വർഷം",
    "2% പലിശ സബ്സിഡി",
    "25% മാർജിൻ",
    "3 മാസം",
    "35% ഗ്രാൻ്റ്",
    "500+ കമ്പനികൾ",
    "5–7 ദിവസം+6 മാസം",
    "68% വനിതാ സംരംഭകർ",
    "7 വർഷം",
    "7% സബ്സിഡി",
    "NBFC/MFI വഴി",
    "QR കോഡ് സഹായം",
    "ഉപകരണ സഹായം",
    "കാർഷിക വായ്പ",
    "കോളാറ്ററൽ രഹിതം",
    "പ്ലഗ് ആൻഡ് പ്ലേ",
    "₹1 ലക്ഷം കോളാറ്ററൽ രഹിതം",
    "₹10 ലക്ഷം",
    "₹10 ലക്ഷം–1 കോടി",
    "₹10000",
    "₹20 ലക്ഷം കോടി ലക്ഷ്യം",
    "₹20000",
    "₹3 ലക്ഷം വരെ",
    "₹4200 കോടി പ്ലാൻഡ്",
    "₹500/ദിവസം",
    "₹5000/മാസം",
    "₹50000 വരെ",
    "₹50000–5 ലക്ഷം",
    "₹5–10 ലക്ഷം",
]

POOL_TARGETS: list[str] = [
    "1 കോടി ഇന്റേൺഷിപ്പ്",
    "1 കോടി ഗൃഹങ്ങൾ",
    "10 കോടി+ വായ്പകൾ",
    "100 നഗരങ്ങൾ",
    "100+ വിമാനത്താവളങ്ങൾ",
    "10000+ ബസുകൾ",
    "14 കോടി കർഷകർ",
    "14500+ സ്കൂളുകൾ",
    "16 മന്ത്രാലയങ്ങൾ",
    "2 കോടി വീടുകൾ",
    "2.5 ലക്ഷം ഗ്രാമ പഞ്ചായത്തുകൾ",
    "2.95 കോടി വീടുകൾ",
    "2967 ഗ്രാമങ്ങൾ",
    "30 ലക്ഷം കരകുശലർ",
    "40 കോടി പേർ",
    "5 MMT/വർഷം",
    "5 കോടി+ കുടുംബങ്ങൾ",
    "50 കോടി",
    "50 ലക്ഷം വ്യാപാരികൾ",
    "7 മെഗാ ടെക്സ്റ്റൈൽ പാർക്ക്",
    "8 കോടി+ കുടുംബങ്ങൾ",
    "80 കോടി+",
    "90%+ പൂർണ്ണ ഇമ്മ്യൂനൈസേഷൻ",
    "PVTG 75 ജനത",
    "എല്ലാ കുടുംബങ്ങൾ",
    "എല്ലാ ഗ്രാമങ്ങളും ഡിജിറ്റൽ",
    "എല്ലാ ഗ്രാമങ്ങൾ 2024",
    "എല്ലാ ജില്ലകളും",
    "ഓപ്പൺ ഡിഫെക്കേഷൻ ഫ്രീ",
    "നോർത്ത്-ഈസ്റ്റ് 8 സംസ്ഥാനങ്ങൾ",
]

POOL_FUNDING: list[str] = [
    "REFINANCE മോഡൽ",
    "കേന്ദ്ര 100%",
    "കേന്ദ്ര 100% ശമ്പളം",
    "കേന്ദ്ര 60%",
    "കേന്ദ്ര 60% സംസ്ഥാന 40%",
    "കേന്ദ്ര CSR",
    "കേന്ദ്ര PLI",
    "കേന്ദ്ര+സംസ്ഥാന+PSU",
    "കേന്ദ്ര+സംസ്ഥാന+സ്വകാര്യം",
    "കേന്ദ്ര-ULB",
    "കേന്ദ്ര-സംസ്ഥാന",
    "കേന്ദ്ര-സംസ്ഥാന 50:50",
    "കേന്ദ്ര-സംസ്ഥാന 60:40",
    "കേന്ദ്ര-സംസ്ഥാന പ്രീമിയം",
    "ബാങ്ക് വായ്പ",
    "യുഎസ്ഒഫ്+കേന്ദ്ര",
    "വിഎഗ്എഫ്",
    "വിഎഗ്എഫ്+സബ്സിഡി",
]

POOL_PORTALS: list[str] = [
    "abdm.gov.in",
    "civilaviation.gov.in",
    "digitalindia.gov.in",
    "diksha.gov.in",
    "doner.gov.in",
    "jaljeevanmission.gov.in",
    "jansuraksha.gov.in",
    "mha.gov.in",
    "mnre.gov.in",
    "mohua.gov.in",
    "mudra.org.in",
    "nfsa.gov.in",
    "nrega.nic.in",
    "pmaymis.gov.in",
    "pmfby.gov.in",
    "pmgatishakti.gov.in",
    "pminternship.mca.gov.in",
    "pmjay.gov.in",
    "pmkisan.gov.in",
    "pmshrischools.education.gov.in",
    "pmsuryaghar.gov.in",
    "pmsvanidhi.mohua.gov.in",
    "pmuy.gov.in",
    "pmvishwakarma.gov.in",
    "sbm.gov.in",
    "skillindia.gov.in",
    "smartcities.gov.in",
    "tribal.nic.in",
    "wani.gov.in",
]

POOL_PMS: list[str] = [
    "നരേന്ദ്ര മോദി",
    "മനമോഹൻ സിംഗ്",
]

POOL_UMBRELLA: list[str] = [
    "Aatmanirbhar Bharat",
    "Ayushman Bharat",
    "Ayushman Bharat Digital Mission",
    "Border Development",
    "Digital India",
    "FAME India",
    "Make in India",
    "NEP 2020",
    "National Hydrogen Mission",
    "National Infrastructure Pipeline",
    "National Nutrition Mission",
    "National Solar Mission",
    "North-East Package",
    "PM Garib Kalyan",
    "PM JANMAN",
    "PMAY",
    "RCS",
    "Skill India",
    "Smart Cities",
    "Universal Immunization",
    "ജന സുരക്ഷാ പദ്ധതികൾ",
]

POOL_WOMEN_SCHEMES: list[str] = [
    "Beti Bachao Beti Padhao",
    "Gender Budgeting",
    "Mahila Police Volunteer",
    "National Creche",
    "One Stop Centre Sakhi",
    "PM Awas",
    "PM Awas Urban women",
    "PM Daksh",
    "PM Garib Kalyan Anna",
    "PM Internship",
    "PM Jan Dhan",
    "PM Matru Vandana",
    "PM Mudra",
    "PM Mudra women share",
    "PM POSHAN",
    "PM SHRI",
    "PM SHRI girls toilet",
    "PM SVANidhi",
    "PM Surya Ghar",
    "PM Ujjwala",
    "PM Ujjwala 2.0",
    "PM Vishwakarma",
    "PM eVIDYA",
    "PM-JAY",
    "PMMVY",
    "She-Box",
    "Stand-Up India",
    "Sukanya Samriddhi",
    "Ujjawala Trafficking",
    "Working Women Hostel",
]

POOL_WOMEN_GOALS: list[str] = [
    "68% വനിതാ വായ്പ",
    "ഔദ്യോഗിക പീഡന പരാതി",
    "കടത്തുകാരുടെ പുനരധിവാസം",
    "ഗൃഹിണി ഊർജ സ്വാതന്ത്ര്യം",
    "ഗർഭിണി+മുലയൂട്ടുന്ന വനിത",
    "ഗർഭിണി+ശിശു പോഷകാഹാരം",
    "ജോലിക്കാരായ വനിത",
    "താമസ സൗകര്യം",
    "പെൺകുട്ടികളുടെ ഓൺലൈൻ വിദ്യാഭ്യാസം",
    "പെൺകുട്ടികളുടെ വിദ്യാഭ്യാസം",
    "പെൺകുട്ടികളുടെ സംരക്ഷണം",
    "പെൺകുട്ടികൾക്ക് ശുചിമുറി",
    "പെൺകുട്ടിയുടെ ഭാവി സമ്പാദ്യം",
    "മാതൃ ആരോഗ്യം",
    "മാതൃ സംരക്ഷണ നേട്ടം",
    "മാതൃ+ശിശു ആരോഗ്യം",
    "മിഗ്രന്റ് കുടുംബങ്ങൾ",
    "യുവതി കൗശലം",
    "യുവതി തൊഴിൽ",
    "ലിംഗ സമത",
    "വനിതാ ആരോഗ്യ സംരക്ഷണം",
    "വനിതാ കരകുശലർ",
    "വനിതാ തെരുവ് വ്യാപാരികൾ",
    "വനിതാ ഭവന ഉടമസ്ഥത",
    "വനിതാ സംരംഭകത്വം",
    "വനിതാ സാമ്പത്തിക ഉൾപ്പെടുത്തൽ",
    "സംയുക്ത ഉടമസ്ഥത",
    "സുരക്ഷാ സഹായം",
    "ഹിംസയെ നേരിടുന്ന വനിത",
]

POOL_RURAL_SCHEMES: list[str] = [
    "BharatNet",
    "DAY-NRLM",
    "DDUGJY",
    "Jal Jeevan Mission",
    "Kisan Credit Card",
    "MGNREGA",
    "MGNREGA asset",
    "National Food Security",
    "National Rural Livelihood",
    "PM Awas Gramin",
    "PM Awas Gramin toilet",
    "PM Daksh",
    "PM FME",
    "PM Fasal Bima",
    "PM Garib Kalyan Anna",
    "PM Jan Dhan",
    "PM Janman",
    "PM Matsya Sampada",
    "PM Surya Ghar rural",
    "PM Ujjwala rural",
    "PM Vishwakarma",
    "PM-KISAN",
    "PM-KMY",
    "PM-KUSUM",
    "PMGSY",
    "RKVY",
    "SVAMITVA",
    "Saubhagya",
    "Soil Health Card",
    "Vibrant Villages",
]

POOL_RURAL_GOALS: list[str] = [
    "100 ദിവസം തൊഴിൽ",
    "PVTG ഗ്രാമ വികസനം",
    "അതിർത്തി ഗ്രാമ വികസനം",
    "എല്ലാ ഗൃഹങ്ങൾക്കും വൈദ്യുതി",
    "എല്ലാ ഗ്രാമങ്ങൾക്കും കുടിവെള്ളം",
    "കാർഷിക വികസനം",
    "കാർഷിക സോളാർ",
    "കർഷക പെൻഷൻ",
    "കർഷക വരുമാനം",
    "ഗ്രാമീണ എൽ.പി.ജി.",
    "ഗ്രാമീണ കരകുശല",
    "ഗ്രാമീണ തൊഴിൽ",
    "ഗ്രാമീണ ഫുഡ് പ്രോസസ്സിംഗ്",
    "ഗ്രാമീണ ബാങ്കിംഗ്",
    "ഗ്രാമീണ ബ്രോഡ്ബാൻഡ്",
    "ഗ്രാമീണ ഭക്ഷ്യ സുരക്ഷ",
    "ഗ്രാമീണ ഭൂമി രേഖ",
    "ഗ്രാമീണ യുവ കൗശലം",
    "ഗ്രാമീണ റോഡ്",
    "ഗ്രാമീണ വൈദ്യുതീകരണം",
    "ഗ്രാമീണ സോളാർ",
    "ജല സംരക്ഷണം",
    "പാക്കാ വീട്",
    "മണ്ണിന്റെ ആരോഗ്യം",
    "മത്സ്യബന്ധന വികസനം",
    "റേഷൻ സുരക്ഷ",
    "വിള നഷ്ട പരിരക്ഷ",
    "ശുചിമുറി ഉൾപ്പെടെ",
    "സമയോചിത കാർഷിക വായ്പ",
    "സ്വയം സഹായ ഗ്രൂപ്പ്",
]

POOL_URBAN_SCHEMES: list[str] = [
    "AMRUT",
    "AMRUT 2.0",
    "AMRUT parks",
    "AMRUT sewerage",
    "AMRUT water",
    "Digital India urban",
    "HRIDAY",
    "HRIDAY Varanasi",
    "Metro Neo",
    "Metro Rail projects",
    "PM Awas CLSS",
    "PM Awas Urban",
    "PM Awas in-situ",
    "PM Gati Shakti multimodal",
    "PM Gati Shakti urban",
    "PM MITRA",
    "PM Mudra urban",
    "PM SHRI urban schools",
    "PM SVANidhi",
    "PM SVANidhi urban local",
    "PM WANI",
    "PM eBus Sewa",
    "PM eBus green",
    "Smart Cities Mission",
    "Smart City IoT",
    "Smart City SPV",
    "Smart City lighthouse",
    "Stand-Up India urban",
    "Swachh Bharat Urban",
    "UDAN",
]

POOL_URBAN_GOALS: list[str] = [
    "നഗര അടിസ്ഥാന സൗകര്യം",
    "നഗര ഇലക്ട്രിക് ബസ്",
    "നഗര കാർബൺ കുറയ്ക്കൽ",
    "നഗര കുടിവെള്ളം",
    "നഗര ജല സംരക്ഷണം",
    "നഗര ടെക്സ്റ്റൈൽ പാർക്ക്",
    "നഗര ട്രാൻസ്പോർട്ട് ഹബ്",
    "നഗര ഡിജിറ്റൽ",
    "നഗര തെരുവ് വ്യാപാരം",
    "നഗര നവീകരണം",
    "നഗര പാർക്ക്",
    "നഗര പുനര്വാസം",
    "നഗര ഭവനരഹിതർക്ക് വീട്",
    "നഗര മലിനജലം",
    "നഗര ലോജിസ്റ്റിക്സ്",
    "നഗര വായ്പ സബ്സിഡി",
    "നഗര വികസന ഏജൻസി",
    "നഗര വിമാന ബന്ധം",
    "നഗര ശുചിത്വം",
    "നഗര സംരംഭകത്വം",
    "നഗര സ്കൂൾ നവീകരണം",
    "നഗര സ്ഥാനിക സ്വയംഭരണം",
    "പബ്ലിക് വൈ-ഫി",
    "പൈതൃക നഗരങ്ങൾ",
    "മാതൃക നഗരം",
    "മെട്രോ റെയിൽ",
    "ലഘു മെട്രോ",
    "വാരണാസി പൈതൃകം",
    "സ്മാർട്ട് സെൻസർ",
]

POOL_AGRI_SCHEMES: list[str] = [
    "Blue Revolution",
    "Horticulture Mission",
    "Kisan Credit Card",
    "National Bamboo Mission",
    "National Livestock Mission",
    "National Mission Oil Palm",
    "PM Aasha",
    "PM Aasha MSP",
    "PM FME",
    "PM FME cluster",
    "PM FME micro",
    "PM Fasal Bima",
    "PM Fasal Bima crop",
    "PM Fasal Bima tech",
    "PM Matsya Sampada",
    "PM Matsya infrastructure",
    "PM-KISAN",
    "PM-KISAN exclusion",
    "PM-KISAN instalment",
    "PM-KMY",
    "PM-KUSUM",
    "PM-KUSUM component A",
    "PM-KUSUM component B",
    "PM-KUSUM component C",
    "PMKSY",
    "Paramparagat Krishi",
    "RKVY",
    "RKVY RAFTAAR",
    "Soil Health Card",
    "e-NAM",
]

POOL_AGRI_GOALS: list[str] = [
    "MSP+20%",
    "ആഗ്രി വിപണി",
    "എഡിബിൾ ഓയിൽ പാം",
    "കന്നുകാലി വികസനം",
    "കാർഷിക നവീകരണം",
    "കാർഷിക വായ്പ",
    "കാർഷിക വികസനം",
    "കാർഷിക സോളാർ പമ്പ്",
    "കർഷക പെൻഷൻ",
    "കർഷക വരുമാന സഹായം",
    "ഗ്രിഡ് കണക്ടഡ് സോളാർ",
    "ജല സേചനം",
    "ജൈവ കൃഷി",
    "ഡ്രോൺ+സാറ്റലൈറ്റ്",
    "തോട്ടക്കൃഷി",
    "പ്രധാന വിളകൾ",
    "ഫുഡ് ക്ലസ്റ്റർ",
    "ഫുഡ് പ്രോസസ്സിംഗ്",
    "മണ്ണിന്റെ ആരോഗ്യം",
    "മത്സ്യ ഉൽപ്പാദനം",
    "മത്സ്യ തുറമുഖം",
    "മത്സ്യബന്ധനം",
    "മുള വികസനം",
    "മൈക്രോ ഫുഡ് യൂണിറ്റ്",
    "വരുമാന നികുതി ദാതാക്കൾ",
    "വിപണി വില സ്ഥിരത",
    "വിള ഇൻഷുറൻസ്",
    "സോളാർ പമ്പ്",
    "സ്റ്റാൻഡ് അലോൺ പമ്പ്",
    "₹2000/തവണ",
]

POOL_HEALTH_SCHEMES: list[str] = [
    "ABDM",
    "Ayushman Bharat PM-JAY",
    "Mission Indradhanush",
    "Mission Indradhanush 4.0",
    "National AIDS Control",
    "National Ayush Mission",
    "National Digital Health",
    "National Health Mission",
    "National Health Policy 2017",
    "National TB Elimination",
    "PM Ayushman 5 lakh",
    "PM Ayushman CAPF",
    "PM Ayushman Health ID",
    "PM Ayushman Health Infra",
    "PM Ayushman PMJAY package",
    "PM Ayushman dialysis",
    "PM Ayushman empaneled",
    "PM Ayushman free drugs",
    "PM Ayushman free test",
    "PM Ayushman launch 2018",
    "PM Ayushman portability",
    "PM Ayushman secondary",
    "PM Ayushman tertiary",
    "PM Ayushman wellness",
    "PM POSHAN",
    "PM POSHAN tracker",
    "PM eSanjeevani",
    "PMMVY",
    "PMMVY 5000",
    "PMSSY",
]

POOL_HEALTH_GOALS: list[str] = [
    "1500+ പാക്കേജ്",
    "2018 സെപ്റ്റംബർ",
    "CAPF ആരോഗ്യം",
    "ആയുർവേദം",
    "ആരോഗ്യ അടിസ്ഥാന സൗകര്യം",
    "ആരോഗ്യ ഇൻഷുറൻസ്",
    "ആരോഗ്യ ഐഡി",
    "ആരോഗ്യ സേവനം",
    "എയ്ഡ്സ് നിയന്ത്രണം",
    "ഓൾ ഇന്ത്യ ചികിത്സ",
    "ക്ഷയരോഗ നിർമാർജനം",
    "ടെലിമെഡിസിൻ",
    "ടെർഷ്യറി ആശുപത്രി",
    "ഡയാലിസിസ്",
    "ഡിജിറ്റൽ ഹെൽത്ത്",
    "പൂർണ്ണ ഇമ്മ്യൂനൈസേഷൻ",
    "പോഷകാഹാരം",
    "പോഷൺ ട്രാക്കർ",
    "മാതൃ സംരക്ഷണം",
    "മെഡിക്കൽ കോളേജ്",
    "വാക്സിനേഷൻ",
    "വെൽനസ് സെന്റർ",
    "സാർവത്രിക ആരോഗ്യം",
    "സെക്കൻഡറി ആശുപത്രി",
    "സൗജന്യ പരിശോധന",
    "സൗജന്യ മരുന്ന്",
    "സർക്കാർ+സ്വകാര്യം",
    "ഹെൽത്ത് റെക്കോർഡ്",
    "₹5 ലക്ഷം പരിരക്ഷ",
    "₹5000 മാതൃ നേട്ടം",
]

POOL_EDU_SCHEMES: list[str] = [
    "Beti Bachao education",
    "DIKSHA",
    "DIKSHA teacher",
    "Mid-Day Meal",
    "Mid-Day Meal nutrition",
    "NEP 2020",
    "NEP multidisciplinary",
    "National Education Policy",
    "National Scholarship Portal",
    "PM Daksh",
    "PM Daksh apprenticeship",
    "PM Internship",
    "PM Internship 5000",
    "PM POSHAN school",
    "PM SHRI",
    "PM SHRI 14500 schools",
    "PM SHRI NEP aligned",
    "PM SHRI green school",
    "PM SHRI lab",
    "PM eVIDYA",
    "PM eVIDYA DTH",
    "PM eVIDYA one class",
    "PM eVIDYA radio",
    "PM eVIDYA special",
    "RTE 25% EWS",
    "RTE Act",
    "SWAYAM",
    "SWAYAM MOOC",
    "Samagra Shiksha",
    "Samagra Shiksha integrated",
]

POOL_EDU_GOALS: list[str] = [
    "14500+ സ്കൂൾ",
    "2030 ലക്ഷ്യം",
    "NEP അനുസൃത സ്കൂൾ",
    "SSA+RMSA+TE",
    "അധ്യാപക പരിശീലനം",
    "അപ്രന്റിസ്ഷിപ്പ്",
    "ഉചിത+നിർബന്ധിത വിദ്യാഭ്യാസം",
    "ഒരു ചാനൽ ഒരു തരം",
    "ഓൺലൈൻ കോഴ്സ്",
    "ഓൺലൈൻ വിദ്യാഭ്യാസം",
    "ഡിജിറ്റൽ ടിവി ചാനൽ",
    "ഡിജിറ്റൽ വിദ്യാഭ്യാസം",
    "പെൺകുട്ടി വിദ്യാഭ്യാസം",
    "പോഷകാഹാര മാനദണ്ഡം",
    "പ്രത്യേക ആവശ്യകത",
    "ബഹു-വിഷയ പഠനം",
    "ഭോജന പദ്ധതി",
    "മാതൃക സ്കൂൾ",
    "യുവ കൗശലം",
    "യുവ തൊഴിൽ പരിശീലനം",
    "രേഡിയോ വിദ്യാഭ്യാസം",
    "ലാബ്+ലൈബ്രറി",
    "വിദ്യാഭ്യാസ നയം",
    "വിദ്യാഭ്യാസ സ്കോളർഷിപ്പ്",
    "സമഗ്ര വിദ്യാഭ്യാസം",
    "സാമ്പത്തിക പിന്നോക്ക വിഭാഗം",
    "സ്കൂൾ പോഷകാഹാരം",
    "സൗജന്യ ഓൺലൈൻ കോഴ്സ്",
    "ഹരിത സ്കൂൾ",
    "₹5000/മാസം",
]

POOL_HOUSING_SCHEMES: list[str] = [
    "PM Awas 2 crore urban",
    "PM Awas 2.95 crore gramin",
    "PM Awas 2022 target urban",
    "PM Awas CLSS",
    "PM Awas Gramin",
    "PM Awas Gramin 2024",
    "PM Awas Gramin IAY",
    "PM Awas LPG",
    "PM Awas MIS",
    "PM Awas PMAY-G",
    "PM Awas PMAY-U",
    "PM Awas Urban",
    "PM Awas Urban JNNURM",
    "PM Awas affordable rental",
    "PM Awas beneficiary led",
    "PM Awas coastal",
    "PM Awas convergence",
    "PM Awas cost sharing",
    "PM Awas electricity",
    "PM Awas full house",
    "PM Awas geo tag",
    "PM Awas hilly",
    "PM Awas in-situ slum",
    "PM Awas north-east",
    "PM Awas plinth",
    "PM Awas subsidy",
    "PM Awas technology",
    "PM Awas toilet",
    "PM Awas tribal",
    "PM Awas women ownership",
]

POOL_HOUSING_GOALS: list[str] = [
    "2 കോടി ലക്ഷ്യം",
    "2.95 കോടി ലക്ഷ്യം",
    "2022 ലക്ഷ്യം",
    "2024 ലക്ഷ്യം",
    "Indira Awas പരിഷ്കാരം",
    "JNNURM പരിഷ്കാരം",
    "MGNREGA+Swachh",
    "pmaymis.gov.in",
    "എൽ.പി.ജി. കണക്ഷൻ",
    "കേന്ദ്ര-സംസ്ഥാന",
    "ഗ്രാമീണ ഘടകം",
    "ഗ്രാമീണ ഭവനരഹിതർക്ക് വീട്",
    "ജിയോ ടാഗിംഗ്",
    "താവുകള പുനര്വാസം",
    "തീരദേശം",
    "നഗര ഘടകം",
    "നഗര ഭവനരഹിതർക്ക് വീട്",
    "നവീന നിർമ്മാണ സാങ്കേതികവിദ്യ",
    "പൂർണ്ണ വീട്",
    "പ്ലിന്ത് മാത്രം",
    "പർവത പ്രദേശം",
    "വടക്കുകിഴക്കൻ സംസ്ഥാനം",
    "വനവാസി പ്രദേശം",
    "വാടക വീട്",
    "വായ്പ സബ്സിഡി",
    "വൈദ്യുതി കണക്ഷൻ",
    "ശുചിമുറി ഉൾപ്പെടെ",
    "സംയുക്ത ഉടമസ്ഥത",
    "സ്വയം നിർമ്മാണം",
    "₹2.5 ലക്ഷം വരെ",
]

POOL_EMP_SCHEMES: list[str] = [
    "Atal Innovation",
    "DDU-GKY",
    "MGNREGA",
    "Make in India",
    "National Green Hydrogen",
    "National Rural Livelihood",
    "PLI scheme",
    "PM Daksh",
    "PM Daksh stipend",
    "PM DevINE",
    "PM FME",
    "PM Garib Kalyan",
    "PM Gati Shakti",
    "PM Internship",
    "PM Internship 1 crore",
    "PM Janman",
    "PM MITRA",
    "PM Matsya Sampada",
    "PM Mudra",
    "PM SHRI",
    "PM SVANidhi",
    "PM Surya Ghar",
    "PM Vishwakarma",
    "PM WANI",
    "PM eBus Sewa",
    "PM eVIDYA",
    "Skill India",
    "Stand-Up India",
    "Startup India",
    "Vibrant Villages",
]

POOL_EMP_GOALS: list[str] = [
    "1 കോടി ഇന്റേൺഷിപ്പ്",
    "100 ദിവസം തൊഴിൽ",
    "PVTG തൊഴിൽ",
    "അതിർത്തി തൊഴിൽ",
    "അപ്രന്റിസ്ഷിപ്പ്",
    "ഇന്റേൺഷിപ്പ്",
    "ഇൻഫ്രാ തൊഴിൽ",
    "കൗശല വികസനം",
    "ഗ്രീൻ ജോബ്",
    "ടെക്സ്റ്റൈൽ തൊഴിൽ",
    "ഡിജിറ്റൽ തൊഴിൽ",
    "താൽക്കാലിക തൊഴിൽ",
    "തെരുവ് വ്യാപാര തൊഴിൽ",
    "നവീന തൊഴിൽ",
    "നിർമ്മാണ തൊഴിൽ",
    "നോർത്ത്-ഈസ്റ്റ് തൊഴിൽ",
    "പാരമ്പര്യ തൊഴിൽ",
    "ഫുഡ് പ്രോസസ്സിംഗ് തൊഴിൽ",
    "മത്സ്യ തൊഴിൽ",
    "യുവ തൊഴിൽ",
    "വിദ്യാഭ്യാസ തൊഴിൽ",
    "വൈ-ഫി തൊഴിൽ",
    "സംരംഭകത്വം",
    "സോളാർ തൊഴിൽ",
    "സ്റ്റാർട്ടപ്പ്",
    "സ്വയം തൊഴിൽ",
    "സ്വയം സഹായ തൊഴിൽ",
    "ഹരിത ഊർജ തൊഴിൽ",
    "₹500/ദിവസം",
]

POOL_DIGITAL_SCHEMES: list[str] = [
    "ABDM",
    "Aarogya Setu",
    "BharatNet",
    "COWIN certificate",
    "CoWIN",
    "DIKSHA",
    "DigiLocker",
    "Digital India",
    "GeM",
    "India Stack",
    "ONORC",
    "PM Awas MIS",
    "PM Fasal Bima app",
    "PM Gati Shakti",
    "PM Gati Shakti GIS",
    "PM Internship portal",
    "PM Jan Dhan",
    "PM Mudra online",
    "PM SVANidhi QR",
    "PM Surya Ghar portal",
    "PM Vishwakarma portal",
    "PM WANI",
    "PM eVIDYA",
    "PM-KISAN portal",
    "SVAMITVA drone",
    "UMANG",
    "UPI",
    "e-Hospital",
    "e-Office",
    "eSanjeevani",
]

POOL_DIGITAL_GOALS: list[str] = [
    "QR പേമെന്റ്",
    "ആരോഗ്യ ട്രാക്കിംഗ്",
    "ആശുപത്രി ഓൺലൈൻ",
    "ഇന്റേൺഷിപ്പ് പോർട്ടൽ",
    "ഓൺലൈൻ PROCUREMENT",
    "ഓൺലൈൻ വായ്പ",
    "കരകുശല പോർട്ടൽ",
    "കാഗതരഹിത ഭരണം",
    "കർഷക പോർട്ടൽ",
    "ഗ്രാമീണ ബ്രോഡ്ബാൻഡ്",
    "ജിയോ-സ്പേഷ്യൽ",
    "ടെലിമെഡിസിൻ",
    "ഡിജിറ്റൽ ഇൻഫ്രാ",
    "ഡിജിറ്റൽ ഉൾപ്പെടുത്തൽ",
    "ഡിജിറ്റൽ ഗവൺമെന്റ്",
    "ഡിജിറ്റൽ ഡോക്യുമെന്റ്",
    "ഡിജിറ്റൽ പഠനം",
    "ഡിജിറ്റൽ പേമെന്റ്",
    "ഡിജിറ്റൽ പ്ലാനിംഗ്",
    "ഡിജിറ്റൽ ബാങ്കിംഗ്",
    "ഡിജിറ്റൽ റേഷൻ",
    "ഡിജിറ്റൽ വിദ്യാഭ്യാസം",
    "ഡിജിറ്റൽ സർട്ടിഫിക്കറ്റ്",
    "ഡിജിറ്റൽ ഹെൽത്ത്",
    "ഡ്രോൺ സർവേ",
    "പബ്ലിക് വൈ-ഫി",
    "വാക്സിൻ ഡിജിറ്റൽ",
    "വിള ഇൻഷുറൻസ് ആപ്പ്",
    "വീട് പോർട്ടൽ",
    "സോളാർ പോർട്ടൽ",
]

POOL_ENV_SCHEMES: list[str] = [
    "DDUGJY",
    "FAME II",
    "FAME India",
    "Namami Gange",
    "National Afforestation",
    "National Biofuel",
    "National Green Hydrogen",
    "National Green Hydrogen 5MMT",
    "National Green Hydrogen PLI",
    "National Hydrogen Energy",
    "National Solar Mission",
    "National Wind Mission",
    "Off-grid solar",
    "PM Gati Shakti energy",
    "PM Gati Shakti green",
    "PM SHRI green school",
    "PM Surya Ghar",
    "PM Surya Ghar 300 unit",
    "PM Surya Ghar central subsidy",
    "PM Surya Ghar rooftop",
    "PM Ujjwala",
    "PM Ujjwala 2.0 migrant",
    "PM Ujjwala clean fuel",
    "PM eBus Sewa",
    "PM eBus zero emission",
    "PM-KUSUM",
    "PM-KUSUM solar pump",
    "SAUBHAGYA",
    "Solar park scheme",
    "Swachh Bharat",
]

POOL_ENV_GOALS: list[str] = [
    "300 യൂണിറ്റ് സൗജന്യം",
    "5 MMT/വർഷം",
    "EV സബ്സിഡി",
    "ഇലക്ട്രിക് ബസ്",
    "ഇലക്ട്രിക് വാഹനം",
    "ഊർജ കോറിഡോർ",
    "ഓഫ്-ഗ്രിഡ് സോളാർ",
    "കമ്മി പുക",
    "കാറ്റ് ഊർജ",
    "കാർഷിക സോളാർ",
    "ഗംഗാ ശുദ്ധീകരണം",
    "ഗൃഹ മേൽക്കൂര",
    "ഗ്രാമീണ വൈദ്യുതി",
    "ഡീസൽ കുറയ്ക്കൽ",
    "നിർമ്മാണ സബ്സിഡി",
    "പൂജ്യം ഉത്സർജനം",
    "ബയോഫ്യൂവൽ",
    "മാലിന്യ നിർമാർജനം",
    "മിഗ്രന്റ് കുടുംബം",
    "വനം വർദ്ധന",
    "വൈദ്യുതീകരണം",
    "ശുദ്ധ ഇന്ധനം",
    "സോളാർ ഊർജ",
    "സോളാർ പാർക്ക്",
    "സോളാർ ലക്ഷ്യം",
    "ഹരിത ലോജിസ്റ്റിക്സ്",
    "ഹരിത സ്കൂൾ",
    "ഹരിത ഹൈഡ്രജൻ",
    "ഹൈഡ്രജൻ മിഷൻ",
    "₹78000 സബ്സിഡി",
]

POOL_RECENT_SCHEMES: list[str] = [
    "ABDM nationwide",
    "National Edible Oil Mission",
    "National Green Hydrogen Mission",
    "PM Awas Gramin extension",
    "PM Awas Urban extension",
    "PM Ayushman CAPF",
    "PM Daksh expansion",
    "PM DevINE",
    "PM FME Phase II",
    "PM Fasal Bima 2024",
    "PM Garib Kalyan Anna extension",
    "PM Gati Shakti",
    "PM Internship Scheme",
    "PM Janman",
    "PM MITRA",
    "PM Mudra expansion",
    "PM SHRI",
    "PM SVANidhi 2.0",
    "PM Surya Ghar",
    "PM Surya Ghar 2024 launch",
    "PM Ujjwala 2.0",
    "PM Vishwakarma",
    "PM Vishwakarma 2023 launch",
    "PM WANI expansion",
    "PM eBus Sewa",
    "PM eVIDYA expansion",
    "PM-JAY 50 crore target",
    "PM-KISAN 17th instalment",
    "PM-KUSUM expansion",
    "Vibrant Villages Programme",
]

POOL_RECENT_GOALS: list[str] = [
    "1 കോടി ഇന്റേൺഷിപ്പ്",
    "1 കോടി ഗൃഹ ലക്ഷ്യം",
    "10000 ഇലക്ട്രിക് ബസ്",
    "2024 ഗ്രാമീണ ലക്ഷ്യം",
    "2024 വീട് ലക്ഷ്യം",
    "30 ലക്ഷം കരകുശലർ",
    "50 കോടി ആരോഗ്യ പരിരക്ഷ",
    "CAPF ആരോഗ്യ പരിരക്ഷ",
    "PVTG സമഗ്ര വികസനം",
    "അടിസ്ഥാന സൗകര്യ ഏകീകരണം",
    "അതിർത്തി ഗ്രാമ വികസനം",
    "അപ്രന്റിസ്ഷിപ്പ് വിപുലീകരണം",
    "എഡിബിൾ ഓയിൽ സ്വയംപര്യാപ്തത",
    "ഓൺലൈൻ വിദ്യാഭ്യാസ വിപുലീകരണം",
    "കാർഷിക സോളാർ വിപുലീകരണം",
    "കർഷക വരുമാന തുടർച്ച",
    "ഗൃഹ സോളാർ സൗജന്യ വൈദ്യുതി",
    "ഡിജിറ്റൽ ഹെൽത്ത് ഐഡി",
    "നോർത്ത്-ഈസ്റ്റ് നിക്ഷേപം",
    "പബ്ലിക് വൈ-ഫി വിപുലീകരണം",
    "പാരമ്പര്യ കരകുശല സഹായം",
    "ഭക്ഷ്യ സുരക്ഷ തുടർച്ച",
    "മാതൃക സ്കൂൾ നവീകരണം",
    "മിഗ്രന്റ് കുടുംബങ്ങൾ",
    "മെഗാ ടെക്സ്റ്റൈൽ പാർക്ക്",
    "മൈക്രോ ഫുഡ് പ്രോസസ്സിംഗ്",
    "രണ്ടാം തവണ വായ്പ",
    "വിള ഇൻഷുറൻസ് തുടർച്ച",
    "ഹരിത ഹൈഡ്രജൻ ഉൽപ്പാദനം",
    "₹20 ലക്ഷം കോടി ലക്ഷ്യം",
]



def generate_wave30_candidates(existing: set[str], rng: random.Random) -> list[Candidate]:
    out: list[Candidate] = []

    emit_category(
        out, existing, rng, LAUNCH_YEAR,
        ["'{a}' പദ്ധതി ആരംഭിച്ച വർഷം ഏത്?", "'{a}' ഏത് വർഷം ആരംഭിച്ചു?"],
        ["'{b}' വർഷം ആരംഭിച്ച ദേശീയ പദ്ധതി ഏത്?", "'{b}' വർഷത്തിൽ ആരംഭിച്ച പ്രധാന പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, MINISTRY,
        ["'{a}' ഏത് മന്ത്രാലയത്തിന് കീഴിലാണ്?", "'{a}' നടപ്പാക്കുന്ന മന്ത്രാലയം ഏത്?"],
        ["'{b}' മന്ത്രാലയത്തിന് കീഴിലുള്ള പ്രധാന പദ്ധതി ഏത്?", "'{b}' നടപ്പാക്കുന്ന പ്രധാന ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_MINISTRIES,
    )
    emit_category(
        out, existing, rng, SECTOR,
        ["'{a}' ഏത് മേഖലയുമായി ബന്ധപ്പെട്ടതാണ്?", "'{a}'-ന്റെ പ്രധാന ലക്ഷ്യമേഖല ഏത്?"],
        ["'{b}' മേഖലയുമായി ബന്ധപ്പെട്ട ദേശീയ പദ്ധതി ഏത്?", "'{b}' ലക്ഷ്യമേഖലയിലുള്ള പ്രധാന പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_SECTORS,
    )
    emit_category(
        out, existing, rng, BENEFICIARY,
        ["'{a}'-ന്റെ പ്രധാന ലാഭഗ്രാഹികൾ ആരാണ്?", "'{a}' ആർക്കാണ് ലക്ഷ്യമിട്ടുള്ളത്?"],
        ["'{b}' ലാഭഗ്രാഹികൾക്കുള്ള പ്രധാന പദ്ധതി ഏത്?", "'{b}' ആർക്ക് നൽകുന്ന ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_BENEFICIARIES,
    )
    emit_category(
        out, existing, rng, FULL_FORM,
        ["'{a}' എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം ഏത്?", "'{a}'-ന്റെ വിപുലീകരണം ഏത്?"],
        ["'{b}' പൂർണ്ണരൂപമുള്ള പദ്ധതിയുടെ സംക്ഷേപം ഏത്?", "'{b}' ഏത് സംക്ഷേപത്തിൽ അറിയപ്പെടുന്നു?"],
        POOL_ABBREV, POOL_FULL_FORMS,
    )
    emit_category(
        out, existing, rng, BUDGET,
        ["'{a}'-ന്റെ പ്രധാന സാമ്പത്തിക വിവരം/തുക ഏത്?", "'{a}' സംബന്ധിച്ച പ്രധാന തുക/നിക്ഷേപം ഏത്?"],
        ["'{b}' തുക/നിക്ഷേപവുമായി ബന്ധപ്പെട്ട പദ്ധതി ഏത്?", "'{b}' സാമ്പത്തിക വിവരമുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, DBT,
        ["'{a}'-ൽ ധനസഹായം നൽകുന്ന രീതി ഏത്?", "'{a}' ഡിജിറ്റൽ ട്രാൻസ്ഫർ മോഡ് ഉപയോഗിക്കുന്നുണ്ടോ — എങ്ങനെ?"],
        ["'{b}' വഴി ധനസഹായം നൽകുന്ന പ്രധാന പദ്ധതി ഏത്?", "ഡിജിറ്റൽ ട്രാൻസ്ഫർ '{b}' രീതിയിലുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_DBT,
    )
    emit_category(
        out, existing, rng, PARENT_MISSION,
        ["'{a}' ഏത് പരമ്പരാഗത/അംബ്രല്ലാ ദൗത്യത്തിന്റെ ഭാഗമാണ്?", "'{a}' ബന്ധപ്പെട്ട മാതൃ ദൗത്യം ഏത്?"],
        ["'{b}' ദൗത്യത്തിന്റെ ഭാഗമായ പ്രധാന പദ്ധതി ഏത്?", "'{b}' അംബ്രല്ലാ പദ്ധതിയുടെ ഭാഗം ഏത്?"],
        POOL_SCHEMES, POOL_PARENTS,
    )
    emit_category(
        out, existing, rng, STATE_FIRST,
        ["'{a}' ആദ്യം ഏത് സംസ്ഥാനത്തിൽ ആരംഭിച്ചു/പൈലറ്റ് നടത്തി?", "'{a}' പൈലറ്റ് സംസ്ഥാനം ഏത്?"],
        ["'{b}' സംസ്ഥാനത്തിൽ ആദ്യം ആരംഭിച്ച പ്രധാന പദ്ധതി ഏത്?", "'{b}' പൈലറ്റ് നടത്തിയ ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_STATES,
    )
    emit_category(
        out, existing, rng, LEGAL_BASIS,
        ["'{a}'-ന്റെ നിയമപരമായ അടിസ്ഥാനം ഏത്?", "'{a}' ഏത് നിയമം/ആദേശത്തിന് കീഴിലാണ്?"],
        ["'{b}' അടിസ്ഥാനമാക്കിയ പ്രധാന പദ്ധതി ഏത്?", "'{b}' നിയമപരമായ അടിസ്ഥാനമുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_LAWS,
    )
    emit_category(
        out, existing, rng, NODAL,
        ["'{a}'-ന്റെ നോഡൽ ഏജൻസി/സ്ഥാപനം ഏത്?", "'{a}' നടപ്പാക്കുന്ന പ്രധാന ഏജൻസി ഏത്?"],
        ["'{b}' നോഡൽ ഏജൻസിയായ പ്രധാന പദ്ധതി ഏത്?", "'{b}' നടപ്പാക്കുന്ന ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_NODAL,
    )
    emit_category(
        out, existing, rng, PREDECESSOR,
        ["'{a}'-ന്റെ മുൻഗാമി പദ്ധതി ഏത്?", "'{a}' ഏത് പദ്ധതിയുടെ പരിഷ്കരിച്ച/പുനരുജ്ജീവിത രൂപമാണ്?"],
        ["'{b}'-ന്റെ പരിഷ്കരിച്ച/അനുസരണ പദ്ധതി ഏത്?", "'{b}' പുനരുജ്ജീവിതമാക്കിയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_PREDECESSORS,
    )
    emit_category(
        out, existing, rng, INSURANCE,
        ["'{a}'-ന്റെ ഇൻഷുറൻസ് പരിരക്ഷ/തുക ഏത്?", "'{a}' ഇൻഷുറൻസ് സംബന്ധിച്ച പ്രധാന വിവരം ഏത്?"],
        ["'{b}' ഇൻഷുറൻസ് പരിരക്ഷ നൽകുന്ന പദ്ധതി ഏത്?", "'{b}' ആരോഗ്യ/ഇൻഷുറൻസ് പരിരക്ഷയുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_INSURANCE,
    )
    emit_category(
        out, existing, rng, LOAN_LIMIT,
        ["'{a}'-ന്റെ വായ്പ/സഹായ പരിധി ഏത്?", "'{a}' വായ്പാ പരിധി/തുക ഏത്?"],
        ["'{b}' വായ്പാ പരിധിയുള്ള പ്രധാന പദ്ധതി ഏത്?", "'{b}' വായ്പ/സഹായം നൽകുന്ന പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_LOANS,
    )
    emit_category(
        out, existing, rng, TARGET_COUNT,
        ["'{a}'-ന്റെ ലക്ഷ്യ ലാഭഗ്രാഹി എണ്ണം ഏത്?", "'{a}' എത്ര പേർക്ക് ലക്ഷ്യമിട്ടിട്ടുണ്ട്?"],
        ["'{b}' ലാഭഗ്രാഹികളെ ലക്ഷ്യമിട്ട പദ്ധതി ഏത്?", "'{b}' പേർക്ക് ലക്ഷ്യമിട്ട ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_TARGETS,
    )
    emit_category(
        out, existing, rng, FUNDING,
        ["'{a}'-ന്റെ ധനസഹായ രീതി ഏത്?", "'{a}' കേന്ദ്ര-സംസ്ഥാന ഫണ്ടിംഗ് മാതൃക ഏത്?"],
        ["'{b}' ഫണ്ടിംഗ് മാതൃകയുള്ള പ്രധാന പദ്ധതി ഏത്?", "'{b}' ധനസഹായ രീതിയിലുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_FUNDING,
    )
    emit_category(
        out, existing, rng, PORTAL,
        ["'{a}'-ന്റെ പോർട്ടൽ/ആപ്പ് പേര് ഏത്?", "'{a}' ഓൺലൈൻ രജിസ്ട്രേഷൻ/നിരീക്ഷണ പോർട്ടൽ ഏത്?"],
        ["'{b}' പോർട്ടൽ/ആപ്പുമായി ബന്ധപ്പെട്ട പദ്ധതി ഏത്?", "'{b}' വഴി നിരീക്ഷണം നടത്തുന്ന പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_PORTALS,
    )
    emit_category(
        out, existing, rng, PM_LAUNCHED,
        ["'{a}' ആരംഭിച്ച പ്രധാനമന്ത്രി ആരാണ്?", "'{a}' ഏത് പ്രധാനമന്ത്രിയുടെ കാലത്ത് ആരംഭിച്ചു?"],
        ["'{b}' പ്രധാനമന്ത്രിയുടെ കാലത്ത് ആരംഭിച്ച പ്രധാന പദ്ധതി ഏത്?", "'{b}' ആരംഭിച്ച ദേശീയ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_PMS,
    )
    emit_category(
        out, existing, rng, UMBRELLA,
        ["'{a}' ഏത് അംബ്രല്ലാ പദ്ധതിയുടെ ഭാഗമാണ്?", "'{a}' ബന്ധപ്പെട്ട സമഗ്ര പദ്ധതി ഏത്?"],
        ["'{b}' അംബ്രല്ലാ പദ്ധതിയുടെ ഭാഗമായ ഉപപദ്ധതി ഏത്?", "'{b}' കീഴിലെ പ്രധാന ഉപപദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_UMBRELLA,
    )
    emit_category(
        out, existing, rng, WOMEN,
        ["'{a}' വനിതാ/പെൺകുട്ടികൾക്ക് ലക്ഷ്യമിട്ട പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' സ്ത്രീശാക്തീകരണ/പെൺകുട്ടി സംരക്ഷണ പദ്ധതിയുടെ ലക്ഷ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട വനിതാ/പെൺകുട്ടി പദ്ധതി ഏത്?", "'{b}' ഉദ്ദേശ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_WOMEN_SCHEMES, POOL_WOMEN_GOALS,
    )
    emit_category(
        out, existing, rng, RURAL,
        ["'{a}' ഗ്രാമീണ മേഖലയ്ക്ക് ലക്ഷ്യമിട്ട പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' ഗ്രാമീണ വികസന പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട ഗ്രാമീണ പദ്ധതി ഏത്?", "ഗ്രാമീണ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_RURAL_SCHEMES, POOL_RURAL_GOALS,
    )
    emit_category(
        out, existing, rng, URBAN,
        ["'{a}' നഗര മേഖലയ്ക്ക് ലക്ഷ്യമിട്ട പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' നഗര വികസന പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട നഗര പദ്ധതി ഏത്?", "നഗര '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_URBAN_SCHEMES, POOL_URBAN_GOALS,
    )
    emit_category(
        out, existing, rng, AGRI,
        ["'{a}' കാർഷിക പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' കർഷകർക്ക് ലക്ഷ്യമിട്ട പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട കാർഷിക പദ്ധതി ഏത്?", "കാർഷിക '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_AGRI_SCHEMES, POOL_AGRI_GOALS,
    )
    emit_category(
        out, existing, rng, HEALTH,
        ["'{a}' ആരോഗ്യ പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' ആരോഗ്യ സംരക്ഷണ പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട ആരോഗ്യ പദ്ധതി ഏത്?", "ആരോഗ്യ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_HEALTH_SCHEMES, POOL_HEALTH_GOALS,
    )
    emit_category(
        out, existing, rng, EDUCATION,
        ["'{a}' വിദ്യാഭ്യാസ പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' വിദ്യാഭ്യാസ മേഖലയിലെ പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട വിദ്യാഭ്യാസ പദ്ധതി ഏത്?", "വിദ്യാഭ്യാസ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_EDU_SCHEMES, POOL_EDU_GOALS,
    )
    emit_category(
        out, existing, rng, HOUSING,
        ["'{a}' വാസസ്ഥല പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' ഭവനരഹിതർക്ക് ലക്ഷ്യമിട്ട പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട വാസസ്ഥല പദ്ധതി ഏത്?", "വാസസ്ഥല '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_HOUSING_SCHEMES, POOL_HOUSING_GOALS,
    )
    emit_category(
        out, existing, rng, EMPLOYMENT,
        ["'{a}' തൊഴിൽ/തൊഴിൽസൃഷ്ടി പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' തൊഴിൽ മേഖലയിലെ പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട തൊഴിൽ പദ്ധതി ഏത്?", "തൊഴിൽ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_EMP_SCHEMES, POOL_EMP_GOALS,
    )
    emit_category(
        out, existing, rng, DIGITAL,
        ["'{a}' ഡിജിറ്റൽ/ഐ.ടി. പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' സാങ്കേതിക പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട ഡിജിറ്റൽ പദ്ധതി ഏത്?", "ഡിജിറ്റൽ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_DIGITAL_SCHEMES, POOL_DIGITAL_GOALS,
    )
    emit_category(
        out, existing, rng, ENV_ENERGY,
        ["'{a}' പരിസ്ഥിതി/ഊർജ പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' ഊർജ/പരിസ്ഥിതി മേഖലയിലെ പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട ഊർജ/പരിസ്ഥിതി പദ്ധതി ഏത്?", "ഊർജ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_ENV_SCHEMES, POOL_ENV_GOALS,
    )
    emit_category(
        out, existing, rng, RECENT,
        ["'{a}' (2023–25) പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}' ഏറ്റവും പുതിയ ദേശീയ പദ്ധതിയുടെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട 2023–25 പദ്ധതി ഏത്?", "പുതിയ '{b}' ലക്ഷ്യമുള്ള ദേശീയ പദ്ധതി ഏത്?"],
        POOL_RECENT_SCHEMES, POOL_RECENT_GOALS,
    )

    emit_direct(out, existing, rng, DIRECT_FACTS)
    return out


if __name__ == "__main__":
    print(len(generate_wave30_candidates(set(), random.Random(0))))

