#!/usr/bin/env python3
"""Wave 30 social welfare schemes facts — 30 Malayalam PSC topic types."""

from __future__ import annotations

import random

from refill_common import Candidate
from wave30_emit import emit_category, emit_direct

KERALA_SCHEME_YEAR: list[tuple[str, str]] = [
    ("കുടുംബശ്രീ", "1998"),
    ("കാരുണ്യ", "2012"),
    ("LIFE", "2016"),
    ("ആശ്വാസകിരണം", "2012"),
    ("വയോമിത്രം", "2009"),
    ("സുഭിക്ഷ കേരളം", "2020"),
    ("കാരുണ്യ പ്ലസ്", "2014"),
    ("കാരുണ്യ ബെനവലന്റ് ഫണ്ട്", "2012"),
    ("അമ്മ കേരളം", "2017"),
    ("ഹരിത കേരളം", "2017"),
    ("കേരള ക്ഷേമ പെൻഷൻ", "2000"),
    ("നിർമ്മാണ തൊഴിലാളി ക്ഷേമ ബോർഡ്", "1989"),
    ("കേരള സാമൂഹിക സുരക്ഷാ ദൗത്യം", "2008"),
    ("അക്ഷയ", "2002"),
    ("ആരോഗ്യ സുരക്ഷാ കേരളം", "2017"),
    ("കേരള ഭക്ഷ്യ പ്ലാനിംഗ് ബോർഡ്", "1965"),
    ("കേരള സംസ്ഥാന ക്ഷേമ പെൻഷൻ ബോർഡ്", "2013"),
    ("അനുഭവം", "2010"),
    ("സമഗ്ര", "2010"),
    ("അരി കേരളം", "2017"),
    ("അമൃതം", "2017"),
    ("അമൃത കൂട്ടായ്മ", "2017"),
    ("കേരള ഗ്രാമീണ ബാങ്ക് എസ്.എച്ച്.ജി.", "1980"),
    ("കേരള ഹാബിറ്റാറ്റ് മിഷൻ", "2001"),
]

KERALA_SCHEME_GOAL: list[tuple[str, str]] = [
    ("കുടുംബശ്രീ", "സ്ത്രീ ശാക്തീകരണവും ദാരിദ്ര്യ നിർമാർജനവും"),
    ("LIFE", "ഭൂമിയില്ലാത്തവർക്ക് വീട്"),
    ("കാരുണ്യ", "ആരോഗ്യ സഹായം"),
    ("ആശ്വാസകിരണം", "പടുക്കിൽ കിടക്കുന്ന രോഗികളുടെ പരിചരകർ"),
    ("വയോമിത്രം", "മുതിർന്നവർക്ക് മൊബൈൽ ആരോഗ്യ സേവ"),
    ("സുഭിക്ഷ കേരളം", "ഭക്ഷ്യ സുരക്ഷ"),
    ("കാരുണ്യ പ്ലസ്", "ഗുരുതര രോഗ ചികിത്സ"),
    ("കാരുണ്യ ബെനവലന്റ് ഫണ്ട്", "ദുർബല വിഭാഗങ്ങൾക്ക് സാമ്പത്തിക സഹായം"),
    ("അമ്മ കേരളം", "മാതൃ-ശിശു ആരോഗ്യം"),
    ("ഹരിത കേരളം", "പരിസ്ഥിതി സംരക്ഷണം"),
    ("അക്ഷയ", "വനിതാ സ്വയം സഹായ"),
    ("ആരോഗ്യ സുരക്ഷാ കേരളം", "എല്ലാവർക്കുമുള്ള ആരോഗ്യ പരിരക്ഷ"),
    ("അനുഭവം", "മുതിർന്നവർക്ക് തൊഴിൽ"),
    ("സമഗ്ര", "വികലാംഗ സമഗ്ര പരിചരണം"),
    ("അരി കേരളം", "സ്വയംപര്യാപ്ത അരി ഉൽപ്പാദനം"),
    ("അമൃതം", "ശുദ്ധമായ കുടിവെള്ളം"),
    ("അമൃത കൂട്ടായ്മ", "ജനകീയ പങ്കാളിത്തം"),
    ("കേരള ക്ഷേമ പെൻഷൻ", "ദാരിദ്ര്യ രേഖയിലുള്ളവർക്ക് പെൻഷൻ"),
    ("നിർമ്മാണ തൊഴിലാളി ബോർഡ്", "നിർമ്മാണ തൊഴിലാളികളുടെ ക്ഷേമം"),
    ("കേരള സാമൂഹിക സുരക്ഷാ ദൗത്യം", "സാമൂഹിക സുരക്ഷാ പദ്ധതികൾ"),
    ("കേരള ഭക്ഷ്യ പ്ലാനിംഗ് ബോർഡ്", "പൊതു ഭക്ഷ്യ വിതരണം"),
    ("LIFE Mission", "2024 വരെ 4 ലക്ഷം വീട്"),
    ("കുടുംബശ്രീ NHG", "അയൽപക്ക ഗ്രൂപ്പ്"),
    ("കാരുണ്യ ആരോഗ്യ സുരക്ഷ", "ആയുർഷ്മാൻ ഭാരതം"),
]

NRLM: list[tuple[str, str]] = [
    ("NRLM", "ദേശീയ ഗ്രാമീണ ഉപജീവന ദൗത്യം"),
    ("DAY-NRLM", "2015-ൽ പുനർനാമകരണം"),
    ("Aajeevika", "NRLM-ന്റെ മുൻ പേര്"),
    ("SHG", "സ്വയം സഹായ സംഘം"),
    ("CLF", "സംഘ തല ഫെഡറേഷൻ"),
    ("VO", "ഗ്രാമ ഓർഗനൈസേഷൻ"),
    ("SRLM", "സംസ്ഥാന ഗ്രാമീണ ഉപജീവന ദൗത്യം"),
    ("കുടുംബശ്രീ", "കേരളത്തിലെ എസ്.ആർ.എൽ.എം."),
    ("Deendayal Antyodaya Yojana", "DAY-NRLM-ന്റെ പൂർണ്ണ പേര്"),
    ("NRLM", "2011-ൽ ആരംഭം"),
    ("SHG-ബാങ്ക് ലിങ്കേജ്", "NRLM-ന്റെ പ്രധാന തന്ത്രം"),
    ("Interest Subvention", "SHG വായ്പയ്ക്ക് 7%/4%"),
    ("RF", "റിവോൾവിംഗ് ഫണ്ട്"),
    ("CRF", "കമ്യൂണിറ്റി നിക്ഷേപ ഫണ്ട്"),
    ("VO Fund", "₹10 ലക്ഷം/VO"),
    ("NRLM", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("NRLM", "ഉപജീവന മെച്ചപ്പെടുത്തൽ"),
    ("DAY-NRLM", "ദാരിദ്ര്യ നിർമാർജനം"),
    ("NRLM", "വനിതാ SHG-കൾ"),
    ("NRLM", "ദേശീയ ഗ്രാമീണ ഉപജീവന ദൗത്യം"),
    ("Aajeevika Mission", "NRLM മുൻഗാമി"),
    ("SHG-ബാങ്ക് ലിങ്കേജ്", "1992-ൽ NABARD"),
    ("NRLM", "50% SC/ST, 15% minorities"),
    ("DAY-NRLM", "Deendayal Antyodaya Yojana"),
]

PENSION_AMOUNT: list[tuple[str, str]] = [
    ("IGNOAPS", "₹200/മാസം (കേന്ദ്രം)"),
    ("IGNWPS", "₹200/മാസം (കേന്ദ്രം)"),
    ("IGNDPS", "₹200/മാസം (കേന്ദ്രം)"),
    ("NFBS", "₹20000 (ഏകകാലം)"),
    ("Annapurna", "10 കിലോ ഭക്ഷ്യധാന്യം/മാസം"),
    ("PMMVY", "₹5000"),
    ("കേരള ക്ഷേമ പെൻഷൻ", "₹1600/മാസം"),
    ("കേരള വാർദ്ധക്യ പെൻഷൻ", "₹1600/മാസം"),
    ("കേരള വിധവാ പെൻഷൻ", "₹1600/മാസം"),
    ("കേരള വികലാംഗ പെൻഷൻ", "₹1600/മാസം"),
    ("കേരള കർഷക പെൻഷൻ", "₹1600/മാസം"),
    ("Atal Pension Yojana", "₹1000–5000/മാസം"),
    ("EPS", "₹1000/മാസം (കുറഞ്ഞത്)"),
    ("EPFO", "₹15000/മാസം (പരമാവധി)"),
    ("NSAP", "1999-ൽ ആരംഭം"),
    ("IGNOAPS", "60+ വയസ്സ്"),
    ("IGNWPS", "40–79 വയസ്സ് വിധവ"),
    ("IGNDPS", "18–79 വയസ്സ് 80%+ വികലാംഗത"),
    ("NFBS", "BPL കുടുംബത്തിലെ പ്രധാന വരുമാനക്കാരൻ മരണം"),
    ("Annapurna", "65+ പെൻഷൻ ലഭിക്കാത്തവർ"),
    ("PMMVY", "ആദ്യ ഗർഭധാരണം"),
    ("JSY", "₹1400/₹1000 (ഗ്രാമ/നഗര)"),
    ("JSSK", "സൗജന്യ ആരോഗ്യ പരിചരണം"),
    ("RSBY", "₹30000/കുടുംബം/വർഷം"),
]

AGE_ELIGIBILITY: list[tuple[str, str]] = [
    ("IGNOAPS", "60+ വയസ്സ്"),
    ("IGNWPS", "40–79 വയസ്സ്"),
    ("IGNDPS", "18–79 വയസ്സ്"),
    ("Annapurna", "65+ വയസ്സ്"),
    ("RTE", "6–14 വയസ്സ്"),
    ("MGNREGA", "18+ വയസ്സ്"),
    ("RPwD Act", "40% വികലാംഗത"),
    ("ICDS", "0–6 വയസ്സ്"),
    ("PMMVY", "19+ വയസ്സ്"),
    ("JSY", "19+ വയസ്സ്"),
    ("POCSO", "18 വയസ്സ് താഴെ"),
    ("JJ Act", "18 വയസ്സ് താഴെ"),
    ("Atal Pension", "18–40 വയസ്സ്"),
    ("NFBS", "18–64 പ്രധാന വരുമാനക്കാരൻ"),
    ("Mid Day Meal", "1–8 ക്ലാസ്"),
    ("POSHAN", "0–6 വയസ്സ്"),
    ("NRLM SHG", "18+ വയസ്സ്"),
    ("Ujjawala", "18+ വയസ്സ്"),
    ("Sakhi", "18+ വയസ്സ്"),
    ("NPHCE", "60+ വയസ്സ്"),
    ("Vayomithram", "65+ വയസ്സ്"),
    ("ADIP", "0–19 വയസ്സ്"),
    ("NSP", "SC/ST/OBC"),
    ("Maternity Benefit Act", "160 days leave"),
]

BPL_AAY: list[tuple[str, str]] = [
    ("BPL", "Below Poverty Line"),
    ("AAY", "Antyodaya Anna Yojana"),
    ("NFSA", "75% ഗ്രാമീണ 50% നഗര"),
    ("AAY", "ഏറ്റവും ദരിദ്ര കുടുംബങ്ങൾ"),
    ("BPL", "സംസ്ഥാന BPL പട്ടിക"),
    ("AAY", "35 കിലോ ഭക്ഷ്യധാന്യം/മാസം"),
    ("PHH", "Priority Household"),
    ("NPHH", "Non-Priority Household"),
    ("NFSA", "5 കിലോ/വ്യക്തി/മാസം"),
    ("AAY", "₹2/കിലോ"),
    ("BPL card", "സബ്സിഡി റേഷൻ"),
    ("SECC 2011", "BPL തിരിച്ചറിയൽ"),
    ("AAY", "MGNREGA 100 ദിവസം"),
    ("BPL", "NSAP പെൻഷൻ"),
    ("AAY", "ഏറ്റവും കുറഞ്ഞ വരുമാനം"),
    ("NFSA", "2013 നിയമം"),
    ("TPDS", "Targeted PDS"),
    ("AAY", "25 കിലോ (പഴയ)"),
    ("BPL", "സാമൂഹിക സുരക്ഷ"),
    ("AAY", "അന്ത്യോദയ"),
    ("PHH", "5 കിലോ/വ്യക്തി"),
    ("NFSA", "67% ജനസംഖ്യ"),
    ("BPL", "ആരോഗ്യ/വിദ്യാ സഹായം"),
    ("എ.എ.വൈ. റേഷൻ കാർഡ്", "ഏറ്റവും ദരിദ്ര കുടുംബം"),
]

ICDS: list[tuple[str, str]] = [
    ("ICDS", "1975"),
    ("ICDS", "Integrated Child Development Services"),
    ("Anganwadi", "ICDS-ന്റെ grassroot unit"),
    ("AWW", "Anganwadi Worker"),
    ("AWH", "Anganwadi Helper"),
    ("ICDS", "0–6 വയസ്സ്"),
    ("Supplementary nutrition", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("Immunization", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("Health check-up", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("Referral services", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("Pre-school education", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("Nutrition & health education", "6 സേവനങ്ങളിൽ ഒന്ന്"),
    ("ICDS", "Ministry of WCD"),
    ("POSHAN Abhiyaan", "ICDS പുനരുജ്ജീവിതം"),
    ("POSHAN 2.0", "Saksham Anganwadi"),
    ("Anganwadi", "Courtyard shelter"),
    ("ICDS", "1975-10-02"),
    ("World Food Day", "1975-10-02 ICDS"),
    ("AWW", "Community-based worker"),
    ("ICDS", "India's largest outreach"),
    ("Hot cooked meal", "3–6 വയസ്സ്"),
    ("Take home ration", "0–3 വയസ്സ്"),
    ("Growth monitoring", "ICDS"),
    ("ICDS", "6 services"),
]

RTE: list[tuple[str, str]] = [
    ("RTE Act", "2009"),
    ("RTE", "6–14 വയസ്സ്"),
    ("Article 21A", "Right to Education"),
    ("RTE", "86th Constitutional Amendment"),
    ("RTE", "Free & compulsory education"),
    ("RTE", "25% EWS reservation"),
    ("RTE", "No capitation fee"),
    ("RTE", "No screening test"),
    ("RTE", "No corporal punishment"),
    ("RTE", "No expulsion"),
    ("RTE", "Qualified teachers"),
    ("RTE", "Pupil-teacher ratio"),
    ("RTE", "2010 April 1 effective"),
    ("RTE", "Elementary education"),
    ("RTE", "State responsibility"),
    ("RTE", "Private school inclusion"),
    ("RTE", "Mid Day Meal link"),
    ("RTE", "2010 notification"),
    ("Article 21A", "2002 amendment"),
    ("RTE", "Fundamental right"),
    ("RTE", "8 years education"),
    ("RTE", "Std I–VIII"),
    ("RTE", "NCPCR monitoring"),
    ("RTE", "SMC formation"),
]

NFSA: list[tuple[str, str]] = [
    ("NFSA", "2013"),
    ("NFSA", "National Food Security Act"),
    ("NFSA", "5 കിലോ/വ്യക്തി/മാസം"),
    ("NFSA", "75% ഗ്രാമീണ"),
    ("NFSA", "50% നഗര"),
    ("NFSA", "67% coverage"),
    ("NFSA", "₹3/കിലോ അരി"),
    ("NFSA", "₹2/കിലോ ഗോതമ്പ്"),
    ("NFSA", "₹1/കിലോ coarse grain"),
    ("AAY", "NFSA-യുടെ ഭാഗം"),
    ("PHH", "NFSA-യുടെ ഭാഗം"),
    ("NFSA", "Food entitlement"),
    ("NFSA", "Legal right to food"),
    ("NFSA", "TPDS reform"),
    ("NFSA", "2013-09-12"),
    ("NFSA", "Centre-state cost sharing"),
    ("NFSA", "Maternity benefit 6000"),
    ("NFSA", "Mid Day Meal"),
    ("NFSA", "ICDS nutrition"),
    ("NFSA", "3 years implementation"),
    ("NFSA", "State food commission"),
    ("NFSA", "Grievance redressal"),
    ("NFSA", "Digitized ration cards"),
    ("NFSA", "ONORC link"),
]

MGNREGA: list[tuple[str, str]] = [
    ("MGNREGA", "2005"),
    ("MGNREGA", "100 ദിവസം"),
    ("MGNREGA", "18+ വയസ്സ്"),
    ("MGNREGA", "Rural households"),
    ("MGNREGA", "Unskilled manual work"),
    ("MGNREGA", "Gram Panchayat"),
    ("MGNREGA", "Job card"),
    ("MGNREGA", "Muster roll"),
    ("MGNREGA", "Wage payment 15 days"),
    ("MGNREGA", "Unemployment allowance"),
    ("MGNREGA", "50:50 Centre-State"),
    ("MGNREGA", "Mahatma Gandhi"),
    ("MGNREGA", "2005-08-25"),
    ("MGNREGA", "Legal guarantee"),
    ("MGNREGA", "Women 1/3 reservation"),
    ("MGNREGA", "Schedule I works"),
    ("MGNREGA", "Schedule II wages"),
    ("MGNREGA", "Social audit"),
    ("MGNREGA", "NREGA 2005"),
    ("MGNREGA", "MoRD"),
    ("MGNREGA", "Asset creation"),
    ("MGNREGA", "Drought proofing"),
    ("MGNREGA", "Water conservation"),
    ("MGNREGA", "Rural connectivity"),
]

NSAP: list[tuple[str, str]] = [
    ("NSAP", "1999"),
    ("NSAP", "National Social Assistance Programme"),
    ("IGNOAPS", "Indira Gandhi Old Age Pension"),
    ("IGNWPS", "Indira Gandhi National Widow Pension"),
    ("IGNDPS", "Indira Gandhi Disability Pension"),
    ("NFBS", "National Family Benefit Scheme"),
    ("Annapurna", "Food to destitute elderly"),
    ("NSAP", "5 components"),
    ("IGNOAPS", "60+ BPL"),
    ("IGNWPS", "40–79 BPL widow"),
    ("IGNDPS", "18–79 80% disability"),
    ("NFBS", "₹20000 lumpsum"),
    ("Annapurna", "10 kg grains/month"),
    ("NSAP", "MoRD"),
    ("NSAP", "Central assistance"),
    ("IGNOAPS", "State top-up"),
    ("NFBS", "Primary പ്രധാന വരുമാനക്കാരൻ death"),
    ("Annapurna", "65+ no pension"),
    ("NSAP", "BPL criterion"),
    ("NSAP", "Social security"),
    ("IGNOAPS", "Old age"),
    ("IGNWPS", "Widow"),
    ("IGNDPS", "Disability"),
    ("NSAP", "1999-08-15"),
]

WOMEN_CHILD: list[tuple[str, str]] = [
    ("PMMVY", "₹5000 maternity benefit"),
    ("Sakhi", "One Stop Centre"),
    ("Ujjawala", "Trafficking victims rehabilitation"),
    ("POCSO", "2012"),
    ("JJ Act", "2015"),
    ("Beti Bachao Beti Padhao", "2015"),
    ("Sukanya Samriddhi", "Girl child savings"),
    ("Mahila Police Volunteer", "WCD"),
    ("181", "Women helpline"),
    ("1098", "Child helpline"),
    ("POCSO", "Protection of Children"),
    ("JJ Act", "Juvenile Justice"),
    ("Nirbhaya Fund", "Women safety"),
    ("Sakhi", "181 helpline link"),
    ("Ujjawala", "NOT LPG scheme"),
    ("PM Ujjwala", "LPG (different)"),
    ("POSHAN", "Child nutrition"),
    ("ICDS", "Child development"),
    ("PMMVY", "First living child"),
    ("Sakhi", "Violence against women"),
    ("Ujjawala", "Rescue & rehabilitation"),
    ("POCSO", "Special courts"),
    ("JJ Act", "Child in conflict with law"),
    ("WCD Ministry", "Women & child schemes"),
]

ELDERLY: list[tuple[str, str]] = [
    ("വയോമിത്രം", "മുതിർന്നവർക്ക് മൊബൈൽ ആരോഗ്യ സേവ"),
    ("NPHCE", "60+ വയസ്സ് ആരോഗ്യ പരിചരണം"),
    ("IGNOAPS", "60+ വാർദ്ധക്യ പെൻഷൻ"),
    ("Annapurna", "65+ ഭക്ഷ്യ പദ്ധതി"),
    ("വയോമിത്രം", "65+ കേരളം"),
    ("NPHCE", "2010-ൽ ആരംഭം"),
    ("IGNOAPS", "₹200 കേന്ദ്ര സഹായം"),
    ("Annapurna", "10 കിലോ/മാസം"),
    ("വയോമിത്രം", "മരുന്ന് എത്തിക്കൽ"),
    ("National Policy on Older Persons", "1999"),
    ("Maintenance Act", "2007"),
    ("IGNOAPS", "BPL വാർദ്ധക്യം"),
    ("Annapurna", "പെൻഷൻ ലഭിക്കാത്ത 65+"),
    ("വയോമിത്രം", "കേരള സാമൂഹിക സുരക്ഷാ ദൗത്യം"),
    ("NPHCE", "ജെറിയാട്രിക് പരിചരണം"),
    ("Senior Citizens Act", "2007"),
    ("IGNOAPS", "സംസ്ഥാന അധിക പെൻഷൻ"),
    ("Annapurna", "NSAP ഘടകം"),
    ("വയോമിത്രം", "സൗജന്യ മരുന്ന്"),
    ("NPHCE", "AIIMS ജെറിയാട്രിക്"),
    ("Elder Line", "14567"),
    ("Rashtriya Vayoshri Yojana", "സഹായ ഉപകരണങ്ങൾ"),
    ("വയോമിത്രം", "മരുന്ന് വീട്ടിൽ എത്തിക്കൽ"),
    ("Annapurna", "10 കിലോ ഭക്ഷ്യധാന്യം"),
]

DISABILITY: list[tuple[str, str]] = [
    ("RPwD Act", "2016"),
    ("RPwD Act", "40% disability"),
    ("NHFDC", "National Handicapped Finance"),
    ("ADIP", "Assistance to Disabled"),
    ("IGNDPS", "80%+ disability pension"),
    ("RPwD Act", "Rights of Persons with Disabilities"),
    ("RPwD Act", "21 types disability"),
    ("NHFDC", "1997"),
    ("ADIP", "Ministry of SJ&E"),
    ("RPwD Act", "Replaced 1995 Act"),
    ("Accessible India", "Sugamya Bharat"),
    ("ADIP", "Aids & appliances"),
    ("NHFDC", "Loan for PwD"),
    ("RPwD Act", "4% reservation"),
    ("RPwD Act", "5% education"),
    ("Unique Disability ID", "UDID"),
    ("RPwD Act", "2017 notification"),
    ("National Trust Act", "1999"),
    ("Deendayal Disabled Scheme", "Insurance"),
    ("ADIP", "Free aids"),
    ("RPwD Act", "Non-discrimination"),
    ("RPwD Act", "Equal opportunity"),
    ("NHFDC", "NBCFDC subsidiary"),
    ("RPwD Act", "21 disabilities"),
]

TRIBAL: list[tuple[str, str]] = [
    ("PM JANMAN", "2023"),
    ("TRIFED", "Tribal cooperative marketing"),
    ("FRA", "2006"),
    ("FRA", "Forest Rights Act"),
    ("PM JANMAN", "PVTG welfare"),
    ("TRIFED", "Ministry of Tribal Affairs"),
    ("FRA", "Individual & community rights"),
    ("PM JANMAN", "75 PVTG communities"),
    ("TRIFED", "Minor forest produce"),
    ("FRA", "Scheduled Tribes"),
    ("PM JANMAN", "11 interventions"),
    ("TRIFED", "1967"),
    ("FRA", "Gram Sabha recognition"),
    ("PM JANMAN", "₹24000 crore"),
    ("TRIFED", "TRIFED eSampada"),
    ("FRA", "2006-12-29"),
    ("PESA", "1996 Panchayat Extension"),
    ("PM JANMAN", "PM Janjatiya Adivasi Nyaya"),
    ("TRIFED", "Van Dhan Vikas"),
    ("FRA", "Habitat rights"),
    ("PM JANMAN", "Road, housing, water"),
    ("TRIFED", "Retail marketing"),
    ("FRA", "Community forest resource"),
    ("PM JANMAN", "25000+ villages"),
]

SCHOLARSHIP: list[tuple[str, str]] = [
    ("NSP", "National Scholarship Portal"),
    ("Post Matric SC", "Higher education"),
    ("Pre Matric SC", "Class 9–10"),
    ("Post Matric ST", "Higher education"),
    ("Pre Matric ST", "Class 9–10"),
    ("Merit-cum-Means", "Minority scholarship"),
    ("Begum Hazrat Mahal", "Minority girls"),
    ("Central Sector Scheme", "Top 20% class 12"),
    ("PM Yasasvi", "OBC/EBC/DNT"),
    ("NSP", "scholarships.gov.in"),
    ("Post Matric OBC", "Higher education"),
    ("Pre Matric OBC", "Class 1–10"),
    ("Top Class Education", "SC students"),
    ("Rajiv Gandhi Fellowship", "SC/ST PhD"),
    ("Maulana Azad Fellowship", "Minority PhD"),
    ("NSP", "2020 launch"),
    ("Post Matric SC", "MoSJE"),
    ("Pre Matric SC", "MoSJE"),
    ("Post Matric ST", "MoTA"),
    ("National Fellowship", "SC/ST MPhil/PhD"),
    ("Ishan Uday", "NE region"),
    ("PM Scholarship", "Defence wards"),
    ("AICTE Scholarship", "Technical education"),
    ("UGC Scholarship", "University grants"),
]

SHG: list[tuple[str, str]] = [
    ("Kudumbashree NHG", "Neighbourhood Group"),
    ("NRLM SHG", "10–20 members"),
    ("SHG-Bank Linkage", "1992 NABARD"),
    ("Kudumbashree", "15–20 women"),
    ("CLF", "Cluster Level Federation"),
    ("VO", "Village Organization"),
    ("Kudumbashree", "Weekly meetings"),
    ("NRLM", "4–10 lakh SHGs target"),
    ("SHG", "Self Help Group"),
    ("Kudumbashree", "1998 Kerala"),
    ("Interest subvention", "7% SHG loan"),
    ("Revolving Fund", "₹10000–15000/SHG"),
    ("Kudumbashree", "Micro credit"),
    ("NRLM", "Women empowerment"),
    ("SHG", "Group guarantee"),
    ("Kudumbashree", "Poverty eradication"),
    ("Bank Linkage", "Collateral free"),
    ("Kudumbashree ADS", "Area Development Society"),
    ("Kudumbashree CDS", "Community Development Society"),
    ("NRLM", "Institutional platform"),
    ("SHG grading", "A/B/C/D"),
    ("Kudumbashree", "Largest SHG network"),
    ("NRLM", "Livelihood collectives"),
    ("SHG", "Internal savings first"),
]

LEGAL_AID: list[tuple[str, str]] = [
    ("NALSA", "1995"),
    ("LSA Act", "1987"),
    ("Lok Adalat", "Alternative dispute resolution"),
    ("NALSA", "National Legal Services Authority"),
    ("LSA Act", "Legal Services Authorities Act"),
    ("Lok Adalat", "CPC Section 89"),
    ("NALSA", "Chief Justice of India patron"),
    ("SLSA", "State Legal Services Authority"),
    ("DLSA", "District Legal Services Authority"),
    ("Taluk Legal Services", "Taluk level"),
    ("Free legal aid", "LSA Act Section 12"),
    ("Lok Adalat", "Binding award"),
    ("NALSA", "Article 39A"),
    ("Para Legal Volunteers", "PLV"),
    ("Legal Aid Clinics", "Law colleges"),
    ("Lok Adalat", "No court fee"),
    ("NALSA", "1995-12-05"),
    ("LSA Act", "1987-10-11"),
    ("Permanent Lok Adalat", "Public utility services"),
    ("NALSA", "Justice K.G. Balakrishnan"),
    ("Legal Services Day", "November 9"),
    ("Lok Adalat", "Compromise settlement"),
    ("NALSA", "Legal awareness"),
    ("LSA Act", "Eligible categories"),
    ("Lok Adalat", "National Lok Adalat"),
]

FOOD_SECURITY: list[tuple[str, str]] = [
    ("PMGKAY", "Free food grains"),
    ("Mid Day Meal", "1995"),
    ("PDS", "Public Distribution System"),
    ("PMGKAY", "COVID extension"),
    ("Mid Day Meal", "Hot cooked meal"),
    ("PDS", "Fair price shop"),
    ("PMGKAY", "5+1 kg free"),
    ("Mid Day Meal", "School children"),
    ("PDS", "Ration card"),
    ("PMGKAY", "Garib Kalyan Anna"),
    ("Mid Day Meal", "MDM Scheme"),
    ("PDS", "TPDS"),
    ("PMGKAY", "2020 launch"),
    ("Mid Day Meal", "Class 1–8"),
    ("PDS", "Subsidized grains"),
    ("PMGKAY", "80 crore beneficiaries"),
    ("Mid Day Meal", "Nutrition & attendance"),
    ("PDS", "State agencies"),
    ("PMGKAY", "No cost grains"),
    ("Mid Day Meal", "Central-state sharing"),
    ("PDS", "AAY & PHH"),
    ("PMGKAY", "Phase VIII"),
    ("Mid Day Meal", "Akshaya Patra"),
    ("PDS", "Digitization"),
]

ONORC: list[tuple[str, str]] = [
    ("ONORC", "2020"),
    ("ONORC", "One Nation One Ration Card"),
    ("ONORC", "Portable ration"),
    ("ONORC", "Inter-state സഞ്ചാര സാധ്യത"),
    ("ONORC", "2020-08-01"),
    ("ONORC", "81 crore beneficiaries"),
    ("ONORC", "Aadhaar seeding"),
    ("ONORC", "ePoS devices"),
    ("ONORC", "Intra-state first"),
    ("ONORC", "National സഞ്ചാര സാധ്യത"),
    ("ONORC", "NFSA link"),
    ("ONORC", "2020 COVID"),
    ("ONORC", "Integrated management"),
    ("ONORC", "Any FPS"),
    ("ONORC", "Biometric auth"),
    ("ONORC", "State implementation"),
    ("ONORC", "100% coverage target"),
    ("ONORC", "MoCAFPD"),
    ("ONORC", "Digitized PDS"),
    ("ONORC", "Migrant workers"),
    ("ONORC", "2020 nationwide"),
    ("ONORC", "Ration card merge"),
    ("ONORC", "IM-PDS"),
    ("ONORC", "Food security സഞ്ചാര സാധ്യത"),
]

DISASTER_RELIEF: list[tuple[str, str]] = [
    ("SDRF", "State Disaster Response Fund"),
    ("NDRF", "National Disaster Response Fund"),
    ("DM Act", "2005"),
    ("SDRF", "75:25 Centre-State"),
    ("NDRF", "Central fund"),
    ("DM Act", "Disaster Management Act"),
    ("SDRF", "State level"),
    ("NDRF", "National level"),
    ("NDMA", "National Disaster Management Authority"),
    ("SDMA", "State Disaster Management Authority"),
    ("DM Act", "2005-12-23"),
    ("SDRF", "Calamity relief"),
    ("NDRF", "Supplement SDRF"),
    ("NDRF", "PM chaired"),
    ("DM Act", "NDMA establishment"),
    ("SDRF", "State executive committee"),
    ("NDRF", "Central assistance"),
    ("NDRF battalions", "12 battalions"),
    ("DM Act", "Hazard zonation"),
    ("SDRF", "Natural calamities"),
    ("NDRF", "Man-made disasters"),
    ("NDMA", "2005"),
    ("DM Act", "National plan"),
    ("SDRF", "Financed by states"),
]

COVID_WELFARE: list[tuple[str, str]] = [
    ("PMGKAY", "Free 5 kg rice/wheat"),
    ("PM CARES", "2020"),
    ("Subhiksha Keralam", "Kerala food security"),
    ("PMGKAY", "Garib Kalyan Anna Yojana"),
    ("PM CARES", "Prime Minister's Citizen Assistance"),
    ("Subhiksha Keralam", "2020 Kerala"),
    ("PMGKAY", "Phase I 2020"),
    ("PM CARES", "Trust fund"),
    ("Subhiksha Keralam", "Community kitchens"),
    ("PMGKAY", "80 crore people"),
    ("PM CARES", "COVID relief"),
    ("Subhiksha Keralam", "Free food kits"),
    ("PMGKAY", "Extended multiple phases"),
    ("PM CARES", "Voluntary contribution"),
    ("Subhiksha Keralam", "Lockdown relief"),
    ("PMGKAY", "1 kg pulses"),
    ("PM CARES", "Healthcare infrastructure"),
    ("Subhiksha Keralam", "Kerala government"),
    ("PMGKAY", "MoCAFPD"),
    ("PM CARES", "2020-03-28"),
    ("Subhiksha Keralam", "Hunger free Kerala"),
    ("PMGKAY", "No cost to beneficiaries"),
    ("PM CARES", "80G exemption"),
    ("Subhiksha Keralam", "Local bodies"),
]

RIGHTS_LAW: list[tuple[str, str]] = [
    ("NFSA", "Right to food"),
    ("RTE", "Right to education"),
    ("MGNREGA", "Right to work"),
    ("RPwD Act", "Disability rights"),
    ("POCSO", "Child protection"),
    ("DV Act", "2005"),
    ("NFSA", "2013"),
    ("RTE", "Article 21A"),
    ("MGNREGA", "2005"),
    ("RPwD Act", "2016"),
    ("POCSO", "2012"),
    ("DV Act", "Protection of Women"),
    ("NFSA", "Legal entitlement"),
    ("RTE", "Fundamental right"),
    ("MGNREGA", "Legal guarantee"),
    ("RPwD Act", "Non-discrimination"),
    ("POCSO", "Special POCSO courts"),
    ("DV Act", "Domestic violence"),
    ("NFSA", "Food security"),
    ("RTE", "Free education"),
    ("MGNREGA", "100 days work"),
    ("RPwD Act", "Equal opportunity"),
    ("POCSO", "Sexual offences against children"),
    ("DV Act", "Protection officer"),
]

MINISTRY: list[tuple[str, str]] = [
    ("MGNREGA", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("NFSA", "ഭക്ഷ്യ & പൊതു വിതരണ മന്ത്രാലയം"),
    ("ICDS", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("PMMVY", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("NSAP", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("NRLM", "ഗ്രാമീണ വികസന മന്ത്രാലയം"),
    ("PM-JAY", "ആരോഗ്യ & കുടുംബക്ഷേമ മന്ത്രാലയം"),
    ("RTE", "വിദ്യാഭ്യാസ മന്ത്രാലയം"),
    ("POCSO", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("RPwD Act", "സാമൂഹിക നീതി & അധികാരപ്പെടുത്തൽ"),
    ("NALSA", "നിയമ & നീതി മന്ത്രാലയം"),
    ("TRIFED", "ഗിരിജന കാര്യ മന്ത്രാലയം"),
    ("PM JANMAN", "ഗിരിജന കാര്യ മന്ത്രാലയം"),
    ("ONORC", "ഭക്ഷ്യ & പൊതു വിതരണ മന്ത്രാലയം"),
    ("Mid Day Meal", "വിദ്യാഭ്യാസ മന്ത്രാലയം"),
    ("Ujjawala", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("Sakhi", "വനിതാ & ശിശു വികസന മന്ത്രാലയം"),
    ("NDMA", "ഗൃഹ മന്ത്രാലയം"),
    ("NSP", "വിദ്യാഭ്യാസ മന്ത്രാലയം"),
    ("ADIP", "സാമൂഹിക നീതി & അധികാരപ്പെടുത്തൽ"),
    ("JSSK", "ആരോഗ്യ & കുടുംബക്ഷേമ മന്ത്രാലയം"),
    ("JSY", "ആരോഗ്യ & കുടുംബക്ഷേമ മന്ത്രാലയം"),
    ("PMGKAY", "ഭക്ഷ്യ & പൊതു വിതരണ മന്ത്രാലയം"),
    ("FRA", "ഗിരിജന കാര്യ മന്ത്രാലയം"),
]

KERALA_BOARD: list[tuple[str, str]] = [
    ("Building Workers Board", "നിർമ്മാണ തൊഴിലാളികൾ"),
    ("Welfare Pension Board", "ക്ഷേമ പെൻഷൻ"),
    ("Kerala Social Security Mission", "സാമൂഹിക സുരക്ഷ"),
    ("Kudumbashree", "സ്ത്രീ empowerment"),
    ("Kerala State Housing Board", "വീട്"),
    ("Kerala Women's Commission", "സ്ത്രീ حقوق"),
    ("Kerala SC/ST Commission", "SC/ST"),
    ("Kerala Human Rights Commission", "Human rights"),
    ("Kerala State Child Rights Commission", "Child rights"),
    ("Kerala State Disaster Management Authority", "Disaster"),
    ("Kerala State Food Commission", "Food"),
    ("Kerala State Legal Services Authority", "Legal aid"),
    ("Kerala State Social Welfare Board", "Social welfare"),
    ("Kerala State Handicapped Persons Welfare", "Disability"),
    ("Kerala State Old Age Welfare", "Elderly"),
    ("Kerala State Widow Pension", "Widow"),
    ("Kerala State Disability Pension", "Disability"),
    ("Kerala State Agriculture Workers Welfare", "Farm workers"),
    ("Kerala State Beedi Workers Welfare", "Beedi workers"),
    ("Kerala State Fishermen Welfare", "Fishermen"),
    ("Kerala State Textile Workers Welfare", "Textile"),
    ("Kerala State Plantation Workers Welfare", "Plantation"),
    ("Kerala State Transport Workers Welfare", "Transport"),
    ("Kerala State Headload Workers Welfare", "Headload"),
]

HEALTH_WELFARE: list[tuple[str, str]] = [
    ("Karunya", "Kerala health assistance"),
    ("PM-JAY", "₹5 lakh coverage"),
    ("RSBY", "Rashtriya Swasthya Bima Yojana"),
    ("Janani Shishu Suraksha", "Free delivery & child"),
    ("Karunya Arogya Suraksha", "Ayushman Bharat Kerala"),
    ("PM-JAY", "2018"),
    ("RSBY", "2008"),
    ("JSSK", "2011"),
    ("Karunya", "2012"),
    ("PM-JAY", "50 crore beneficiaries"),
    ("RSBY", "BPL health insurance"),
    ("JSSK", "Free C-section"),
    ("Karunya Plus", "Critical illness"),
    ("PM-JAY", "Cashless treatment"),
    ("RSBY", "₹30000/family"),
    ("JSSK", "Free drugs & diet"),
    ("Karunya Benevolent", "Financial aid"),
    ("PM-JAY", "AB-PMJAY"),
    ("RSBY", "Smart card"),
    ("JSSK", "JSY integration"),
    ("Karunya", "Health dept Kerala"),
    ("PM-JAY", "NHPM"),
    ("RSBY", "Predecessor PM-JAY"),
    ("Janani Suraksha", "Safe motherhood"),
]

LAUNCH_YEAR: list[tuple[str, str]] = [
    ("MGNREGA", "2005"),
    ("NFSA", "2013"),
    ("RTE Act", "2009"),
    ("NSAP", "1999"),
    ("ICDS", "1975"),
    ("PMMVY", "2017"),
    ("PM-JAY", "2018"),
    ("NRLM", "2011"),
    ("ONORC", "2020"),
    ("POCSO", "2012"),
    ("JJ Act", "2015"),
    ("RPwD Act", "2016"),
    ("FRA", "2006"),
    ("Mid Day Meal", "1995"),
    ("RSBY", "2008"),
    ("JSSK", "2011"),
    ("JSY", "2005"),
    ("PMGKAY", "2020"),
    ("PM CARES", "2020"),
    ("NALSA", "1995"),
    ("LSA Act", "1987"),
    ("DM Act", "2005"),
    ("Ujjawala", "2016"),
    ("Sakhi", "2015"),
]

FULL_FORM: list[tuple[str, str]] = [
    ("NSAP", "ദേശീയ സാമൂഹിക സഹായ പ്രോഗ്രാം"),
    ("ICDS", "Integrated Child Development Services"),
    ("NFSA", "ദേശീയ ഭക്ഷ്യ സുരക്ഷാ നിയമം"),
    ("ONORC", "One Nation One Ration Card"),
    ("NRLM", "ദേശീയ ഗ്രാമീണ ഉപജീവന ദൗത്യം"),
    ("MGNREGA", "Mahatma Gandhi National Rural Employment Guarantee Act"),
    ("RTE", "Right to Education"),
    ("PMMVY", "പ്രധാനമന്ത്രി മാതൃ വന്ദന യോജന"),
    ("PM-JAY", "പ്രധാനമന്ത്രി ജന ആരോഗ്യ യോജന"),
    ("IGNOAPS", "ഇന്ദിരാ ഗാന്ധി ദേശീയ വാർദ്ധക്യ പെൻഷൻ"),
    ("IGNWPS", "ഇന്ദിരാ ഗാന്ധി ദേശീയ വിധവാ പെൻഷൻ"),
    ("IGNDPS", "ഇന്ദിരാ ഗാന്ധി ദേശീയ വികലാംഗ പെൻഷൻ"),
    ("NFBS", "ദേശീയ കുടുംബ ക്ഷേമ പദ്ധതി"),
    ("NALSA", "ദേശീയ നിയമ സേവാ അതോറിറ്റി"),
    ("LSA", "നിയമ സേവാ അധികാര നിയമം"),
    ("POCSO", "കുട്ടികളുടെ ലൈംഗിക അതിക്രമങ്ങളിൽ നിന്നുള്ള സംരക്ഷണ"),
    ("RPwD", "വികലാംഗ വ്യക്തികളുടെ അവകാശങ്ങൾ"),
    ("FRA", "വന അവകാശ നിയമം"),
    ("JSSK", "ജനനി ശിശു സുരക്ഷാ പദ്ധതി"),
    ("JSY", "ജനനി സുരക്ഷാ യോജന"),
    ("PMGKAY", "പ്രധാനമന്ത്രി ഗരീബ് കല്യാൺ അന്ന യോജന"),
    ("SDRF", "സംസ്ഥാന ദുരന്ത പ്രതികരണ നിധി"),
    ("NDRF", "ദേശീയ ദുരന്ത പ്രതികരണ നിധി"),
    ("ADIP", "വികലാംഗർക്കുള്ള ഉപകരണ സഹായം"),
]

MATERNITY: list[tuple[str, str]] = [
    ("PMMVY", "₹5000 instalments"),
    ("JSSK", "Free delivery & treatment"),
    ("JSY", "Institutional delivery incentive"),
    ("Maternity Benefit Act", "1961"),
    ("PMMVY", "2017"),
    ("JSSK", "2011"),
    ("JSY", "2005"),
    ("PMMVY", "First living child"),
    ("JSSK", "Free C-section"),
    ("JSY", "ASHA incentive"),
    ("Maternity Benefit Act", "26 weeks leave"),
    ("PMMVY", "PM Matru Vandana"),
    ("JSSK", "Zero expense delivery"),
    ("JSY", "₹1400 rural"),
    ("PMMVY", "Anganwadi/health centre"),
    ("JSSK", "Free transport"),
    ("JSY", "Below poverty line"),
    ("Maternity Benefit Act", "12 weeks paid"),
    ("PMMVY", "Direct benefit transfer"),
    ("JSSK", "All government hospitals"),
    ("JSY", "Safe motherhood"),
    ("PMMVY", "WCD ministry"),
    ("JSSK", "MoHFW"),
    ("JSY", "NRHM component"),
]

ANGANWADI: list[tuple[str, str]] = [
    ("AWW", "Anganwadi Worker"),
    ("AWH", "Anganwadi Helper"),
    ("Anganwadi", "Courtyard shelter"),
    ("ICDS", "Anganwadi under ICDS"),
    ("AWW", "Community mobilizer"),
    ("6 services", "ICDS package"),
    ("POSHAN", "Anganwadi nutrition"),
    ("Supplementary nutrition", "Hot cooked meal"),
    ("Pre-school", "3–6 years"),
    ("Growth monitoring", "Weight & height"),
    ("Immunization", "Health camp link"),
    ("Health check-up", "Monthly"),
    ("Referral", "To PHC/CHC"),
    ("Nutrition education", "Mothers"),
    ("AWW", "Minimum qualification 10th"),
    ("Anganwadi", "1 per 1000 population"),
    ("POSHAN 2.0", "Saksham Anganwadi"),
    ("AWW honorarium", "Central + state"),
    ("Take Home Ration", "0–3 years"),
    ("AWW", "In-charge of centre"),
    ("Anganwadi", "13.9 lakh centres"),
    ("POSHAN tracker", "ICT enabled"),
    ("AWW", "Lady supervisor oversees"),
    ("Anganwadi", "WCD ministry"),
]

DIRECT_FACTS: list[tuple[str, str, list[str], str]] = [
    ("MGNREGA-യിൽ ഗ്യാരന്റി ചെയ്യുന്ന തൊഴിൽ ദിവസങ്ങൾ എത്ര?", "100 ദിവസം", ["50 ദിവസം", "150 ദിവസം", "200 ദിവസം"], "medium"),
    ("NFSA-യിൽ ഓരോ വ്യക്തിക്ക് മാസത്തിൽ ലഭിക്കുന്ന ഭക്ഷ്യധാന്യം എത്ര കിലോ?", "5 കിലോ", ["2 കിലോ", "10 കിലോ", "35 കിലോ"], "easy"),
    ("RTE നിയമം പ്രകാരം സൗജന്യ ആവശ്യ വിദ്യാഭ്യാസ വയസ്സ് എത്ര?", "6–14 വയസ്സ്", ["3–10 വയസ്സ്", "5–16 വയസ്സ്", "6–18 വയസ്സ്"], "easy"),
    ("വികലാംഗതയ്ക്ക് RPwD Act 2016-ൽ നിർവചിച്ച കുറഞ്ഞ ശതമാനം എത്ര?", "40%", ["20%", "60%", "80%"], "medium"),
    ("PMMVY-യിൽ ഗർഭിണിക്ക് ലഭിക്കുന്ന ആനുകൂല്യം എത്ര?", "₹5000", ["₹1000", "₹20000", "₹500"], "medium"),
    ("NFBS-ൽ BPL കുടുംബത്തിന് ലഭിക്കുന്ന ഏകകാല സഹായം എത്ര?", "₹20000", ["₹5000", "₹50000", "₹2000"], "medium"),
    ("IGNOAPS പെൻഷന് അർഹതയുള്ള വയസ്സ് എത്ര?", "60+ വയസ്സ്", ["50+ വയസ്സ്", "65+ വയസ്സ്", "55+ വയസ്സ്"], "easy"),
    ("Annapurna പദ്ധതിയിൽ മാസത്തിൽ നൽകുന്ന ഭക്ഷ്യധാന്യം എത്ര കിലോ?", "10 കിലോ", ["5 കിലോ", "25 കിലോ", "35 കിലോ"], "medium"),
    ("ICDS പദ്ധതി ആരംഭിച്ച വർഷം ഏത്?", "1975", ["1965", "1985", "1995"], "medium"),
    ("NSAP ആരംഭിച്ച വർഷം ഏത്?", "1999", ["1989", "2005", "2010"], "medium"),
    ("NFSA നടപ്പാക്കിയ വർഷം ഏത്?", "2013", ["2009", "2016", "2005"], "easy"),
    ("One Nation One Ration Card-ന്റെ ദേശവ്യാപക സഞ്ചാര സാധ്യത ഏത് വർഷം?", "2020", ["2018", "2022", "2015"], "medium"),
    ("കുടുംബശ്രീ ആരംഭിച്ച വർഷം ഏത്?", "1998", ["1990", "2005", "2010"], "easy"),
    ("കേരള LIFE മിഷൻ ആരംഭിച്ച വർഷം ഏത്?", "2016", ["2012", "2018", "2014"], "medium"),
    ("കാരുണ്യ ആരോഗ്യ പദ്ധതി ആരംഭിച്ച വർഷം ഏത്?", "2012", ["2008", "2016", "2020"], "medium"),
    ("ആശ്വാസകിരണം പദ്ധതി ആരെയാണ് പിന്തുണയ്ക്കുന്നത്?", "പടുക്കിൽ കിടക്കുന്ന രോഗികളുടെ പരിചരകർ", ["വിദ്യാർത്ഥികൾ", "കർഷകർ", "നിർമ്മാണ തൊഴിലാളികൾ"], "hard"),
    ("Ujjawala പദ്ധതി ഏത് വിഭാഗത്തിനാണ്?", "മനുഷ്യക്കടത്ത് ഇരകൾ", ["എൽ.പി.ജി. കണക്ഷൻ", "വീട് നിർമ്മാണം", "വിദ്യാഭ്യാസം"], "hard"),
    ("PM Ujjwala Yojana ഏത് വിഭാഗത്തിനാണ്?", "എൽ.പി.ജി. കണക്ഷൻ", ["മനുഷ്യക്കടത്ത് ഇരകൾ", "വാർദ്ധക്യ പെൻഷൻ", "വിദ്യാഭ്യാസം"], "medium"),
    ("MGNREGA-യിൽ തൊഴിൽ അർഹതയുള്ള കുറഞ്ഞ വയസ്സ് എത്ര?", "18+ വയസ്സ്", ["14+ വയസ്സ്", "21+ വയസ്സ്", "16+ വയസ്സ്"], "easy"),
    ("NFSA-യിൽ ഗ്രാമീണ മുൻഗണനാ കുടുംബങ്ങളുടെ എത്ര ശതമാനം?", "75%", ["50%", "67%", "100%"], "medium"),
    ("അന്ത്യോദയ അന്ന യോജന (AAY) കുടുംബങ്ങൾക്ക് മാസം എത്ര കിലോ?", "35 കിലോ", ["5 കിലോ", "10 കിലോ", "25 കിലോ"], "hard"),
    ("POCSO നിയമം നടപ്പാക്കിയ വർഷം ഏത്?", "2012", ["2010", "2015", "2005"], "medium"),
    ("Juvenile Justice Act (JJ Act) 2015-ൽ കുട്ടി എന്നാൽ?", "18 വയസ്സ് താഴെ", ["14 വയസ്സ് താഴെ", "21 വയസ്സ് താഴെ", "16 വയസ്സ് താഴെ"], "medium"),
    ("NALSA സ്ഥാപിച്ച വർഷം ഏത്?", "1995", ["1987", "2000", "1990"], "medium"),
    ("നിയമ സേവന അധികാരികൾ നിയമം പ്രാബല്യത്തിൽ വന്ന വർഷം?", "1987", ["1995", "2005", "1975"], "hard"),
    ("ദുരന്ത നിയന്ത്രണ നിയമം പ്രാബല്യത്തിൽ വന്ന വർഷം?", "2005", ["2000", "2010", "1995"], "medium"),
    ("വന അവകാശ നിയമം (FRA) പ്രാബല്യത്തിൽ വന്ന വർഷം?", "2006", ["2004", "2010", "1996"], "medium"),
    ("മിഡ്-ഡേ മീൽ പദ്ധതി കേന്ദ്രത്തിൽ ആരംഭിച്ച വർഷം?", "1995", ["2000", "2009", "1985"], "medium"),
    ("ICDS-ൽ ഉൾപ്പെടുന്ന സേവനങ്ങളുടെ എണ്ണം എത്ര?", "6", ["4", "8", "10"], "easy"),
    ("Article 21A-ൽ ഉറപ്പു നൽകുന്നത് ഏത്?", "വിദ്യാഭ്യാസം", ["വോട്ട്", "തൊഴിൽ", "വീട്"], "medium"),
]

POOL_SCHEMES: list[str] = [
    "MGNREGA", "NFSA", "ICDS", "NSAP", "RTE", "PMMVY", "PM-JAY", "NRLM",
    "ONORC", "POCSO", "JJ Act", "RPwD Act", "PMGKAY", "Mid Day Meal",
    "IGNOAPS", "IGNWPS", "IGNDPS", "NFBS", "Annapurna", "Ujjawala",
    "Sakhi", "NALSA", "LSA Act", "FRA", "TRIFED", "PM JANMAN",
    "JSSK", "JSY", "Karunya", "RSBY", "Kudumbashree", "LIFE",
    "Vayomithram", "Aswasakiranam", "Subhiksha Keralam", "PM CARES",
    "SDRF", "NDRF", "DM Act", "ADIP", "NHFDC", "NSP", "POSHAN",
    "BPL", "AAY", "Anganwadi", "AWW", "Lok Adalat", "PDS",
]

POOL_YEARS: list[str] = [
    "1975", "1987", "1989", "1995", "1998", "1999", "2005", "2006",
    "2008", "2009", "2011", "2012", "2013", "2015", "2016", "2017",
    "2018", "2020", "2023", "1990", "2000", "2010", "2014", "2019",
    "1980", "2002", "2007", "1996", "2004", "1965",
]

POOL_GOALS: list[str] = [
    "സ്ത്രീ ശാക്തീകരണവും ദാരിദ്ര്യ നിർമാർജനവും",
    "ഭൂമിയില്ലാത്തവർക്ക് വീട്",
    "ആരോഗ്യ സഹായം",
    "പടുക്കിൽ കിടക്കുന്ന രോഗികളുടെ പരിചരകർ",
    "മുതിർന്നവർക്ക് മൊബൈൽ ആരോഗ്യ സേവ",
    "ഭക്ഷ്യ സുരക്ഷ",
    "ഗുരുതര രോഗ ചികിത്സ",
    "മാതൃ-ശിശു ആരോഗ്യം",
    "പരിസ്ഥിതി സംരക്ഷണം",
    "വനിതാ സ്വയം സഹായ",
    "ദാരിദ്ര്യ നിർമാർജനം",
    "തൊഴിൽ ഗ്യാരന്റി",
    "വിദ്യാഭ്യാസ അവകാശം",
    "വികലാംഗ സമഗ്ര പരിചരണം",
    "ഗിരിജന വികസനം",
    "നിയമ സഹായം",
    "കുട്ടി സംരക്ഷണം",
    "മാതൃ ആരോഗ്യം",
    "പോഷകാഹാരം",
    "സാമൂഹിക സുരക്ഷ",
    "ദുരന്ത പ്രതികരണം",
    "മനുഷ്യക്കടത്ത് പുനർ കുടിയിറക്കം",
    "സ്വയം സഹായ സംഘം",
    "ക്ഷേമ പെൻഷൻ",
    "എല്ലാവർക്കുമുള്ള ആരോഗ്യ പരിരക്ഷ",
    "ജനകീയ പങ്കാളിത്തം",
    "ശുദ്ധമായ കുടിവെള്ളം",
    "സ്വയംപര്യാപ്ത അരി ഉൽപ്പാദനം",
    "നിർമ്മാണ തൊഴിലാളി ക്ഷേമം",
    "COVID സഹായം",
]

POOL_AMOUNTS: list[str] = [
    "₹200/മാസം (കേന്ദ്രം)", "₹20000 (ഏകകാലം)", "₹5000", "₹1600/മാസം",
    "10 കിലോ ഭക്ഷ്യധാന്യം/മാസം", "₹1000–5000/മാസം", "₹1400/₹1000 (ഗ്രാമ/നഗര)",
    "₹30000/കുടുംബം/വർഷം", "₹5 ലക്ഷം/കുടുംബം/വർഷം", "100 ദിവസം",
    "5 കിലോ/വ്യക്തി/മാസം", "35 കിലോ ഭക്ഷ്യധാന്യം/മാസം", "₹2000/മാസം",
    "₹500/മാസം", "₹10000/SHG", "₹24000 crore", "₹6000/വർഷം",
    "₹78000 സബ്സിഡി", "₹1600/മാസം", "₹50000 വരെ",
    "₹1 ലക്ഷം", "₹2 ലക്ഷം", "₹10 ലക്ഷം", "₹500/ദിവസം",
    "₹3/കിലോ അരി", "₹2/കിലോ ഗോതമ്പ്", "₹1/കിലോ coarse grain",
    "₹10000–15000/SHG", "₹10 ലക്ഷം/VO", "7%/4% interest",
]

POOL_AGES: list[str] = [
    "60+ വയസ്സ്", "40–79 വയസ്സ്", "18–79 വയസ്സ്", "65+ വയസ്സ്",
    "6–14 വയസ്സ്", "18+ വയസ്സ്", "40% വികലാംഗത", "0–6 വയസ്സ്",
    "19+ വയസ്സ്", "18 വയസ്സ് താഴെ", "18–40 വയസ്സ്", "0–19 വയസ്സ്",
    "1–8 ക്ലാസ്", "3–6 വയസ്സ്", "0–3 വയസ്സ്", "14+ വയസ്സ്",
    "21+ വയസ്സ്", "50+ വയസ്സ്", "55+ വയസ്സ്", "80%+ വികലാംഗത",
    "160 days leave", "26 weeks leave", "12 weeks paid",
    "10–20 members", "15–20 women", "18–64 പ്രധാന വരുമാനക്കാരൻ",
    "SC/ST/OBC", "First living child", "Below poverty line",
    "Qualified teachers",
]

POOL_MINISTRIES: list[str] = [
    "ഗ്രാമീണ വികസന മന്ത്രാലയം", "ഭക്ഷ്യ & പൊതു വിതരണ മന്ത്രാലയം",
    "വനിതാ & ശിശു വികസന മന്ത്രാലയം", "ആരോഗ്യ & കുടുംബക്ഷേമ മന്ത്രാലയം",
    "വിദ്യാഭ്യാസ മന്ത്രാലയം", "സാമൂഹിക നീതി & അധികാരപ്പെടുത്തൽ",
    "നിയമ & നീതി മന്ത്രാലയം", "ഗിരിജന കാര്യ മന്ത്രാലയം",
    "ഗൃഹ മന്ത്രാലയം", "ധനകാര്യ മന്ത്രാലയം",
    "കൃഷി മന്ത്രാലയം", "വാസസ്ഥല മന്ത്രാലയം", "കാജ് & ഉദ്യോഗ സൃഷ്ടി",
    "പുതുനവീകരണ ഊർജ മന്ത്രാലയം", "പെട്രോളിയം & പ്രകൃതി വാതക",
    "വാണിജ്യ & വ്യവസായ", "പൗരവ്യവഹാര", "ജല ശക്തി",
    "മത്സ്യബന്ധന", "ഇലക്ട്രോണിക്സ് & ഐ.ടി.", "കൾചർ",
    "സcience & technology", "Defence", "External affairs",
    "Information & broadcasting", "Minority affairs",
    "Cooperation", "Statistics", "Tourism", "Youth affairs",
]

POOL_ABBREV: list[str] = [
    "NSAP", "ICDS", "NFSA", "ONORC", "NRLM", "MGNREGA", "RTE", "PMMVY",
    "PM-JAY", "IGNOAPS", "IGNWPS", "IGNDPS", "NFBS", "NALSA", "LSA",
    "POCSO", "RPwD", "FRA", "JSSK", "JSY", "PMGKAY", "SDRF", "NDRF",
    "ADIP", "NHFDC", "NSP", "AWW", "AWH", "BPL", "AAY", "PHH", "NPHH",
    "TPDS", "PDS", "MDM", "RTE", "JJ", "DV", "PESA", "TRIFED",
]

POOL_FULL_FORMS: list[str] = [
    "ദേശീയ സാമൂഹിക സഹായ പ്രോഗ്രാം", "Integrated Child Development Services",
    "ദേശീയ ഭക്ഷ്യ സുരക്ഷാ നിയമം", "One Nation One Ration Card",
    "ദേശീയ ഗ്രാമീണ ഉപജീവന ദൗത്യം",
    "Mahatma Gandhi National Rural Employment Guarantee Act",
    "Right to Education", "പ്രധാനമന്ത്രി മാതൃ വന്ദന യോജന",
    "പ്രധാനമന്ത്രി ജന ആരോഗ്യ യോജന", "ഇന്ദിരാ ഗാന്ധി ദേശീയ വാർദ്ധക്യ പെൻഷൻ",
    "ഇന്ദിരാ ഗാന്ധി ദേശീയ വിധവാ പെൻഷൻ", "ഇന്ദിരാ ഗാന്ധി ദേശീയ വികലാംഗ പെൻഷൻ",
    "ദേശീയ കുടുംബ ക്ഷേമ പദ്ധതി", "ദേശീയ നിയമ സേവാ അതോറിറ്റി",
    "നിയമ സേവാ അധികാര നിയമം",
    "കുട്ടികളുടെ ലൈംഗിക അതിക്രമങ്ങളിൽ നിന്നുള്ള സംരക്ഷണ",
    "വികലാംഗ വ്യക്തികളുടെ അവകാശങ്ങൾ", "വന അവകാശ നിയമം",
    "ജനനി ശിശു സുരക്ഷാ പദ്ധതി", "ജനനി സുരക്ഷാ യോജന",
    "പ്രധാനമന്ത്രി ഗരീബ് കല്യാൺ അന്ന യോജന",
    "സംസ്ഥാന ദുരന്ത പ്രതികരണ നിധി", "ദേശീയ ദുരന്ത പ്രതികരണ നിധി",
    "വികലാംഗർക്കുള്ള ഉപകരണ സഹായം", "Forest Rights Act",
    "National Social Assistance Programme", "National Food Security Act",
    "Protection of Children from Sexual Offences", "Rights of Persons with Disabilities",
    "State Disaster Response Fund", "National Disaster Response Fund",
]

POOL_KERALA: list[str] = [
    "കുടുംബശ്രീ", "LIFE", "കാരുണ്യ", "ആശ്വാസകിരണം", "വയോമിത്രം",
    "സുഭിക്ഷ കേരളം", "കാരുണ്യ പ്ലസ്", "കാരുണ്യ ബെനവലന്റ് ഫണ്ട്",
    "അമ്മ കേരളം", "ഹരിത കേരളം", "അക്ഷയ", "ആരോഗ്യ സുരക്ഷാ കേരളം",
    "അനുഭവം", "സമഗ്ര", "അരി കേരളം", "അമൃതം", "അമൃത കൂട്ടായ്മ",
    "കേരള ക്ഷേമ പെൻഷൻ", "നിർമ്മാണ തൊഴിലാളി ബോർഡ്",
    "കേരള സാമൂഹിക സുരക്ഷാ ദൗത്യം", "കേരള ഫുഡ് പ്ലാനിംഗ് ബോർഡ്",
    "കാരുണ്യ ആരോഗ്യ സുരക്ഷ", "കുടുംബശ്രീ NHG", "കേരള ഹാബിറ്റാറ്റ് മിഷൻ",
    "Building Workers Board", "Welfare Pension Board",
    "Kerala Social Security Mission", "Kerala State Housing Board",
    "Kerala Women's Commission", "Kerala SC/ST Commission",
]

POOL_LAWS: list[str] = [
    "NFSA", "RTE", "MGNREGA", "RPwD Act", "POCSO", "DV Act",
    "FRA", "LSA Act", "DM Act", "JJ Act", "Maternity Benefit Act",
    "Maintenance Act", "Senior Citizens Act", "National Trust Act",
    "PESA", "Article 21A", "Article 39A", "86th Amendment",
    "Right to food", "Right to education", "Right to work",
    "Disability rights", "Child protection", "Domestic violence",
    "Forest rights", "Legal aid", "Disaster management",
    "Juvenile justice", "Fundamental right", "Legal guarantee",
]

POOL_SERVICES: list[str] = [
    "Supplementary nutrition", "Immunization", "Health check-up",
    "Referral services", "Pre-school education", "Nutrition & health education",
    "Hot cooked meal", "Take home ration", "Growth monitoring",
    "Anganwadi Worker", "Anganwadi Helper", "Courtyard shelter",
    "6 services", "POSHAN tracker", "Saksham Anganwadi",
    "Community mobilizer", "Weight & height", "Health camp link",
    "Monthly check-up", "To PHC/CHC", "Mothers education",
    "Minimum qualification 10th", "1 per 1000 population",
    "Central + state honorarium", "0–3 years", "3–6 years",
    "Lady supervisor", "13.9 lakh centres", "ICT enabled", "WCD ministry",
]

POOL_BOARDS: list[str] = [
    "Building Workers Board", "Welfare Pension Board",
    "Kerala Social Security Mission", "Kerala State Housing Board",
    "Kerala Women's Commission", "Kerala SC/ST Commission",
    "Kerala Human Rights Commission", "Kerala State Child Rights Commission",
    "Kerala State Disaster Management Authority", "Kerala State Food Commission",
    "Kerala State Legal Services Authority", "Kerala State Social Welfare Board",
    "Kerala State Handicapped Persons Welfare", "Kerala State Old Age Welfare",
    "Kerala State Widow Pension", "Kerala State Disability Pension",
    "Kerala State Agriculture Workers Welfare", "Kerala State Beedi Workers Welfare",
    "Kerala State Fishermen Welfare", "Kerala State Textile Workers Welfare",
    "Kerala State Plantation Workers Welfare", "Kerala State Transport Workers Welfare",
    "Kerala State Headload Workers Welfare", "Kudumbashree",
    "Kerala State Housing Board", "Labour Welfare Board",
    "Construction Workers Welfare", "Social Security Mission",
    "Welfare Fund Board", "Pension Board",
]


def generate_wave30_candidates(existing: set[str], rng: random.Random) -> list[Candidate]:
    out: list[Candidate] = []

    emit_category(
        out, existing, rng, KERALA_SCHEME_YEAR,
        ["'{a}' പദ്ധതി ആരംഭിച്ച വർഷം ഏത്?", "'{a}' ഏത് വർഷം ആരംഭിച്ചു?"],
        ["'{b}' വർഷം ആരംഭിച്ച കേരള പദ്ധതി ഏത്?", "'{b}'-ൽ ആരംഭിച്ച കേരള ക്ഷേമ പദ്ധതി ഏത്?"],
        POOL_KERALA, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, KERALA_SCHEME_GOAL,
        ["'{a}' പദ്ധതിയുടെ പ്രധാന ലക്ഷ്യം ഏത്?", "'{a}'-ന്റെ ഉദ്ദേശ്യം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട കേരള പദ്ധതി ഏത്?", "'{b}' ഉദ്ദേശ്യമുള്ള കേരള പദ്ധതി ഏത്?"],
        POOL_KERALA, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, NRLM,
        ["'{a}'-ന്റെ പ്രധാന വിവരം/ലക്ഷ്യം ഏത്?", "'{a}' സംബന്ധിച്ച പ്രധാന വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള NRLM/SHG സംബന്ധിത പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ഉപജീവന ദൗത്യ വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, PENSION_AMOUNT,
        ["'{a}'-ന്റെ പെൻഷൻ/സഹായ തുക ഏത്?", "'{a}'-ൽ ലഭിക്കുന്ന തുക/പരിരക്ഷ ഏത്?"],
        ["'{b}' തുക/പരിരക്ഷ നൽകുന്ന പദ്ധതി ഏത്?", "'{b}' ആനുകൂല്യമുള്ള പെൻഷൻ/സഹായ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, AGE_ELIGIBILITY,
        ["'{a}'-ന്റെ പ്രായ/അർഹതാ വയസ്സ് ഏത്?", "'{a}'-ൽ പ്രായം ഏത്?"],
        ["'{b}' പ്രായ അർഹതയുള്ള പദ്ധതി/നിയമം ഏത്?", "'{b}' വയസ്സുള്ളവർക്കുള്ള പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AGES,
    )
    emit_category(
        out, existing, rng, BPL_AAY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' സംബന്ധിച്ച BPL/AAY വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള BPL/AAY/PHH പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ഭക്ഷ്യ സുരക്ഷ വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, ICDS,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ICDS/anganwadi സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ICDS പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ICDS വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_SERVICES,
    )
    emit_category(
        out, existing, rng, RTE,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' RTE/വിദ്യാഭ്യാസ അവകാശം സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള RTE പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട RTE വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_AGES,
    )
    emit_category(
        out, existing, rng, NFSA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' NFSA/ഭക്ഷ്യ സുരക്ഷ സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള NFSA പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട NFSA വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, MGNREGA,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' MGNREGA സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള MGNREGA പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട MGNREGA വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, NSAP,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' NSAP/പെൻഷൻ സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള NSAP പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട NSAP വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, WOMEN_CHILD,
        ["'{a}'-ന്റെ പ്രധാന ലക്ഷ്യം/വിവരം ഏത്?", "'{a}' വനിത/ശിശു പദ്ധതിയുടെ വിവരം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട വനിത/ശിശു പദ്ധതി ഏത്?", "'{b}' ഉദ്ദേശ്യമുള്ള വനിത/ശിശു പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, ELDERLY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' മുതിർന്നവർ/വാർദ്ധക്യ പദ്ധതിയുടെ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള വാർദ്ധക്യ പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട മുതിർന്നവർ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, DISABILITY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' വികലാംഗ ക്ഷേമ/അവകാശ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള വികലാംഗ പദ്ധതി/നിയമം ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട വികലാംഗ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AGES,
    )
    emit_category(
        out, existing, rng, TRIBAL,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ഗിരിജന/വന അവകാശ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ഗിരിജന പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ഗിരിജന പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, SCHOLARSHIP,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' സ്കോളർഷിപ്പ് സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള സ്കോളർഷിപ്പ് പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട സ്കോളർഷിപ്പ് പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, SHG,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' SHG/കുടുംബശ്രീ സംബന്ധിച്ച വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള SHG പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട സ്വയം സഹായ സംഘ വിവരം ഏത്?"],
        POOL_SCHEMES, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, LEGAL_AID,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' നിയമ സഹായ/ലോക് അadalat വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള നിയമ സഹായ ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട നിയമ സഹായ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, FOOD_SECURITY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ഭക്ഷ്യ സുരക്ഷ/പDS വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ഭക്ഷ്യ സുരക്ഷ പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ഭക്ഷ്യ സുരക്ഷ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, ONORC,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ONORC/റേഷൻ സഞ്ചാര സാധ്യത വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ONORC പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട റേഷൻ കാർഡ് സഞ്ചാര സാധ്യത ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, DISASTER_RELIEF,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ദുരന്ത/NDRF/SDRF വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ദുരന്ത നിവാരണ നിധി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ദുരന്ത നിവാരണം ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, COVID_WELFARE,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' COVID ക്ഷേമ/ഭക്ഷ്യ സഹായ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള COVID ക്ഷേമ പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട COVID ക്ഷേമം ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, RIGHTS_LAW,
        ["'{a}'-ന്റെ പ്രധാന വിവരം/അവകാശം ഏത്?", "'{a}' ക്ഷേമ/അവകാശ നിയമ വിവരം ഏത്?"],
        ["'{b}' അവകാശ/നിയമ വിവരമുള്ള ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട അവകാശ/നിയമ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_LAWS,
    )
    emit_category(
        out, existing, rng, MINISTRY,
        ["'{a}' ഏത് മന്ത്രാലയത്തിന് കീഴിലാണ്?", "'{a}' നടപ്പാക്കുന്ന മന്ത്രാലയം ഏത്?"],
        ["'{b}' മന്ത്രാലയത്തിന് കീഴിലുള്ള ക്ഷേമ പദ്ധതി ഏത്?", "'{b}' നടപ്പാക്കുന്ന പ്രധാന ക്ഷേമ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_MINISTRIES,
    )
    emit_category(
        out, existing, rng, KERALA_BOARD,
        ["'{a}'-ന്റെ പ്രധാന ലക്ഷ്യ/വിഭാഗം ഏത്?", "'{a}' കേരള ബോർഡ്/സ്ഥാപനത്തിന്റെ വിവരം ഏത്?"],
        ["'{b}' ലക്ഷ്യമിട്ട കേരള ബോർഡ്/സ്ഥാപനം ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട കേരള ബോർഡ് ഏത്?"],
        POOL_BOARDS, POOL_GOALS,
    )
    emit_category(
        out, existing, rng, HEALTH_WELFARE,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ആരോഗ്യ ക്ഷേമ പദ്ധതിയുടെ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ആരോഗ്യ ക്ഷേമ പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ആരോഗ്യ ക്ഷേമ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, LAUNCH_YEAR,
        ["'{a}' ദേശീയ ക്ഷേമ പദ്ധതി ആരംഭിച്ച വർഷം ഏത്?", "'{a}' ഏത് വർഷം ആരംഭിച്ചു?"],
        ["'{b}' വർഷം ആരംഭിച്ച ദേശീയ ക്ഷേമ പദ്ധതി ഏത്?", "'{b}'-ൽ ആരംഭിച്ച പ്രധാന ക്ഷേമ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_YEARS,
    )
    emit_category(
        out, existing, rng, FULL_FORM,
        ["'{a}' എന്ന സംക്ഷേപത്തിന്റെ പൂർണ്ണരൂപം ഏത്?", "'{a}'-ന്റെ വിപുലീകരണം ഏത്?"],
        ["'{b}' പൂർണ്ണരൂപമുള്ള പദ്ധതിയുടെ സംക്ഷേപം ഏത്?", "'{b}' ഏത് സംക്ഷേപത്തിൽ അറിയപ്പെടുന്നു?"],
        POOL_ABBREV, POOL_FULL_FORMS,
    )
    emit_category(
        out, existing, rng, MATERNITY,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' മാതൃ/ഗർഭിണി പദ്ധതിയുടെ വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള മാതൃ ക്ഷേമ പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട മാതൃ ക്ഷേമ പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_AMOUNTS,
    )
    emit_category(
        out, existing, rng, ANGANWADI,
        ["'{a}'-ന്റെ പ്രധാന വിവരം ഏത്?", "'{a}' ആംഗൻവാടി/ICDS സേവന വിവരം ഏത്?"],
        ["'{b}' വിവരമുള്ള ആംഗൻവാടി പദ്ധതി ഏത്?", "'{b}'-മായി ബന്ധപ്പെട്ട ആംഗൻവാടി പദ്ധതി ഏത്?"],
        POOL_SCHEMES, POOL_SERVICES,
    )

    emit_direct(out, existing, rng, DIRECT_FACTS)
    return out


if __name__ == "__main__":
    print(len(generate_wave30_candidates(set(), random.Random(0))))
